#!/usr/bin/env python3
"""FLESHOUT-QUEUE.md: thin pages Cyan's carve-outs keep on Google.

Cyan's ruling, 5 Sep 2026: thin pages are noindexed UNLESS popular, new, or a
main actor - and "if the thin page is popular, new, or a main actor then I
need to flesh it out." This worklist is those survivors: pages Google still
sees that have almost nothing on them, ranked by how much traffic they can
earn. Criteria MUST stay in sync with the NOINDEX block in build.py.

Run: python3 generator/make_fleshout_queue.py   (from the repo root)
"""
import csv
import datetime
import os
import re
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def rows(name):
    with open(os.path.join(ROOT, "data", name), encoding="utf-8") as f:
        return list(csv.DictReader(f))


def view_num(s):
    s = (s or "").strip().upper()
    if not s: return 0
    mult = 1
    if s.endswith("B"): mult, s = 10**9, s[:-1]
    elif s.endswith("M"): mult, s = 10**6, s[:-1]
    elif s.endswith("K"): mult, s = 10**3, s[:-1]
    try: return int(float(s) * mult)
    except ValueError: return 0


titles = rows("titles.csv")
people = rows("people.csv")
credits = rows("credits.csv")
availability = rows("availability.csv")

avail_by_title = defaultdict(list)
for a in availability: avail_by_title[a["title_id"]].append(a)
credits_by_title = defaultdict(list)
credits_by_person = defaultdict(list)
for c in credits:
    credits_by_title[c["title_id"]].append(c)
    credits_by_person[c["person_id"]].append(c)


def title_views(t):
    return max((view_num(a.get("view_count")) for a in avail_by_title.get(t["title_id"], [])), default=0)


SEEN_DATE = re.compile(r"weekly[_-](20\d\d-\d\d-\d\d)")
NEW_CUTOFF = (datetime.date.today() - datetime.timedelta(days=90)).isoformat()
TOP600_FLOOR = max(1, sorted((title_views(t) for t in titles), reverse=True)[:600][-1])


def views_label(n):
    if n >= 10**9: return "%.1fB" % (n / 10**9)
    if n >= 10**6: return "%.1fM" % (n / 10**6)
    if n >= 10**3: return "%.0fK" % (n / 10**3)
    return str(n)


kept_titles = []
for t in titles:
    if (t.get("synopsis_short") or "").strip(): continue
    if credits_by_title.get(t["title_id"]): continue
    reasons = []
    if title_views(t) >= TOP600_FLOOR: reasons.append("popular")
    m = SEEN_DATE.search(t.get("source") or "")
    if m and m.group(1) >= NEW_CUTOFF: reasons.append("new")
    if reasons:
        kept_titles.append((title_views(t), t, "+".join(reasons)))
kept_titles.sort(key=lambda x: -x[0])

kept_people = []
for p in people:
    cs = credits_by_person.get(p["person_id"], [])
    if len(cs) > 1: continue
    if (p.get("bio_short") or "").strip(): continue
    if any((c.get("role") or "").strip().lower() == "lead" for c in cs):
        kept_people.append(p)
kept_people.sort(key=lambda p: p["name"])

out = ["# Flesh-out queue - thin pages the carve-outs keep on Google",
       "",
       "GENERATED by generator/make_fleshout_queue.py - do not hand-edit.",
       "",
       "Cyan's ruling (5 Sep 2026): thin pages are noindexed unless popular, new,",
       "or a main actor - and the survivors get fleshed out. These pages are still",
       "offered to Google with almost nothing on them, so they are the next",
       "content priority after the caption queue. A title leaves this list when it",
       "gains a synopsis or cast; an actor leaves it with a bio or second credit.",
       "",
       f"## Titles kept indexed while thin: {len(kept_titles)}",
       "",
       "| # | Views | Why kept | Title | title_id |",
       "|---|-------|----------|-------|----------|"]
for i, (v, t, why) in enumerate(kept_titles, 1):
    out.append(f"| {i} | {views_label(v)} | {why} | {t['primary_title']} | {t['title_id']} |")
out += ["", f"## Actors kept indexed while thin (lead credit, no bio): {len(kept_people)}", "",
        "| # | Name | person_id |", "|---|------|-----------|"]
for i, p in enumerate(kept_people, 1):
    out.append(f"| {i} | {p['name']} | {p['person_id']} |")
out.append("")

path = os.path.join(ROOT, "FLESHOUT-QUEUE.md")
open(path, "w", encoding="utf-8").write("\n".join(out))
print(f"wrote {path}: {len(kept_titles)} titles, {len(kept_people)} actors")
print(f"top-600 views floor: {views_label(TOP600_FLOOR)}; new cutoff: {NEW_CUTOFF}")
