#!/usr/bin/env python3
"""Generate TROPES-WANTED.md - the titles carrying NO trope, for Cyan to rule on.

Cyan, 14 Aug 2026, setting the publish rule after the trope vocabulary cleanup:
"if there's at least one trope tag on the title, it can definitely go live on the
website. If there aren't any, then I need to look at the title myself. You will
need to make a list of titles that I need to look at."

So a title with one trope needs nobody. A title with none is a human decision,
because the alternatives - guess a trope, or take the platform's - are the two
things this project does not do.

GENERATED FROM data/, like CAST-WANTED.md and AI-CHECK.md, so a title leaves the
list the moment it gains a trope. Never hand-edit it.

RANKED BY REACH using views(), never int(): view_count is a display string
('218.1M'), and int() on it silently yields zero, which would rank every title at
0 and look merely uninteresting rather than broken.

Usage:
    py generator/make_trope_worklist.py [--dry-run]
"""
import csv, io, os, re, sys, collections

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.environ.get("DEA_DATA") or os.path.join(os.path.dirname(HERE), "data")
REPO = os.path.dirname(HERE)
DRY = "--dry-run" in sys.argv


def rows(name):
    with io.open(os.path.join(DATA, name), encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def views(s):
    m = re.match(r"^([\d.]+)\s*([KMB])?$", (s or "").strip().upper())
    if not m:
        return 0
    return int(float(m.group(1)) * {"K": 1e3, "M": 1e6, "B": 1e9, None: 1}[m.group(2)])


def views_label(n):
    if n >= 1e6:
        return "%.1fM" % (n / 1e6)
    if n >= 1e3:
        return "%.1fK" % (n / 1e3)
    return "n/a" if not n else str(n)


def main():
    titles = rows("titles.csv")
    avail = rows("availability.csv")
    platforms = {p["platform_id"]: p.get("name") or p["platform_id"]
                 for p in rows("platforms.csv")}

    reach, plat, link = {}, collections.defaultdict(list), {}
    for r in avail:
        tid = r["title_id"]
        reach[tid] = max(reach.get(tid, 0), views(r.get("view_count")))
        pid = r.get("platform_id") or ""
        if pid:
            plat[tid].append(platforms.get(pid, pid))
        if r.get("direct_link") and tid not in link:
            link[tid] = r["direct_link"]

    want = [t for t in titles
            if not [x for x in (t.get("tropes") or "").split(";") if x.strip()]]
    want.sort(key=lambda t: -reach.get(t["title_id"], 0))

    out = []
    out.append("# Tropes wanted - titles carrying no trope at all\n")
    out.append("GENERATED by generator/make_trope_worklist.py - do not hand-edit.\n")
    out.append("Cyan's rule, 14 Aug 2026: a title with at least one trope can go live as\n"
               "is. A title with NONE needs her eye, because guessing a trope or copying\n"
               "the platform's are both off the table. %d titles qualify, ranked by reach.\n"
               % len(want))
    out.append("Add a trope to the title's row in data/titles.csv (semicolon separated,\n"
               "matching an existing name in data/tropes.csv where one fits) and the title\n"
               "drops off this list on the next run.\n")
    out.append("| # | Reach | Title | Platform | title_id | Link |")
    out.append("|---|-------|-------|----------|----------|------|")
    for i, t in enumerate(want, 1):
        tid = t["title_id"]
        ps = ", ".join(sorted(set(plat.get(tid, [])))) or "none"
        url = link.get(tid, "")
        cell = "[watch](%s)" % url if url else ""
        out.append("| %d | %s | %s | %s | %s | %s |"
                   % (i, views_label(reach.get(tid, 0)), t["primary_title"], ps, tid, cell))
    body = "\n".join(out) + "\n"

    by_src = collections.Counter(t.get("source", "") for t in want)
    print("titles with no trope: %d" % len(want))
    print("by source: %s" % dict(by_src))
    if DRY:
        print("\nDRY RUN - nothing written.")
        return
    p = os.path.join(REPO, "TROPES-WANTED.md")
    with io.open(p, "w", encoding="utf-8", newline="\n") as f:
        f.write(body)
    print("written: TROPES-WANTED.md")


if __name__ == "__main__":
    main()
