"""Generate REWRITE-QUEUE.md: every live synopsis that is scrape-sourced and
unverified, ranked by reach.

WHY THIS LIST EXISTS (Cyan's ruling, 14 Aug 2026). After the provably-copied
synopses were quarantined, 646 survivors still trace to a scrape run: they pass
every mechanical check (full sentences, not the 300 shapes) but cannot be proven
ours. Cyan ruled they stay live for now and get REWRITTEN in the brand voice,
top reach first - blanking them all had a real SEO cost for no legal gain.

These are invisible to TITLES-INCOMPLETE.md, which only sees mechanically-failing
captions. This list is the only place the suspect set is tracked.

Regenerate after any caption pass:  py generator/make_rewrite_queue.py
"""
import csv, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.environ.get("DEA_DATA") or os.path.join(HERE, "..", "data")
OUT = os.path.join(HERE, "..", "REWRITE-QUEUE.md")
sys.path.insert(0, HERE)
from make_gap_report import views  # noqa: E402  the one true view_count parser


def is_copied_shape(s):
    return bool(s) and (len(s) == 300 or len(s.encode("utf-8")) == 300)


def main():
    titles = list(csv.DictReader(open(os.path.join(DATA, "titles.csv"), newline="", encoding="utf-8-sig")))
    av = list(csv.DictReader(open(os.path.join(DATA, "availability.csv"), newline="", encoding="utf-8-sig")))
    reach = {}
    for r in av:
        v = views(r["view_count"])
        reach[r["title_id"]] = max(reach.get(r["title_id"], 0), v)

    suspects = []
    for t in titles:
        s = (t["synopsis_short"] or "").strip()
        if not s or is_copied_shape(s):
            continue
        if "\n" in s:
            continue                      # hook structure = written by us
        if t.get("data_confidence") == "verified":
            continue
        suspects.append((reach.get(t["title_id"], 0), t))
    suspects.sort(key=lambda x: -x[0])

    def m(v):
        return f"{v/1e6:.1f}M" if v >= 1e6 else (f"{v/1e3:.0f}K" if v >= 1e3 else str(v))

    lines = [
        "# Rewrite queue - scrape-sourced synopses still live",
        "",
        "GENERATED by generator/make_rewrite_queue.py - do not hand-edit.",
        "",
        f"{len(suspects)} live synopses trace to a scrape run and cannot be proven ours.",
        "Cyan's ruling (14 Aug 2026): they stay live and get REWRITTEN in the brand",
        "voice, top reach first. The voice spec is in the READ FIRST standing rules.",
        "A rewritten caption carries a HOOK line + newline, which is how this list",
        "knows to drop it on the next run.",
        "",
        "| # | Reach | Title | title_id |",
        "|---|-------|-------|----------|",
    ]
    for i, (v, t) in enumerate(suspects, 1):
        lines.append(f"| {i} | {m(v)} | {t['primary_title']} | {t['title_id']} |")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"suspect synopses queued: {len(suspects)}")
    print(f"wrote {os.path.abspath(OUT)}")


if __name__ == "__main__":
    main()
