# -*- coding: utf-8 -*-
# APPROVED batch two, 45 captions. Cyan signed off 20 Aug 2026.
# Basis: her rule that read means done, plus her line edits applied verbatim
# (12 edits of hers). Copied from generator/staging/captions_2026_08_16_r45.py at approval; the two files
# are identical at this commit and this one is the one apply consumes.
# -*- coding: utf-8 -*-
"""Batch generated by caption_pipeline.py next.

Fill CAPTIONS. Each value is HOOK newline BODY newline ASIDE.
  HOOK  one sentence, leads as the subheading
  BODY  the synopsis, in our words, ONLY facts from the source below
  ASIDE us talking to the reader, must stand alone with the rest covered

FETCH REQUIRED means there is no fact source on disk. Read the platform page
first, paste what it says into FACTS below, then write. Never write from the
title alone.
"""

CAPTIONS = {

    # 135.1M   Reborn to Love Mr. Right
    # FACTS: Arianna dies a tragic death on the day of her graduation, while Derek, the driver's son,
    # FACTS:  takes all the spotlight on stage.
    'reborn-to-love-mr-right':
        "She gave him everything, right down to her father's "
        "company.\nArianna gave Derek all of it. Her car, her credit card, "
        "the company itself. "
        "Derek is the driver's son, and he took the lot while spoiling "
        "Ivy like a princess and treating Arianna like a servant. She "
        "dies on the day of her graduation, and only then does she "
        "understand that Hayden, the billionaire's heir, had been waiting "
        "for her the whole time. Then fate hands her a second chance at "
        "all of it.",

    # 132.3M   Love at Dangerous Speeds
    # FACTS: When Violet flees her abusive fiancé on their wedding day, she hides with Marcus, a noto
    # FACTS: rious street racer.
    'love-at-dangerous-speeds':
        "She runs on her wedding day and hides with a stranger.\nViolet "
        "gets away from an abusive fiance on the day she is meant to "
        "marry him, and hides with Marcus, a street racer with a name "
        "people know. What starts as protection in exchange for a kiss "
        "turns into something neither of them planned. Then Marcus tells "
        "her the truth about the hit and run he has never got past: the "
        "man it killed was her father.",

    # 132.1M   Mr Hills' Adorable Wife
    # FACTS: Overlooked by her family for a birthmark, Valerie finds unexpected love with billionaire
    # FACTS:  Andrew Hills.
    'mr-hills-adorable-wife':
        "Her own family tried to swap her out.\nValerie Patterson was "
        "born with a birthmark her mother decided was ugly, and her "
        "family have ignored her ever since. When a billionaire takes an "
        "interest, the Pattersons very nearly succeed in putting her "
        "sister Daphne in her place instead. What none of them account "
        "for is Andrew Hills falling for Valerie herself.",

    # 130.8M   We Will Love Again
    # FACTS: Noah Preston returns as a billionaire after six years of being away, and his fiance brea
    # FACTS: king up with him because he was poor in We Will Love Again Movie.
    'we-will-love-again':
        "She left him for being poor. That is not the whole story.\nNoah "
        "Preston comes back after six years away, and this time he is a "
        "billionaire. The woman who left him did it because he had "
        "nothing, or that is what he has believed ever since. He comes "
        "home wanting revenge. What nobody has told him is that his own "
        "mother made her end it, and that she never wanted to at all.",

    # 130.6M   The Billionaire's Baby Bargain
    # FACTS: To save her dying sister, Amelia agrees to billionaire Nathan's contract marriage of no 
    # FACTS: sex, no love, and a baby by insemination; unexpected feelings complicate the deal.
    'the-billionaire-s-baby-bargain':
        "No sex, no love, and a baby by contract.\nAmelia's sister Abby "
        "is dying, and signing a contract marriage is the only way Amelia "
        "can pay for what she needs. The terms are exact: no sex, no "
        "love, and a baby by insemination. Nathan set it up because he is "
        "fighting to get his position as CEO back and his father's wish "
        "is the price of it. Neither of them writes feelings into the "
        "agreement.",

    # 129.9M   Claimed by the Alpha I Hate
    # FACTS: Daisy Storm cannot shift and is hated by her pack; her Alpha mate cheats and breaks thei
    # FACTS: r bond on her eighteenth birthday. After her mother dies she is ordered back by new Alph
    # FACTS: a Nolan Fenrir, the man she blames, and a forbidden second mate bond pulls them together
    # FACTS: .
    'claimed-by-the-alpha-i-hate':
        "She blames him for her mother's death.\nDaisy Storm has never "
        "known what is wrong with her. She cannot shift and she has no "
        "wolf, and on her eighteenth birthday her pack and her own mate "
        "reject her for it. The one person she finds herself pulled "
        "towards is Nolan Fenrir, the Alpha she holds responsible for her "
        "mother's death. Neither of them can explain the pull, and "
        "neither of them wants it.",

    # 129.7M   Do Not Disturb: Lady Boss in Disguise!
    # FACTS: To become heiress of her family hotel chain, Violet Trenton goes undercover as a cleanin
    # FACTS: g lady and takes out the troublemakers one by one, while sexy new COO Kasey Johnson may 
    # FACTS: be more than an ally.
    'do-not-disturb-lady-boss-in-disguise':
        "Nobody at the hotel knows whose daughter she is.\nViolet Trenton "
        "is set on becoming the heiress to her family's hotel chain. So "
        "she goes undercover in her own hotels as a cleaning lady, where "
        "not one person knows her face, and deals with all the people "
        "causing trouble one at a time.",

    # 127.8M   Claimed by My Ex's Alpha Brother
    # FACTS: Wolfless Ella catches her Beta mate cheating and falls into the arms of his brother, the
    # FACTS:  newly returned Alpha who has loved her since childhood.
    'claimed-by-my-ex-s-alpha-brother':
        "Her mate cheats. His brother has waited years.\nElla has no wolf "
        "of her own, but she has a mate in Beta Noah Gravens, right up "
        "until she catches him with her rival Ava. She ends up with "
        "Noah's brother instead. Liam Gravens has just come back as Alpha "
        "of the Crescent Pack, he has loved her since they were children, "
        "and he knows she is his fated mate. Jealous rivals and bitter "
        "exes are already pulling at the pair of them.",

    # 125.3M   Dear Husband, Delete My Number!
    # FACTS: Emma got into a car accident and when she tried to reach her husband, Elijah, he ignored
    # FACTS:  her to be with his wanna-be girlfriend, Stella.
    'dear-husband-delete-my-number':
        "She called him from the crash. He did not pick up.\nEmma is in a "
        "car accident, and when she tries to reach her husband Elijah he "
        "ignores her because he is with Stella. Then she finds out Stella "
        "may be carrying his child. Emma files for divorce and refuses to "
        "take a penny from him, which is the part Elijah cannot make "
        "sense of, because he always assumed the money was why she "
        "stayed.",

    # 124.8M   Pregnant by My Ex's Professor Dad
    # FACTS: After catching her boyfriend cheating, Emily has a one-night stand with a stranger who t
    # FACTS: urns out to be her new professor, then discovers she is pregnant.
    'pregnant-by-my-ex-s-professor-dad':
        "The stranger from last night is at the front of the "
        "class.\nEmily catches her boyfriend cheating on the first day of "
        "the semester. That night she goes home with a stranger called "
        "Charles. The next morning she walks into a lecture and finds him "
        "standing at the front of it, because Charles is her new "
        "professor. They keep it professional but then Emily finds out she "
        "is pregnant.",

    # 123.3M   The Reckoning Takes Flight
    # FACTS: Eve takes a flight to Hawaii to attend her big brother's wedding, booking an extra-wide 
    # FACTS: seat because of her broken leg in a cast.
    'the-reckoning-takes-flight':
        "One seat on one flight, and a wedding does not survive it.\nEve "
        "books an extra wide seat to Hawaii for her brother's wedding, "
        "because her leg is in a cast. A woman and her son demand she "
        "move. When the boy trips in turbulence, his mother turns on the "
        "pilots and forces an emergency landing. Her sister Clara arrives "
        "to back her up and accuses Eve of being her fiance's mistress, "
        "without realising that Eve is her fiance's little sister.",

    # 122.8M   You Belong With Me
    # FACTS: Eric Taylor Guilmette lead.
    'you-belong-with-me':
        "Revenge first. Feelings were not part of the plan.\nKristine's "
        "boyfriend has been cheating with her best friend, and coasting "
        "on her brains the whole time. So she goes to his rich uncle "
        "Henry and evens the score. Henry knows exactly what he is being "
        "used for, because Kristine tells him outright. What neither of "
        "them arranges for is any of it turning real.",

    # 119.1M   My Secret Lover Is His Brother
    # FACTS: To forgive Piper's family debt, she's promised to marry one of the Bellfort brothers.
    'my-secret-lover-is-his-brother':
        "Her family's debt comes with a choice of brother."
        "\nPiper is promised to one of the Bellfort brothers to clear her "
        "family's debt, and the choice of which one is hers to make. Drew is "
        "the star of the lacrosse team. Noah is the handsome loner nobody "
        "gets close to. She has a real connection with both of them but "
        "picking one means letting the other go.",

    # 118.2M   The CEO's Contract Wife
    # FACTS: Jasper needed a wife urgently, Chloe needed money urgently; their contract marriage beco
    # FACTS: mes the real thing.
    'the-ceo-s-contract-wife':
        "He needed a wife. She needed money.\nJasper Tate needs a wife "
        "and has no time to go looking for one. Chloe Adams needs money "
        "and has run out of other ideas. They both go to the same person "
        "for help, and Madam G puts them in front of each "
        "other. What they sign is a contract and nothing else but it does "
        "not stay that way for long.",

    # 116.7M   Kiss Me One Last Time
    # FACTS: In Kiss Me One Last Time full movie, Adeline has cancer.
    'kiss-me-one-last-time':
        "She has a few months left, and he has never once looked at "
        "her.\nAdeline is dying. She has a few months, and the only thing "
        "she wants in them is for her husband to love her. Blake has "
        "never treated her as his wife but to him she has always been a "
        "blood bank, kept close for her step sister's sake.",

    # 115.6M   We Are Never Ever Getting Back Together
    # FACTS: Lisa's contract marriage ends without notice. Then her ex-husband becomes her boss.
    'we-are-never-ever-getting-back-together':
        "The contract ended without a word. Then he turned up as her "
        "boss.\nLisa's contract marriage to Aidan ends without warning "
        "and without explanation. What stayed with her is that she always "
        "valued him more than he ever valued her. When they cross paths "
        "again she takes her moment and leaves him a note he will not "
        "enjoy reading but then she starts at her new job, and now Aidan "
        "is the man she is reporting to.",

    # 115.3M   Big Bad Husband, Please Wake Up!
    # FACTS: Ciara marries comatose billionaire Adrian to save her sick family. Then he wakes up.
    'big-bad-husband-please-wake-up':
        "Her groom is in a coma on the wedding day."
        "\nCiara agrees to marry Adrian Lewis while he is lying unconscious, "
        "because her family are sick and the money is the only thing that "
        "saves them. She is humiliated by the choice and carries that for as "
        "long as it lasts. Then Adrian opens his eyes.",

    # 115.2M   The Return of the Lost Heiress
    # FACTS: Mute since her father's death, lost heiress Lana is adopted by a loving stranger while h
    # FACTS: er birth family unknowingly mistreats the daughter they keep searching for.
    'the-return-of-the-lost-heiress':
        "She stopped speaking the day her father died."
        "\nLana watches her father die and never says another word after it. "
        "Escaping the guard who tries to sell her, she is lost, and it is Ron "
        "who finds her and raises her with every bit of the love a father "
        "has. Her birth family never stop searching for her in all the years "
        "that follow. When she finally stands in front of them they do not "
        "know who she is, and they treat her accordingly.",

    # 114.4M   Secret Surrogate to the Mafia King
    # FACTS: Selling her eggs to pay her boyfriend's debt, Vanessa ends up pregnant by clinical error
    # FACTS: ; the father is ruthless Mafia King Marcello Lavigne, who moves her into his mansion and
    # FACTS:  proves his devotion as she decides whether to become queen of his empire.
    'secret-surrogate-to-the-mafia-king':
        "She goes in to sell her eggs and leaves pregnant."
        "\nVanessa Peters sells her eggs to clear her boyfriend's debt, and a "
        "mistake at the clinic leaves her carrying a child instead. She finds "
        "out he has been cheating on her, decides to keep the baby anyway, "
        "and only then learns whose it is. Marcello Lavigne is a ruthless "
        "and murderous mafia king, and his answer is to move her "
        "into his mansion where he can keep her safe.",

    # 111.8M   Escorting the Ruthless Billionaire Doctor
    # FACTS: Desperate to fund her father's surgery, Violet meets Dax, a billionaire doctor determine
    # FACTS: d to pull her back from the edge.
    'escorting-the-ruthless-billionaire-doctor':
        "Her father needs surgery and she has nothing left to sell."
        "\nViolet cannot pay for her father's operation and decides to sell "
        "her virginity to cover it. The doctor who answers determinedly tries "
        "to change her very dangerous decision. They end up spending the "
        "night together anyway, and afterwards Dax cannot get her out of his "
        "head even while he is sure she is just another gold digger. And "
        "still neither of them has told the truth about themselves yet. Wait "
        "until they find out.",

    # 111.0M   Open Your Eyes, My Billionaire Husband
    # FACTS: Desperate for her mother's medical bills, Hailey marries comatose billionaire Samuel Tre
    # FACTS: nt, who soon wakes to find himself engaged to a stranger.
    'open-your-eyes-my-billionaire-husband':
        "Her mother's care comes at the price of a husband who cannot object."
        "\nHailey has no way to cover her mother's medical bills, and her "
        "family will only step in on one condition. She has to marry Samuel "
        "Trent, a billionaire who has been unconscious since a car accident "
        "nearly killed him. She takes the deal, because there is no other way "
        "to pay for her mother's care. Then Samuel wakes up and finds out he is "
        "engaged to a woman he has never met.",

    # 109.9M   The Hidden Billionaire in First Class
    # FACTS: They all thought Jett Hawkings was a lowly baggage handler and threatened to throw him o
    # FACTS: ff the flight.
    'the-hidden-billionaire-in-first-class':
        "They want the baggage handler thrown off the plane."
        "\nEveryone in the cabin has Jett Hawkings pegged as a lowly baggage "
        "handler who does not belong up there with them, and they push to "
        "have him removed from the flight. Then a storm hits and the plane "
        "starts going down. The passenger they spent the whole journey "
        "looking down on is not a baggage handler at all.",

    # 109.3M   The Tutor Trap
    # FACTS: School hockey star Brady asks brainy wallflower Harper to be his chemistry tutor.
    'the-tutor-trap':
        "Chemistry lessons in exchange for a fake boyfriend"
        "\nBrady is the school hockey star and he needs a chemistry tutor, so "
        "he asks Harper. Harper is the brainy wallflower nobody "
        "notices, and what she wants is the boy she has a crush on. So the "
        "deal they strike is that Brady plays her fake boyfriend, teaches her "
        "how to flirt, and helps her land him. The contract covers everything "
        "but the chemistry is not staying on paper.",

    # 109.2M   Resisting Mr. Lloyd: An Age Gap Romance
    # FACTS: Pressured to quit college and marry, Clarisse meets Lloyd Group CEO Austin, who offers m
    # FACTS: oney for a fake marriage to fulfill his grandmother's wish while hiding his true identit
    # FACTS: y.
    'resisting-mr-lloyd-an-age-gap-romance':
        "Her family want her out of college and married off."
        "\nClarisse is under pressure at home to drop her degree and find a "
        "husband. Then she helps an older woman who has been scammed, and she "
        "meets the woman's grandson Austin. He runs the Lloyd Group, "
        "and what he offers is money for a fake marriage that gives his "
        "grandmother the wedding she keeps asking for. Clarisse takes the "
        "arrangement but Austin never tells her who he actually is.",

    # 107.6M   The Quarterback Next Door
    # FACTS: Invisible Skylar is paired with her crush and childhood best friend Jamie on a project, 
    # FACTS: then forced to live with him when his house burns down, while his crazy ex plots against
    # FACTS:  them.
    'the-quarterback-next-door':
        "She asks out her best friend and the whole school watches it go "
        "wrong."
        "\nSkylar Heron has spent her life being invisible, and senior year "
        "opens with her asking Jamie Donner out in front of everybody and "
        "being humiliated for it. Jamie has been her best friend and the boy "
        "next door since they were children. They get paired for a class "
        "project, and then his house burns down and he moves into her room. "
        "His ex girlfriend makes life difficult for both of them, so they "
        "set about turning Skylar into the most popular girl in "
        "school.",

    # 107.0M   Once Upon A Breakup
    # FACTS: After being abandoned on her birthday by her college boyfriend, Mia impulsively proposes
    # FACTS:  to Carson, the charming but dangerous leader of the Moretti crime family.
    'once-upon-a-breakup':
        "Dumped on her birthday, engaged to a crime boss."
        "\nMia's college boyfriend walks out on her on her birthday, and she "
        "answers it by proposing to the first man in front of her. Carson is "
        "charming, and he runs the Moretti crime family, which makes the "
        "whole thing a spectacularly bad escape plan. It becomes something "
        "real anyway. Her ex is not letting go though, and he is jealous "
        "enough to come after the life she is building.",

    # 106.8M   Accidental Triplets with the Billionaire
    # FACTS: Needing an heir, Oscar turns to surrogacy but his sperm is accidentally given to Phoebe 
    # FACTS: during a gynecological exam; a contract marriage follows to keep the baby.
    'accidental-triplets-with-the-billionaire':
        "She goes in for a routine exam and leaves pregnant."
        "\nOscar needs an heir quickly to hold on to his position at the "
        "company, so he arranges a surrogacy. A mistake at the clinic puts "
        "his sperm into Phoebe instead, who is only there for a "
        "gynaecological exam. He wants the baby kept, and the way he proposes "
        "to guarantee that is a contract marriage. Neither of them is ready "
        "for what the arrangement asks of them.",

    # 106.3M   You Fired A Tech Genius
    # FACTS: Fired by his CEO's son, Silicon Valley genius Erik joins the rival company and bankrupts
    # FACTS:  his old employer.
    'you-fired-a-tech-genius':
        "Firing him was the most expensive decision in the building."
        "\nErik is the biggest name in tech in the whole of Silicon Valley, "
        "right up until his boss's son sacks him. William makes that call. "
        "What Erik does next is walk straight across to the competition, "
        "where Evelyn runs the company that has spent years trying to beat "
        "his old one.",

    # 106.2M   Submitting to My Ex's Dad
    # FACTS: After catching her fiancé cheating with her best friend just before their wedding, Flora
    # FACTS:  runs away and has a wild one-night stand with a handsome stranger.
    'submitting-to-my-ex-s-dad':
        "She catches her fiance with her best friend days before the wedding."
        "\nFlora finds them together with the wedding just around the "
        "corner, so she runs. The night she spends with a handsome "
        "stranger afterwards is meant to be a fling and nothing more. That "
        "is not how things play out though because his identity is not as "
        "simple as it seems, and because of what he is keeping quiet.",

    # 106.0M   The Billionaire's Virgin Surrogate
    # FACTS: What happens when a student surrogate proposes to her client that they should conceive t
    # FACTS: he baby the natural way?
    'the-billionaire-s-virgin-surrogate':
        "Saving her father costs her nine months and rather more besides."
        "\nHarper agrees to carry a baby for Will Trenton because her father "
        "needs saving and this is what pays for it. Will is a single "
        "billionaire and the arrangement is meant to be purely clinical. "
        "Harper is a student, and the provocative proposal she puts to him is "
        "that the two of them conceive the baby naturally rather than "
        "artificially. Harper knows she is falling for him but does he feel "
        "the same?",

    # 105.1M   Obsessed with His Silent Bride
    # FACTS: Nonverbal Eva endures a marriage of duty to her childhood protector Declan while his mis
    # FACTS: tress schemes to drive her out.
    'obsessed-with-his-silent-bride':
        "She has loved him since he was the boy protecting her."
        "\nEva grew up a ward of the Calvert family, and Declan Calvert was "
        "the one who looked after her. She has loved him ever since. "
        "Nonverbal since birth, she has no easy way of telling him so, and "
        "the marriage they end up in is built on duty and nothing warmer. "
        "Declan married her only to honour his grandfather's dying wish, "
        "nothing more. So she is left to endure Declan's cruelty. His "
        "mistress Selene meanwhile works relentlessly to drive her away.",

    # 104.4M   The Billionaire Married a Homeless Girl
    # FACTS: After a one-night stand Adele Moore becomes pregnant; her father kicks her out and with 
    # FACTS: nowhere to go her life takes a billionaire turn.
    'the-billionaire-married-a-homeless-girl':
        "Her father put her out for keeping the baby."
        "\nAdele Moore gets pregnant after one night with a stranger, and "
        "when she says she is keeping the child her father throws her out of "
        "the house. She and her son Brad become homeless. She does her best "
        "to give her son everything she can. Years later Brad runs into a "
        "billionaire called Heston Deleon by pure chance, and Heston works "
        "out that the boy is his. He loses their trail before he can reach "
        "them but he and Adele are destined to find their way back to each "
        "other.",

    # 104.0M   Swapped My Ex for His Billionaire Uncle
    # FACTS: Divorced and done with love, Nina is relentlessly pursued by Damon, her ex-husband's you
    # FACTS: ngest uncle.
    'swapped-my-ex-for-his-billionaire-uncle':
        "She is finished with love and finished with that family."
        "\nNina once believed the best day of her life would be the one she "
        "walked down the aisle towards Evan, her college sweetheart. Then he "
        "betrayed her, they divorced, and she decided she was never doing any "
        "of it again. Damon is Evan's youngest uncle, and he keeps appearing "
        "out of nowhere to drive her crazy. Nina wants nothing more to do "
        "with that whole family but Damon is not taking the hint.",

    # 102.9M   CEO's Twins Want Mommy Back
    # FACTS: Cassandra's flash marriage with a loving husband and cute stepkids seems too good to be 
    # FACTS: true; her troubled past closes in and the kids seem strangely familiar.
    'ceo-s-twins-want-mommy-back':
        "A husband, two stepkids, and a flash marriage."
        "\nCassandra flash marries a man who adores her, and two stepchildren "
        "who are adorable come as a package deal. It is a better deal than "
        "she was expecting to get. But there is something about those "
        "children she cannot quite place. She better figure it out fast "
        "though as her past is about to catch up to her.",

    # 102.9M   Trapped in the Boss's Embrace
    # FACTS: Secretly married to college sweetheart Desmond for ten years, Beatrice discovers his aff
    # FACTS: air with a wealthy socialite and everything changes.
    'trapped-in-the-boss-s-embrace':
        "Ten years of a marriage nobody knew about."
        "\nBeatrice Lawson eloped with Desmond Belmont in college and has "
        "been quietly married to him ever since. Then she finds out about the "
        "wealthy socialite he has been seeing, and she files for divorce. "
        "What she wants after that is her own life back rather than any more "
        "time spent living in his shadow, so she gets a new apartment and a "
        "career. Then Damian Crowley walks into her brand new life.",

    # 99.8M    The Billionaire's Masquerade
    # FACTS: To claim her late father's inheritance Shelby must marry, so she weds poor stranger Grif
    # FACTS: fin, unaware he is a billionaire who has admired her since a chance meeting three years 
    # FACTS: ago.
    'the-billionaire-s-masquerade':
        "The inheritance is hers on one condition. She has to be married."
        "\nShelby's father leaves her everything and attaches terms, the main "
        "one being a wedding before she can claim any of it. So she marries a "
        "stranger with nothing to his name, which is the cheapest way of "
        "satisfying the paperwork. But Griffin is not poor. He is a "
        "billionaire, and he has had Shelby in mind since the last time the "
        "two of them met three years ago.",

    # 99.8M    Never Divorce a Secret Billionaire Heiress
    # FACTS: Joyce served as a walking blood bank for her sister Selena as the price of forcing Trist
    # FACTS: an to marry her; after losing her baby with no support, the secret heiress demands a div
    # FACTS: orce.
    'never-divorce-a-secret-billionaire-heiress':
        "Being her sister's blood bank is what the marriage costs her."
        "\nJoyce forced Tristan into marrying her, and the price of that has "
        "been years of giving her blood to her sister Selena whenever it is "
        "asked for. Then she loses her baby, and her husband is not there for "
        "any of it. That is when she stops hoping and files for divorce.",

    # 98.7M    Runaway Single Mom, Safe in His Arms
    # FACTS: Single mom Maria escapes abuse and fights to protect her daughter through factory strugg
    # FACTS: les, family betrayal and unexpected love when billionaire Levi enters her life.
    'runaway-single-mom-safe-in-his-arms':
        "She gets herself and her daughter out."
        "\nMaria leaves an abusive situation with her daughter Judy and "
        "starts again from nothing. With enemies around every corner from her "
        "workplace to her daughter's elite schools. She stands against "
        "everyone including her own family who let her down. Then Levi comes "
        "into her life and everything changes.",

    # 98.0M    Escorting the Heiress
    # FACTS: Serena catches her boyfriend cheating with her half-sister, gets drunk, and lands in the
    # FACTS:  bed of Jesse, a man who has loved her for years and is not the escort she assumed.
    'escorting-the-heiress':
        "He said he was waiting until marriage. Not with her, as it happens."
        "\nSerena finds her boyfriend Ken in bed with Carol, her half sister, "
        "after years of him telling her he was saving himself for the "
        "wedding. She gets furious, gets drunk, and ends up with Jesse "
        "instead. She is under the impression she has hired him for the night "
        "but Jesse has been in love with her for years.",

    # 97.6M    The Billionaire's Accidental Bride
    # FACTS: Stood up and cheated on by her fiance, Claire marries stranger Christian Cross on the sp
    # FACTS: ot while both are stranded.
    'the-billionaire-s-accidental-bride':
        "Stood up by her fiance, married by the end of the night."
        "\nClaire Duval is happily engaged to Dylan Maxwell right up until "
        "she learns he has been seeing her friend Ava. Stranded that evening "
        "with nothing much left to lose, she quietly marries Christian Cross "
        "instead. An unexpected marriage they both take a chance on.",

    # 97.2M    Dominated by My Dad's Boss
    # FACTS: Jayne's secret arrangement with a stranger turns risky when he proves to be the man over
    # FACTS: seeing her father's exit from the family company.
    'dominated-by-my-dad-s-boss':
        "She asks a stranger at a party to teach her how to dominate."
        "\nJayne Turner wants to learn to be a dominatrix, so she puts the "
        "question to a man at a bondage party. He is the one handling her "
        "father's exit from the family company. They keep the relationship "
        "quiet, which gets harder with a morality clause hanging over them "
        "and threatening messages arriving about Jayne's late mother.",

    # 96.3M    The Senator's Son
    # FACTS: Class president Emma hides that she is a poor girl at a wealthy school; rival Zach Walke
    # FACTS: r hires her as his personal maid. Interactive vertical.
    'the-senator-s-son':
        "All she wants is a quiet degree."
        "\nEmma Andrews arrives at college planning to keep her head down, "
        "and Zach Walker makes that impossible. He is a famous senator's son "
        "and the most wanted boy on campus, and he singles her out for "
        "relentless bullying. Then they get trapped in a boathouse together "
        "with nothing to do but talk, and Emma starts seeing what is really "
        "underneath the big man on campus act.",

    # 95.8M    Mic Drop Diva
    # FACTS: High-school sophomore Ivy, a secretly wealthy heiress with an angelic voice, is used as 
    # FACTS: a voice double by fake bestie Vanessa; after catching her boyfriend cheating with Vaness
    # FACTS: a she reclaims her spotlight with quarterback Blake.
    'mic-drop-diva':
        "She hides the money so she can find out who her real friends are."
        "\nIvy is a sophomore with a voice people stop for, and an heiress "
        "fortune she keeps to herself because she wants friends who like her "
        "rather than it. Vanessa looks like proof that it worked. She is in "
        "fact treating Ivy as a tool, and guilt tripping her into singing as "
        "her voice double. Then Ivy catches her boyfriend with that same best "
        "friend, and the person she goes to is Blake, her childhood best "
        "friend and the school's star quarterback.",

    # 95.5M    Djinn Under Contract
    # FACTS: Eli Baran is a genie in a magic lamp who can grant three wishes.
    'djinn-under-contract':
        "His freedom comes with five years of marriage attached."
        "\nEli Baran has spent thousands of years inside a lamp granting "
        "wishes in threes. A billionaire spends his last one setting Eli "
        "free, and puts a condition on it: five years married to his "
        "granddaughter Christine Parrish. Eli takes human form and quietly "
        "builds Christine into a successful CEO without ever telling her he "
        "is doing it. She spends the whole marriage looking down on him. "
        "Little does she know that without Eli her life will be much harder "
        "and time is running out.",

    # 95.1M    True Luna
    # FACTS: Grace Swanson credit.
    'true-luna':
        "Getting her wolf came with a warning attached."
        "\nEmma is a true Luna, which is a rare thing to be and a powerful "
        "one. Her wolf arrives with a warning alongside it, because the rogue "
        "king is coming for her. At the same time she finds her mate and it "
        "should be the best thing that has ever happened to her, but he "
        "rejects her instead.",
}

FACTS = {
    # Fetched from each title's own ReelShort page, 16 Aug 2026. EVERY ONE of these
    # held a truncated fragment on disk - 27 to 197 characters - against a full
    # published synopsis. Episode counts recorded for the parked later pass.
    'reborn-to-love-mr-right':
        "Arianna dies a tragic death on the day of her graduation, while Derek, the "
        "driver's son, takes all the spotlight on stage. She gave him everything, her "
        "car, her credit card, even her father's company, only to be used and "
        "discarded. While he spoiled Ivy like a princess, he treated Arianna like a "
        "servant. Only in death does she realize that Hayden, the billionaire's heir, "
        "had been waiting for her all along. Now, fate gives her a second chance to "
        "make things right. 91 episodes.",
    'love-at-dangerous-speeds':
        "When Violet flees her abusive fiance on their wedding day, she hides with "
        "Marcus, a notorious street racer. Their protection for a kiss deal ignites "
        "into passion, giving her the freedom she craves. Then Marcus confesses a "
        "dark secret: the hit and run accident that haunts him killed Violet's "
        "father. 71 episodes.",
    'mr-hills-adorable-wife':
        "Valerie Patterson almost lost out a luxurious life with a billionaire lover "
        "after the Patterson family nearly succeeded in exchanging her with her "
        "sister, Daphne. Born with a birthmark which her mother considered ugly, "
        "Valerie was ignored by her family until Andrew Hills fell in love with her. "
        "85 episodes.",
    'we-will-love-again':
        "Noah Preston returns as a billionaire after six years of being away, and his "
        "fiancee breaking up with him because he was poor. His fiancee did not "
        "genuinely want to end their relationship, his mother forced her to do so. "
        "Noah initially seeks revenge but ultimately discovers the truth behind the "
        "breakup. 53 episodes.",
    'the-billionaire-s-baby-bargain':
        "To save her dying sister, Abby, Amelia agrees to a contract marriage that "
        "will involve no sex, no love, and a baby by insemination. The arrangement "
        "was instigated by Nathan, a billionaire struggling to regain his position as "
        "CEO by fulfilling his father's wish. As they navigate their false marriage, "
        "unexpected feelings develop. 76 episodes.",
    'claimed-by-the-alpha-i-hate':
        "All her life, Daisy Storm never knew what was wrong with her. Why couldn't "
        "she shift? Why didn't she have a wolf? Despite being rejected by her pack "
        "and her original mate on her eighteenth birthday, Daisy finds herself drawn "
        "to Nolan Fenrir, the Alpha she blames for her mother's mysterious death. An "
        "unnatural pull develops between them despite their conflicted history. "
        "73 episodes.",
    'do-not-disturb-lady-boss-in-disguise':
        "To become the heiress of her family hotel chain, Violet Trenton goes "
        "undercover as a cleaning lady and takes out the troublemakers one by one. "
        "Kasey Johnson is the COO. 81 episodes.",
    'claimed-by-my-ex-s-alpha-brother':
        "Ella is wolfless amongst the wolves, but at least she has her mate, Beta "
        "Noah Gravens, until she catches him cheating with her rival Ava. Shattered, "
        "Ella falls straight into the arms of Noah's brother, Liam Gravens, the newly "
        "returned Alpha of the Crescent Pack, who has loved her since childhood and "
        "knows she's his fated mate. But with jealous rivals, bitter exes, and two "
        "worlds pulling them apart, can Ella and Liam embrace the love they are "
        "destined for? 64 episodes.",
    'dear-husband-delete-my-number':
        "Emma got into a car accident and when she tried to reach her husband, "
        "Elijah, he ignored her to be with his wanna-be girlfriend, Stella. Emma "
        "decides to divorce Elijah after discovering Stella might be pregnant with "
        "his child. Emma refused any financial settlement, which confused Elijah who "
        "had assumed she was motivated by money. 88 episodes.",
    'pregnant-by-my-ex-s-professor-dad':
        "On her first day of the semester, Emily catches her boyfriend cheating on "
        "her. That night, she has a wild one night stand with a stranger named "
        "Charles. The next day, they are mutually shocked to find out that Charles is "
        "Emily's new professor. They maintain a professional student teacher "
        "relationship, but there's an undeniable tension between them. Just when "
        "Emily thinks everything will get back on track, she unexpectedly finds out "
        "she's pregnant. 63 episodes.",
    'the-reckoning-takes-flight':
        "Eve takes a flight to Hawaii to attend her big brother's wedding, booking an "
        "extra wide seat because of her broken leg in a cast. A nasty woman and her "
        "bratty son demand Eve switch seats with them. The kid trips because of "
        "turbulence, his mom demands the flight turn back and fights the pilots, "
        "forcing an emergency landing. The mom's sister, Clara, shows up to back her "
        "up. Clara accuses Eve of being her fiancee's mistress, not realizing that "
        "she's her fiancee's little sister. The wedding is canceled, and Clara is "
        "sent to jail. 41 episodes.",
    'you-belong-with-me':
        "Kristine was betrayed by her boyfriend and best friend. She knew about him "
        "cheating on her while riding on her intelligence. Kristine decided to get "
        "back at him by sleeping with his rich uncle, Henry. Henry was aware he was "
        "being used as Kristine made it clear to him. But what started as revenge "
        "changed into genuine feelings. 79 episodes.",
    'my-secret-lover-is-his-brother':
        "To forgive Piper's family debt, she's promised to marry one of the Bellfort "
        "brothers. Will she choose the star lacrosse player Drew? Or the handsome "
        "loner Noah? How can she decide when she has a connection with both? "
        "74 episodes.",
    'the-ceo-s-contract-wife':
        "Jasper Tate needed a wife urgently, while Chloe Adams needed money urgently. "
        "Seeking help from the same source leads the two needy people together, and "
        "they get married after Madam G recommended them to each other. What was "
        "supposed to be a contract agreement morphed into a full blown love affair "
        "that they never expected. 93 episodes.",
    'kiss-me-one-last-time':
        "Adeline has cancer. A few months to live and she'll be dead. The one thing "
        "she needed was her husband, Blake's love. She couldn't get it as he never "
        "saw her as his wife rather as a blood bank for her step sister. 90 episodes.",
    'we-are-never-ever-getting-back-together':
        "Lisa's contract marriage with Aidan ended without notice. She was agitated "
        "that he never valued her as much as she valued him. When they crossed paths "
        "again, she took her chance with him leaving an ill note on his chest. Lisa "
        "didn't know she would be seeing Aidan again, this time, as her boss. "
        "103 episodes.",
    'big-bad-husband-please-wake-up':
        "Ciara is slated to get married to Adrian Lewis, who is in a coma. Ciara is "
        "desperate to do so because she needs the money to save her sick family, and "
        "she is humiliated by her choice until Adrian wakes up to the surprise of "
        "everyone and falls in love with Ciara. 104 episodes.",
    'the-return-of-the-lost-heiress':
        "Lana experienced her father's death. This made her never speak again. She "
        "became a mute. A few days later, she was lost while escaping being sold by "
        "her guard. Lana was found and adopted by Ron who showered her with fatherly "
        "love. Years passed and her birth family kept searching for her. Unaware of "
        "Lana's identity, they mistreated her. 90 episodes.",
    'secret-surrogate-to-the-mafia-king':
        "Vanessa Peters is in for a surprise when she goes to sell her eggs to pay "
        "off her boyfriend's debt and ends up pregnant due to a clinical error. She "
        "decides to keep the child after finding out her boyfriend is cheating on "
        "her, but begins to fear her decision when she finds out that the father is "
        "no other than Marcello Lavigne, a ruthless, murderous Mafia King. Marcello "
        "protects Vanessa and moves her to his mansion. 63 episodes.",
    'escorting-the-ruthless-billionaire-doctor':
        "Violet, desperate to pay for her father's surgery, decides to sell her "
        "virginity, but the good doctor she calls is determined to pull her back from "
        "the edge. However, as the two share a heated, unforgettable night, Dax finds "
        "himself hooked on Violet, despite thinking she's just another gold digger. "
        "When their darkest secrets are laid bare, will their fragile connection "
        "survive? 68 episodes.",
    'open-your-eyes-my-billionaire-husband':
        "Hailey is cash strapped and desperate for a way to pay her mother's hefty "
        "medical bills. Her family agrees to help her, on the condition she marries "
        "the billionaire Samuel Trent, who is in a coma after a near fatal car "
        "accident. Samuel awakens from his coma and discovers he has been engaged to "
        "a complete stranger. 72 episodes.",
    'the-hidden-billionaire-in-first-class':
        "They all thought Jett Hawkings was a lowly baggage handler and threatened to "
        "throw him off the flight. But when their plane is about to crash due to a "
        "storm, he's actually the secret billionaire that can save them. 83 episodes.",
    'the-tutor-trap':
        "School hockey star Brady asks brainy wallflower Harper to be his chemistry "
        "tutor. In exchange, he promises to be her fake boyfriend, teach her how to "
        "flirt, and help her land her crush. But what will happen when their contract "
        "backfires, and the chemistry becomes more than just on paper? 78 episodes.",
    'resisting-mr-lloyd-an-age-gap-romance':
        "Facing family pressure to quit college and marry, Clarisse's world changes "
        "when she meets Austin, the CEO of Lloyd Group, after helping his grandmother "
        "following a scam. Austin offers her money for a fake marriage to fulfil his "
        "grandmother's wish, forming an unexpected alliance while keeping his true "
        "identity secret from her. 70 episodes.",
    'the-quarterback-next-door':
        "Forever invisible Skylar Heron hasn't started her senior year so hot. First, "
        "she's embarrassed in front of the whole school when trying to ask out her "
        "crush Jamie Donner, her childhood best friend and next door neighbour. "
        "Skylar and Jamie are paired for a class project, then Jamie moves into her "
        "room after his house burns down. His ex girlfriend creates conflict, "
        "prompting them to transform Skylar into the school's most popular girl. "
        "87 episodes.",
    'once-upon-a-breakup':
        "After being abandoned on her birthday by her college boyfriend, Mia "
        "impulsively proposes to Carson, the charming but dangerous leader of the "
        "Moretti crime family. Though their relationship begins as a rash escape, it "
        "quickly turns into something real. But Mia's ex refuses to let go. Obsessed, "
        "jealous, and spiraling out of control, he'll stop at nothing to win her "
        "back, even if it means destroying the new life Mia's trying to build with "
        "Carson. 60 episodes.",
    'accidental-triplets-with-the-billionaire':
        "Urgently needing an heir to secure his position in the company, Oscar turns "
        "to surrogacy. But unexpectedly, his sperm is accidentally injected into "
        "Phoebe, who comes in for a gynecological exam. To ensure Phoebe keeps the "
        "baby, Oscar proposes a contract marriage, and the two embark on a journey "
        "filled with tests. 91 episodes.",
    'you-fired-a-tech-genius':
        "After Erik, the biggest tech hotshot in all of Silicon Valley, gets sacked "
        "by his CEO's son William, he joins forces with Evelyn, the beautiful CEO of "
        "his old company's competitor. 59 episodes.",
    'submitting-to-my-ex-s-dad':
        "After catching her fiance cheating with her best friend just before their "
        "wedding, Flora runs away and has a wild one night stand with a handsome "
        "stranger. Little does she know he's her ex fiance's father, and he has a "
        "dark secret. 56 episodes.",
    'the-billionaire-s-virgin-surrogate':
        "Desperate to save her father, Harper agrees to carry a baby for Will "
        "Trenton, a single billionaire. As their worlds collide and the boundaries "
        "blur, Harper finds herself irresistibly drawn to Will. But beneath the "
        "surface, a question remains: is Will feeling the same? The student surrogate "
        "proposes to her client that they conceive the baby naturally instead of "
        "through artificial means. 64 episodes.",
    'obsessed-with-his-silent-bride':
        "Taken in as a ward of the Calvert family, Eva has always loved Declan "
        "Calvert, the boy who grew up as her protector. Nonverbal since birth, she "
        "struggles to express her feelings in a marriage built on duty. Declan only "
        "married her to honour his grandfather's dying wish. Trapped in a toxic "
        "union, Eva endures Declan's cruelty and his mistress Selene's relentless "
        "schemes to drive her out. 85 episodes.",
    'the-billionaire-married-a-homeless-girl':
        "After a one night stand, Adele Moore becomes pregnant. She wants to keep the "
        "child, but her father kicks her out of the house. With nowhere else to go, "
        "Adele becomes homeless. She tries her best to raise her son despite her "
        "challenging circumstances. One day, Adele's son, Brad Moore, runs into "
        "billionaire Heston Deleon. By chance, Heston discovers that Brad is his son. "
        "He tries to track down Brad, but loses their trail. Through a series of "
        "misunderstandings, Adele and Heston become entangled again. 58 episodes.",
    'swapped-my-ex-for-his-billionaire-uncle':
        "There was a time when Nina believed her happiest moment would be walking "
        "down the aisle with Evan, her college sweetheart. But betrayal shattered "
        "that dream. After divorcing Evan, Nina refuses to love again, until Damon, "
        "Evan's youngest uncle, persistently enters her life despite her resistance "
        "to maintaining family connections. 80 episodes.",
    'ceo-s-twins-want-mommy-back':
        "With a loving hubby and cute stepkids, Cassandra's flash marriage seems too "
        "good to be true. But will her troubled past catch up to her? And why do the "
        "kids seem so familiar? 105 episodes.",
    'trapped-in-the-boss-s-embrace':
        "Lovestruck, Beatrice Lawson eloped with her college sweetheart Desmond "
        "Belmont and has been secretly married to him for ten years. However, when "
        "she discovers his affair with a wealthy socialite, Beatrice decides to "
        "divorce him and finally stop living in his shadow. As she begins to make a "
        "name for herself with a new apartment and new career, she meets the "
        "mysterious and attractive Damian Crowley. 87 episodes.",
    'the-billionaire-s-masquerade':
        "After Shelby's father died, he passed on his inheritance to her with "
        "unfavourable conditions. She must get married to claim her inheritance. To "
        "claim it, she marries a poor stranger, Griffin. She didn't know that Griffin "
        "wasn't a poor man as she had thought. He's a billionaire who had admired "
        "Shelby from their last encounter, three years ago. 79 episodes.",
    'never-divorce-a-secret-billionaire-heiress':
        "Joyce has been a walking blood bank for her sister, Selena. It was the price "
        "she had to pay for forcing Tristan into marrying her. Joyce realises her "
        "situation when she loses her baby without receiving support from her "
        "husband, and subsequently seeks a divorce. 55 episodes.",
    'runaway-single-mom-safe-in-his-arms':
        "Single mom Maria escapes abuse and fights to protect her daughter, Judy. "
        "From factory struggles to elite schools, she faces enemies, family betrayal, "
        "and unexpected love. When billionaire Levi enters her life, everything "
        "changes. 57 episodes.",
    'escorting-the-heiress':
        "Serena caught her boyfriend, Ken, cheating on her with her half sister, "
        "Carol. He had always lied about holding it all in till marriage. Furious by "
        "their actions, Serena gets drunk and ends up in the bed of Jesse. She "
        "thought he was her escort but he was a man who has been in love with her for "
        "years. 74 episodes.",
    'the-billionaire-s-accidental-bride':
        "Claire Duval and Christian Cross get married by chance. Claire was glad to "
        "have gotten engaged with Dylan Maxwell until he stood her up and she found "
        "out that he was cheating on her with her friend, Ava. Claire secretly got "
        "married to Christian on the spot as they were both stranded. 82 episodes.",
    'dominated-by-my-dad-s-boss':
        "When Jayne Turner asks a stranger at a bondage party to teach her how to be "
        "a dominatrix, she has no idea he'll turn out to be the man overseeing her "
        "father's exit from the family company. Their secret relationship is "
        "complicated by a morality clause and threatening messages connected to "
        "Jayne's deceased mother. 73 episodes.",
    'the-senator-s-son':
        "Emma Andrews wants to lead a quiet life in college, but that's impossible "
        "when Zach Walker, son of a famous senator and the hottest guy on campus, "
        "targets her for relentless bullying. An enemies to lovers arc where the two "
        "are unexpectedly trapped together in a boathouse, leading Emma to discover "
        "hidden depths beneath Zach's bully facade.",
    'mic-drop-diva':
        "Ivy is a high school sophomore with the voice of an angel. She's also a "
        "super wealthy heiress, but she hides her identity in the hopes of making "
        "real friends at school. After becoming besties with Vanessa, she thinks "
        "she's made the right choice. But Vanessa actually treats Ivy like a total "
        "tool, and even guilt trips Ivy into being her voice double. Things start to "
        "fall apart after Ivy catches her boyfriend cheating on her with her bestie. "
        "Heartbroken and betrayed, Ivy seeks help from her childhood best friend and "
        "star quarterback, Blake. 52 episodes.",
    'djinn-under-contract':
        "Eli Baran is a genie in a magic lamp who can grant three wishes. After "
        "thousands of years, a billionaire uses his last wish to grant Eli freedom, "
        "but on one condition: Eli must marry his granddaughter, Christine Parrish, "
        "for five years. Eli transforms into human form and secretly helps Christine "
        "become a successful CEO. However, Christine belittles him throughout their "
        "marriage. 67 episodes.",
    'true-luna':
        "Emma is a powerful wolf known as the true Luna. Her kind is rare. When she "
        "got her wolf, a warning came along with it. Emma will be in danger soon as "
        "the rogue king is after her. Her joy of getting a wolf and finding a mate is "
        "torn when her mate rejects her. 61 episodes.",
}

# WHERE EACH FACT SOURCE CAME FROM. Cyan, 16 Aug 2026: be clear whether the
# text came from a third party website or the PDFs she supplied.
# kind -> caption_pipeline.SOURCE_KINDS.
SOURCES = {
    'accidental-triplets-with-the-billionaire': ('platform', 'reelshort.com own page'),
    'big-bad-husband-please-wake-up': ('platform', 'reelshort.com own page'),
    'ceo-s-twins-want-mommy-back': ('platform', 'reelshort.com own page'),
    'claimed-by-my-ex-s-alpha-brother': ('platform', 'reelshort.com own page'),
    'claimed-by-the-alpha-i-hate': ('platform', 'reelshort.com own page'),
    'dear-husband-delete-my-number': ('platform', 'reelshort.com own page'),
    'djinn-under-contract': ('platform', 'reelshort.com own page'),
    'do-not-disturb-lady-boss-in-disguise': ('platform', 'reelshort.com own page'),
    'dominated-by-my-dad-s-boss': ('platform', 'reelshort.com own page'),
    'escorting-the-heiress': ('platform', 'reelshort.com own page'),
    'escorting-the-ruthless-billionaire-doctor': ('platform', 'reelshort.com own page'),
    'kiss-me-one-last-time': ('platform', 'reelshort.com own page'),
    'love-at-dangerous-speeds': ('platform', 'reelshort.com own page'),
    'mic-drop-diva': ('platform', 'reelshort.com own page'),
    'mr-hills-adorable-wife': ('platform', 'reelshort.com own page'),
    'my-secret-lover-is-his-brother': ('platform', 'reelshort.com own page'),
    'never-divorce-a-secret-billionaire-heiress': ('platform', 'reelshort.com own page'),
    'obsessed-with-his-silent-bride': ('platform', 'reelshort.com own page'),
    'once-upon-a-breakup': ('platform', 'reelshort.com own page'),
    'open-your-eyes-my-billionaire-husband': ('platform', 'reelshort.com own page'),
    'pregnant-by-my-ex-s-professor-dad': ('platform', 'reelshort.com own page'),
    'reborn-to-love-mr-right': ('platform', 'reelshort.com own page'),
    'resisting-mr-lloyd-an-age-gap-romance': ('platform', 'reelshort.com own page'),
    'runaway-single-mom-safe-in-his-arms': ('platform', 'reelshort.com own page'),
    'secret-surrogate-to-the-mafia-king': ('platform', 'reelshort.com own page'),
    'submitting-to-my-ex-s-dad': ('platform', 'reelshort.com own page'),
    'swapped-my-ex-for-his-billionaire-uncle': ('platform', 'reelshort.com own page'),
    'the-billionaire-married-a-homeless-girl': ('platform', 'reelshort.com own page'),
    'the-billionaire-s-accidental-bride': ('platform', 'reelshort.com own page'),
    'the-billionaire-s-baby-bargain': ('platform', 'reelshort.com own page'),
    'the-billionaire-s-masquerade': ('platform', 'reelshort.com own page'),
    'the-billionaire-s-virgin-surrogate': ('platform', 'reelshort.com own page'),
    'the-ceo-s-contract-wife': ('platform', 'reelshort.com own page'),
    'the-hidden-billionaire-in-first-class': ('platform', 'reelshort.com own page'),
    'the-quarterback-next-door': ('platform', 'reelshort.com own page'),
    'the-reckoning-takes-flight': ('platform', 'reelshort.com own page'),
    'the-return-of-the-lost-heiress': ('platform', 'reelshort.com own page'),
    'the-senator-s-son': ('platform', 'reelshort.com own page'),
    'the-tutor-trap': ('platform', 'reelshort.com own page'),
    'trapped-in-the-boss-s-embrace': ('platform', 'reelshort.com own page'),
    'true-luna': ('platform', 'reelshort.com own page'),
    'we-are-never-ever-getting-back-together': ('platform', 'reelshort.com own page'),
    'we-will-love-again': ('platform', 'reelshort.com own page'),
    'you-belong-with-me': ('platform', 'reelshort.com own page'),
    'you-fired-a-tech-genius': ('platform', 'reelshort.com own page'),
}
