# -*- coding: utf-8 -*-
"""New titles from the 20 Sep 2026 weekly scrape (reelshort_weekly_2026-09-20),
34 titles that landed needs_check with no synopsis of ours.

Written from each title's own ReelShort page, banked by the scrape in
generator/staging/reelshort_2026-09-20.json and read by
caption_pipeline.load_facts(). The Reddit research is NOT a source here.

All 34 rank below top 300 by reach, so the 16 Aug 2026 ruling would allow
applying without review. Cyan asked to check this batch (20 Sep), so it is
STAGED UNAPPROVED and goes through her review page before apply.

honey-cut: the platform synopsis is truncated mid sentence in the scrape, so
its caption is written from the intact setup only and kept short.
"""

CAPTIONS = {
    'the-mob-boss-spoils-his-pregnant-wife':
        "He threw her away. He didn't know what she took with her.\nDamon Blackwood is a mafia don who has never touched a woman, until a rainstorm and a mistake put college student Lily in his bed for one brutal night. He casts her out with a Patek Philippe on her wrist. A month later finds her just getting by while pregnant with twins, sold by her own parents to cover her brother's debts. Seven months on she collapses in Damon's bar, his heirs are dying inside the girl he destroyed, and the killer learns to kneel.",
    'married-ex-fiance-s-uncle':
        "She caught her fiance in bed with her best friend. So she married the first stranger she saw.\nOn her wedding day the groom was already busy or getting busy with the maid of honor, so the bride walked out and married a random man on the spot to spite him. The nobody she picked turns out to be her ex's own uncle, and the richest man alive. Did her worst day just become the best mistake she has ever made?",
    'man-to-man':
        "Two rivals for the same shirt. One night that changes them both.\nAhead of the 2022 World Cup, Javi and Danny are gifted right wingers from rival clubs, both called up to the national team and both fighting for Spain's number seven. Then they are made roommates, and their first night together ends in a one night stand. Now they have a title to win and a secret neither of them planned for.",
    'pregnant-with-the-dragon-king-s-sextuplets':
        "She saved her professor's life. He gave her six baby dragons.\nBullied student Elena saves her mysterious professor Lucien from a deadly poison, and their one encounter leaves her pregnant with sextuplets, six dragon heirs. When her cruel family and classmates try to burn her alive for carrying monsters, Lucien descends as the Black and Gold Dragon King and claims her as his Queen. But a womb that can bear dragon heirs makes Elena the ultimate prize, and the wicked Frost Dragon Kael wants her for himself.",
    'the-alpha-s-forbidden-mate':
        "The Alpha who slaughtered her family wants her at the altar. His son has other plans.\nLyra is enslaved by the Alpha who killed her family and dragged to his wedding, until his son Asher kills him and claims her himself. Their fated bond ignites, so Asher hides her and takes the political Luna Selene as cover, letting everyone think he is cruel to Lyra to keep her safe. When Selene's jealousy turns to torture and her brother launches a coup, Lyra reveals she is a lost Alpha's daughter, crushes the war, and is crowned Asher's equal.",
    'the-heirless-alpha-s-miracle-omega':
        'His curse kills any Luna who bears his heir. She walked into the selection anyway.\nEthan is the cursed Alpha of Silver Moon, and no Luna has survived carrying his child. Hope is a poor outland Omega who enters the mate selection only to save her own pack, and accidentally wakes an ancient wolf power inside her. Forced into the bond, Ethan rejects her at first, but when she risks her life for him his hate turns to obsession. Now they have to break the Luna curse before the mate bond kills her.',
    'our-camp-night-went-wrong':
        "A tent full of sleeping classmates. A stepbrother's hands in the dark.\nPacked into one tent for the night, one of the campers lies frozen while everyone around them dozes, as stepbrother Hunter starts a silent game that cannot be stopped without waking the whole group. Lip bitten, heart pounding, she prays not a single sound escapes, caught between panic and a thrill neither has felt before. One forbidden night that neither of them can walk back.",
    'step-back-that-homeless-man-is-not-to-be-messed-with':
        "The homeless man she married is worth twenty billion dollars.\nAfter three years hidden in a homeless camp as a test, Vince Astor is crowned America's Godfather and heir to twenty billion, and he keeps it quiet when Helen Stark, the CEO he once saved, proposes to him on the street. Still dressed as a homeless man, he follows her home and swallows her family's scorn as they try to force her to marry another man. Then his power surfaces layer by layer, a bank president kneels, an underboss kisses his ring, and Helen chooses him anyway, for who he is.",
    'honey-cut':
        'Her father marries her off to a billionaire she has never met.\nBased on the novel by Sierra Simone. Good Catholic girl Isolde is forced by her father into marriage with billionaire Mark Trevena, a stranger who is about to become her whole world. What she expects from that arrangement and what she gets are two very different things.',
    'i-flew-home-pregnant-only-to-see-his-secret':
        "Seven years married, pregnant, and he is at dinner with another woman.\nOn her anniversary Amelia flies home to surprise Trevor and finds him dining with someone else. She leaves Boston, files for divorce using the prenup clause he wrote himself, and reclaims the identity she buried: Dr Amelia Voss, co founder of Longmoor Labs. As she rebuilds her career and fights for her daughter, Trevor's world falls apart. She wins sole custody, most of the assets and a new life, and by the time he sees who she really is, it is far too late.",
    'brothers-in-arms':
        "Their brother died. His wife and daughter are next, unless three veterans get there first.\nAfter a fellow veteran's apparent death, hard bitten Nick Gallo and his two brothers in arms regroup in Las Vegas to protect the man's wife and daughter from a savage local mob. Nick starts falling for the family he swore only to guard. Then a shocking return throws everything he thought he knew into total chaos.",
    'my-hot-firefighter-ex-boyfriend':
        'She called 911 for a locksmith. Her ex kicked the door down instead.\nShe handcuffed herself to her own bed by accident and dialled for help, expecting a locksmith. What arrives is her ex boyfriend and three firefighters behind him, and he takes one look and decides another man tied her up and left her. Then she blurts out the worst possible thing, and now he is furious, jealous and refusing to hear the truth. Her most embarrassing moment just became his biggest misunderstanding.',
    'i-married-the-other-woman-s-billionaire-brother':
        "Her groom picked another woman at the gala. So she picked that woman's brother.\nThe night before her wedding, Sloane walks into heiress Vivienne Vale's husband selection gala and watches her own fiance hold up the winning card. Reid puts Sloane's ring on Vivienne and casts her aside, sure she will come crawling back. Instead she accepts a secret proposal from Vivienne's wheelchair bound billionaire brother Dane. When Reid and Vivienne leave Sloane beaten and her father fighting for his life, Dane steps in to protect the woman he has loved and searched for over ten years.",
    'i-m-done-playing-along':
        'Every single person she loved chose her fragile stepsister. So she stopped begging.\nOn her wedding day Orton Reed is abandoned, slapped and humiliated in front of everyone, all because her stepsister Lucy is having another crisis. Her fiance, her childhood friend and even her own parents side with Lucy every time. Then Orton learns she is seriously ill, and something in her finally goes quiet. She leaves New York for a remote school in New Mexico to teach and heal, and when the people who hurt her turn up with apologies, she no longer wants them in her life.',
    'one-night-with-my-billionaire-ceo':
        "She caught her boyfriend cheating with her boss. She woke up pregnant by her CEO.\nIsabella always believed being useful was the same as being loved. The night she plans to propose to her boyfriend, she catches him with her boss instead, and drunk and heartbroken she stumbles into the hotel room of Owen, her company's cold CEO, who has been drugged by a business rival. One night binds two strangers in a marriage of convenience, and distrust slowly turns real. Then his glamorous ex returns to feed every insecurity Isabella has, and an accident sends her running with a secret that takes five years to surface.",
    'the-elf-bride-s-impossible-choice':
        "Chosen as a bargaining chip, ordered to marry one of two orc princes.\nAfter her father's sudden death, Charlotte is abused by her succubus stepmother and stepsisters, until a magical goblin at an elven banquet chooses her and carries her off to the orc castle. She is told to pick one of two princes and marry him at her eighteenth birthday: Vesper, an aloof snake prince, and Claude, a sunlit lion prince. As her stepsisters torment her at their supernatural academy, both princes turn fiercely protective and declare her theirs in front of the whole school. Torn between them, Charlotte falls for both, and awakens a rare and supreme bloodline of her own.",
    'the-cold-ceo-who-spoiled-me-online':
        "She ghosted her clingy online boyfriend. He turned out to be her best friend's brother.\nShe lied about her age and vanished on her needy online boyfriend six months ago. Staying at her best friend's house for the break, she freezes when her friend's cold CEO older brother Rhys walks in, the exact man she dumped. He knows her by her voice alone and starts testing her without mercy. Later at a bar he downs eight drinks to shield her from a creep who spiked her drink, then traps her in his car and recites every fake detail she ever told him. Did she ever regret leaving him?",
    'bully-me-i-run-the-mob':
        "A mafia boss dies saving a bullied teenager. Then he wakes up in the boy's body.\nWill O'Connell, the city's most powerful mafia boss, dies shielding an overweight, bullied teenager named Cayden, and wakes up inside him, back in high school and squaring off against a campus bully. After a brutal public beating he floors his tormentor with a single punch. Posing as his own illegitimate son and helped by his loyal confidant, Will quietly takes back the O'Connell family, transforms Cayden's body and returns to school to humiliate the bully, outsmart a vindictive teacher and survive an assassination attempt.",
    'the-alpha-king-is-my-baby-s-daddy':
        "She has run from him for five years. She can't run forever.\nLayla Hale is a fallen heiress scraping by at a small town bakery with her twin sons, who happen to shift into wolf cubs. A friend enters her in a jewelry competition, she wins it on pure talent, and then her malicious adopted sister frames her and forces her to take her place marrying the notorious CEO of Voss Group, a man rumored to be brutal and hideous. When the door opens, the man is the one who marked her five years ago, the father of her wolf cub boys, and he has been searching for her the whole time.",
    'i-taught-him-to-court-a-mate-he-chose-me':
        "She taught a lone dragon how to court a mate. He picked her.\nPhD candidate Thea teaches a solitary male dragon the courtship calls and the Flame Dance for her thesis, and he performs the move for her the instant he learns it. Her mentor's phone call tears the truth open: the ritual ends with the dragon dragging his chosen mate into his nest and locking her there. It is already too late. Claws rip through the roof, he takes human form to carry her off, and a fever drags her back twelve years to the young dragon she once rescued, and once caged herself.",
    'my-second-life-as-a-billionaire-heiress':
        "Sold off by the family who raised her, reborn to take everything back.\nExploited and sold by her adoptive family, reborn genius Scout uses a DNA match to find her real father: Dominic Moretti, America's supreme mafia don. Backed by three elite brothers, she debuts as the sole Moretti heiress at her coming of age gala, exposes the people who abused her, and claims her place at the top of everything they thought she would never reach.",
    'boyfriend-from-the-future':
        "A version of her rival crashes in from the future with one warning: don't fall for him.\nWhen Riggs Heartstone's future self appears with a terrible message, motocross star Tessa learns that loving Riggs ends in tragedy. Now she is stuck as his racing partner, fighting their chemistry while she races toward the biggest competition of her life. The harder she tries to save him, the harder she falls.",
    'flash-marriage-to-the-wild-billionaire':
        'She put him through law school. He dumped her for a rich girl.\nAbril supports Vicente through law school, and the moment he graduates he leaves her, because he has found a wealthy girl to marry instead. Heartbroken, she does something reckless and flash marries a complete stranger, only to discover the man she just wed is the billionaire CEO Cristóbal Noriega.',
    'the-destined-one':
        "She saved a billionaire's life and woke the wolf mark that names her as his mate.\nVictoria is the secret head of a powerful family who turns down an arranged marriage for her longtime boyfriend Julian. On the way to see him she saves billionaire CEO Alexander Blackwood from a crash, unknowingly waking the wolf spirit mark that marks her as his destined mate. She rejects his sudden proposal and heads to Julian's promotion party, the promotion she quietly arranged, where he humiliates her and offers her a buyout so he can marry an executive's daughter. When Victoria reveals she is the mastermind behind his rise, the room mocks her, and then Alexander crashes the party.",
    'sinking-with-my-step-sister':
        "One night stand, one horrifying morning. The woman is her new stepsister.\nAfter a drunken night together, Shirley discovers her lover Sophia is her stepsister, and tries desperately to keep her distance. Sophia pursues her anyway, bold and reckless, nearly caught by their blended family more than once, until Shirley gives in to a forbidden secret romance. A jealous classmate sets them up and drives them apart, and when hitmen abduct Shirley she learns Professor Sophia is secretly an underworld kingpin. They reconcile, only for Sophia's first love to come home, and they have to stand firm against every prejudice to stay together.",
    'quads-mafia-divorce-i-took-the-money-and-ran':
        'One hundred million to sign the divorce and disappear. She signed it and vanished.\nSerena marries mafia boss Dante Santoro for pure convenience, no love involved. When she finds out she is pregnant with quadruplets, a text arrives offering her a hundred million to sign the papers and leave. She does not weep or break down, she signs and vanishes overnight. Dante comes home to find the whole divorce was forged by his childhood friend Vivienne, and realises he has loved Serena all along. He apologises in public and spares nothing to win her back, and she is in no hurry to forgive him.',
    'the-wolf-queen-strikes-back':
        "She hid her crown to give her daughter a normal life. The pack made it a nightmare.\nDiana, the Wolf Queen, grew tired of war and disguised herself as a simple healer in the woods, sending her daughter Katherine to the Conroy pack for a normal life. Instead they treated Katherine like a worthless slave, humiliating and beating her because she had no power. When Diana learns the truth, her fury is unleashed, and as the Conroy pack's old betrayal comes to light, the Wolf Queen stops hiding, strikes back, and reclaims her crown.",
    'my-possessive-ex-husband':
        "She fled the marriage carrying his daughter. One drunken night lands her right back in his bed.\nFive years ago surgeon Elara Voss fled a suffocating marriage, secretly pregnant with her husband's child. Now one mistake puts her back in bed with her cold billionaire ex Damian Sterling, and to protect their daughter she swears the girl is not his and offers a strictly physical arrangement: Tuesdays only, no publicity, no feelings. What she does not know is that Damian has loved her the whole five years and never knew how to say so. As the old desire reignites, their daughter's identity and the fake infidelity that wrecked their marriage begin to surface. Can two people who never learned each other's love give the marriage a second chance once the truth is out?",
    'married-to-the-demon-king-the-sun-god-begs-for-my-return':
        "Framed, stripped of her divinity, thrown into the Abyss as a sacrifice. She came back a queen.\nOn the eve of her wedding, Alicia, the Saintess of Order, is drugged by her sister Lina and finds her fiance the Sun God Apollo in Lina's arms. The two frame Alicia, annul her engagement, strip her divinity and cast her into the Abyss. At the brink of death the royal blood of Lilith wakes inside her, turning her into a succubus, and she falls into the cavern where the Demon King Lucifer has been sealed for a thousand years. She bonds with him, breaks his prison, and rises as a reborn queen who joins him to wage war on the Divine Court and make every traitor pay.",
    'bound-by-secrets-her-billionaire-doctor':
        'She hid their son from him for five years. Now the boy needs the one thing only his father can give.\nFive years ago Luna, a girl from the slums, was driven by her wealthy mother in law to jump from a building, and gave birth to their son Neo alone. When Neo is diagnosed with leukaemia and needs a bone marrow transplant, Luna crosses paths again with Ken, her former boyfriend, now a chief surgeon. To protect her son she hides their history and signs an agreement with him, but a series of plots costs her a pregnancy and sends her fleeing to France. Once Ken uncovers the whole truth, he clears the way and sets out to bring his family back together.',
    'the-slum-girl-who-became-a-billionaire-s-wife':
        "For five years she was the nanny to the daughter she gave birth to.\nFive years ago Evelyn, a girl from the slums, was chosen by Adrian, a wealthy young man from New York, to be a surrogate and bear his daughter Chloe. After the birth she was stripped of any claim to the child and kept on at Blackwood Estate as a live in nanny, quietly memorising Chloe's every habit and fear while the nominal wife Lillian humiliated her, made her kneel and kept her at arm's length. Chloe clings to Evelyn all the same, the only person who truly cares for her, through crisis after crisis.",
    'bitter-burn':
        'Her father orders her to kill her husband. She protects him instead, and he never believes it.\nBased on the novel by Sierra Simone. When Isolde Laurence is pressured by her father to murder her husband Mark Trevena, she chooses to shield him, but Mark overhears the orders and is sure she still means to do it. The misunderstanding shatters a whirlwind romance, and Mark puts Isolde through a world of punishment that not even her bodyguard can pull her out of. In this end to the Salt Kiss trilogy, what does a man do once he realises he has hurt the ones he loved, and how far will he go to win them back?',
    'i-don-t-need-no-alpha-brothers':
        "Five brothers, one promise, and the outsider who turned them all against her.\nAs a child Elara saved Alpha Mason's life, and in gratitude he adopted her into the Stormfang Pack and promised that at eighteen she would choose one of his five sons to marry. The six of them grew up inseparable, until Jenny arrived. Fed by her lies, the five brothers hurt Elara again and again, slowly breaking the girl who once loved all of them. Betrayed one time too many, Elara decides she is done, and cuts every tie.",
    'just-one-kiss':
        'She wants to lose her virginity before college. Her best friend offers to handle it.\nBased on the Wattpad novel by Emily Jean. Determined not to start college a virgin, Farrah Blake strikes a deal with her lifelong best friend and secret crush, billionaire heir Ethan Sinclair: he will either find her the perfect guy for her first time, or take her v card himself. The trouble is she has wanted him all along.',
}

SOURCES = {k: ("platform", "reelshort_2026-09-20.json") for k in CAPTIONS}
