# -*- coding: utf-8 -*-
"""Part 4 of 4 of the 28 Sep 2026 new-titles batch (new234): new-title
captions (synopsis_short), HOOK line, newline, BODY. UNAPPROVED draft.

All 58 titles in this part are captioned. None left out: every title had a
story on its platform page. 13 had no synopsis in the scrape and were fetched
from the linked platform page on 28 Sep 2026 (the ReelShort, CandyJar,
StardustTV and MoboReels titles); FACTS holds exactly the text each caption was
written from.

Thin sources, captioned from what the page gives and nothing more:
  our-dirty-little-secret (CandyJar publishes a one sentence premise only),
  destined-reunion, my-sunshine-in-the-ruins (short platform blurbs).
Same story, two titles: that-prince-is-a-girl-the-princess-and-her-grand-king and
  the-prince-is-a-girl-the-slave-in-a-princess-disguise carry near identical
  MoboReels synopses; the two captions are written separately so they do not
  duplicate each other.
"""

CAPTIONS = {
    'fake-dating-my-rich-nemesis':
        "One mistake with her childhood nemesis. Now they're fake dating to get back at their exes.\nWhen she comes back to North Lake High, the last thing she expects is to spend one night with the Beaumont heir, the boy who has been her enemy since they were kids. It was a mistake and they both know it. But they each have an ex they'd love to see squirm, so they strike a deal and start dating for show. It's supposed to be an act. Will they end up falling for each other anyway?",
    'think-again-i-m-the-hidden-boss-mom':
        "They picked on the wrong mom.\nThe PTA moms have decided her son is an easy target, and they frame him. His mother looks like a nobody to them, so they humiliate her too and shove her aside. What none of them know is that she's the secret billionaire standing behind their children's school. Now their fate is in her hands.",
    'waking-up-married-to-my-crush':
        "She wakes up married to her college crush, with no memory of how she got there.\nAn accident has damaged Jasmine's brain and wiped out the last few years, so as far as she knows she's still 21. Then she finds out she's married to Patrick, the handsome, rich guy she had a crush on in college. The catch is that their marriage is falling apart, and the wife she's been all this time is a lovesick, obedient one. At 25 she refuses to keep playing that part and sets out to get her spark back. The new Jasmine is someone Patrick never noticed before, and now he's the one falling for her.",
    'forever-was-a-lie':
        "Twenty years of being adored, undone by the nanny's daughter.\nWhen her family goes bankrupt, her mother's best friend takes Nicole Quinn in, and she grows up alongside the Smith brothers, Colin and Abel. For twenty years they spoil her and she's the center of their world. Then Mandy Moore, the nanny's daughter, shows up. Mandy schemes against Nicole and humiliates her at every turn, and Nicole is left in an impossible spot as the brothers start pulling away and lose interest in her. Twenty years together, and it turns out forever was a lie.",
    'the-billionaires-rescue':
        "He saved her at the bar. Then he came back for her and the baby.\nEmily is working long hours at a bar to put money aside for college when a customer attacks her. Luke steps in and saves her, and something real starts between them. When she finds herself pregnant, she makes up her mind to raise the baby on her own, until Luke turns up again ready to stand by her. Then his ex fiancee Clara comes back, set on breaking them up, and she digs up a secret. Emily was switched at birth, and she's the real Cassano heiress. Clara will do anything to keep that buried, but her schemes fall apart. Emily's real family takes her home, Clara pays for what she did, and Emily and Luke make it all the way to a grand wedding.",
    'guess-who-they-miss-now':
        "She was framed and killed. Then she was reborn.\nSamantha manages the high school basketball team, and it ends with her framed and dead. She's reborn right back at the moment people first started to suspect her, and this time she doesn't stay to take it. She walks away from basketball and signs on with the ice hockey team, and that's where she learns what she's really worth. It's only then that the basketball team figures out how much they needed her. By then it's much too late.",
    'the-tiny-tyrant-of-go':
        "A little girl, a Go board, and a puzzle nobody could solve for twenty years.\nMaster Glenn is too poor to keep looking after his young student Anna, so he sends her down the mountain to the Nova Go Club and Master Parker Jordan. Overnight the little girl solves the Sovereign Gambit, a puzzle that has beaten every Go player for two decades. Parker takes her in, and then Owl, the ruthless Go King, turns up demanding a match. Anna stays calm and takes him apart one move at a time, until the beaten king is on his knees asking to be her student. Then Parker tells her what he has wanted all his life. He needs to get into the Zenith Go Championship, because that's how he'll learn the truth about how his wife died.",
    'the-mvp-s-plus-size-love':
        "Bullied as Alexandra, she comes back as Lexi.\nAlexandra is a high schooler who gets bullied, and she's had enough. With her childhood friend Dan in her corner, she remakes herself from the ground up and comes back as Lexi. Now she's ready to show everyone who her tormentors really are and take back the dignity they stripped from her. And somewhere along the way, true love finds her.",
    'ascension-to-the-lost-throne':
        'The Lord of War beat them once. Now his own brother has joined them.\nHarry White, the Lord of War, crushed the Killer Sect. But trouble in his family forces him out of the War Sect, and he leaves with his wife. Then the Killer Sect rises again, and this time his brother John White is working with them to bring Harry down. Even his wife turns on him and takes their side. With almost everyone against him, Mary Norris is the one who gives Harry a fighting chance.',
    'lady-diamond-s-lost-heiress-returns':
        "She gave herself to the mafia to save her mother. Twenty years later, her mother finds her.\nWhen she's still just a girl, Bella Rossi hands herself over to the mafia to save her mother Maria. Twenty years pass. Maria is now Lady Diamond, a powerful mogul who has never stopped searching for the child she lost. Bella, meanwhile, is getting married, and on the day itself her fiance Vince betrays her. He has stolen her savings and he's using them to marry someone else. Bella is being humiliated in the middle of her own wedding when Maria spots her birthmark. Lady Diamond has found her daughter, and everyone who hurt her is about to be crushed.",
    'matrimoney':
        "Thirty days as a billionaire's fake fiancee, to save her sister.\nShe walks dogs for a living and she's barely getting by, so when a reckless billionaire underwear model offers her a fake engagement for thirty days, she says yes for her sister's sake. Living under one roof in his mansion is a disaster from the start. They fight constantly, they fall into bed out of pure spite, and something neither of them planned starts to grow. Then jealousy creeps in and the feelings get harder to ignore. Is this still just business, or the love they've both been running from?",
    'mated-to-my-rival-alpha':
        "A forbidden mark ties her to her rival's son.\nIvy is an Alpha heir whose family has disowned her, and Alex is the son of her rival. When they find out a forbidden mark has bonded them together, they set off in secret to break it. The trouble is that the closer they get, the harder they fall for each other, and that's exactly the danger. Because if what they feel is real, the curse is going to destroy both of them.",
    'riding-with-my-bully-stepbrother':
        "A family vacation stuck with the stepbrother who bullied her.\nHayley's mother has remarried, and that means Hayley gets dragged along on a family trip with her stepbrother Cole, the boy who used to bully her. The old hurt is still there, but something else keeps getting in the way of it, an attraction neither of them can shake. With forbidden feelings rising and secrets that have been buried for years coming to the surface, this trip could change what they are to each other for good.",
    'signed-sealed-deceived-by-my-billionaire-mailboy':
        "The mailroom guy she's falling for isn't who he says he is.\nEllie has fallen hard for Colton, a charming mailroom clerk who seems to really see her when nobody else does. But the more she lets herself fall, the stronger her feeling that he's keeping something from her. Then she finds out the truth. Colton is a billionaire heir caught up in a world of power and secrets, and suddenly their love is forbidden. Now every choice is a test of loyalty, and every lie could cost them.",
    'shaping-soulmate-my-soulmate-professor-is-taken':
        "Her summer fling just walked in as her new professor.\nHannah is an art student with graduation almost in sight, and she has never forgotten the man she had a fling with over the summer. Then he walks into her class, and he's her new professor. What they have now is forbidden, and keeping it hidden drags them into secrets, obsession, betrayal and power games at the university. The deeper they fall, the more they stand to lose. Is this their second chance at something fated, or the thing that ruins them both?",
    'my-freeze-their-tears-no-forgiveness':
        "Thirty years asleep. Now they want her back.\nThe wealthy Johnson family adopted Sophie when she was six, and for years she was the daughter they loved most. Then their real daughter came home, and suddenly Sophie was the one everyone blamed and left behind. Heartbroken, she volunteered for her brother's sleep experiment and walked away from the family she'd loved. Thirty years go by before they finally come looking for her, desperate to have her back. She doesn't remember a single one of them.",
    'her-kept-husband-was-the-king-of-everything':
        "She treated him like a servant. He was the genie keeping her on top.\nEvren is a powerful genie bound by a promise to spend six years with Layla. He keeps who he is a secret and looks after his wife, pulling her company out of one disaster after another. Layla never notices. To her he's a worthless servant, and she treats him like one. When the six years are up, Evren leaves. Only then does Layla find out that every bit of her success came from the husband she couldn't stand.",
    'fall-for-mafia-boss-who-killed-my-fiance':
        'He killed her fiance on their wedding day, then married her himself.\nOn the day Helena is supposed to get married, mafia don Cesare murders her fiance and her family, and forces her to become his wife instead. For seven years she lives through his cruelty and his obsession with her. Then, pregnant, she fakes her own death and runs. But Cesare tracks her down, and she learns a bloody truth that turns everything she believed on its head.',
    'married-an-elven-king-by-mistake':
        "She let her sister have the prince. The dwarf she married instead is the Elven King.\nVera knows that marrying the Crown Prince means a future of nothing but humiliation. So when her sister goes after him, Vera lets her have him and weds a dwarf instead. The dwarf turns out to be the Elven King. Vera's honesty wins him over, and the bride everyone looked down on becomes a queen. Her sister isn't so lucky. She's banished to live among the Dragons, and now she's the one living the fate she created.",
    'too-late-to-mourn-our-daughter-alpha':
        "He saved his mistress and left his daughter to the dragons.\nIt's Alpha Kurtis's birthday when a dragon attacks, and he makes his choice. He runs to save his mistress and leaves his Luna Melanie and their little girl behind. Melanie watches the light of her daughter's wolf soul go out. Then she cuts the mate bond herself, and swears Kurtis will pay for it in blood.",
    'from-loving-wife-to-bloodthirsty-queen':
        "She gave up her crown for him. He murdered her.\nFor love she walked away from her crown and her immortality, and the man she gave them up for betrayed her and killed her. The Queen of the Night has climbed out of her grave, and she's taking back everything that was hers. Her ex is on his knees begging for another chance, but someone new is already standing guard beside her throne.",
    'ditched-my-wolf-fiance-for-the-beast-king':
        "Betrayed by her fiance and her sister, she married the man everyone fears.\nWisteria is a nine tailed fox shifter, and the two people who betray her are her fiance and her adopted sister. So she takes her sister's place as the bride of the Serpent Lord, the one everybody is afraid of. He turns out to be the only one who has ever truly loved her. Wisteria becomes a legendary alchemist, and now her ex and her family are the ones begging her to forgive them. She never will.",
    'mommy-my-new-dad-is-the-dragon-king':
        "Her husband's mistress wants her dead. The King of Dragons wants her safe.\nJessica is a white dragon from the bottom of the ranks, and she works as a trainer. Her son is sick and her husband is cheating on her, and she's trying to hold it all together. Then her path crosses with two dangerous people. One is her husband's mistress, and she wants Jessica dead. The other is the King of Dragons, and he'll do whatever it takes to protect her.",
    'useless-knight-my-mounts-conquered-every-era':
        "Top of the academy for four years, then he drew the most useless class there is.\nFor four years he's the academy's star prodigy. Then his class awakens, and it's Knight, the one everybody laughs at. His girlfriend dumps him right there for a corporate heir and the whole hall jeers him out. What none of them know is that he's really a Chronicle Knight, and the Throne of Mounts is his to inherit. He can bind legendary steeds from any age of history to him. When Odin's mythic warhorse rides down a rainbow bridge out of a torn sky, and a war machine made of liquid metal arrives from the future in flames, the people who mocked him end up on their knees. The reject everyone laughed at has become an S rank legend the whole academy fears. One mount after another he wakes beasts, ships, machines and even gods from beyond time, and one enemy after another he flattens every last person who doubted him. The real war hasn't even started, though. An invasion from outside time is coming to wipe out the kingdom, and when everyone else pulls back, he charges in with seven eras at his back as the last Knight between humanity and the end. They'll be sorry they ever threw him away.",
    'our-dirty-little-secret':
        "Her one night stand from a college party turns out to be her professor.\nTulli hooks up with a stranger at a college party and figures that's the end of it. She's never going to see him again. Then she finds out exactly who he is. The man she spent the night with is her professor, and now they share a secret nobody can ever find out about.",
    'the-godfather-s-heartbroken-lover':
        "Five years with a mafia godfather, and one choice ended it all.\nEvelyn spent five years sure that Dante Moretti, the mafia godfather, loved her. Then his first love came back, and one cruel choice broke everything. Humiliated and heartbroken, Evelyn vanishes to Berlin to start over. But Dante is a man everyone fears, and he won't let her go. His obsession slowly becomes regret, just as another man comes along offering Evelyn the safety Dante never gave her. By the time the Godfather learns what loving someone means, will she still be his to win?",
    'downgrade-my-ride-i-ll-upgrade-my-groom':
        "Her fiance put his secretary in the wedding car. So she married someone better.\nEleanor Vance's wedding day is supposed to start with the bridal Rolls Royce. But her fiance Julian sends her off to a cramped backup SUV, all so his secretary Sophia, who claims she gets carsick, can sit next to him. Her jealous coworkers film the whole humiliating scene, and Eleanor keeps her head up anyway. Then a car accident, set up on purpose, stops her from reaching the ceremony, and Sophia takes her dress, her walk down the aisle and her kiss with Julian. But Eleanor still has Christian Thorne. He's been her best friend since they were kids, he's a powerful heir, and he's been in love with her for years. An hour later they're legally married, and they walk into the reception holding the certificate. Julian thinks the bride he threw away is still his to control. He's about to watch her build a whole new life and tear his empire down.",
    'destined-reunion':
        "At a birthday feast, one child's claim reveals a hidden son.\nLogan Campbell is desperate to find Ruby and little Nolan, and the search turns his family upside down. There's pressure on him to marry, and questions start being asked about whose blood is whose. Then, at a lavish birthday feast, a child makes a bold claim in front of everyone, and it comes out that Logan has a son nobody knew about. Now the secrets are coming undone, every family tie is being tested, and the Campbell legacy may never be the same.",
    'back-with-baby-ex-regrets-deeply':
        "Dumped at the clerk's office. Back three years later with a billionaire's son.\nSeth dumps Vanessa right there at the clerk's office, before they can even get married. She goes abroad, where an arranged marriage makes her the wife of billionaire Grayson. Three years later she comes home with their son, and Seth and Chloe waste no time humiliating her. Grayson's revenge is brutal, and it shows how long he has quietly loved her. Seth is left with nothing but regret.",
    'the-hidden-queen-my-husband-s-mistress-ruined-my-empire':
        "She made him a tycoon. She can unmake him too.\nShe's secretly an heiress of the Sinclair family, and she has spent her marriage quietly making her husband a tycoon in the luxury world. Then he starts an affair with a restaurant manager, and an electric eel attack that goes viral puts his cheating out in the open. So she drops the act, tells the world who she really is, and tears down the empire she made for him.",
    'not-your-average-crow':
        "She thinks she's a crow in a nest full of phoenixes.\nEmily is sure she's nothing more than a common crow who ended up in a phoenix nest by accident. Queen Angelina adopts her anyway, and Emily keeps trying to run away before some trial can reveal what she really is. Then the Magic Mirror shatters and the Hellfire goes out all around her, and Emily finds out the truth. She's the Abyssal Phoenix, lost long ago. And someone is plotting against the family that took her in.",
    'weak-dragons-covenanted-harem':
        "Her family despised her. Then she awakened a system that makes her stronger.\nClaire's father and brothers have nothing but contempt for her. Then, at a ceremony to choose wives, she awakens a system that grows her power through mating. Every time she's with someone of the opposite sex she gets stronger, and she never stops. In the end she's crowned Dragon Lord of both races, with a harem of beauties drawn from every race, and the dragons enter a new era under her.",
    'forbidden-vows-my-bestie-s-billionaire-dad':
        "She moved in with her best friend and fell for her best friend's dad.\nWhen her fiance's scandal destroys her family, Chloe is left with nothing and goes to live with her best friend Mia. There she falls for Mia's father Victor, a cold, controlling billionaire. What starts between them is forbidden, and it burns hot. Victor protects her and ruins the ex fiance who wrecked her life. But the closer they come to being found out, the more Chloe wants to run, and when she tries, Victor won't let her go.",
    'the-ceos-exclusive-milk-mommy':
        "Her breast milk once saved a stranger. That stranger is now her CEO.\nElla has lost her husband and her baby, and she starts over with a job at Winter Group. Once, Ella's breast milk saved a woman's life, and that woman turns out to be CEO Celine Winter. Celine makes Ella her personal assistant and quickly becomes obsessed with her. The attraction between them grows in secret, but a jealous Margaret has plans for Ella, and they could get her badly hurt.",
    'clinic-miracle':
        "A young doctor who can see inside his patients.\nJohn is a resident when he suddenly gains a power no doctor should have. He can see injuries hidden inside a patient's body. He starts catching critical conditions everyone else missed and pulling patient after patient back from the edge. But a diagnosis that good gets noticed, and his colleagues start asking questions and digging into him. Working the emergency department against the clock, John has to keep his secret hidden while the danger closes in.",
    'exiled-genius-dragon-contract-2':
        "His family threw him out. Now he's bonded to a demon dragon.\nEvan Lowe is betrayed and robbed of his gift, and his own family throws him out. Then the Mythic Beast System awakens for him. The Apocalyptic Demon Dragon becomes bound to him, and he gains an SSS talent. Now he's coming back for everyone who wronged him, and every one of them owes him. So who's going to pay first?",
    'space-cowboy-s-royal-escort':
        "A dying friend's last wish, and a princess to get through enemy ground.\nCaesar is the strongest Mechanical Man in the universe, and he made a promise to a friend who was dying. He'll get Princess Shirley safely across territory that could kill her. The Wild Grass Gang comes after them again and again, and Caesar fights them off every time, holding his ground until help arrives. He keeps his word, and he keeps the people he cares about alive.",
    'death-forgot-he-loved-me':
        'She stole a ring. It tied her to Death himself.\nLara is a thief, and the ring she steals carries a curse that binds her to a Death God who has lost his memory. What he has forgotten is her. Lara is the love he lost, born again. Breaking the curse costs him everything. He gives up being a god to become mortal, and Lara is the one who holds his soul here on earth.',
    'our-crew-has-no-tomorrow':
        "A billion views, and they still owe millions.\nSix Hollywood rejects everyone had written off shoot a zombie film on one iPhone, and overnight it racks up a billion views. The champagne is still flowing when the contract lands in front of them, and it's a trap. For all those views they haven't made a cent, and they owe the company millions. Every time the film spreads further, they get poorer. Stuck inside their own hit, these nobodies are ready to turn the tables.",
    'my-boss-is-my-babys-father':
        "She's carrying her boss's baby, and the baby is giving her advice.\nNora Shaw is pregnant with Lennox Foster's child, and she can hear her unborn baby talking to her, handing out advice right when she needs it. She takes a job in the Foster household as a top maternity nanny, looking after their quintuplets without letting anyone know who she really is. Soon she's the most wanted nanny in Capital City. But when Lennox finds out the truth, can he win her back from five crying babies?",
    'the-alphas-cursed-luna':
        "A routine checkup, a hospital mistake, and an Alpha's baby.\nAria only goes in for a checkup at the hospital, and she comes out pregnant, after a mistake leaves her carrying a powerful Alpha werewolf's child. Now she's caught up in a world she never asked to be part of, and it's a dangerous one. She'll have to fight to keep herself safe, and the baby too.",
    'my-sunshine-in-the-ruins':
        'A cheerful nurse and a man the slums made hard.\nAnna is a nurse who always looks on the bright side, and Elias is a man life in the slums has turned to ice. She sets out to thaw him anyway. What grows between them shows that even in the worst of places, love can be the light that lets two people heal and start over.',
    'sold-to-the-ice-king':
        "Total obedience, in exchange for everything she needs.\nDamon rules the ice hockey team, cold and arrogant, and he's secretly a mafia heir. Aria is a beautiful, bookish girl being bullied almost to breaking point by Daisy. With her grandmother dying and no way out, Aria makes a deal with Damon. She'll do whatever he says, and in return he saves her family, destroys her bullies and makes her queen of the campus. Their game of control and submission is dangerous, and bit by bit it turns real. The coldest boy on campus falls for her quiet strength, and the girl who was broken climbs out of hell.",
    'they-don-t-know-i-m-the-don-s-pregnant-queen':
        "Her family thinks she married a nobody. He owns New York.\nShe's secretly married to New York's mafia king, and her family has no idea. When she comes home eight months pregnant, they treat her like dirt. They starve her, smash the ring he gave her, make her wear a dog collar and cut her belly, laughing the whole time about the nobody she married. That nobody runs the whole city, which makes her its queen. One phone call brings the helicopters and armored cars, and every one of them pays.",
    'from-one-night-to-mrs-billionaire':
        "Framed by the richest man's daughter. Pregnant with the richest man's child.\nKaden is the richest man around, and Claudia is his adopted daughter. She drugs and frames Anastasia hoping to wreck her reputation and end her marriage to Lucius. But by mistake it's a drunk Kaden who rescues Anastasia, and she becomes pregnant with his only child. Claudia leans on being the rich man's adopted daughter to push Anastasia around at the company and at a banquet, with no idea that Kaden has taken Anastasia home, looked after her and fallen in love with her. And in the end, Kaden finds out who Claudia really is.",
    'bring-it-on-my-mafia-life':
        "Her parents sold her to the mafia for five million.\nRhea's own parents sell her to the mafia for five million, and Lukas is the man they sell her to. She's supposed to be nothing more than a toy to him. Instead he goes to extraordinary lengths to keep her safe in the deadly world of the mafia. So is it love, or is she just one more piece in a dangerous game he enjoys playing?",
    'my-boyfriend-gave-my-virginity-to-his-bro':
        "She lost her memory. Her boyfriend told her she was dating his best friend.\nEmma has it all planned. On her birthday she's going to sleep with her boyfriend Blake for the first time. Then a chandelier comes down, knocks her out and wipes her memory. Blake has been cheating on her with her best friend, so to cover it up he tells Emma that her boyfriend is actually Dylan, his best friend. She believes it and starts seeing Dylan, and then she learns his secret. Dylan has quietly loved her for years. When her memory finally comes back, she's furious that he lied to her. But Dylan pulls her close and tells her the only lie he ever told was acting like he didn't want her.",
    'her-rich-dream-shatters':
        "She bullied a grandmother and her granddaughter. They were the family she wanted to marry into.\nA wealthy matriarch is leaving the hospital with her granddaughter when they run into the gold digger her son is seeing, along with the woman's own daughter. The gold digger is counting on marrying into the family to clear her ex's debts, and she means to charm the woman who'll be her mother in law. But she has no idea who these two are, so she bullies them and attacks them. The moment she finds out who she laid hands on, her dream of marrying rich falls apart.",
    'my-future-daughter-in-law-has-syphilis-obstetrics-director-henry-carter-discovers-his-future-daughter-in-law-lydia-shaw-has-syphilis-she-responds-by':
        "He found out his future daughter in law has syphilis. She made him kneel.\nHenry Carter runs obstetrics at the hospital, and he discovers that Lydia Shaw, the woman about to marry into his family, has syphilis. Lydia's answer is to attack him, humiliate him, force him to his knees and smash his trophy. With her rich fiance protecting her, she terrorizes everyone around her. Henry bides his time. Then, at a birthday banquet and a hospital ceremony, he lays out her affairs, her infection and her lies for everyone to see. Lydia and her lover turn against each other, and it comes to murder. Lydia lands in prison, and justice finally catches up with her.",
    'that-prince-is-a-girl-the-princess-and-her-grand-king':
        "Sold into a beast kingdom, she hides as a boy to protect her sister.\nWhen Emeriel and her sister are sold as slaves to Urai, the kingdom of the beasts, Emeriel passes herself off as a male servant to keep her sister safe. But she isn't an ordinary human. She's a Syren, one of the rarest there is, and when the beast king Daemonikai goes feral, nobody but her can calm him. Before long they're secretly in love. Jealous Sinai makes her life miserable, the ambitious lord Zaiper plots against her, and Vladya, who carries a curse, can't stop obsessing over her sister. Through one deadly trap after another, Emeriel fights to keep her secret. And in the end, it's Emeriel who lifts the curse on the beast king, when nobody expected it.",
    'miss-urologist-and-her-ceo-patient':
        "She blackmailed her CEO patient. Now she's his contract wife.\nXimena is a urologist who needs money for her research, so she blackmails one of her patients, the cold and distant CEO Ayden. Soon they're stuck in a contract marriage, living under one roof and trading jabs and laughs. Then Ximena realizes his impotence isn't what it seems. It's caused by chronic poisoning, and she throws herself into curing him. Ayden started out planning to use her, but bit by bit he falls for her. What began as a fake relationship turns into the real thing.",
    'my-secret-protector-was-in-love-with-me':
        "Humiliated at her father's will reading, she finds out someone has been protecting her all along.\nAt the reading of her father's will, Eliza is shamed in front of everyone by her fiance Wayne and her sister Beth, who have been plotting to ruin her. What they didn't count on is Doris, who has been watching over Eliza the whole time. Doris steps in, exposes the scheme and brings two secrets to light. Beth is the illegitimate daughter of their mother, and Wayne had a hand in the death of Eliza's father. Eliza and Doris sign a one year marriage contract, and Eliza drags everything into the open, sending Wayne and Ruby to prison. Beth hits back with a kidnapping and a fire, until Doris kills her. Then Maren, out of jealousy, joins forces with a mafia boss. Doris turns their trap around and Maren doesn't survive it. In the end Doris proposes, and the two women marry and rebuild the family side by side.",
    'burning-hot-laps':
        "Five years after he vanished, the man he used to race beside is now his boss.\nJace is a gifted Omega, and he once raced side by side with Darius, his lover and the Alpha heir of the Aegis Syndicate. Someone framed Jace as a traitor, and he disappeared for five years. Now he spends his days fixing cars, weighed down by his brother and a pile of debts, and a harsh contract ties him to Darius, his new boss. Jace keeps winning races, and Darius can't ignore how loyal he still is. The conspiracy that tore them apart leads back to Darius's own father. Then Jace's jealous rival tampers with the car to cause a crash meant to kill, and Jace takes the impact to protect Darius. When he wakes up, the truth finally comes out. Jace gets back everything he lost and returns to the track as a champion, with Darius beside him.",
    'the-abandoned-god-of-olympus':
        "Olympus let him die. This time he walks away first.\nIn his last life Elon was the true prince of Olympus, until the adopted son Valerius framed him. He lost his divinity, and Zeus and the rest of his family left him to die. Now he's reborn twenty years before all of that, and this time he leaves Olympus on his own. He builds his power back up through the faith of mortals and joins forces with Gaea. When the Titans threaten everything and the gods come begging for his help, Elon turns them down cold. He defeats the enemy himself and rules over the mortal world.",
    'the-rogue-brother-s-claimed-omega':
        "Rejected by the heir he loved, he's claimed by the brother nobody wants.\nAiden Clark is a sailor near the bottom of the ranks, and he has been quietly in love with Ethan Iverson, the heir to the fleet. When Aiden finally gets his fated tidal mark, Ethan rejects him cruelly, and the mark is left damaged. That's when Ryan steps in. He's Ethan's older brother, the one everyone shuts out, and he's rough with Aiden but gentle at the same time. Pulled in two directions, Aiden starts to see that his real destiny lies with someone else.",
    'his-neglected-wife-is-the-top-scientist':
        "She gave up science for him. He was with his mistress while she lost their baby.\nJune was a brilliant scientist, and she walked away from her career to marry Cole because she loved him. He barely noticed her. While she was bleeding out from a miscarriage, Cole was off with his mistress Alycia. The baby didn't survive, June could never have another, and every bit of love she had for him died too. So she went back to her research, fought the lies Cole spread about her, and took back the work that had been stolen from her. She never stopped being the top scientist.",
    'the-prince-is-a-girl-the-slave-in-a-princess-disguise':
        "A slave girl disguised as a boy, and a beast king only she can reach.\nEmeriel and her sister are sold as slaves into Urai, a kingdom ruled by beasts. To shield her sister, Emeriel dresses as a male servant and keeps her real self hidden. What nobody knows is that she's a rare Syren, and when the beast king Daemonikai loses himself to his feral side, she alone can bring him back. They fall for each other in secret. Around them the danger keeps building. Sinai is jealous and cruel, lord Zaiper is scheming for power, and the cursed Vladya can't stop fixating on her sister. Emeriel has to keep her disguise intact through trap after trap, and no one sees it coming when she's the one who ends the beast king's curse.",
    'revenge-backfired-now-my-stepbrother-is-my-boyfriend':
        "His hero and his hated stepbrother turn out to be the same guy.\nOliver is the star receiver on his high school football team. He idolizes Captain and can't stand his own stepbrother, until he realizes they're both Carlos. Carlos wrecked Oliver's relationship, so Oliver gets even by telling everyone he's Carlos's boyfriend. The joke goes wrong fast and lights something dangerous between them. From tense moments in the locker room to face offs by the pool, the enemies turn into something much hotter, and there's no denying it. Carlos's hidden feelings come out, and Oliver finds himself falling for the guy he swore he hated. By the end they're standing side by side, done hiding and done pretending.",
}

FACTS = {
    'fake-dating-my-rich-nemesis':
        "When a sassy high school girl returns to North Lake High, she doesn't expect to have a one-night mistake with the Beaumont heir, her childhood nemesis, and later team up with him to piss off their exes. Will they eventually fall in love?",
    'think-again-i-m-the-hidden-boss-mom':
        'After PTA (Parent Teacher Association) moms target and frame her son, a "nobody" mom is humiliated and cast aside—as an even bigger secret unfolds behind the scenes... until they discover she\'s the secret billionaire behind the school. Now, she decides their fate.',
    'waking-up-married-to-my-crush':
        'Jasmine awoke to find herself married her college crush Patrick – who is both handsome and wealthy! Yet, she quickly discovers that her marriage is sinking. A tragic accident had damaged her brain, erased the last few years of her life, trapping her at the age of 21. Determined not to spend her 25th year as a love-struck, subservient wife, Jasmine decides to reclaim her sparkle. This transformation gives Patrick a new perspective on Jasmine, he starts to fall in love with her',
    'forever-was-a-lie':
        'Nicole Quinn is taken in by her mother’s best friend after her family goes bankrupt, beginning a 20-year bond with Colin and Abel from the Smith family. The brothers dote on Nicole, but everything changes when the nanny’s daughter, Mandy Moore, enters the picture. Nicole becomes the target of Mandy’s schemes and humiliation, placing her in a difficult situation where the Smith brothers start distancing themselves and lose interest in her.',
    'the-billionaires-rescue':
        "After their encounter, he became a patron saint to protect her all the time. Emily works tirelessly at a bar to save money for college, but her life takes a dark turn when she's assaulted by a customer. In her darkest moment, Luke heroically intervenes, saving her and sparking a deep emotional connection between them. Initially determined to raise her unexpected child alone, Emily reconsiders when Luke reappears, offering unwavering support and love. Their budding romance faces a formidable challenge with the sudden reemergence of Luke’s ex-fiancée, Clara, who is bent on tearing them apart. The stakes rise when Clara uncovers a shocking secret: Emily is the true heiress of the Cassano family, switched at birth in a malicious plot. Desperate to keep this secret, Clara schemes against Emily, but her plans ultimately unravel.Reclaimed by her rightful family, Emily witnesses Clara face the consequences of her actions. Amidst the revelations and justice, Emily and Luke's love triumphs. They celebrate their journey with a grand wedding, their story becoming a legend of enduring love and resilience, as they step into a blissful married life together.",
    'guess-who-they-miss-now':
        'Samantha, the high school basketball team manager, is framed and killed. Reborn at the moment when suspicion first arose, Samantha makes a different choice: she leaves the basketball team and joins the ice hockey team, where she finally discovers her own worth. Only then does the basketball team realize how indispensable she was—but by then, it is far too late.',
    'the-tiny-tyrant-of-go':
        'In the gritty urban backdrop, the destitute Master Glenn, unable to care for his young disciple Anna, sends the child down the mountain to seek refuge at the Nova Go Club under Master Parker Jordan.To everyone’s shock, the tiny prodigy cracks the “Sovereign Gambit”—a Go puzzle unsolved for 20 years—overnight. Parker Jordan takes Anna into the club, but crisis strikes again when the ruthless “Go King”Owl storms in for a showdown.Calm and unstoppable, Anna dismantles Owl’s attacks move by move, forcing the defeated king to his knees—begging to become her disciple.When the dust settles, Parker Jordan confides in Anna his lifelong obsession: entering the legendary “Zenith Go Championship” to uncover the truth behind his wife’s death. And so—their fated journey begins.',
    'the-mvp-s-plus-size-love':
        'In a tale of transformation and revenge, bullied high schooler Alexandra reinvents herself as "Lexi" with the help of childhood friend Dan, returning to expose her tormentors, reclaim her dignity, and find true love.',
    'ascension-to-the-lost-throne':
        'After defeating the Killer Sect, the Lord of War, Harry White, is forced to leave the War Sect with his wife due to family conflicts. Unexpectedly, the Killer Sect rejuvenates and collaborates with Harry’s brother, John White, to take him down. Even Harry’s wife betrays him and stands against him. Thanks to Mary Norris, Harry stands a chance to win this battle.',
    'lady-diamond-s-lost-heiress-returns':
        'To save her mother Maria, young Bella Rossi sacrifices herself to the mafia. Twenty years later, Maria has become "Lady Diamond," a powerful mogul searching for her lost child. Meanwhile, Bella is betrayed at her own wedding by her fiancé, Vince, who steals her savings to marry another woman. When Maria recognizes Bella\'s birthmark while Bella is being humiliated at her wedding, she unleashes her power to protect her daughter and crush their enemies.',
    'matrimoney':
        'When a struggling dog-walker agrees to a 30-day fake engagement with a reckless underwear-model billionaire to save her sister, she expects a simple transaction. But sharing a mansion sparks explosive clashes, steamy hate-sex, and an undeniable connection. As jealousy ignites and feelings deepen, they must decide if their pretend marriage is just a deal—or the real love they’ve been avoiding.',
    'mated-to-my-rival-alpha':
        'When Ivy, a disowned Alpha heir, and Alex, her rival’s son, discover they’re bonded by a forbidden mark, they embark on a secret journey to break it. But the deeper they fall for each other, the more dangerous it becomes, because if their love is real, the curse will destroy them both.',
    'riding-with-my-bully-stepbrother':
        'After her mother remarries, Hayley is forced to spend a family vacation with her bully stepbrother, Cole. As old wounds give way to undeniable attraction, forbidden feelings and long-buried secrets threaten to change their relationship forever.',
    'signed-sealed-deceived-by-my-billionaire-mailboy':
        'Ellie falls hard for Colton, the charming mailroom clerk who sees her in a way no one else does. But the deeper she falls, the more she senses he’s hiding something. When she uncovers his true identity a billionaire heir tangled in a web of power and secrets—their forbidden love becomes a dangerous game of loyalty, lies, and desire.',
    'shaping-soulmate-my-soulmate-professor-is-taken':
        'On the brink of graduation, art student Hannah is stunned when her unforgettable summer fling walks into class as her new professor. Caught in a forbidden romance, they must navigate secrets, obsession, betrayal, and academic power plays. As their love deepens, so do the stakes. Is this fated connection a second chance or the start of their undoing?',
    'my-freeze-their-tears-no-forgiveness':
        'Adopted into the wealthy Johnson family at six, Sophie was once their most treasured daughter. But when their biological daughter returns, she becomes the one everyone blames and abandons. Heartbroken, she enters her brother’s life-changing sleep experiment, leaving behind the family she once loved. Thirty years later, they finally want her back—but she no longer remembers them.',
    'her-kept-husband-was-the-king-of-everything':
        'Bound by a six-year promise, the powerful genie Evren hides his identity and protects his wife, Layla, saving her company from every crisis. Yet she treats him like a useless servant. When the contract expires, Evren walks away—leaving Layla to discover that everything she had was built by the husband she despised.',
    'fall-for-mafia-boss-who-killed-my-fiance':
        "Mafia Don Cesare slaughters Helena's fiancé and family on her wedding day, forcing her into a hellish marriage. For seven years, Helena endures his cruel obsession until she fakes her death and flees pregnant. But when Cesare hunts her down, the bloody truth shatters everything she ever believed...",
    'married-an-elven-king-by-mistake':
        "Seeing a future of humiliation as the Crown Prince's bride, Vera lets her sister steal him and marries a dwarf instead, only to discover he is the Elven King. Vera’s sincerity wins his heart, turning a lowly bride into a queen, while her sister is exiled to the land of the Dragons to suffer the fate she created.",
    'too-late-to-mourn-our-daughter-alpha':
        "On Alpha Kurtis's birthday, he abandoned his Luna, Melanie, and their daughter in a deadly dragon attack just to save his mistress. As her daughter's wolf soul faded into darkness, Melanie severed the Mate Bond, swearing blood vengeance.",
    'from-loving-wife-to-bloodthirsty-queen':
        'She gave up her crown and immortality for love—and he repaid her with betrayal and murder. Now the Queen of the Night rises from the grave to reclaim everything. Her groveling ex wants her back, but another guardian already stands at her throne.',
    'ditched-my-wolf-fiance-for-the-beast-king':
        'Betrayed by her fiancé and adopted sister, nine-tailed fox shifter Wisteria takes her sister’s place and marries the feared Serpent Lord. He becomes the only one who truly loves her. Now a legendary alchemist, Wisteria leaves her ex and family begging for forgiveness she’ll never give.',
    'mommy-my-new-dad-is-the-dragon-king':
        "While taking care of her sick son and dealing with her cheating husband, Jessica, a low-level white dragon and trainer, finds herself crossing dangerous paths with her husband's mistress who wants her dead and the King of Dragons who will do anything to protect her.",
    'useless-knight-my-mounts-conquered-every-era':
        '"Four years as the academy\'s top prodigy — then he awakens the ""most useless class in existence"": Knight. His girlfriend dumps him on the spot, running straight into the arms of a corporate heir, while the whole hall laughs him out of the room. What they don\'t know: his real class is Chronicle Knight — heir to the Throne of Mounts, able to contract legendary steeds from EVERY era in history. When Odin\'s mythic warhorse tears open the sky on a rainbow bridge, and a liquid-metal war machine from the future ignites in flame, his enemies drop to their knees begging for mercy. The ""trash"" everyone mocked is now the S-rank legend the entire academy fears. Mount by mount, he awakens gods, machines, ships, and beasts beyond time. Enemy by enemy, he crushes everyone who doubted him. But the real war is just beginning — an invasion from beyond time itself threatens to erase the entire kingdom. When everyone else retreats, he rides forward with seven eras behind him, the last Knight standing between humanity and extinction. The day they threw him away was the day his legend began. Now it\'s their turn to regret it."',
    'our-dirty-little-secret':
        'When Tulli has a one-night-stand at a college party, she expects to never see the man again. Until she discovers that he’s her professor…',
    'the-godfather-s-heartbroken-lover':
        'For five years, Evelyn believed Mafia godfather Dante Moretti loved her—until his first love returned and one cruel choice shattered everything. Humiliated and heartbroken, Evelyn disappears to Berlin, determined to rebuild her life. But Dante, a man feared by everyone, refuses to let her go. As obsession turns into regret and another man offers her the safety Dante never could, one question remains: when the Godfather finally learns how to love, will it already be too late?',
    'downgrade-my-ride-i-ll-upgrade-my-groom':
        'On her wedding day, Eleanor Vance expects to step into the bridal Rolls-Royce. Instead, her fiancé Julian orders her into a cramped backup SUV so his “carsick” secretary Sophia can ride beside him. Humiliated in front of guests and filmed by jealous coworkers, Eleanor refuses to break. When a staged car accident keeps her from the ceremony, Sophia steals her gown, her aisle, and Julian’s kiss. But Eleanor has one card left: Christian Thorne, her childhood best friend and the powerful heir who has loved her for years. Within an hour, Eleanor and Christian are legally married. Then they return to the reception with a marriage certificate and a smile. Julian thinks he can still control the bride he discarded. He has no idea she is done begging for respect. This time, Eleanor is upgrading more than her ride—she is upgrading her whole life forever, and destroying his empire too.',
    'destined-reunion':
        "Logan Campbell's desperate search for Ruby and young Nolan ignites family turmoil, marriage pressure, and questions of bloodline. At a grand birthday feast, a child's bold claim sparks the revelation of a hidden son. Secrets unravel, ties are tested, and the Campbell legacy is pushed to the brink of change.",
    'back-with-baby-ex-regrets-deeply':
        "Vanessa was dumped by her fiancé Seth at the clerk's office. She married billionaire Grayson in an arranged marriage abroad. Three years later, she returns with their son, faces humiliation from Seth and Chloe, and Grayson's brutal revenge reveals his long-hidden love for her.",
    'the-hidden-queen-my-husband-s-mistress-ruined-my-empire':
        'A hidden heiress of Sinclair family builds her husband into a luxury tycoon—until his affair with the restaurant manager and a viral electro-eel attack expose his betrayal. Revealing her true identity, she destroys the empire she built for him.',
    'not-your-average-crow':
        'Emily believes she is a lowly crow who accidentally lands in a phoenix nest. Adopted by Queen Angelina, she keeps trying to escape before a trial exposes her. But when the Magic Mirror shatters and Hellfire dies around her, Emily learns she is the long-lost Abyssal Phoenix—and uncovers a plot threatening her new family.',
    'weak-dragons-covenanted-harem':
        'At a wife selection ceremony, Claire, who was despised by her father and brothers, awakened the system of mating and becoming stronger. As long as she mated with the opposite sex, she could continuously become stronger. In the end, she was crowned as the Dragon Lord of both races, holding the harem of beauties from all races, and creating a new era for the Dragon race!',
    'forbidden-vows-my-bestie-s-billionaire-dad':
        "After her fiancé's scandal ruins her family, destitute Chloe moves in with her best friend Mia — and falls for Mia's cold, domineering billionaire father, Victor. Their forbidden affair ignites; Victor shields her and destroys her ex-fiancé. As exposure looms, Chloe tries to flee, only to be possessively detained by Victor, who refuses to let her go.",
    'the-ceos-exclusive-milk-mommy':
        'After losing her husband and baby, Ella joins Winter Group, only to discover the woman she once saved with her breast milk is CEO Celine Winter. Celine hires her as a personal assistant and grows obsessed with her. As their secret attraction deepens, jealous Margaret schemes against Ella, putting her in grave danger.',
    'clinic-miracle':
        'Resident John unexpectedly gains miraculous supernatural powers to see internal injuries in patients. He uncovers multiple hidden critical conditions and saves countless dying patients. However, his extraordinary diagnostic skills draw suspicion and investigation from his peers. Racing against death in the emergency department, he carefully hides his supernatural secret, while danger creeps closer to him.',
    'exiled-genius-dragon-contract-2':
        'Betrayed and stripped of his gift, Evan Lowe is cast out by his own family. Then a Mythic Beast System awakens—he bonds with the Apocalyptic Demon Dragon and unlocks an SSS talent. Cast out once, he’s back to collect every debt they owe—who will pay first?',
    'space-cowboy-s-royal-escort':
        'Caesar, the universe\'s strongest "Mechanical Man," honors a dying friend\'s wish by escorting Princess Shirley through deadly territory. Battling the Wild Grass Gang at every turn, he holds the line until reinforcements arrive—keeping his promise, and keeping the people he cares for safe.',
    'death-forgot-he-loved-me':
        'Thief Lara steals a cursed ring that binds her to an amnesiac Death God. She is his reincarnated lost love; to break the curse, he sacrifices his divinity for mortality, and she anchors his soul back to earth.',
    'our-crew-has-no-tomorrow':
        "Six written-off Hollywood rejects shot a zombie phenomenon on a single iPhone that racked up a staggering one billion views overnight. But before the victory champagne even stops flowing, a predatory contract drops on the table: despite a billion hits, they haven't earned a single penny—and instead owe the company millions. The more viral they get, the broke they become. Trapped by their own blockbuster, these nobodies decide it’s time to flip the entire table.",
    'my-boss-is-my-babys-father':
        'Pregnant with Lennox Foster’s baby, Nora Shaw can hear her unborn child’s voice and get on-the-spot advice. She lands a job in the Foster home as a gold-medal maternity nanny, caring for their quintuplets while hiding who she is. In Capital City, she’s in demand, but when Lennox learns the truth, can he win Wifey back from five wailing babies?',
    'the-alphas-cursed-luna':
        'Aria goes to the hospital for a check-up but is accidentally inseminated with a powerful Alpha werewolf’s baby. Now trapped in a dangerous world, she must fight to protect herself and the life growing inside her.',
    'my-sunshine-in-the-ruins':
        'In My Sunshine in the Ruins, an optimistic nurse named Anna attempts to melt the icy heart of Elias, a man hardened by the slums. Their blossoming romance proves that even in the darkest circumstances, love can provide the light needed to heal and start anew.',
    'sold-to-the-ice-king':
        'Ice hockey king Damon is cold, arrogant — and secretly a mafia heir. Scholarly beauty Aria is bullied to the brink by Daisy. With her grandma dying and nowhere to run, she makes a deal with Damon: total obedience in exchange for saving her family, crushing her bullies, and becoming campus queen. Their dangerous game of control and submission slowly turns into something real. The ice-cold monster falls for her gentle strength. The broken girl rises from hell. From deadly bargain to desperate love — they drown together.',
    'they-don-t-know-i-m-the-don-s-pregnant-queen':
        'She married New York\'s mafia king — but her family doesn\'t know. Eight months pregnant, she comes home and they treat her like trash: starve her, smash his ring, put a dog collar on her, slice her belly. They laugh at her "nobody husband." But that nobody owns the city — and she\'s its queen. One call brings helicopters, armored cars, and everyone pays.',
    'from-one-night-to-mrs-billionaire':
        "Claudia is the adopted daughter of the richest man, Kaden. She drugged and framed Anastasia, wanting to ruin her reputation and divorce her husband Lucius. However, Anastasia was rescued by the drunk Kaden by mistake and became pregnant with Kaden's only child. Clarissa, relying on her status as the richest man's adopted daughter, was arrogant and domineering, targeting Anastasia at the company and at the banquet, but she didn't know that Kaden had taken Anastasia home to take care of her and fell in love with her. In the end, Claudia's true identity was also discovered by Kaden...",
    'bring-it-on-my-mafia-life':
        'Sold for five million, Rhea was traded by her parents to the mafia Lukas. While Lukas was supposed to treat her as a mere plaything, he unexpectedly went to great lengths to protect her in the perilous world of the mafia. Does he genuinely love her, or is he merely considering her as part of a dangerous yet thrilling game?',
    'my-boyfriend-gave-my-virginity-to-his-bro':
        "Emma plans to lose her virginity to her boyfriend Blake on her birthday. When a chandelier falls and knocks her out, Emma wakes up with amnesia. To cover up the fact that he’s been cheating with Emma’s best friend, Blake tells Emma she's dating his best friend, Dylan. Emma believes him and starts dating Dylan, only to find out Dylan’s big secret—he’s been secretly in love with her for years! When Emma finally gets her memory back, she cries out shouting, “You lied to me!” Dylan pulls her tight against his chest and says, “The only thing I lied about was pretending I didn’t want you all this time!”",
    'her-rich-dream-shatters':
        "A wealthy matriarch leaves hospital with her granddaughter, only to meet her son's gold-digger and her daughter. Hoping to marry into the family to pay her ex's debts, she plans to flatter her future mother-in-law--but not recognizing them, she bullies and assaults them. When she learns who she attacked, her rich family dream shatters instantly.",
    'my-future-daughter-in-law-has-syphilis-obstetrics-director-henry-carter-discovers-his-future-daughter-in-law-lydia-shaw-has-syphilis-she-responds-by':
        'Obstetrics director Henry Carter discovers his future daughter-in-law Lydia Shaw has syphilis. She responds by assaulting, humiliating, and forcing him to kneel before destroying his trophy. Protected by her wealthy fiancé, Lydia terrorizes everyone. Henry Carter patiently waits, then exposes her affairs, infection, and lies at a birthday banquet and hospital ceremony. Lydia and her lover turn on each other, leading to murder. She ends up in prison, where justice finally prevails.',
    'that-prince-is-a-girl-the-princess-and-her-grand-king':
        "To protect her sister, Emeriel disguises herself as a male servant when both sisters are sold as slaves to the beasts kingdom of Urai. But Emeriel is no ordinary human, she's a rare Syren, the only one who can calm the beast king Daemonikai in his feral state, and they secretly fall for each other. As the jealous Sinai torments her, the ambitious lord Zaiper schemes against her, and the cursed Vladya becomes obsessed with her sister, Emeriel fights to keep her identity hidden while navigating deadly traps. In the end, she breaks the beast-king's curse unexpectedly.",
    'miss-urologist-and-her-ceo-patient':
        'Ximena, a female urolosist, blackmails a patient—the aloof CEO Ayden—to raise research funds. Forced into a contract marriage, the two engage in a battle of wits and laughter after moving in together. Ximena discovers his "impotence" is due to chronic poisoning and dedicates herself to its treatment. Though Ayden only wants to use her at first, he gradually falls for her. Ultimately, their fake relationship becomes real, resulting in a sweet and unexpected romance.',
    'my-secret-protector-was-in-love-with-me':
        "At her father's will reading, Eliza was publicly humiliated by her fiancé Wayne and her sister Beth. They planned to destroy her, but Doris had been protecting her all along. She saved her, exposed the plot, and revealed Beth was their mother's illegitimate daughter, and Wayne was tied to her father's death. Eliza signed a one-year marriage contract with Doris and exposed everything, put Wayne and Ruby in prison. Beth retaliated with kidnapping and arson until Doris killed her. Jealous Maren allied with a mafia boss, but Doris turned the trap around. Maren died. Doris proposed. They married and rebuilt the family together.",
    'burning-hot-laps':
        "Jace, a gifted Omega, once raced beside his lover Darius, the Alpha heir to the Aegis Syndicate. Framed for betrayal, he vanished for five years. Now fixing cars for his brother and endless debts, Jace is bound by a harsh contract to Darius, his new boss. Yet Jace's talent wins races, Darius feels his unwavering devotion. The conspiracy traces back to Darius's father. Worse, Jace's jealous rival sabotages the car to trigger a fatal crash. Jace takes the hit to shield Darius. The truth unfolds when Jace wakes. He reclaims all he lost and returns to racing as champion, with Darius at his side.",
    'the-abandoned-god-of-olympus':
        "Olympus true prince Elon is framed by adopted son Valerius, stripped of divinity and abandoned to death by Zeus and his family in his past life. Reborn 20 years earlier, he leaves Olympus, restores his power via mortal faith, teams up with Gaea, coldly rejects the gods' desperate plea during the Titan crisis, defeats the enemy and reigns over mortals.",
    'the-rogue-brother-s-claimed-omega':
        "Low-ranking sailor Aiden Clark has a secret crush on fleet heir Ethan Iverson. After gaining his fated tidal mark, he is cruelly rejected, leaving the mark damaged. Ethan's ostracized older brother Ryan steps in roughly yet gently. Torn between mixed feelings, Aiden learns his true destiny belongs to someone else.",
    'his-neglected-wife-is-the-top-scientist':
        "June, a genius scientist, gave up her career to marry Cole. She did this for love, yet Cole neglected her. When she was bleeding out from miscarriage, he was with his mistress Alycia. June lost her child, her ability to conceive, and her love for him. She started research again, tackled Cole's slander, and took back her stolen works. She was still the top scientist.",
    'the-prince-is-a-girl-the-slave-in-a-princess-disguise':
        "To protect her sister, Emeriel disguises herself as a male servant when both sisters are sold as slaves to the beasts kingdom of Urai. But Emeriel is no ordinary human, she's a rare Syren, the only one who can calm the beast-king Daemonikai in his feral state, and they secretly fall for each other. As the jealous Sinai torments her, the ambitious lord Zaiper schemes against her, and the cursed Vladya becomes obsessed with her sister, Emeriel fights to keep her identity hidden while navigating deadly traps. No one expected, in the end, she breaks the beast-king's curse...",
    'revenge-backfired-now-my-stepbrother-is-my-boyfriend':
        "Oliver was the star receiver on the high school football team. He worshipped Captain, but hated his own stepbrother. Until he realized they were the same person Carlos. To get back at his stepbrother for ruining his relationship, Oliver publicly claimed to be his boyfriend. But the prank backfired, sparking a dangerous spark between them. From locker room tension to poolside confrontations, enemies became something hotter and undeniable. Carlos' hidden feelings surfaced, and Oliver found himself falling for the man he swore to hate. In the end, they stood together, no longer hiding, and no longer pretending.",
}

SOURCES = {
    'fake-dating-my-rich-nemesis': ('platform', 'https://www.dramaboxdb.com/movie/41000119532/fake-dating-my-rich-nemesis'),
    'think-again-i-m-the-hidden-boss-mom': ('platform', 'https://www.dramaboxdb.com/movie/42000010883/think-again-im-the-hidden-boss-mom'),
    'waking-up-married-to-my-crush': ('platform', 'https://www.dramaboxdb.com/movie/41000107274/waking-up-married-to-my-crush'),
    'forever-was-a-lie': ('platform', 'https://www.dramaboxdb.com/movie/41000110445/forever-was-a-lie'),
    'the-billionaires-rescue': ('platform', 'https://www.flextv.cc/episodes/episode-1-the-billionaire%E2%80%99s-rescue-pEMOJ88nLa'),
    'guess-who-they-miss-now': ('platform', 'https://www.dramaboxdb.com/movie/42000015757/guess-who-they-miss-now'),
    'the-tiny-tyrant-of-go': ('platform', 'https://www.flextv.cc/episodes/episode-1-the-tiny-tyrant-of-go-dubbed-WKzLolDOr0'),
    'the-mvp-s-plus-size-love': ('platform', 'https://www.reelshort.com/movie/the-mvp-s-plus-size-love-6916da90686e13455b00b9d5'),
    'ascension-to-the-lost-throne': ('platform', 'https://www.dramaboxdb.com/movie/41000104164/ascension-to-the-lost-throne'),
    'lady-diamond-s-lost-heiress-returns': ('platform', 'https://www.dramaboxdb.com/movie/42000012143/lady-diamonds-lost-heiress-returns'),
    'matrimoney': ('platform', 'https://www.vigloo.com/en/content/15000316'),
    'mated-to-my-rival-alpha': ('platform', 'https://www.vigloo.com/en/content/15000323'),
    'riding-with-my-bully-stepbrother': ('platform', 'https://www.vigloo.com/en/content/15003223'),
    'signed-sealed-deceived-by-my-billionaire-mailboy': ('platform', 'https://www.vigloo.com/en/content/15000307'),
    'shaping-soulmate-my-soulmate-professor-is-taken': ('platform', 'https://www.vigloo.com/en/content/15000332'),
    'my-freeze-their-tears-no-forgiveness': ('platform', 'https://www.flextv.cc/episodes/episode-1-my-freeze-their-tears-no-forgiveness-BxZ0XB7ZQ7'),
    'her-kept-husband-was-the-king-of-everything': ('platform', 'https://www.goodshort.com/drama/her-kept-husband-was-the-king-of-everything-31001707745'),
    'fall-for-mafia-boss-who-killed-my-fiance': ('platform', 'https://www.goodshort.com/drama/fall-for-mafia-boss-who-killed-my-fiancé-31001775049'),
    'married-an-elven-king-by-mistake': ('platform', 'https://www.goodshort.com/drama/married-an-elven-king-by-mistake-31001719141'),
    'too-late-to-mourn-our-daughter-alpha': ('platform', 'https://www.goodshort.com/drama/too-late-to-mourn-our-daughter-alpha-31001710892'),
    'from-loving-wife-to-bloodthirsty-queen': ('platform', 'https://www.goodshort.com/drama/from-loving-wife-to-bloodthirsty-queen-31001710868'),
    'ditched-my-wolf-fiance-for-the-beast-king': ('platform', 'https://www.goodshort.com/drama/ditched-my-wolf-fiancé-for-the-beast-king-31001755075'),
    'mommy-my-new-dad-is-the-dragon-king': ('platform', 'https://www.goodshort.com/drama/mommy-my-new-dad-is-the-dragon-king-31001770535'),
    'useless-knight-my-mounts-conquered-every-era': ('platform', 'https://www.goodshort.com/drama/useless-knight-my-mounts-conquered-every-era-31001745062'),
    'our-dirty-little-secret': ('platform', 'https://candyjar.com/series/our-dirty-little-secret-269'),
    'the-godfather-s-heartbroken-lover': ('platform', 'https://www.shorttv.live/drama/the-godfathers-heartbroken-lover-33142'),
    'downgrade-my-ride-i-ll-upgrade-my-groom': ('platform', 'https://www.shorttv.live/drama/downgrade-my-rideill-upgrade-my-groom-25800'),
    'destined-reunion': ('platform', 'https://www.shorttv.live/drama/dubbeddestined-reunion-11266'),
    'back-with-baby-ex-regrets-deeply': ('platform', 'https://www.shorttv.live/drama/back-with-baby-ex-regrets-deeply-19718'),
    'the-hidden-queen-my-husband-s-mistress-ruined-my-empire': ('platform', 'https://netshort.com/episode/the-hidden-queen-my-husbands-mistress-ruined-my-empire-2064230228554887169'),
    'not-your-average-crow': ('platform', 'https://netshort.com/episode/not-your-average-crow-2097959125560745985'),
    'weak-dragons-covenanted-harem': ('platform', 'https://netshort.com/episode/weak-dragons-covenanted-harem-2101239560518004737'),
    'forbidden-vows-my-bestie-s-billionaire-dad': ('platform', 'https://netshort.com/episode/forbidden-vowsmy-besties-billionaire-dad-2096775770596225026'),
    'the-ceos-exclusive-milk-mommy': ('platform', 'https://netshort.com/episode/the-ceos-exclusive-milk-mommy-2098613294458261505'),
    'clinic-miracle': ('platform', 'https://netshort.com/episode/clinic-miracle-2102939053153132545'),
    'exiled-genius-dragon-contract-2': ('platform', 'https://netshort.com/episode/exiled-genius-dragon-contract-2-2103025100696715265'),
    'space-cowboy-s-royal-escort': ('platform', 'https://netshort.com/episode/space-cowboys-royal-escort-2102945460413870082'),
    'death-forgot-he-loved-me': ('platform', 'https://netshort.com/episode/death-forgot-he-loved-me-2103396879365910530'),
    'our-crew-has-no-tomorrow': ('platform', 'https://netshort.com/episode/our-crew-has-no-tomorrow-2102947590696673281'),
    'my-boss-is-my-babys-father': ('platform', 'https://netshort.com/episode/my-boss-is-my-babys-father-2102975962508558338'),
    'the-alphas-cursed-luna': ('platform', 'https://my-drama.com/series/the-alphas-cursed-luna-84da5139-d0e1-47fe-b704-5957afac6de7'),
    'my-sunshine-in-the-ruins': ('platform', 'https://pinedrama.com/dramas/my-sunshine-in-the-ruins'),
    'sold-to-the-ice-king': ('platform', 'https://www.flickreels.net/playlist/sold-to-the-ice-king/10268/episode-1'),
    'they-don-t-know-i-m-the-don-s-pregnant-queen': ('platform', 'https://www.flickreels.net/playlist/they-dont-know-im-the-dons-pregnant-queen/9321/episode-1'),
    'from-one-night-to-mrs-billionaire': ('platform', 'https://www.flickreels.net/playlist/from-one-night-to-mrsbillionaire/1253/episode-1'),
    'bring-it-on-my-mafia-life': ('platform', 'https://www.dreameshort.com/en/drama/bring-it-on-my-mafia-life-91'),
    'my-boyfriend-gave-my-virginity-to-his-bro': ('platform', 'https://www.dreameshort.com/en/drama/my-boyfriend-gave-my-virginity-to-his-bro-1309'),
    'her-rich-dream-shatters': ('platform', 'https://www.stardusttv.net/episodes/01-her-rich-dream-shatters-22706'),
    'my-future-daughter-in-law-has-syphilis-obstetrics-director-henry-carter-discovers-his-future-daughter-in-law-lydia-shaw-has-syphilis-she-responds-by': ('platform', 'https://www.stardusttv.net/episodes/01-my-future-daughter-in-law-has-syphilis-18848'),
    'that-prince-is-a-girl-the-princess-and-her-grand-king': ('platform', 'https://www.moboreels.com/drama/that-prince-is-a-girl-the-princess-and-her-grand-king-67906322'),
    'miss-urologist-and-her-ceo-patient': ('platform', 'https://www.moboreels.com/drama/miss-urologist-and-her-ceo-patient-47878322'),
    'my-secret-protector-was-in-love-with-me': ('platform', 'https://www.moboreels.com/drama/my-secret-protector-was-in-love-with-me-72983322'),
    'burning-hot-laps': ('platform', 'https://www.moboreels.com/drama/burning-hot-laps-73183322'),
    'the-abandoned-god-of-olympus': ('platform', 'https://www.moboreels.com/drama/the-abandoned-god-of-olympus-66717322'),
    'the-rogue-brother-s-claimed-omega': ('platform', 'https://www.moboreels.com/drama/the-rogue-brothers-claimed-omega-62085322'),
    'his-neglected-wife-is-the-top-scientist': ('platform', 'https://www.moboreels.com/drama/his-neglected-wife-is-the-top-scientist-60357322'),
    'the-prince-is-a-girl-the-slave-in-a-princess-disguise': ('platform', 'https://www.moboreels.com/drama/the-prince-is-a-girl-the-slave-in-a-princess-disguise-52105322'),
    'revenge-backfired-now-my-stepbrother-is-my-boyfriend': ('platform', 'https://www.moboreels.com/drama/revenge-backfired-now-my-stepbrother-is-my-boyfriend-65313322'),
}
