# -*- coding: utf-8 -*-
"""APPROVED captions only. Chinese short dramas imported 28 Sep 2026 (57).

APPROVAL BASIS, 28 Sep 2026: Cyan asked for these to be captioned ("caption the
57 Chinese dramas"). None ranks in the top 300 by reach, so her 16 Aug 2026 ruling
applies them without her manual check. Written in two parts
(captions_2026_09_28_cn57_part1.py, part2.py), each passing check, lift_check at
6 words and readback. Flags for her eye are in each part's header.
"""

CAPTIONS = {
    'divorce-my-happily-ever-after':
        "Five months pregnant, and her husband throws her out for his mistress.\nRosie Turner gave up everything for her marriage. Her reward is a husband who cheats with his mistress and then puts her out of the house in disgrace while she is five months along. Once the divorce is done she meets Andrew Jaffe, a young CEO with charm to spare, and he's firmly on her side. He backs her as she goes after the people who wronged her and as she builds a career of her own. The woman they humiliated is about to win at work and in love.",
    'moving-on-from-you':
        "Every birthday she tells him she loves him. Every birthday he says no.\nSam Bale took Jane Rowe in when she was seven, and she has loved him ever since. So she confesses to him on her birthday, year after year, and every time he turns her down. He says the ten year age gap between them is too much, and he goes and picks another woman. Then one night they both drink too much and end up in bed together, and in the morning Sam can't remember a thing. When Jane turns up pregnant he calls her shameless. Heartbroken, she walks away and leaves him to his girlfriend. Now she's the one moving on, and she's taking his baby with her.",
    'winning-her-over-a-second-time':
        "Three years together and he still won't marry her.\nSally Nelson has lived with Quinton Young for three years, and he knows perfectly well she wants a wedding. He just keeps pushing it back. Anyone can see he loves her, but he won't even admit out loud that they're a couple. Sally finally runs out of patience. She leaves him and looks to someone else for the commitment Quinton never gave her. Now he has to win her over all over again.",
    'a-contractual-marriage-hell-no':
        "She threw herself at her CEO. Now her parents have picked her a husband.\nKeira Snow wakes up horrified. Last night she was the one who made the move on Nolan Blair, and he's the CEO of the company she works for. The guilt is so bad she thinks about handing in her notice. Her cold hearted parents don't give her time to decide, because they've already arranged a marriage for her and her opinion doesn't come into it. Keira gives in and agrees to it, with the night she spent with her boss still hanging over her.",
    'every-thought-every-love-is-you':
        "Everyone thought he was ice cold. Then he wrote down her name.\nEllis Hill has a reputation for keeping everyone at arm's length, so no one had any idea Claire Newton was part of his marriage pact. Everyone is stunned when he puts her name down as his wife. Claire goes in expecting a marriage that exists on paper and nowhere else. Instead, once they're wed, the man everyone calls cold can't stop spoiling her.",
    'answer-to-my-heart':
        "She's pretended to be mute for years. Now she's pretending to be a kidnapper.\nFor years Cecelia Collins has been made to act as if she can't speak. Then comes a kidnapping, and in the middle of it she gets it into her head that Ivan Justice doesn't want the baby she's carrying. To keep her child safe she takes on the role of the kidnapper herself and pulls Ivan into a nerve racking standoff. As the misunderstandings between them come apart one by one, Ivan urges her on, and Cecelia finally finds the nerve to use her voice and go after what she really wants.",
    'she-came-from-the-abyss':
        "She came to the Bay family as a maid. She came for revenge.\nAdel's mother and older sister are dead, and the woman she holds to account is Jamie Suthern, who is married to Tony Bay. So Adel takes the name Kris Frost and gets herself taken on as their maid. She wins the household's trust, stirs up trouble, seduces Tony and wrecks the marriage. Jamie is clever, but Adel is completely unhinged, and the two women go to war. Adel gets thrown out of the house three times. Every time, she comes back.",
    'the-unknown-man-i-call-mine':
        "She married the man everyone says is ugly to save her family's business.\nClaire Lane needs her family's company rescued, and marrying Linus Lyon is the price, even though he's said to be anything but handsome. Her own relatives turn on her, so she and Linus join forces to fight them off, and bit by bit she wins herself a real place in the business. Then a mysterious figure starts raising questions about who Linus really is. Every new crisis pulls them closer together. And the secrets waiting at the end aren't only his. Claire is about to learn the truth about where she came from too.",
    'the-fiery-young-marshal':
        "She became his secret lover to save the family that raised her.\nSong Shuangxu's parents abandoned her when she was little, and Shen Yu took her in and spoiled her like a princess. As she grew up she misunderstood how much she leaned on him and believed it was love. When the Shen family found out, they sent her abroad, and she stayed away for years. By the time she comes home, rivals have framed the Shens. Owing them everything, Song Shuangxu agrees to be the hidden lover of He Tingzhou, Yancheng's young master. What she doesn't know is that he has wanted her for years and planned every step of this. The way he looks after her, down to the smallest thing, is about to show her what real love looks like.",
    'spring-night-s-fiery-kisses':
        "Three rich young men drove her sister to her death. She wants them to pay.\nThree wealthy young men pushed Li Chuchu's little sister into taking her own life. Her mother took a beating so savage it left her in a vegetative state. Li Chuchu quits school and joins the Cloud Peak Club with one goal, getting close to Pei Qingji, the man who holds the power in Jinggang, and using him for her revenge. She plays the fragile girl and plots every move with care. What she didn't plan for is Pei Qingji spoiling her so fiercely and so relentlessly. Somewhere along the way she falls for the man she meant to use.",
    'victory-in-love':
        "Weekend lovers, strictly business. That was the deal.\nLin Zhanhong rules her office, and Wen Yushi has just been named the new director. They agree to be lovers on weekends only, as partners with no feelings allowed. As they back each other through the company's power struggles, the arrangement quietly turns into the real thing. Then it comes out that Wen is secretly the company heir, a love rival who is hard to beat turns up, and suddenly trust is the one thing they don't have. To come out on top they'll both have to drop their guard and admit what they feel, at work and in love.",
    'embrace-you-through-the-ashes':
        "He took her in and kept her safe. Then he vanished and told her to forget him.\nWith her father gone, Jiang Wu spends her days hiding from debt collectors. Then she meets Jiang Yan, a quiet man who always seems to be hurt somewhere, and he gives her a place to stay and keeps her safe. She has no idea his real name is Lu Xiao, or that he's an undercover cop inside a gang in their border town. Two lonely people draw closer, but she can never quite read him. When his mission reaches its most dangerous point he's gone, leaving her some money and a note that says she should forget him. Four years on, she's a reporter at North City TV and he's out of the force with injuries, running a guesthouse he named Yearning for Wu. When her interview schedule sends her through his door, he calmly tells her who he really is. She has spent years hating him and looking for him, and now she learns every secret and every push away was him protecting her.",
    'dark-light':
        "He's her driver. He's also using her to get his revenge.\nQin Yulin drives for Xingyao Group, and after what looks like a chance meeting at a bar he wakes up in Xu Enxin's bed. She's the heiress to the Fenghua Chamber of Commerce, and she's so taken with him that she asks Xingyao's CEO, Zhou Xinghan, to hand him over as her personal driver. He learns everything she likes, has her coffee ready just how she takes it when she's worn out, and steps between her and every threat. Before long she can't do without him. But eighteen years ago the Zhou family caused his parents' deaths and locked him into an 80 year contract with them, and getting close to Xu Enxin was the key move in his plan to make them pay. He never meant to fall in love with her. When she finds out why he really came, she agrees to get engaged to Zhou Xinghan for political reasons, and all Qin Yulin can do is guard her from a distance. By the night of the engagement banquet, though, both of them are holding a secret.",
    'the-seventh-year-of-pending-love':
        "Seven years of almost. One drunken kiss. Then he says they're just friends.\nCheng Xia grew up alongside Chen Shechuan and has loved him the whole time, and their seven years together have been full of moments that felt like more. Then one night they've been drinking and they kiss. Shechuan's answer is to tell her they're only good friends. The truth is he's afraid of getting close to anyone after watching his parents' marriage fall apart. To make her let go, he shows up at her house with his girlfriend Jiang Yining, and he even sets her up on a blind date and calls it doing her a favor. Heartbroken, Xia decides it's time to walk away from whatever this is. Will he figure it out before she's gone for good?",
    'depth-of-love':
        "One kiss from the secretary and the CEO is hooked.\nSecretary Song Xi is strict and serious at work, all business, all the time. Then comes news of late stage cancer, and Song Xi kisses CEO Jiang Tingzhou like there's no tomorrow. From that moment Jiang Tingzhou can't get enough of Song Xi. Wanting their casual fling over, Song Xi hands in a resignation the very next day with a parting shot: the CEO's performance wasn't very satisfying, so they should split on good terms. Later, when they're deep in love, Jiang Tingzhou makes a habit of asking Song Xi one question. Is Song Xi satisfied now?",
    'heart-throb-fortune':
        "Her mission is to steal a toothbrush. Her cover is a psychic called Mr. Moon.\nRan Xing is a 22 year old graduate student, and with her sister behind bars she has no choice. She has to pose as the psychic Mr. Moon, get inside the rich Ye family, and walk out with a toothbrush. Nothing about the job is simple. Her boyfriend Pu Yubai isn't who he seems, the Ye family are full of feuds, and Ye Zhaoning keeps testing her. Through one crisis and misunderstanding after another, she earns his trust and starts to understand her own heart. In the end she tells him who she really is, ends things with Pu Yubai, and decides to build her studies and career on her own. Three years later she's a counselor helping other people heal when she meets a more grown up Ye Zhaoning again, and this time class and old misunderstandings don't stand in their way.",
    'the-penthouse-club':
        "She sets a father against his son to avenge her sister.\nZhong Xian's sister depended on her, and her sister's tragic death pulls Zhong Xian into the bitter feuds of a powerful old family. She puts herself in the middle of the fight between Qin Hao and Qin Lang, father and son, offering herself as bait and betting her own life to drive the two men further apart. As the power struggle gets uglier, Qin Feng begins to slide toward ruin. But the hatreds inside this family run deeper than Zhong Xian ever guessed, and she was never the one pulling the strings. She's only a piece on Qin Hao's board. And the moment she thinks her revenge is complete is the moment the real bloodshed starts.",
    'affectionate-seduction':
        "She married into the family tied to her parents' deaths.\nLin Yuxi was six when her parents were killed, and she grew up in a welfare home. When she learns the Zhou family is connected to their deaths, she marries Zhou Yanjing, their second son. The marriage is a mess of misunderstandings, with each of them convinced the other is in love with somebody else. Once they finally clear the air, Yanjing goes all in to win her. He fills the sky with fireworks spelling her name, confesses his feelings in a staged interview, and even rigs their watches with sensors that track how far apart they are. The marriage she walked into for her parents turns out to be the real thing.",
    'hunting-love':
        "Three years undercover as his fiancee. On their wedding day, she shoots him.\nWan Lin wants justice for her mother's death, so she spends three years undercover as the fiancee of Fu Yan, heir to Mai City's underworld empire. On the day they're supposed to marry, her own agency storms the wedding, and Wan Lin pulls the trigger on Fu Yan. The next time they meet, the enemies end up on the same side. Wan Lin starts to see that his heart was true, and together they take the criminal network apart from the inside. Revenge brought her to him, and love is what keeps them together.",
    'married-to-my-crush':
        "She married him the night her first love left her. He'd loved her for eleven years.\nOne snowy night in North City, Huo Xin, Zhong Xiran's first love, walks away from her, and she ends up marrying Qi Sinian instead. What she doesn't know is that he has loved her quietly for eleven years. Four years into a marriage that feels cold on the surface, her ex is back, her family is piling on the pressure, and the rumors won't stop. That's when she learns the truth. Qi Sinian planned this marriage long ago, as a way to love her and keep her safe. And once she knows, there's only one place she wants to be.",
    'the-flame-of-love':
        "Her fiance plans to kill her after the wedding. So she goes after his rival.\nShi Ning's younger brother is in a coma, and the only way to save him is to marry Shen Nanxun, the Shen family's eldest grandson. On the day of the engagement she finds out he's sleeping with his secretary and plans to kill her once they're married. Desperate, she sets her sights on Shen Lingchen instead, the most feared man in the Shen family and Nanxun's rival, and tries to make him her husband. Lingchen sees straight through her flirting and her careful testing, and he protects her anyway, again and again. Somewhere in the game of wits, it turns into love. But Shi Ning can't let herself fall. This marriage was only ever about saving her brother.",
    'a-love-beyond-secrets':
        "An accident threw them together. Only he knows it wasn't one.\nJi Xuan is drugged by mistake, and that is how Song Zhaoli comes into the picture. The quiet life Ji Xuan had is turned upside down. Everyone assumes Ji Xuan is using him to get ahead, but Song Zhaoli is the only one who knows the whole thing was his plan from the start. Tangled up with him again and again, Ji Xuan slowly starts to work out the mystery behind it all. What grows between them is fierce and complicated, and each of them turns out to be the other's way back.",
    'perfect-secretary-s-love':
        "She's the perfect secretary. Her love life is a disaster.\nQiu Yu is sharp, funny and level headed, and she's brilliant at her job as secretary to CEO Ji Xiangdong. He's a workaholic who keeps his family at a distance. She's an optimist with parents who adore her. The one thing in her life that won't go right is romance, and all she wants is someone who truly loves and understands her. Between an ex who won't take no for an answer and a family that keeps meddling, the feelings Xiangdong has been hiding behind that cold front finally start to show. With her career and her heart both in a spin, Yu has to decide what will make her happy.",
    'a-thousand-times-for-you':
        "Her fiance betrays her on their wedding day. So she proposes to a mechanic.\nChen Zi is a rich heiress whose wedding day falls apart when her fiance betrays her. She heads to a bar to drown it all, ends up in a scuffle with a thug, and He Chuan steps in to save her. She falls for him on the spot. The next time their paths cross, she doesn't wait around. She's the one who asks him to marry her. But this rough and ready mechanic has been living a double life, and she has no idea.",
    'in-her-charming-grasp':
        "The whole city laughed at her for chasing him. She never loved him at all.\nJiang Xian throws herself at Lin Yuanzhou so openly that the whole city laughs at her. Everyone assumes he's the only man she'll ever marry. Then it comes out that he was never the one she wanted. He was only ever a stand in to her, she doesn't love anyone at all, and she's ready to disappear. Lin Yuanzhou never thought he was capable of love, but now he's falling for her for real. By the end he's half out of his mind, keeping her at his side by force and begging her to love him back.",
    'love-once-again-in-the-80-s':
        "The sisters killed each other. Then they were both reborn.\nIn their first life, Lu Zhaoyan married Kuang Yue when he had nothing, and to her surprise she ended up a rich man's wife. Her sister Lu Qinning married Ling Yue, a military officer, and lost her mind when he died in an accident not long after the wedding. Qinning murdered Zhaoyan, Zhaoyan killed her back, and both sisters were reborn. This time Qinning grabs Kuang Yue for herself, sure she's stealing the better life. What she doesn't know is that Zhaoyan is reborn too, and she has already saved Ling Yue from dying. So who really got the better husband this time?",
    'fake-marriage-real-love':
        "She needed a husband on paper. He needed a wife to get out of an arranged marriage.\nXia Xingyan needs a marriage certificate so her daughter can be registered, but when she goes to get one with her boyfriend, his mistress turns up to taunt her. Zhan Yechen, meanwhile, will do anything to escape the match his family has set up, and he needs a stand in wife fast. So they agree to a fake marriage. Then Xia Xingyan finds out her daughter isn't her boyfriend's child at all, and Zhan Yechen helps her hit back. Her best friend Shen Rui starts posing as the first love Zhan Yechen lost long ago, and the misunderstandings pile up. Through all of it Zhan Yechen falls for Xia Xingyan, and he's starting to wonder whether her little girl might be his.",
    'when-fish-swim-to-land':
        "A teacher who always follows the rules. A dad who runs a fish shop.\nSun Lu teaches elementary school and never puts a foot wrong, but part of her is aching to break loose. A home visit she didn't expect to make puts Chen Xudong, the owner of a fish store, in her path. At first she has him down as a troublesome man with a kid. He looks at her and sees past the good girl act to someone as stubborn and lonely as he is. As their first impressions fall away, they drift closer in the quiet of his tanks. Then Sun Lu discovers this gentle man has a past he's buried deep. With the gap in their social standing and the secrets he's kept locked away, can they still find a way to save each other?",
    'note-to-my-true-love':
        "They passed notes in college. Seven years later he's still waiting for her.\nJi Hanyue gave up on her dream of designing jewelry a long time ago, and now she's stuck in a marriage with no love in it. Her husband He Jiayuan freezes her out and his mother never lets up on her. One snowy night, out looking for a doctor, she runs into Jiang Peizhi, the boy she used to pass notes with in college. He's chairman of the Jiang Group now, and he never stopped loving her. Once he sees how unhappy she is, he sets out to get her free. He carefully brings He Jiayuan's lies to light, from pretending to be someone he isn't to cheating on her and using her for his own gain, and Ji Hanyue gets her divorce. With Jiang Peizhi behind her she picks up her designs again and stuns the industry with a line of butterfly jewelry. And the man who waited seven years for her is right there when she's finally ready.",
    'love-s-trenches':
        "He disappeared without a word. Three years later he's back as a CEO.\nMia Bale's family is as rich as they come, but she's starting at the bottom as an intern in the family business. Then Ken Leed walks back into her life. He's the boyfriend who vanished three years ago and never said why, and now he's the CEO of a company that works with hers. Mia wants to fix what broke between them, but Lily Cork keeps stirring up misunderstandings to keep them apart. Will Mia ever find out why he left?",
    'in-the-snare-of-love':
        "She became his lover to save her sister. Her sister died anyway.\nCheryl Snow's sister Nina has heart disease, and Sean Hall has the cure. So Cheryl goes to him and ends up as his lover. Sienna Zane can see where that's heading and can't stand the thought of Cheryl winning Sean over, so she teams up with Heath Clark to set Cheryl up. Their plan costs Nina her life on the operating table. Cheryl is shattered and tells Sean it's over, and only then does he realize he's already in love with her. Now he wants to know exactly how Nina died.",
    'the-choices-of-fate':
        "Two sisters, one grandmother, and only one of them can go.\nWhen their mother dies, Kate and Amelia Morse are told their grieving grandmother can take just one of them with her. Amelia is sure that's the road to money, so she's the one who goes. What she gets is a completely ordinary life. Years later Kate marries into the rich Warren family, and Amelia can't bear it. Her jealousy turns to rage, and she kills her sister and then herself. One choice made when they were girls ends with both sisters dead.",
    'trapped-in-the-allure':
        "She sold one night to save her sister. A year later she ran into him again.\nTanya Abell had to pay for her sister's treatment, so she sold her virginity to Taylor Wayne for a very high price. A year on she runs into him at a gathering, and he knows her straight away and pins her to a wall. She gets away from him and slips back into the private room, but Jason hauls her right back to Taylor. Then Jason tells her the one thing she can't walk away from. The only person who can cure her sister is Taylor.",
    'his-dangerous-obsession':
        "He came home from service to find his own family's company hunting him.\nAustin Gorman is a powerful family's illegitimate son, and when he gets back from serving overseas the directors of the family company want him gone. It's a ruthless fight for power and he ends up running for his life. That's when Diane Hoover crosses his path and saves him. The night she rescues him turns out to be the start of a love that was always meant to be.",
    'survive-and-thrive-the-mute-consort':
        'Poisoned as a child and left without a voice.\nEverly Swan and her mother grew up under the thumb of the family matriarch, who bullied them without mercy and even poisoned Everly, leaving her unable to speak. At the lowest point, one piece of candy shared between two kids became a friendship nothing could break. Years later Everly is set on protecting her mother, and the only way she can see to do it is to climb high enough that nobody can touch them. Her cruel half sister has other ideas and grinds her pride into the dirt. Can Everly survive this family, let alone thrive?',
    'of-his-day-and-night':
        "She married Jordan. On her wedding night she met Simon.\nTessa Tilden is an andrologist who takes Jordan Slate as her husband to save her mother, and she walks straight into a family full of schemes. On their wedding night she comes face to face with Simon Slate. Later she learns Simon isn't another man at all. He's a second personality that split off from Jordan after a trauma he suffered as a boy seventeen years ago. The deeper Tessa digs, the clearer it gets that a kidnapping was behind it all, so she and Jordan team up to take down his uncle Marcel Slate and put the Slate family back together.",
    'sometimes-calm-is-deadly':
        "Everyone thinks he's recovered. He's only getting started.\nWhen his girlfriend Aurora Golde dies, Noah Stark loses his mind. By the time the hospital lets him out he's acting perfectly well, but it's all an act. Quietly and patiently he builds his revenge, setting Jerry Fox and Jade White at each other's throats. When the truth finally comes out he has to answer for what he's done, and for the woman he loved he pays that price gladly.",
    'starlight-redemption':
        "His price for her mother's treatment is dinner. Every single day.\nLin Qingzhu is a talented architecture student whose mother is gravely ill, and Chu Guanxing is using the hospital bills to humiliate her. Then his uncle Chu Nanhe makes her an offer nobody saw coming. He's in a wheelchair and he's the one who really runs the Chu family, and all he wants is for her to eat dinner with him each day. In return he pays for her mother's care. He's reserved but gracious, he helps her grow, and every time someone doubts her or does her wrong he steps in. What's between them soon goes well past a deal. But Chu Nanhe's quiet protection seems to hide a very big secret.",
    'all-about-secretary-li':
        "She's playing the sweet secretary. He saw through her from the start.\nLi Weixi is a brilliant, highly educated operator, and she goes undercover as a harmless secretary to get close to Jia He, the CEO of the Jia Group. She believes he turned his back on his own sister, and she wants to prove it and bring him crashing down. Jia He saw through her act long ago and keeps her near anyway. He lets her scheme, sits back and enjoys the show, and even covers for her lies. Just when she's close to winning, one problem after another lands on her, and the enemy she came to ruin keeps stepping in to protect her. Her need for revenge starts to crack, then a misunderstanding leaves her heartbroken and she vanishes. Jia He falls apart without her, walks away from his fortune and chases her all the way to the countryside. By the time the old secrets come out, he's ready to give up his powerful family for her.",
    'bright-moon-of-spring-night':
        "He caught her boyfriend cheating. So he offered to play the new one.\nLaw student Wen Yue is at the Zhongtai Law Firm's anniversary party when she ends up helping Jiang Hansheng through a sudden episode. He's a lawyer who has been haunted ever since he watched his mother die when he was a boy. Not long after, he finds out that Liang Xiao, the man Wen Yue is dating, is seeing someone else behind her back, and he's set on dragging the affair into the open. So he offers to pose as her new boyfriend. The closer they get, the more Wen Yue learns about the secrets in his family's past, and the more they start to heal each other.",
    'start-from-scratch':
        "She's trying to seduce her fiance's uncle. He's the one running the game.\nWen Shiyi was once a well off heiress, and now she's stuck being engaged to Fu Yixuan, a playboy she never chose. Her way out is his uncle Fu Shen, the man with the real power in the Fu family, so she sets out to win him over. She thinks it's going perfectly. What she doesn't know is that every lucky run in and every flirty moment was set up by Fu Shen himself. He knew her right away as the woman he's been looking for all these years. He isn't trying to trap her. He wants to show her what it means to love someone and be loved back, and to be the one she can always lean on.",
    'accidentally-wooing-you':
        "She meant to send her resignation. She sent him her novel instead.\nTian Yiyi has been using Gu Xuan as the model for the hero of the novel she's writing. Then she attaches the wrong file, and instead of her resignation letter he gets her draft. Gu decides she's coming on to him and puts her on probation so he can keep her close and work out what she's really after. The harder she tries to explain, the more he thinks she's playing hard to get. Under all the misunderstandings something real grows. He stays up late cooking porridge when she's sick, and an offhand comment from her fixes a work problem he's been stuck on. She can't tell anymore whether she's falling for the domineering CEO she made up or the actual man. Seeing her admire Zhao Chengchen makes Gu jealous enough to lose his cool, so he proposes by the sea with fireworks and a ring, and she says yes on the spot. And when she quits to chase her dream of writing, he's right behind her.",
    'a-dash-of-sweetness':
        "They met while running for their lives and saved each other.\nShi Yin is a wealthy heiress who looks soft but has a spine of steel. Han Zhan is a rich young master who is ice cold to everyone but her, and with her he can't get close enough. They cross paths by pure chance in the middle of an assassination attempt, and each ends up rescuing the other. After that they live side by side, Shi Yin spoils him, and feelings start to grow. With power struggles swirling all around them, they'll have to keep each other safe.",
    'no-one-but-you':
        "One drunken mistake, and now she's marrying a CEO under another woman's name.\nSong Yanzhi catches her boyfriend cheating with a rich woman, drinks to forget, and ends up in bed with the wrong man. He's Jiang Yancheng, a CEO who never cracks a smile. His arranged match was supposed to be Shen Zhiyi, but she's just gone to prison for drunk driving and the wedding can't happen. The Jiang family still needs its partnership with the Shen family to go through, so Jiang Yancheng asks Song Yanzhi to stand in as Shen Zhiyi and marry him. She becomes his substitute bride, and the love comes after the wedding.",
    'midsummer-s-vendela':
        "She wrote him off as a boring older man. He learned to cook for her.\nBai Qingmei is a freelance photographer pushed into getting engaged to Zhou Sheng'an, who runs Hengtai Group. She wants no part of it, sets her own rules and decides he's dull and middle aged. He just keeps quietly showing up. He carries her shoes, makes her brown sugar water and teaches himself to cook. But her mother's painful past has left Bai Qingmei scared of open relationships, so she reads his patience as not caring and coldly ends it. It takes Zhang Jiuwan's shallow flirting to show her who she really wants, and Zhou Sheng'an comes down hard on anyone who threatens her. He goes after her as far as Jingbei with a proposal, and she still can't decide. It's only when she sees everything he's done without a word, keeping her clothes, reading up on photography, turning down work to stay near her, that she finally lets herself love him back.",
    'ceo-s-arrange-bride':
        'One blind date, then a flash marriage.\nShi Sheng is a designer and Yu Wenzhou is a businessman, and after a single blind date they rush into a flash marriage. It starts out as an arrangement that suits them both and nothing more. Between their jobs and their home life they slowly learn how the other one works, and somewhere along the way the convenience turns into real love. Can two people who married for practical reasons build a future together?',
    'a-tragedy-in-your-name':
        "She's the only one who can save his life. It could cost her hers.\nFu Hanchuan is a CEO who keeps away from women, and his body is so full of Yang energy that he won't live to see New Year's Eve. Then he finds out that Shi Yue, a broke college student, is the one person alive with a pure Yin body that can heal him. So he marries her to stay alive. But healing him puts her own life at risk, and once he knows that, he slowly falls in love with her. Now he has to choose between his life and hers.",
    'phoenix-lord':
        "Reborn, and ready to fight for each other.\nNing Buyu is the war god who guards the Empire's northern frontier. To everyone else he's hard and unbending, but underneath he's tender and completely devoted. Yun Lian is the empress of Dayuan, brave, determined and full of fire, and she brings all of that to their love. After they're reborn, trouble and misunderstandings come at them from every side. Whatever the world throws at them, they refuse to let go of each other.",
    'the-love-you-gave-me':
        "A misunderstanding brought them together. Another one broke them up.\nMin Hui is a software engineer and Xin Qi is a CEO. They fell in love because of one misunderstanding and split up because of another. Years later work throws them back together, and they both find they've ended up right where it all started. Now they're rivals on the job and tangled up in everything else, and neither one can quite let go.",
    'clocking-in-for-love':
        "At work they can't stand each other. Online they're in love.\nZhou Cancan is a sharp, self assured manager whose main goal in life is making money. Li Jinshu seems cool and distant, but he's softhearted underneath, and nobody knows he's secretly a rich heir. At the office they're rivals. Online, with no idea who the other really is, they're sweethearts. As they go about ordinary life in Chengdu, all the squabbling slowly turns into love. What happens when they work out who's on the other side of the screen?",
    'inescapable-scorching-love':
        "She faked cheating to end it. Six years later he makes her pay for it.\nWhen her father was sent to prison, Su Qian ended things with Shao Hanli by making him believe she'd cheated. Six years on she's raising a son alone and can barely cover his medical bills. When she runs into Shao Hanli again, he's now the heir to a rich family. He's sure she's only after his money, and he humiliates her again and again. Then a DNA test tells him the truth, and the regret hits him all at once.",
    'the-best-couple':
        "She spent five years planning her revenge. Then he stumbled in badly hurt.\nIn the neon back streets, Mu Wan runs the Renxin Clinic, an underground doctor everyone knows as cold and only in it for the money. It's a cover. For five years she's been working toward one target, Ma Yuting, the heir to the Dark Empire. When he staggers into her clinic with serious wounds, her dangerous game finally starts. But he figured out her plan a long time ago. Now two predators are circling each other with lies and seduction, and the closer they get the hotter it burns. She could be his destiny, or the death of him.",
    'my-national-husband':
        "Their marriage was fake. Their feelings never were.\nAfter Xu Jiamu's car accident, Qiao Anhao and Lu Jinnian agree to a fake marriage, and both of them keep what they really feel to themselves. Later they end up working on the same film. Through misunderstandings, looking out for each other and old secrets coming to light, it's a long road. But they finally admit how they feel and get married for real.",
    'obsession-after-separation':
        "Three years married and he's never touched her. She thinks she knows why.\nRan Shuang was once Wall Street's top trader, and she married Fu Zhiheng to pay him back for the money he put behind her. Three years later they still haven't been intimate. She's convinced he's still hung up on Lu Mengli, the girl he grew up with. The truth is very different. When he was a boy his nanny abused him, and the trauma left him unable to be close to any woman. After being turned away one time too many, Ran Shuang decides to let him go and walks out. Only then does Fu Zhiheng realize what she means to him, and he sets out to win his wife back.",
    'two-poor-ceos':
        "Two CEOs on a blind date, both hiding who they really are.\nJiang Li goes on a blind date without mentioning she's a CEO, because what she wants is a man who'll do as he's told. Lin Jun runs the Chenglin Group, and he turns up to his blind date playing poor so no gold digger comes near him. They click right away and jump into a flash marriage. What neither of them saw coming is how often their two companies end up doing business together, and every deal brings their secrets one step closer to coming out.",
    'secretly-loving-you':
        "She dumped him without a word. Now he's a CEO and she's waiting on her fiance.\nHe Lingfei was a big spending heiress until her family went bankrupt, and then she cut off her college boyfriend Lu Yichen out of nowhere. What she never knew was that he was the abandoned heir of a rich family himself. After he was thrown out he fought his way back to the top and turned into a cold, hard CEO. Years later they meet again at a banquet. She's a fallen heiress now, running around after her fiance, and he can't decide whether he loves her or hates her. Did she ever once think about the man she left behind?",
    'my-beloved-serpent':
        "She died protecting the prince she trained. He's been paying for it ever since.\nQing'er is a serpent demon with six months to live, and if the curse runs its course she'll never be reborn. To break it she makes the deposed prince Zhao Jin her disciple and treats him with real kindness. She has no idea how dark and cruel he is underneath. He uses her and tests her, falls in love with her and never says so, and in the end she dies protecting him. She comes back as Wei Ji, an empress shut away in the cold palace, with no memory of her old life, and Zhao Jin is now a tyrant eaten up by regret. He's kept himself alive with a blood curse just to find her, and still he misses her. So he poses as Ah Jin, a martial arts master, and wins her over one misunderstanding at a time. Meanwhile Zhao Ke, the old regent, has been reborn as Wei Zhongping and wants revenge through her. When Qing'er's memories return she has to face everything that stands between them, teacher and student, demon and human. Can a love that already cost her one life survive a second?",
}

FACTS = {
    'divorce-my-happily-ever-after':
        'Betrayed by her husband and his mistress while five months pregnant, Rosie Turner is cast out in humiliation despite having sacrificed everything for him. After the divorce, she finds new strength in Andrew Jaffe, a young and charismatic CEO who not only helps her seek revenge but also supports her rise to success. With him by her side, Rosie discovers both triumph in her career and lasting happiness in love.',
    'moving-on-from-you':
        'Jane Rowe has been in love with Sam Bale ever since he took her in at the age of seven. Every year on her birthday, she confesses her feelings, only to be rejected as Sam, believing their ten-year age gap is too large, chooses someone else. One night, they get drunk and spend the night together, but Sam has no recollection of it. When Jane becomes pregnant, Sam accuses her of being indecent. Heartbroken, Jane leaves him to continue his life with his girlfriend.',
    'winning-her-over-a-second-time':
        "Despite living with his girlfriend, Sally Nelson, for the past three years and being fully aware of her expectations for marriage, Quinton Young continually delays their potential marital bliss. Although it's clear to everyone that he loves Sally, he refuses to acknowledge their relationship. Eventually, Sally, frustrated by his reluctance, decides to leave him and turns to someone else for what he won’t give her.",
    'a-contractual-marriage-hell-no':
        'Keira Snow wakes up in shock, realizing that she had forced herself onto Nolan Blair, the CEO of her company, the night before. Overcome with guilt and pressure, she considers quitting her job. But her heartless parents have other plans, pushing her into a marriage arrangement she has no say in. Reluctantly, Keira decides to go along with it.',
    'every-thought-every-love-is-you':
        'Ellis Hill is known for being cold and aloof, so no one ever suspected that his marriage pact involved Claire Newton. Everyone is therefore stunned when he fills in her name as his wife. Claire had assumed their relationship would remain purely nominal, making it all the more surprising when he begins to shower her with love and tender care after their marriage.',
    'answer-to-my-heart':
        "For years, Cecelia Collins lived in silence, forced to pretend she could not speak. During a kidnapping, she mistakenly believes Ivan Justice doesn't want her unborn child. To protect the baby, she poses as the kidnapper, drawing him into a tense game of confrontation. As their misunderstandings unravel, Cecelia, encouraged by him, finds the courage to speak—and to follow her heart.",
    'she-came-from-the-abyss':
        "In order to exact her revenge for her mother and older sister's death, Adel infiltrated the Bay family disguised as the maid Kris Frost. Her target? Jamie Suthern, who married into the Bay family. She gained others' trust, created conflict, seduced Tony Bay, and destroyed his marriage with Jamie. Jamie was smart, yet she was a lunatic. The two fought, and Adel was kicked out of the Bay family thrice, but she would always return.",
    'the-unknown-man-i-call-mine':
        'Claire Lane marries the supposedly unattractive Linus Lyon to save her family’s business. She teams up with him to fend off malicious attacks from her own relatives and gradually gains a foothold in the company. As a mysterious figure casts doubt on Linus’s true identity, their bond deepens while they face crisis after crisis. In the end, Claire uncovers shocking secrets about her own origins and the mystery surrounding Linus.',
    'the-fiery-young-marshal':
        "Song Shuangxu was abandoned by her parents since childhood. It was Shen Yu who took her home and raised her like a princess. She misunderstood her dependence on Shen Yu as love. After being discovered by the Shen family, she was'sent' abroad for many years. After returning, the Shen family was framed by their opponents. To repay the kindness of upbringing, Song Shuangxu became the secret lover of He Tingzhou, the young master of Yancheng. What she didn't know was that He Tingzhou had a crush on her for many years and had long planned it. In the process, He Tingzhou's meticulous care for Song Shuangxu touched her and also made her understand what true love is.",
    'spring-night-s-fiery-kisses':
        "Li Chuchu's younger sister was forced to commit suicide by three rich young men, and her mother was beaten into a vegetative state. Since then, Li Chuchu has dropped out of school and entered the Cloud Peak Club, all to attach herself to Pei Qingji, the person in power in Jinggang, to get her revenge. In this act of using him, she pretended to be weak and planned carefully step by step. And yet, she unexpectedly fell for him when he continued to aggressively dote on her.",
    'victory-in-love':
        'Lin Zhanhong, the queen of the workplace, and Wen Yushi, the "newly appointed director," start as weekend lovers with a deal: cooperation only, no feelings involved. As they stand together against internal power plays at the company, their arrangement slowly turns into real love. When Wen\'s hidden identity as the "company heir" and a formidable love rival come to light, they face a crisis of trust. But through it all, they confirm their true feelings, tear down their defenses, and emerge victorious in love and work.',
    'embrace-you-through-the-ashes':
        'Jiang Wu has always lived in fear of debt collectors due to her father\'s disappearance, until she meets Jiang Yan, a silent man always covered in wounds, who takes her in and protects her. What she does not know is that he is actually an undercover police officer named Lu Xiao, who has infiltrated a border town gang incognito. The two lonely souls grow closer, yet she can never see through the mist in his eyes. At a critical juncture of his mission, he leaves without a word, leaving only some money and a letter telling her to forget him. Four years later, she becomes a reporter for North City TV, while he, retired due to injuries, runs a homestay called "Yearning for Wu." Fate brings them together again—she arrives with an interview list, and he calmly says he is Lu Xiao. Be it Jiang Yan or Lu Xiao, he remains an indelible part of her life. After years of hating him and searching for him, she now realizes that him keeping secrets and pushing her away are just to protect her.',
    'dark-light':
        'Qin Yulin, a driver for Xingyao Group, woke up in the bed of Xu Enxin, the heiress of the prestigious Fenghua Chamber of Commerce, after what seemed like a chance encounter in the bar. Captivated by him, Xu Enxin requested him from Xingyao Group’s CEO, Zhou Xinghan. Thus, Qin Yulin became her driver. He quietly memorized all her preferences, handed her the perfect cup of coffee when she was tired, and shielded her from every sign of danger. Xu Enxin gradually found herself growing increasingly reliant on this "driver." But in truth, Qin Yulin carried a deep, blood-soaked vendetta. 18 years ago, the Zhou family was responsible for the death of his parents and bound him to them with an 80-year contract. Approaching the Xu heiress was supposed to be the most crucial move in his revenge plan. But somewhere along the way, he fell in love with the proud yet pure-hearted young lady. The truth, however, is always cruel. When Xu Enxin discovered Qin Yulin’s true motives, she chose to accept a political engagement with Zhou Xinghan. And when Qin Yulin learned that the woman he loved was to marry another, all he could do was silently protect her from the shadows. Caught in the tug-of-war between deception and sincerity, how could a love that began with calculation possibly continue? At the engagement banquet, Qin Yulin tore off his disguise and exposed the Zhou family’s crimes, while Xu Enxin revealed her own trump card. It turns out the entire “lovers turned enemies” drama had been their silent, mutual plan all along. In the end, the villains were brought to justice, and Qin Yulin finally held her in his arms openly. All those moments of feigned indifference and distant affection melt at last into a single passionate kiss.',
    'the-seventh-year-of-pending-love':
        "Cheng Xia has been in love with Chen Shechuan, whom she grew up with, and their seven years together are filled with romantic tension. After an accidental drunken kiss, Shechuan rejects Xia, claiming they are just good friends, when really, he is emotionally avoidant because of his parents' failed marriage. To make her give up, he introduces his girlfriend Jiang Yining when he visits her house, and even sets her up with a blind date, under the guise of doing her a favor. Heartbroken, she resolves to move on from this vague situationship...",
    'depth-of-love':
        "Secretary Song, who is usually strict in his work, passionately kissed CEO Jiang Tingzhou after learning that he was in the late stage of cancer. Since then, Jiang Tingzhou has become addicted to Song Xi. To end their casual relationship, Song Xi submitted his resignation the next day. 'CEO, I'm not very satisfied with your performance. Let's part amicably.' Later, at the depth of love, Jiang Tingzhou would always ask Song Xi, 'Are you satisfied?'",
    'heart-throb-fortune':
        '22-year-old graduate student Ran Xing is forced to impersonate the psychic "Mr. Moon" and infiltrate the wealthy Ye family to complete a mission of stealing a toothbrush, after her sister is imprisoned. In the process, she must navigate the complex identity of her boyfriend Pu Yubai, the internal family conflicts of the Ye family, and the constant probing of Ye Zhaoning. Through crises and misunderstandings, Ran Xing gradually earns Ye Zhaoning\'s trust and discerns the truth of her own emotions. Eventually, Ran Xing confesses her true identity, cuts ties with Pu Yubai, and chooses to stand on her own to complete her studies and career. Three years later, she becomes a psychological counselor, helping others heal, while reuniting with a matured Ye Zhaoning, breaking through class barriers and past misunderstandings to start a new chapter in their relationship.',
    'the-penthouse-club':
        'Zhong Xian, driven by the tragic death of her sister who depended on her, is drawn into the fierce rivalries of a powerful aristocratic family. Navigating the conflicts between Qin Hao and his son Qin Lang, she uses herself as bait and risks her life as a gamble, stirring up strife between father and son. However, through the intense power struggles, Qin Feng gradually falls into a downward spiral. In the end, Zhong Xian realizes that the grudges and betrayals within the noble family are far more complex than they seem, and she herself is merely a pawn in Qin Hao’s game. Just when she believes her revenge has succeeded, the real storm of bloodshed and chaos is only just beginning.',
    'affectionate-seduction':
        "Lin Yuxi's parents are killed when she is six years old, and she is sent to a welfare home. When she finds out her parents' death is related to the Zhou family, she marries their second son Zhou Yanjing. The two face many misunderstandings and obstacles, such as mistakenly assuming that the other has someone else they love. Once the misunderstandings are resolved, Yanjing starts pursuing Yuxi by setting fireworks with her name, confessing through a fake interview, and installing distance sensors on their watches. Eventually, they find true love in each other.",
    'hunting-love':
        'To avenge her mother’s death, Wan Lin goes undercover for three years, posing as the fiancée of Fu Yan, heir to the underworld empire in Mai City. But on their wedding day, during a raid led by her own agency, Wan Lin shoots Fu Yan. When they meet again, enemies become allies. As Wan Lin begins to see the sincerity in Fu Yan’s heart. Together, they dismantle the criminal forces from within. Vengeance eventually gives way to love, and the two step into a new life, hand in hand.',
    'married-to-my-crush':
        'On a snowy night in North City, Zhong Xiran was abandoned by her first love, Huo Xin, and entered into a marriage with Qi Sinian, who had secretly loved her for eleven years. Four years of a "cold" marriage later, with her ex-husband returning, family pressures mounting, and rumors swirling, she unexpectedly discovers that this marriage was his long-planned act of deep love and protection. When the truth is revealed, she turns and throws herself into his arms: "Let\'s spend the rest of our lives together."',
    'the-flame-of-love':
        "A life-saving marriage turns into a game of survival! To save her comatose younger brother, Shi Ning has no choice but to marry Shen Nanxun, the eldest grandson of the Shen family. However, on the engagement day, she learns of his affair with his secretary and his plan to kill her after marriage. In desperation, she turns to Shen Lingchen, the most intimidating half-son of the Shen family—and also Nanxun's rival—hoping to marry him instead. Despite seeing through her scheme of active seduction and gradual probing, the cold Lingchen repeatedly protects her. How did this battle of wits turn into love? But she cannot afford to love, as her marriage is only meant to save her brother.",
    'a-love-beyond-secrets':
        "Ji Xuan is drugged by accident, and thus encounters Song Zhaoli. It disrupts Ji Xuan's originally peaceful life. Everyone thinks Ji Xuan is to climb the social ladder, but only Song Zhaoli knows this is his long-planned scheme. And then, Ji Xuan gradually uncovers the mystery amid the constant entanglement. The two embark on a relationship of extreme entanglement and mutual redemption.",
    'perfect-secretary-s-love':
        "The witty, humorous, and clear-headed Qiu Yu excels in the workplace as the capable secretary to CEO Ji Xiangdong. Unlike the workaholic Xiangdong who is not close to his family, Yu is optimistic and blessed with loving parents. The only flaw in Yu's life is her tumultuous love life; she yearns for real love and an understanding lover. Dealing with an ex's persistence and family interference, Xiangdong's hidden feelings beneath his cold exterior finally come to light. In the whirlwind of career and love, Yu chooses her own happiness.",
    'a-thousand-times-for-you':
        'The wedding day turns into a nightmare for Chen Zi, the rich heiress, as her fiance betrays her. She goes to a bar to drink away her sorrows and gets into a fight with a thug. He Chuan comes to her rescue like a knight in shining armor. She is instantly smitten. When they cross paths again, she takes the initiative and proposes marriage. But she has no clue that this rugged mechanic has a secret life.',
    'in-her-charming-grasp':
        'Jiang Xian willingly clung to Lin Yuanzhou and became the city’s laughingstock. Everyone thought she would marry no one but him, until they realized she only treated him as a stand-in. She loved no one and even wanted to run away. Lin Yuanzhou, once incapable of love, gradually fell for her for real, and in the end, like a madman, bound her to his side and pleaded for her love.',
    'love-once-again-in-the-80-s':
        "In the previous life, Lu Zhaoyan marries the poor boy Kuang Yue but unexpectedly becomes a rich wife. On the other hand, Zhaoyan’s sister, Lu Qinning, who marries the military officer Ling Yue, goes crazy because of Ling Yue's accidental death shortly after the wedding. As Lu Qinning kills Lu Zhaoyan, Zhaoyan retaliates and kills Qinning too, and they are both reborn. Lu Qinning chooses to snatch Kuang Yue away, not knowing that Lu Zhaoyan, who is also reborn, has prevented Ling Yue's death and is living a better life...",
    'fake-marriage-real-love':
        "To register her daughter's household, Xia Xingyan goes to get a marriage certificate with her boyfriend, only to be provoked by his mistress. Meanwhile, Zhan Yechen, desperate to reject a family-arranged marriage, urgently needs a temporary wife and enters a fake marriage with Xia Xingyan. Xia Xingyan soon discovers that her daughter is not her boyfriend's child, and Zhan Yechen helps her fight back. Later, Xia Xingyan's best friend, Shen Rui, pretends to be Zhan Yechen’s long-lost first love, stirring up misunderstandings. As they navigate the complications, Zhan Yechen gradually falls in love with Xia Xingyan and begins to suspect that her daughter might actually be his own.",
    'when-fish-swim-to-land':
        'Sun Lu, a rule-abiding elementary school teacher, harbors a rebellious desire to break free from constraints. An unexpected home visit leads her into the life of Chen Xudong, a fish store owner. In her eyes, he is a "problematic" man with a child; yet, beneath her obedient facade, he sees the same stubbornness and loneliness as his own. As prejudices dissolve, their hearts quietly draw closer in the tranquil world of the aquarium. However, Sun Lu discovers that this gentle man hides a deeply buried past. Disparities in social status and sealed secrets form a chasm between them. Can their love overcome the barriers of reality and become each other\'s salvation?',
    'note-to-my-true-love':
        "Ji Hanyue, who long abandoned her dream of jewelry design, is trapped in a loveless marriage, enduring the silent treatment from her husband He Jiayuan and harassment from her mother-in-law. On a snowy night seeking medical help, she reunites with Jiang Peizhi, with whom she had a note-passing romance during college. Now the chairman of Jiang Group, Jiang is still in love with Ji. Upon learning of her unhappy marriage, he resolves to rescue her from the misery. He meticulously exposes He's true colors—impersonation, infidelity, and exploiting his wife for personal gain—helping Ji secure a divorce. With Jiang's support, Ji rediscovers her passion for design and stuns the industry with her butterfly-themed jewelry. Ultimately, Ji realizes her true feelings, breaks free from her past, and starts a new chapter in life with Jiang, who has waited for her for seven years.",
    'love-s-trenches':
        "Mia Bale, the daughter of the wealthiest family, works as an intern in her family's company. Unexpectedly, she encounters Ken Leed, the CEO of a collaborating company who is also her former boyfriend, having vanished without explanation three years ago. As Mia tries to reconcile with Ken, she faces obstacles from Lily Cork, who exacerbates misunderstandings between them.",
    'in-the-snare-of-love':
        'To save her sister Nina from heart disease, Cheryl Snow asks Sean Hall for a cure and becomes his lover in the process. Worried that Cheryl will eventually win Sean’s heart, Sienna Zane conspires with Heath Clark to frame Cheryl, resulting in Nina’s death in the operating room. Devastated, Cheryl demands a breakup. It is then that Sean realizes he is already in love with her. Sean later investigates the circumstances surrounding Nina’s death.',
    'the-choices-of-fate':
        'After their mother’s death, Kate and Amelia Morse face a cruel choice—only one can leave with their grieving grandmother. Believing wealth awaits, Amelia departs, only to find an ordinary life. Years later, envy consumes her when Kate marries into the wealthy Warren family. In a fit of rage, she kills her sister before taking her own life.',
    'trapped-in-the-allure':
        'Tanya Abell sells her virginity at a high price to Taylor Wayne in order to raise money for her sister’s medical treatment. One year later, she bumps into him at a gathering. Taylor recognizes her and traps her against the wall. She escapes and rushes back into the private room, only to be dragged back to Taylor by Jason, who tells her that the only person who has the cure to save her sister is Taylor.',
    'his-dangerous-obsession':
        "Austin Gorman, the illegitimate son of a powerful family, returns from overseas service—only to find himself hunted by the directors of his family's company in a ruthless power struggle. While on the run, he crosses paths with Diane Hoover, who saves him, and that fateful night becomes the beginning of their destined love.",
    'survive-and-thrive-the-mute-consort':
        'In her tumultuous childhood, Everly Swan and her mother endured relentless bullying and oppression at the hands of the matriarch, who even resorted to poisoning Everly, leaving her mute. Yet, in her darkest hour, a simple shared piece of candy sparks an unbreakable bond of friendship between two innocent children.Years later, driven by a fierce desire to protect her mother, Everly seeks high status, only to have her dignity trampled underfoot by her cruel half-sister.',
    'of-his-day-and-night':
        "Andrologist Tessa Tilden marries Jordan Slate to save her mother—only to be ensnared in a web of family intrigue. On their wedding night, she encounters Simon Slate, discovering later that he is Jordan's alternate persona, born from a childhood trauma seventeen years ago. As Tessa unravels the kidnapping plot behind it all, she and Jordan join forces to expose his uncle Marcel Slate and restore both love and peace to the Slate family.",
    'sometimes-calm-is-deadly':
        "After his girlfriend Aurora Golde's tragic death, Noah Stark loses his sanity. He feigns recovery upon release from the hospital, carefully setting a web of revenge and turning Jerry Fox and Jade White against each other. When the truth comes to light, he faces justice—the cost he willingly pays for the love of his life.",
    'starlight-redemption':
        'Lin Qingzhu, a gifted architecture student, is pushed to the brink when her mother is critically ill. Faced with humiliation from Chu Guanxing, who uses medical expenses as leverage, Lin Qingzhu accepts an unexpected bargain proposed by his uncle, Chu Nanhe. Confined to a wheelchair, Chu Nanhe only asks her to share dinner with him every day in exchange for her mother’s treatment. Being the young power holder of the Chu family, Chu Nanhe is distant yet refined. He covers her mother’s medical costs, guides Lin Qingzhu’s growth, offers her meticulous protection, and steps forward whenever she is questioned or wronged. The tacit understanding and care between them soon surpasses anything ordinary. Yet behind Chu Nanhe’s gentle guardianship, there seems to lie an enormous secret.',
    'all-about-secretary-li':
        'Li Weixi, an elite “hunter” among the highly educated, disguises herself as a harmless, innocent secretary and infiltrates the side of Jia He, the president of the Jia Group. Her goal is to expose the truth that he abandoned his own sister and drag him down from his pedestal. But Jia He, a calculating CEO, has long seen through her disguise and decides to keep her close. He indulges her little schemes, watches her act, and even helps cover up her lies. The two circle each other in constant testing and tension. Just as Li Weixi is about to succeed, trouble comes one after another, throwing her into chaos. Most unexpected of all, her supposed enemy Jia He repeatedly steps in to protect her. As her desire for revenge begins to waver, a misunderstanding breaks her heart and drives her away.Li Weixi’s complete disappearance sends Jia He into a downward spiral. Abandoning his wealth, he sets off on a warm yet comedic pursuit to win her back in the countryside. In the end, the secrets of the past are revealed, and all grudges fade away. He gives up his powerful family for love, while she transforms from an avenger into a lover. In a game that began with lies, the two ultimately achieve mutual redemption.',
    'bright-moon-of-spring-night':
        'At the anniversary celebration of Zhongtai Law Firm, law student Wen Yue accidentally ends up helping Jiang Hansheng, a lawyer experiencing a sudden episode due to trauma. Since witnessing his mother’s death as a child, Jiang Hansheng has been deeply tormented. Later, he catches Wen Yue’s boyfriend, Liang Xiao, cheating on her, stirring up ripples in his already unsettled heart. Determined to expose the truth of the affair, Jiang Hansheng offers to help Wen Yue while pretending to be her new boyfriend, thus beginning their unexpected bond. As their connection deepens, Wen Yue gradually uncovers the secrets behind Jiang Hansheng’s family background. Together, they begin to heal, finding redemption and comfort in each other’s arms.',
    'start-from-scratch':
        "Wen Shiyi, the once-prosperous young heiress, has no choice but to be the fiancée of playboy Fu Yixuan. Desperate to break free, she sets her sights on Yixuan's uncle, Fu Shen, the one who truly holds sway in the Fu family. She thinks her seduction plot is going smoothly, when in fact every seemingly coincidental encounter and flirtation is orchestrated by Shen, as he recognized her as the beloved he has been searching for all these years. He weaves a web of love not to ensnare her but to teach her the meaning of loving and being loved, making himself her strongest support.",
    'accidentally-wooing-you':
        "Tian Yiyi's infatuation with Gu Xuan stems from a creative fascination. She views him as the blueprint for the male lead in her novel on a superficial level. An email—accidentally sent with her novel draft attached instead of her resignation letter—leads Gu to believe she is making a move on him. To discern her true intentions, he keeps her by his side under the guise of a probation period. She desperately tries to clear things up, which he misinterprets as playing hard to get. Yet, beneath the misunderstandings, a genuine connection blossoms. When she falls ill, he simmers porridge late into the night; when he is exhausted, a casual remark from her resolves his work dilemmas. Lines blur as her heart races when she is right next to him in the elevator and she cannot stop staring as he cooks for her—is she falling for the domineering CEO persona she has written or for the man who furrows his brows over the precise heat needed for the porridge? He, too, is falling for her—her candor at investment meetings, the fatigue evident as she rubs her neck during late-night work sessions, and the sparkle in her eyes when she writes—every facet of her lowers his emotional guard. When he loses his composure out of jealousy over the way she looks at Zhao Chengchen and proposes by the seaside with fireworks and a ring, she accepts without hesitation. She professes her love for him, clarifying that she merely admires Zhao professionally. When she decides to quit her job and pursue her dream of writing, he supports her without reservation. Ultimately, this relationship born of a mistake has led her to a true love rooted in mutual fulfillment.",
    'a-dash-of-sweetness':
        'The story follows Shi Yin, a wealthy heiress who appears gentle but is in fact resolute, and Han Zhan, a wealthy young master who is cold to outsiders but clingy and affectionate toward her. They meet by chance while fleeing an assassination attempt and save each other. Living side by side afterward, Shi Yin dotes on Han Zhan as feelings blossom between them. Together, they protect one another and grow hand in hand amid the whirlpool of power and love.',
    'no-one-but-you':
        "Song Yanzhi accidentally discovers her boyfriend cheating with a wealthy woman and gets drunk in sorrow, mistakenly sleeping with the cold-faced CEO Jiang Yancheng. Jiang Yancheng's arranged marriage partner, Shen Zhiyi, is imprisoned for drunk driving, making the marriage impossible. To secure the cooperation between the Jiang and Shen families, Jiang Yancheng proposes that Song Yanzhi pretend to be Shen Zhiyi to complete the marriage. Thus begins a story of love after wedding between the substitute bride and the CEO.",
    'midsummer-s-vendela':
        'Independent photographer Bai Qingmei is forced into an engagement with Zhou Sheng’an, the president of Hengtai Group. Resisting the chains of marriage, she lays down her ground rules and dismisses him as a dull, middle-aged man. Yet Zhou Sheng’an, with quiet patience, carries her shoes, prepares brown sugar water, and learns to cook, gradually melting the walls around her heart. Haunted by her mother’s tragic past and her own fear of “open relationships,” Bai Qingmei mistakes Zhou Sheng’an’s tolerance for indifference and ruthlessly calls off the engagement. After their separation, the frivolous advances of Zhang Jiuwan make her realize where her true feelings lie, while Zhou Sheng’an strikes back with thunderous resolve to protect her. He chases her all the way to Jingbei to propose, but she still struggles with hesitation. Through cycles of avoidance, unexpected reunions, and passion breaking through restraint, she finally recognizes Zhou Sheng’an’s unwavering devotion, his quiet love shown in keeping her clothes, studying photography books, and turning down work just to stay by her side. With the warmth of the Zhou family, Bai Qingmei steps out of the shadows, embracing a love that shatters cold rules with its depth and fidelity. In the height of summer, like the blooming of the vendela roses, their love finally blossoms for each other.',
    'ceo-s-arrange-bride':
        'The story tells the emotional journey of designer Shi Sheng and entrepreneur Yu Wenzhou, who got married in a flash through a blind date. Their relationship developed from a union of interests to one of mutual understanding and love. With a dual-line narrative, the story intertwines workplace interactions and family life, showing the growth trajectory of the two, from tentative adaptation to planning for the future.',
    'a-tragedy-in-your-name':
        'The abstinent CEO Fu Hanchuan, doomed to die before New Year’s Eve due to his fully Yang constitution, unexpectedly discovers that impoverished college student Shi Yue is the only one in the world with a fully Yin body capable of healing him. To survive, Fu Hanchuan marries Shi Yue. But learning that her healing him puts her life at risk, he gradually falls in love and faces a torturous choice between life and death.',
    'phoenix-lord':
        'The story follows the tumultuous yet heartfelt romance between Yun Lian and Ning Buyu. Ning Buyu, the war god of the Empire’s northern frontier, appears stern and unyielding but hides a heart full of tenderness and devotion. Yun Lian, the empress of Dayuan, brings courage, determination, and passion into their love, making it all the more vibrant. After being reborn, the two face challenges and misunderstandings from the outside world, yet they remain steadfast in their love and overcome every obstacle together.',
    'the-love-you-gave-me':
        "Software engineer Min Hui and CEO Xin Qi fell in love due to a misunderstanding, only to part ways because of another. Years later, they meet again in the workplace and realize they've both returned to where their love began. From then on, their professional rivalry and personal entanglements weave a bittersweet emotional tug-of-war.",
    'clocking-in-for-love':
        'Zhou Cancan, a clearheaded and confident manager focused on making money, and Li Jinshu, a secretly wealthy heir who is aloof on the outside but innocent at heart, find themselves in a double identity mix-up as workplace rivals and online lovers. As they spend time together amid the everyday bustle of Chengdu, their bickering and push and pull gradually turn into mutual love.',
    'inescapable-scorching-love':
        'Because her father was imprisoned, Su Qian pretended to cheat and broke up with her lover, Shao Hanli. Six years later, she’s a single mother struggling with the high cost of her son’s medical treatment. When they reunite, Shao Hanli is now the heir of a wealthy family. Mistaking her for a gold-digger, he repeatedly humiliates her until a DNA test reveals the truth, leaving him overwhelmed with regret.',
    'the-best-couple':
        'In the neon-lit alleys, the Renxin Clinic is known for its cold-hearted and money-driven underground doctor, Mu Wan. But behind the façade lies a five-year plan, which her true target is the Dark Empire’s heir, Ma Yuting. When he stumbles in, seriously wounded, her deadly game begins. Yet he has long seen through her revenge plot. Between manipulation and temptation, two powerful predators engage in a fierce game of strategy and seduction. Passion ignites in their deadly confrontation. Not only is she his fate, but also the inescapable doom he cannot avoid…',
    'my-national-husband':
        "Qiao Anhao and Lu Jinnian faked their marriage due to Xu Jiamu's car accident, concealing their feelings. Later, they joined the crew of a film together. After navigating misunderstandings, protection, and past revelations, they finally overcame obstacles, confirmed their feelings, and got married, achieving a happy ending.",
    'obsession-after-separation':
        "Ran Shuang, who is once the best trader on Wall Street, agrees to marry Fu Zhiheng to repay Zhiheng's financial support. After three years of marriage, the two still share no intimacy. Shuang thinks Zhiheng is pining for his childhood sweetheart Lu Mengli, when the truth is that Zhiheng is unable to have intimate contact with women because of his trauma from being abused by his nanny as a child. After repeated rejection, Shuang decides to let go and leave. Zhiheng now gradually realizes his feelings for Shuang and resolutely pursues his wife.",
    'two-poor-ceos':
        'Jiang Li conceals her CEO identity on a blind date, hoping to find an obedient man. Likewise, Lin Jun, the current person in charge of Chenglin Group, pretends to be poor on a blind date to avoid gold diggers. The two instantly hit it off and get married in a flash. However, they are not prepared for the many cooperations between their respective groups, and they constantly come close to being exposed...',
    'secretly-loving-you':
        "Heiress He Lingfei, who once lived extravagantly, abruptly severed ties with her college boyfriend after her family went bankrupt. Unbeknownst to her, Lu Yichen was actually an abandoned heir of a wealthy family. After being cast out, he clawed his way back and transformed into a cold-hearted CEO. Years later, they reunite at a banquet where He Lingfei, now a fallen heiress, is busy serving her fiancé. Lu Yichen's eyes blaze with love and resentment: When you left me without a word back then, did you ever think about the man you discarded?",
    'my-beloved-serpent':
        "To break the curse of dying within six months and not being reincarnated, the serpent demon Qing'er takes the deposed prince Zhao Jin as her disciple, treating him with genuine kindness. Unbeknownst to her, Zhao is inscrutable, sinister, and cruel. As he uses and tests her, he falls in love but dares not confess, leading to Qing'er's tragic death to protect him. Qing'er is reborn as the cold palace empress Wei Ji without her past memories, and reunites with Zhao, now a tyrant. Filled with regret, Zhao uses a blood curse to prolong his life to find her, only to miss her again. He disguises himself as a martial arts master Ah Jin to get close, earnestly winning her heart amid misunderstandings. Meanwhile, Zhao Ke, the regent reborn as Wei Zhongping, schemes in the shadows, seeking revenge through Qing'er. When Qing'er regains her memories, she confronts the restrains of their master-disciple and human-demon differences, seeing Zhao's sincerity through life-and-death trials. Overcoming countless obstacles, they unite, weaving a tale of undying love across two lifetimes.",
}

SOURCES = {
    'divorce-my-happily-ever-after': ('platform', 'https://www.dramaboxdb.com/movie/41000121188/divorce-my-happily-ever-after'),
    'moving-on-from-you': ('platform', 'https://www.dramaboxdb.com/movie/41000111514/moving-on-from-you'),
    'winning-her-over-a-second-time': ('platform', 'https://www.dramaboxdb.com/movie/41000105524/winning-her-over-a-second-time'),
    'a-contractual-marriage-hell-no': ('platform', 'https://www.dramaboxdb.com/movie/41000110197/a-contractual-marriage-hell-no'),
    'every-thought-every-love-is-you': ('platform', 'https://www.dramaboxdb.com/movie/42000000611/every-thought-every-love-is-you'),
    'answer-to-my-heart': ('platform', 'https://www.dramaboxdb.com/movie/41000122286/answer-to-my-heart'),
    'she-came-from-the-abyss': ('platform', 'https://www.dramaboxdb.com/movie/41000110205/she-came-from-the-abyss'),
    'the-unknown-man-i-call-mine': ('platform', 'https://www.dramaboxdb.com/movie/42000009660/the-unknown-man-i-call-mine'),
    'the-fiery-young-marshal': ('platform', 'https://www.iq.com/album/the-fiery-young-marshal-2025-xko713tb91?lang=en_us'),
    'spring-night-s-fiery-kisses': ('platform', 'https://www.iq.com/album/spring-night-s-fiery-kisses-2025-13daa88wyrd?lang=en_us'),
    'victory-in-love': ('platform', 'https://wetv.vip/en/album/yvsowl0lrz2xbqu'),
    'embrace-you-through-the-ashes': ('platform', 'https://www.iq.com/album/embrace-you-through-the-ashes-2025-24gl6jty62d?lang=en_us'),
    'dark-light': ('platform', 'https://www.iq.com/album/x-z3xyt35nv5?lang=en_us'),
    'the-seventh-year-of-pending-love': ('platform', 'https://www.iq.com/album/the-seventh-year-of-pending-love-2026-kb0i0uw939?lang=en_us'),
    'depth-of-love': ('platform', 'https://www.iq.com/album/depth-of-love-2025-1n72yysuhtl?lang=en_us'),
    'heart-throb-fortune': ('platform', 'https://www.iq.com/album/heart-throb-fortune-2025-24yxdo411cx?lang=en_us'),
    'the-penthouse-club': ('platform', 'https://www.iq.com/album/x-lhnltpf0gh?lang=en_us'),
    'affectionate-seduction': ('platform', 'https://www.iq.com/album/affectionate-seduction-2025-tadp5my3nh?lang=en_us'),
    'hunting-love': ('platform', 'https://wetv.vip/en/album/gjy6zzlb8jp2ddu'),
    'married-to-my-crush': ('platform', 'https://www.iq.com/album/x-h5pyllmjb9?lang=en_us'),
    'the-flame-of-love': ('platform', 'https://www.iq.com/album/x-1n8vdeessyp?lang=en_us'),
    'a-love-beyond-secrets': ('platform', 'https://wetv.vip/en/album/6fjk0kwhe912n4r'),
    'perfect-secretary-s-love': ('platform', 'https://www.iq.com/album/x-1izxbuk2001?lang=en_us'),
    'a-thousand-times-for-you': ('platform', 'https://wetv.vip/en/album/f8pgl3c7dcit3c3'),
    'in-her-charming-grasp': ('platform', 'https://www.iq.com/album/x-15z2rtltywl?lang=en_us'),
    'love-once-again-in-the-80-s': ('platform', 'https://www.iq.com/album/x-1j5itwaqif1?lang=en_us'),
    'fake-marriage-real-love': ('platform', 'https://www.iq.com/album/x-2bt98z213hh?lang=en_us'),
    'when-fish-swim-to-land': ('platform', 'https://www.iq.com/album/x-xeyajwdynd?lang=en_us'),
    'note-to-my-true-love': ('platform', 'https://www.iq.com/album/note-to-my-true-love-2026-c0wcgqtuph?lang=en_us'),
    'love-s-trenches': ('platform', 'https://www.dramaboxdb.com/movie/41000103453/love-s-trenches'),
    'in-the-snare-of-love': ('platform', 'https://www.dramaboxdb.com/movie/41000107789/in-the-snare-of-love'),
    'the-choices-of-fate': ('platform', 'https://www.dramaboxdb.com/movie/41000112841/the-choices-of-fate'),
    'trapped-in-the-allure': ('platform', 'https://www.dramaboxdb.com/movie/41000108407/trapped-in-the-allure'),
    'his-dangerous-obsession': ('platform', 'https://www.dramaboxdb.com/movie/41000122333/his-dangerous-obsession'),
    'survive-and-thrive-the-mute-consort': ('platform', 'https://www.dramaboxdb.com/movie/41000107076/survive-and-thrive-the-mute-consort'),
    'of-his-day-and-night': ('platform', 'https://www.dramaboxdb.com/movie/41000123323/of-his-day-and-night'),
    'sometimes-calm-is-deadly': ('platform', 'https://www.dramaboxdb.com/movie/42000000021/sometimes-calm-is-deadly'),
    'starlight-redemption': ('platform', 'https://www.iq.com/album/x-18ken2epzq9?lang=en_us'),
    'all-about-secretary-li': ('platform', 'https://www.iq.com/album/all-about-secretary-li-2026-24cqs5dyntx?lang=en_us'),
    'bright-moon-of-spring-night': ('platform', 'https://www.iq.com/album/x-dao29595t5?lang=en_us'),
    'start-from-scratch': ('platform', 'https://www.iq.com/album/x-1kq1kuutbwd?lang=en_us'),
    'accidentally-wooing-you': ('platform', 'https://www.iq.com/album/accidentally-wooing-you-2026-r594r3mqdt?lang=en_us'),
    'a-dash-of-sweetness': ('platform', 'https://www.iq.com/album/a-dash-of-sweetness-2025-14gblem7669?lang=en_us'),
    'no-one-but-you': ('platform', 'https://www.iq.com/album/x-gkh0sce2yl?lang=en_us'),
    'midsummer-s-vendela': ('platform', 'https://www.iq.com/album/x-e9d27gkpqt?lang=en_us'),
    'ceo-s-arrange-bride': ('platform', 'https://www.iq.com/album/x-o6nwdlw5vp?lang=en_us'),
    'a-tragedy-in-your-name': ('platform', 'https://www.iq.com/album/x-zhmigtjd2t?lang=en_us'),
    'phoenix-lord': ('platform', 'https://www.iq.com/album/x-pxwusila0l?lang=en_us'),
    'the-love-you-gave-me': ('platform', 'https://www.iq.com/album/x-x1c5ifh681?lang=en_us'),
    'clocking-in-for-love': ('platform', 'https://wetv.vip/en/album/avke5ieglak0ms7'),
    'inescapable-scorching-love': ('platform', 'https://www.iq.com/album/x-28xqcrcog61?lang=en_us'),
    'the-best-couple': ('platform', 'https://wetv.vip/en/album/c4u50m10ehwlshy'),
    'my-national-husband': ('platform', 'https://www.iq.com/album/x-ngzd8sponl?lang=en_us'),
    'obsession-after-separation': ('platform', 'https://www.iq.com/album/x-n5rc93hj0x?lang=en_us'),
    'two-poor-ceos': ('platform', 'https://www.iq.com/album/x-pw6j793uup?lang=en_us'),
    'secretly-loving-you': ('platform', 'https://wetv.vip/en/album/mgem2srgv1w24t9'),
    'my-beloved-serpent': ('platform', 'https://www.iq.com/album/x-ddszjxrmsx?lang=en_us'),
}
