# -*- coding: utf-8 -*-
"""Batch generated by caption_pipeline.py next.

Fill CAPTIONS. Each value is HOOK newline BODY newline ASIDE.
  HOOK  one sentence, leads as the subheading
  BODY  the synopsis, in our words, ONLY facts from the source below
  ASIDE us talking to the reader, must stand alone with the rest covered

FETCH REQUIRED means there is no fact source on disk. Read the platform page
first, paste what it says into FACTS below, then write. Never write from the
title alone.
"""

CAPTIONS = {

    # 135.1M   Reborn to Love Mr. Right
    # FACTS: Arianna dies a tragic death on the day of her graduation, while Derek, the driver's son,
    # FACTS:  takes all the spotlight on stage.
    'reborn-to-love-mr-right':
        "",

    # 132.3M   Love at Dangerous Speeds
    # FACTS: When Violet flees her abusive fiancé on their wedding day, she hides with Marcus, a noto
    # FACTS: rious street racer.
    'love-at-dangerous-speeds':
        "",

    # 132.1M   Mr Hills' Adorable Wife
    # FACTS: Overlooked by her family for a birthmark, Valerie finds unexpected love with billionaire
    # FACTS:  Andrew Hills.
    'mr-hills-adorable-wife':
        "",

    # 130.8M   We Will Love Again
    # FACTS: Noah Preston returns as a billionaire after six years of being away, and his fiance brea
    # FACTS: king up with him because he was poor in We Will Love Again Movie.
    'we-will-love-again':
        "",

    # 130.6M   The Billionaire's Baby Bargain
    # FACTS: To save her dying sister, Amelia agrees to billionaire Nathan's contract marriage of no 
    # FACTS: sex, no love, and a baby by insemination; unexpected feelings complicate the deal.
    'the-billionaire-s-baby-bargain':
        "",

    # 129.9M   Claimed by the Alpha I Hate
    # FACTS: Daisy Storm cannot shift and is hated by her pack; her Alpha mate cheats and breaks thei
    # FACTS: r bond on her eighteenth birthday. After her mother dies she is ordered back by new Alph
    # FACTS: a Nolan Fenrir, the man she blames, and a forbidden second mate bond pulls them together
    # FACTS: .
    'claimed-by-the-alpha-i-hate':
        "",

    # 129.7M   Do Not Disturb: Lady Boss in Disguise!
    # FACTS: To become heiress of her family hotel chain, Violet Trenton goes undercover as a cleanin
    # FACTS: g lady and takes out the troublemakers one by one, while sexy new COO Kasey Johnson may 
    # FACTS: be more than an ally.
    'do-not-disturb-lady-boss-in-disguise':
        "",

    # 127.8M   Claimed by My Ex's Alpha Brother
    # FACTS: Wolfless Ella catches her Beta mate cheating and falls into the arms of his brother, the
    # FACTS:  newly returned Alpha who has loved her since childhood.
    'claimed-by-my-ex-s-alpha-brother':
        "",

    # 125.3M   Dear Husband, Delete My Number!
    # FACTS: Emma got into a car accident and when she tried to reach her husband, Elijah, he ignored
    # FACTS:  her to be with his wanna-be girlfriend, Stella.
    'dear-husband-delete-my-number':
        "",

    # 124.8M   Pregnant by My Ex's Professor Dad
    # FACTS: After catching her boyfriend cheating, Emily has a one-night stand with a stranger who t
    # FACTS: urns out to be her new professor, then discovers she is pregnant.
    'pregnant-by-my-ex-s-professor-dad':
        "",

    # 123.3M   The Reckoning Takes Flight
    # FACTS: Eve takes a flight to Hawaii to attend her big brother's wedding, booking an extra-wide 
    # FACTS: seat because of her broken leg in a cast.
    'the-reckoning-takes-flight':
        "",

    # 122.8M   You Belong With Me
    # FACTS: Eric Taylor Guilmette lead.
    'you-belong-with-me':
        "",

    # 119.1M   My Secret Lover Is His Brother
    # FACTS: To forgive Piper's family debt, she's promised to marry one of the Bellfort brothers.
    'my-secret-lover-is-his-brother':
        "",

    # 118.2M   The CEO's Contract Wife
    # FACTS: Jasper needed a wife urgently, Chloe needed money urgently; their contract marriage beco
    # FACTS: mes the real thing.
    'the-ceo-s-contract-wife':
        "",

    # 116.7M   Kiss Me One Last Time
    # FACTS: In Kiss Me One Last Time full movie, Adeline has cancer.
    'kiss-me-one-last-time':
        "",

    # 115.6M   We Are Never Ever Getting Back Together
    # FACTS: Lisa's contract marriage ends without notice. Then her ex-husband becomes her boss.
    'we-are-never-ever-getting-back-together':
        "",

    # 115.3M   Big Bad Husband, Please Wake Up!
    # FACTS: Ciara marries comatose billionaire Adrian to save her sick family. Then he wakes up.
    'big-bad-husband-please-wake-up':
        "",

    # 115.2M   The Return of the Lost Heiress
    # FACTS: Mute since her father's death, lost heiress Lana is adopted by a loving stranger while h
    # FACTS: er birth family unknowingly mistreats the daughter they keep searching for.
    'the-return-of-the-lost-heiress':
        "",

    # 114.4M   Secret Surrogate to the Mafia King
    # FACTS: Selling her eggs to pay her boyfriend's debt, Vanessa ends up pregnant by clinical error
    # FACTS: ; the father is ruthless Mafia King Marcello Lavigne, who moves her into his mansion and
    # FACTS:  proves his devotion as she decides whether to become queen of his empire.
    'secret-surrogate-to-the-mafia-king':
        "",

    # 111.8M   Escorting the Ruthless Billionaire Doctor
    # FACTS: Desperate to fund her father's surgery, Violet meets Dax, a billionaire doctor determine
    # FACTS: d to pull her back from the edge.
    'escorting-the-ruthless-billionaire-doctor':
        "",

    # 111.0M   Open Your Eyes, My Billionaire Husband
    # FACTS: Desperate for her mother's medical bills, Hailey marries comatose billionaire Samuel Tre
    # FACTS: nt, who soon wakes to find himself engaged to a stranger.
    'open-your-eyes-my-billionaire-husband':
        "",

    # 109.9M   The Hidden Billionaire in First Class
    # FACTS: They all thought Jett Hawkings was a lowly baggage handler and threatened to throw him o
    # FACTS: ff the flight.
    'the-hidden-billionaire-in-first-class':
        "",

    # 109.3M   The Tutor Trap
    # FACTS: School hockey star Brady asks brainy wallflower Harper to be his chemistry tutor.
    'the-tutor-trap':
        "",

    # 109.2M   Resisting Mr. Lloyd: An Age Gap Romance
    # FACTS: Pressured to quit college and marry, Clarisse meets Lloyd Group CEO Austin, who offers m
    # FACTS: oney for a fake marriage to fulfill his grandmother's wish while hiding his true identit
    # FACTS: y.
    'resisting-mr-lloyd-an-age-gap-romance':
        "",

    # 107.6M   The Quarterback Next Door
    # FACTS: Invisible Skylar is paired with her crush and childhood best friend Jamie on a project, 
    # FACTS: then forced to live with him when his house burns down, while his crazy ex plots against
    # FACTS:  them.
    'the-quarterback-next-door':
        "",

    # 107.0M   Once Upon A Breakup
    # FACTS: After being abandoned on her birthday by her college boyfriend, Mia impulsively proposes
    # FACTS:  to Carson, the charming but dangerous leader of the Moretti crime family.
    'once-upon-a-breakup':
        "",

    # 106.8M   Accidental Triplets with the Billionaire
    # FACTS: Needing an heir, Oscar turns to surrogacy but his sperm is accidentally given to Phoebe 
    # FACTS: during a gynecological exam; a contract marriage follows to keep the baby.
    'accidental-triplets-with-the-billionaire':
        "",

    # 106.3M   You Fired A Tech Genius
    # FACTS: Fired by his CEO's son, Silicon Valley genius Erik joins the rival company and bankrupts
    # FACTS:  his old employer.
    'you-fired-a-tech-genius':
        "",

    # 106.2M   Submitting to My Ex's Dad
    # FACTS: After catching her fiancé cheating with her best friend just before their wedding, Flora
    # FACTS:  runs away and has a wild one-night stand with a handsome stranger.
    'submitting-to-my-ex-s-dad':
        "",

    # 106.0M   The Billionaire's Virgin Surrogate
    # FACTS: What happens when a student surrogate proposes to her client that they should conceive t
    # FACTS: he baby the natural way?
    'the-billionaire-s-virgin-surrogate':
        "",

    # 105.1M   Obsessed with His Silent Bride
    # FACTS: Nonverbal Eva endures a marriage of duty to her childhood protector Declan while his mis
    # FACTS: tress schemes to drive her out.
    'obsessed-with-his-silent-bride':
        "",

    # 104.4M   The Billionaire Married a Homeless Girl
    # FACTS: After a one-night stand Adele Moore becomes pregnant; her father kicks her out and with 
    # FACTS: nowhere to go her life takes a billionaire turn.
    'the-billionaire-married-a-homeless-girl':
        "",

    # 104.0M   Swapped My Ex for His Billionaire Uncle
    # FACTS: Divorced and done with love, Nina is relentlessly pursued by Damon, her ex-husband's you
    # FACTS: ngest uncle.
    'swapped-my-ex-for-his-billionaire-uncle':
        "",

    # 102.9M   CEO's Twins Want Mommy Back
    # FACTS: Cassandra's flash marriage with a loving husband and cute stepkids seems too good to be 
    # FACTS: true; her troubled past closes in and the kids seem strangely familiar.
    'ceo-s-twins-want-mommy-back':
        "",

    # 102.9M   Trapped in the Boss's Embrace
    # FACTS: Secretly married to college sweetheart Desmond for ten years, Beatrice discovers his aff
    # FACTS: air with a wealthy socialite and everything changes.
    'trapped-in-the-boss-s-embrace':
        "",

    # 99.8M    The Billionaire's Masquerade
    # FACTS: To claim her late father's inheritance Shelby must marry, so she weds poor stranger Grif
    # FACTS: fin, unaware he is a billionaire who has admired her since a chance meeting three years 
    # FACTS: ago.
    'the-billionaire-s-masquerade':
        "",

    # 99.8M    Never Divorce a Secret Billionaire Heiress
    # FACTS: Joyce served as a walking blood bank for her sister Selena as the price of forcing Trist
    # FACTS: an to marry her; after losing her baby with no support, the secret heiress demands a div
    # FACTS: orce.
    'never-divorce-a-secret-billionaire-heiress':
        "",

    # 98.7M    Runaway Single Mom, Safe in His Arms
    # FACTS: Single mom Maria escapes abuse and fights to protect her daughter through factory strugg
    # FACTS: les, family betrayal and unexpected love when billionaire Levi enters her life.
    'runaway-single-mom-safe-in-his-arms':
        "",

    # 98.0M    Escorting the Heiress
    # FACTS: Serena catches her boyfriend cheating with her half-sister, gets drunk, and lands in the
    # FACTS:  bed of Jesse, a man who has loved her for years and is not the escort she assumed.
    'escorting-the-heiress':
        "",

    # 97.6M    The Billionaire's Accidental Bride
    # FACTS: Stood up and cheated on by her fiance, Claire marries stranger Christian Cross on the sp
    # FACTS: ot while both are stranded.
    'the-billionaire-s-accidental-bride':
        "",

    # 97.2M    Dominated by My Dad's Boss
    # FACTS: Jayne's secret arrangement with a stranger turns risky when he proves to be the man over
    # FACTS: seeing her father's exit from the family company.
    'dominated-by-my-dad-s-boss':
        "",

    # 96.3M    The Senator's Son
    # FACTS: Class president Emma hides that she is a poor girl at a wealthy school; rival Zach Walke
    # FACTS: r hires her as his personal maid. Interactive vertical.
    'the-senator-s-son':
        "",

    # 95.8M    Mic Drop Diva
    # FACTS: High-school sophomore Ivy, a secretly wealthy heiress with an angelic voice, is used as 
    # FACTS: a voice double by fake bestie Vanessa; after catching her boyfriend cheating with Vaness
    # FACTS: a she reclaims her spotlight with quarterback Blake.
    'mic-drop-diva':
        "",

    # 95.5M    Djinn Under Contract
    # FACTS: Eli Baran is a genie in a magic lamp who can grant three wishes.
    'djinn-under-contract':
        "",

    # 95.1M    True Luna
    # FACTS: Grace Swanson credit.
    'true-luna':
        "",
}

FACTS = {
    # Fetched from each title's own ReelShort page, 16 Aug 2026. EVERY ONE of these
    # held a truncated fragment on disk - 27 to 197 characters - against a full
    # published synopsis. Episode counts recorded for the parked later pass.
    'reborn-to-love-mr-right':
        "Arianna dies a tragic death on the day of her graduation, while Derek, the "
        "driver's son, takes all the spotlight on stage. She gave him everything, her "
        "car, her credit card, even her father's company, only to be used and "
        "discarded. While he spoiled Ivy like a princess, he treated Arianna like a "
        "servant. Only in death does she realize that Hayden, the billionaire's heir, "
        "had been waiting for her all along. Now, fate gives her a second chance to "
        "make things right. 91 episodes.",
    'love-at-dangerous-speeds':
        "When Violet flees her abusive fiance on their wedding day, she hides with "
        "Marcus, a notorious street racer. Their protection for a kiss deal ignites "
        "into passion, giving her the freedom she craves. Then Marcus confesses a "
        "dark secret: the hit and run accident that haunts him killed Violet's "
        "father. 71 episodes.",
    'mr-hills-adorable-wife':
        "Valerie Patterson almost lost out a luxurious life with a billionaire lover "
        "after the Patterson family nearly succeeded in exchanging her with her "
        "sister, Daphne. Born with a birthmark which her mother considered ugly, "
        "Valerie was ignored by her family until Andrew Hills fell in love with her. "
        "85 episodes.",
    'we-will-love-again':
        "Noah Preston returns as a billionaire after six years of being away, and his "
        "fiancee breaking up with him because he was poor. His fiancee did not "
        "genuinely want to end their relationship, his mother forced her to do so. "
        "Noah initially seeks revenge but ultimately discovers the truth behind the "
        "breakup. 53 episodes.",
    'the-billionaire-s-baby-bargain':
        "To save her dying sister, Abby, Amelia agrees to a contract marriage that "
        "will involve no sex, no love, and a baby by insemination. The arrangement "
        "was instigated by Nathan, a billionaire struggling to regain his position as "
        "CEO by fulfilling his father's wish. As they navigate their false marriage, "
        "unexpected feelings develop. 76 episodes.",
    'claimed-by-the-alpha-i-hate':
        "All her life, Daisy Storm never knew what was wrong with her. Why couldn't "
        "she shift? Why didn't she have a wolf? Despite being rejected by her pack "
        "and her original mate on her eighteenth birthday, Daisy finds herself drawn "
        "to Nolan Fenrir, the Alpha she blames for her mother's mysterious death. An "
        "unnatural pull develops between them despite their conflicted history. "
        "73 episodes.",
    'do-not-disturb-lady-boss-in-disguise':
        "To become the heiress of her family hotel chain, Violet Trenton goes "
        "undercover as a cleaning lady and takes out the troublemakers one by one. "
        "Kasey Johnson is the COO. 81 episodes.",
    'claimed-by-my-ex-s-alpha-brother':
        "Ella is wolfless amongst the wolves, but at least she has her mate, Beta "
        "Noah Gravens, until she catches him cheating with her rival Ava. Shattered, "
        "Ella falls straight into the arms of Noah's brother, Liam Gravens, the newly "
        "returned Alpha of the Crescent Pack, who has loved her since childhood and "
        "knows she's his fated mate. But with jealous rivals, bitter exes, and two "
        "worlds pulling them apart, can Ella and Liam embrace the love they are "
        "destined for? 64 episodes.",
    'dear-husband-delete-my-number':
        "Emma got into a car accident and when she tried to reach her husband, "
        "Elijah, he ignored her to be with his wanna-be girlfriend, Stella. Emma "
        "decides to divorce Elijah after discovering Stella might be pregnant with "
        "his child. Emma refused any financial settlement, which confused Elijah who "
        "had assumed she was motivated by money. 88 episodes.",
    'pregnant-by-my-ex-s-professor-dad':
        "On her first day of the semester, Emily catches her boyfriend cheating on "
        "her. That night, she has a wild one night stand with a stranger named "
        "Charles. The next day, they are mutually shocked to find out that Charles is "
        "Emily's new professor. They maintain a professional student teacher "
        "relationship, but there's an undeniable tension between them. Just when "
        "Emily thinks everything will get back on track, she unexpectedly finds out "
        "she's pregnant. 63 episodes.",
    'the-reckoning-takes-flight':
        "Eve takes a flight to Hawaii to attend her big brother's wedding, booking an "
        "extra wide seat because of her broken leg in a cast. A nasty woman and her "
        "bratty son demand Eve switch seats with them. The kid trips because of "
        "turbulence, his mom demands the flight turn back and fights the pilots, "
        "forcing an emergency landing. The mom's sister, Clara, shows up to back her "
        "up. Clara accuses Eve of being her fiancee's mistress, not realizing that "
        "she's her fiancee's little sister. The wedding is canceled, and Clara is "
        "sent to jail. 41 episodes.",
    'you-belong-with-me':
        "Kristine was betrayed by her boyfriend and best friend. She knew about him "
        "cheating on her while riding on her intelligence. Kristine decided to get "
        "back at him by sleeping with his rich uncle, Henry. Henry was aware he was "
        "being used as Kristine made it clear to him. But what started as revenge "
        "changed into genuine feelings. 79 episodes.",
    'my-secret-lover-is-his-brother':
        "To forgive Piper's family debt, she's promised to marry one of the Bellfort "
        "brothers. Will she choose the star lacrosse player Drew? Or the handsome "
        "loner Noah? How can she decide when she has a connection with both? "
        "74 episodes.",
    'the-ceo-s-contract-wife':
        "Jasper Tate needed a wife urgently, while Chloe Adams needed money urgently. "
        "Seeking help from the same source leads the two needy people together, and "
        "they get married after Madam G recommended them to each other. What was "
        "supposed to be a contract agreement morphed into a full blown love affair "
        "that they never expected. 93 episodes.",
    'kiss-me-one-last-time':
        "Adeline has cancer. A few months to live and she'll be dead. The one thing "
        "she needed was her husband, Blake's love. She couldn't get it as he never "
        "saw her as his wife rather as a blood bank for her step sister. 90 episodes.",
    'we-are-never-ever-getting-back-together':
        "Lisa's contract marriage with Aidan ended without notice. She was agitated "
        "that he never valued her as much as she valued him. When they crossed paths "
        "again, she took her chance with him leaving an ill note on his chest. Lisa "
        "didn't know she would be seeing Aidan again, this time, as her boss. "
        "103 episodes.",
    'big-bad-husband-please-wake-up':
        "Ciara is slated to get married to Adrian Lewis, who is in a coma. Ciara is "
        "desperate to do so because she needs the money to save her sick family, and "
        "she is humiliated by her choice until Adrian wakes up to the surprise of "
        "everyone and falls in love with Ciara. 104 episodes.",
    'the-return-of-the-lost-heiress':
        "Lana experienced her father's death. This made her never speak again. She "
        "became a mute. A few days later, she was lost while escaping being sold by "
        "her guard. Lana was found and adopted by Ron who showered her with fatherly "
        "love. Years passed and her birth family kept searching for her. Unaware of "
        "Lana's identity, they mistreated her. 90 episodes.",
    'secret-surrogate-to-the-mafia-king':
        "Vanessa Peters is in for a surprise when she goes to sell her eggs to pay "
        "off her boyfriend's debt and ends up pregnant due to a clinical error. She "
        "decides to keep the child after finding out her boyfriend is cheating on "
        "her, but begins to fear her decision when she finds out that the father is "
        "no other than Marcello Lavigne, a ruthless, murderous Mafia King. Marcello "
        "protects Vanessa and moves her to his mansion. 63 episodes.",
    'escorting-the-ruthless-billionaire-doctor':
        "Violet, desperate to pay for her father's surgery, decides to sell her "
        "virginity, but the good doctor she calls is determined to pull her back from "
        "the edge. However, as the two share a heated, unforgettable night, Dax finds "
        "himself hooked on Violet, despite thinking she's just another gold digger. "
        "When their darkest secrets are laid bare, will their fragile connection "
        "survive? 68 episodes.",
    'open-your-eyes-my-billionaire-husband':
        "Hailey is cash strapped and desperate for a way to pay her mother's hefty "
        "medical bills. Her family agrees to help her, on the condition she marries "
        "the billionaire Samuel Trent, who is in a coma after a near fatal car "
        "accident. Samuel awakens from his coma and discovers he has been engaged to "
        "a complete stranger. 72 episodes.",
    'the-hidden-billionaire-in-first-class':
        "They all thought Jett Hawkings was a lowly baggage handler and threatened to "
        "throw him off the flight. But when their plane is about to crash due to a "
        "storm, he's actually the secret billionaire that can save them. 83 episodes.",
    'the-tutor-trap':
        "School hockey star Brady asks brainy wallflower Harper to be his chemistry "
        "tutor. In exchange, he promises to be her fake boyfriend, teach her how to "
        "flirt, and help her land her crush. But what will happen when their contract "
        "backfires, and the chemistry becomes more than just on paper? 78 episodes.",
    'resisting-mr-lloyd-an-age-gap-romance':
        "Facing family pressure to quit college and marry, Clarisse's world changes "
        "when she meets Austin, the CEO of Lloyd Group, after helping his grandmother "
        "following a scam. Austin offers her money for a fake marriage to fulfil his "
        "grandmother's wish, forming an unexpected alliance while keeping his true "
        "identity secret from her. 70 episodes.",
    'the-quarterback-next-door':
        "Forever invisible Skylar Heron hasn't started her senior year so hot. First, "
        "she's embarrassed in front of the whole school when trying to ask out her "
        "crush Jamie Donner, her childhood best friend and next door neighbour. "
        "Skylar and Jamie are paired for a class project, then Jamie moves into her "
        "room after his house burns down. His ex girlfriend creates conflict, "
        "prompting them to transform Skylar into the school's most popular girl. "
        "87 episodes.",
    'once-upon-a-breakup':
        "After being abandoned on her birthday by her college boyfriend, Mia "
        "impulsively proposes to Carson, the charming but dangerous leader of the "
        "Moretti crime family. Though their relationship begins as a rash escape, it "
        "quickly turns into something real. But Mia's ex refuses to let go. Obsessed, "
        "jealous, and spiraling out of control, he'll stop at nothing to win her "
        "back, even if it means destroying the new life Mia's trying to build with "
        "Carson. 60 episodes.",
    'accidental-triplets-with-the-billionaire':
        "Urgently needing an heir to secure his position in the company, Oscar turns "
        "to surrogacy. But unexpectedly, his sperm is accidentally injected into "
        "Phoebe, who comes in for a gynecological exam. To ensure Phoebe keeps the "
        "baby, Oscar proposes a contract marriage, and the two embark on a journey "
        "filled with tests. 91 episodes.",
    'you-fired-a-tech-genius':
        "After Erik, the biggest tech hotshot in all of Silicon Valley, gets sacked "
        "by his CEO's son William, he joins forces with Evelyn, the beautiful CEO of "
        "his old company's competitor. 59 episodes.",
    'submitting-to-my-ex-s-dad':
        "After catching her fiance cheating with her best friend just before their "
        "wedding, Flora runs away and has a wild one night stand with a handsome "
        "stranger. Little does she know he's her ex fiance's father, and he has a "
        "dark secret. 56 episodes.",
    'the-billionaire-s-virgin-surrogate':
        "Desperate to save her father, Harper agrees to carry a baby for Will "
        "Trenton, a single billionaire. As their worlds collide and the boundaries "
        "blur, Harper finds herself irresistibly drawn to Will. But beneath the "
        "surface, a question remains: is Will feeling the same? The student surrogate "
        "proposes to her client that they conceive the baby naturally instead of "
        "through artificial means. 64 episodes.",
    'obsessed-with-his-silent-bride':
        "Taken in as a ward of the Calvert family, Eva has always loved Declan "
        "Calvert, the boy who grew up as her protector. Nonverbal since birth, she "
        "struggles to express her feelings in a marriage built on duty. Declan only "
        "married her to honour his grandfather's dying wish. Trapped in a toxic "
        "union, Eva endures Declan's cruelty and his mistress Selene's relentless "
        "schemes to drive her out. 85 episodes.",
    'the-billionaire-married-a-homeless-girl':
        "After a one night stand, Adele Moore becomes pregnant. She wants to keep the "
        "child, but her father kicks her out of the house. With nowhere else to go, "
        "Adele becomes homeless. She tries her best to raise her son despite her "
        "challenging circumstances. One day, Adele's son, Brad Moore, runs into "
        "billionaire Heston Deleon. By chance, Heston discovers that Brad is his son. "
        "He tries to track down Brad, but loses their trail. Through a series of "
        "misunderstandings, Adele and Heston become entangled again. 58 episodes.",
    'swapped-my-ex-for-his-billionaire-uncle':
        "There was a time when Nina believed her happiest moment would be walking "
        "down the aisle with Evan, her college sweetheart. But betrayal shattered "
        "that dream. After divorcing Evan, Nina refuses to love again, until Damon, "
        "Evan's youngest uncle, persistently enters her life despite her resistance "
        "to maintaining family connections. 80 episodes.",
    'ceo-s-twins-want-mommy-back':
        "With a loving hubby and cute stepkids, Cassandra's flash marriage seems too "
        "good to be true. But will her troubled past catch up to her? And why do the "
        "kids seem so familiar? 105 episodes.",
    'trapped-in-the-boss-s-embrace':
        "Lovestruck, Beatrice Lawson eloped with her college sweetheart Desmond "
        "Belmont and has been secretly married to him for ten years. However, when "
        "she discovers his affair with a wealthy socialite, Beatrice decides to "
        "divorce him and finally stop living in his shadow. As she begins to make a "
        "name for herself with a new apartment and new career, she meets the "
        "mysterious and attractive Damian Crowley. 87 episodes.",
    'the-billionaire-s-masquerade':
        "After Shelby's father died, he passed on his inheritance to her with "
        "unfavourable conditions. She must get married to claim her inheritance. To "
        "claim it, she marries a poor stranger, Griffin. She didn't know that Griffin "
        "wasn't a poor man as she had thought. He's a billionaire who had admired "
        "Shelby from their last encounter, three years ago. 79 episodes.",
    'never-divorce-a-secret-billionaire-heiress':
        "Joyce has been a walking blood bank for her sister, Selena. It was the price "
        "she had to pay for forcing Tristan into marrying her. Joyce realises her "
        "situation when she loses her baby without receiving support from her "
        "husband, and subsequently seeks a divorce. 55 episodes.",
    'runaway-single-mom-safe-in-his-arms':
        "Single mom Maria escapes abuse and fights to protect her daughter, Judy. "
        "From factory struggles to elite schools, she faces enemies, family betrayal, "
        "and unexpected love. When billionaire Levi enters her life, everything "
        "changes. 57 episodes.",
    'escorting-the-heiress':
        "Serena caught her boyfriend, Ken, cheating on her with her half sister, "
        "Carol. He had always lied about holding it all in till marriage. Furious by "
        "their actions, Serena gets drunk and ends up in the bed of Jesse. She "
        "thought he was her escort but he was a man who has been in love with her for "
        "years. 74 episodes.",
    'the-billionaire-s-accidental-bride':
        "Claire Duval and Christian Cross get married by chance. Claire was glad to "
        "have gotten engaged with Dylan Maxwell until he stood her up and she found "
        "out that he was cheating on her with her friend, Ava. Claire secretly got "
        "married to Christian on the spot as they were both stranded. 82 episodes.",
    'dominated-by-my-dad-s-boss':
        "When Jayne Turner asks a stranger at a bondage party to teach her how to be "
        "a dominatrix, she has no idea he'll turn out to be the man overseeing her "
        "father's exit from the family company. Their secret relationship is "
        "complicated by a morality clause and threatening messages connected to "
        "Jayne's deceased mother. 73 episodes.",
    'the-senator-s-son':
        "Emma Andrews wants to lead a quiet life in college, but that's impossible "
        "when Zach Walker, son of a famous senator and the hottest guy on campus, "
        "targets her for relentless bullying. An enemies to lovers arc where the two "
        "are unexpectedly trapped together in a boathouse, leading Emma to discover "
        "hidden depths beneath Zach's bully facade.",
    'mic-drop-diva':
        "Ivy is a high school sophomore with the voice of an angel. She's also a "
        "super wealthy heiress, but she hides her identity in the hopes of making "
        "real friends at school. After becoming besties with Vanessa, she thinks "
        "she's made the right choice. But Vanessa actually treats Ivy like a total "
        "tool, and even guilt trips Ivy into being her voice double. Things start to "
        "fall apart after Ivy catches her boyfriend cheating on her with her bestie. "
        "Heartbroken and betrayed, Ivy seeks help from her childhood best friend and "
        "star quarterback, Blake. 52 episodes.",
    'djinn-under-contract':
        "Eli Baran is a genie in a magic lamp who can grant three wishes. After "
        "thousands of years, a billionaire uses his last wish to grant Eli freedom, "
        "but on one condition: Eli must marry his granddaughter, Christine Parrish, "
        "for five years. Eli transforms into human form and secretly helps Christine "
        "become a successful CEO. However, Christine belittles him throughout their "
        "marriage. 67 episodes.",
    'true-luna':
        "Emma is a powerful wolf known as the true Luna. Her kind is rare. When she "
        "got her wolf, a warning came along with it. Emma will be in danger soon as "
        "the rogue king is after her. Her joy of getting a wolf and finding a mate is "
        "torn when her mate rejects her. 61 episodes.",
}

