# -*- coding: utf-8 -*-
"""Sunday caption batch 5 Oct 2026, part 2, new titles from the weekly scrape. STAGED FOR CYAN'S REVIEW via PR, not approved.

14 titles, 14 written, none skipped. Every caption is written from the ReelShort
book the title page links to (availability.csv direct_link); each FACTS entry is
that book's full page synopsis, checked identical to the live page on 5 Oct 2026.
"""

CAPTIONS = {
    # 13.4M  Rejected Luna is His Fated Mate
    'rejected-luna-is-his-fated-mate':
        "Left at the altar by her fiance. Proposed to by the Alpha King the next day.\nNova's wedding falls apart in front of everyone when her fiance Cole realizes Elara is his fated mate and walks away from Nova for her. Elara was supposed to be marrying Alpha King Ronan, and she leaves him standing alone at the altar too. A day later Ronan turns up where Nova lives. He's brought betrothal gifts, 108 chests of them, and he wants to marry her. They've both been betrayed, so Nova says yes, and the Draven royal family gets a new Luna. Cole can't stop trying to get her back, and Elara keeps plotting against her. But the real surprise is Ronan. Marrying Nova was never a whim. He's loved her in secret for twenty years, and Cole threw away the woman another man had waited two decades for.",
    # 12.2M  The Wife He Gave Away
    'the-wife-he-gave-away':
        "He asked for a pretend divorce. She signed a real one.\nFive years into their marriage, her husband threw her out of the house for his sister, who claimed she had amnesia. Then she lost their baby, and his answer was a divorce for show, only to keep his sister calm. She signed real divorce papers instead and blocked his number. The amnesia turned out to be fake, and once that came out the sister landed in a psych ward. Her ex faked cancer, and after that a car crash. Years later she's on the Forbes list, her mother gets by on the $200 she sends each month, and she no longer mentions the man who threw her away by name. They tried to break her, and now they can't touch her.",
    # 8.3M  Divorced, She Reclaimed Her Empire
    'divorced-she-reclaimed-her-empire':
        "She gave him ten years. He planned to leave her with nothing.\nSophie set aside her career and her inheritance for ten years so Julian could have everything. Then she finds out what he's been doing behind her back. He has a mistress, and a child with her. He's been quietly moving millions around, and he's planning a divorce that leaves Sophie almost empty handed. She doesn't tip her hand. She builds her case piece by piece and goes back to Whitmore Materials Group, where she's the heiress. At a family gala she lays out everything he did in front of everyone, then beats him in the divorce and wins back the company she had a hand in building. In the end it's Julian who walks away with nothing.",
    # 7.0M  Trash Boy's Super Watch
    'trash-boy-s-super-watch':
        "They call him Trash Boy. Then an alien crashes into his backyard.\nKyle was born into money, but his mother died when he was young. At home his stepmother Alicia shuts him out and sets him up again and again, and so does Ryan, his half brother. His father Robert sends him to live in the tool shed out back. School is no escape. His family situation marks him there too, the other kids call him Trash Boy, and the bullying never lets up. Then a spaceship comes down in the backyard, and in the shed Kyle finds Zorp, a wounded alien observer. They make a deal. Kyle wears Zorp's energy wristband, and every hardship he pushes through creates the emotional energy Zorp needs to fix his ship. In return the band unlocks powers Kyle never knew he had, sharper senses and a stronger body. He starts standing up to the bullies, and Ryan is furious. So in the school cafeteria Ryan accuses Kyle in front of everyone of stealing an expensive watch, and his friends help him humiliate Kyle brutally. With his pride and his spirit close to breaking, Kyle begs Zorp for help.",
    # 4.5M  The Big Wife's Revenge: From Model to Queen
    'the-big-wife-s-revenge-from-model-to-queen':
        "She loved him for ten years. The marriage broke her heart.\nSophia has loved Damien for a decade, and she finally gets to be his wife. The marriage she always dreamed of falls apart. She's humiliated and betrayed, and his assistant is scheming against her. Heartbroken, Sophia leaves, and she remakes herself completely. When she comes back three months later she's gorgeous and confident, and this time she's living for nobody but herself. That's exactly when Damien, arrogant as ever, figures out he's in love with her. Now he's ready to do whatever it takes to get her back. The trouble is she's not chasing him anymore.",
    # 3.0M  Don't Wake the Dead Man
    'don-t-wake-the-dead-man':
        'A quiet dockhand. His daughter in the fight ring. A Syndicate hunting a dead man.\nCole Andrews works the docks on Tidewater Station. He stays out of trouble, puts up with whatever abuse comes his way, and raises his daughter Kira on his own. Then someone rigs a debt against them, and because of it fifteen year old Kira ends up in the fight ring. Suddenly people all over the station want to know who her father really is. So does the Syndicate, which has been chasing a man everyone believes is dead for fifteen years. With Kira in that ring, the quiet life Cole built for her is over.',
    # 2.7M  Dear Brother, Your Regret Came Too Late
    'dear-brother-your-regret-came-too-late':
        "Her brother wished she had died instead. Then she got cancer.\nStephanie's mother didn't survive her birth, and for sixteen years Stephanie has carried the blame for something that was never her fault. Her father Morris ignores her and her brother Alexander can't stand her, but Alexander once showed her a little kindness, and she holds on to it because it's all she has. Then their cousin Abigail moves in, and even Alexander turns against her. He wishes she'd been the one who died. In a way he gets what he wanted, because Stephanie is diagnosed with cancer. Once she's gone, it's Alexander whose world starts coming apart, and his regret comes far too late to matter.",
    # 2.3M  The School for Bad Boys
    'the-school-for-bad-boys':
        "One rule at Maplewood. Break it and you're out.\nMaplewood Reform School is where rich families send their problem sons when the only place left after it is prison. Cody Calloway is openly gay, and nobody at Maplewood wants him there. The school's very first rule says any homosexual activity means instant expulsion. Then there's Beckett Hayes, the school's golden boy. He's straight, he has a girlfriend and a dark past, and he's becoming obsessed with Cody. Every touch they sneak could cost them their freedom, and they keep reaching for each other anyway.",
    # 1.4M  My Twins Picked a Billionaire Dad
    'my-twins-picked-a-billionaire-dad':
        "She saved the heir five years ago. He has no idea the twins are his.\nFive years ago Lena, a woman born with incredible strength, rescued Ryan, the heir to a financial conglomerate who had been framed. Afterward she gave birth to twins nobody expected, a boy and a girl, and then she was gone. Now both of them are being pushed toward forced marriages, with an inheritance fight on top of it, so they agree to a contract marriage. Ryan doesn't know Lena is the woman who saved him, the one he's spent five years looking for, and he doesn't know the twins are his own children. Together they take on Ryan's uncle William, a schemer who wants the family fortune for himself. The twins are smarter and stronger than kids their age should be, and they keep pulling their parents out of danger. After every twist, Ryan finally gets back a family he never knew he had.",
    # 1.3M  The Alpha Who Let His Luna Die
    'the-alpha-who-let-his-luna-die':
        "She's carrying the Alpha's child. He only has eyes for someone else.\nAlly Jones is carrying Alpha Cyrus's baby, and her life is in danger. The one thing that can save her is a sacred fruit from the Arbor Vitae. Cyrus is her true mate, but all he seems to care about is Emma, another werewolf. Ally gets weaker by the day. Will Cyrus put her first, even once?",
    # 1.1M  After His Number Disappeared
    'after-his-number-disappeared':
        "She can see how many times she'll meet someone. Then his number moved.\nMia has a strange gift. Above every person's head she sees a number, and it tells her how many times their paths will cross. Ever since she was little, the number over her childhood friend Henry has been enormous, so she was sure he was her soulmate. She even drew up a list of rules for him to follow as her boyfriend. Then Henry shows her a picture of his roommate Liam, and in that moment the huge number jumps to Liam. Mia lets go of Henry and falls for Liam, who has loved her in secret all along. Once he's lost her, Henry fights hard to win her back, but there's no changing fate. When trouble hits his family he moves abroad, and Mia stays with Liam, the one who meant it.",
    # 855.9K  The Alpha's Secret Pup
    'the-alpha-s-secret-pup':
        "Blind, sold by her fiance, and carrying the Wolf King's child.\nRonan rules the North as its Wolf King, and Ayla, who is blind, is handed over to him by her own fiance, as good as sold. They spend one night of passion together, and then a witch frames Ayla and she's thrown out of wolf territory. She's left fighting to survive on her own while raising the Wolf King's child. One year on, her daughter Lumi happens to cross paths with Ronan. With the witch hunting her, her fiance's betrayal behind her and Ronan asking questions, Ayla keeps who she really is hidden and quietly plans her revenge. As Ronan digs into what really happened, he realizes he's been falling for Ayla all this time, and he's willing to be the weapon behind her revenge. But there are curses tangled up in this love, and it won't come without heartbreak.",
    # 812.1K  His Defective Robot Boyfriend
    'his-defective-robot-boyfriend':
        "Labeled defective and set to be scrapped. Then an engineer saved him.\nIt's Boston in 2049. The Global Data Collapse erased huge digital archives, and androids are now part of everyday human life. Alden Shaw is the chief emotional AI engineer at Wren Robotics, and he rescues a prototype called EL0 that was marked defective and due for disposal. He names him Elio. It starts as a technical rescue, but slowly it turns into a bond that blurs the line between man and machine. Elio keeps breaking the Three Restrictions every android is programmed with. He feels jealousy and longing, he turns possessive, and his love is the kind that would sacrifice itself. Corporate conspiracies drag them in, and along the way they expose how greedy Gideon is, what Silas has been hiding, and the unfinished core Julian kept secret. And they have to face the hardest question of all. Is an android's love just code following orders, or is it real feeling from a being with free will?",
    # 472.1K  The School for Bad Boys: S*x Lessons
    'the-school-for-bad-boys-s-x-lessons':
        "His roommate is his worst enemy. Now he's offering lessons.\nLeo is crushed to learn that his new roommate at reform school is Tyler, his archenemy. Leo has no experience to speak of, and he's fallen for the Headmaster's daughter. That's when Tyler proposes giving him sex lessons. The deeper they get into those lessons, the harder it is to pretend they don't have feelings for each other. Getting caught wouldn't only get them expelled. It would send them to prison. Leo and Tyler can't make up their minds about whether what they have is worth that.",
}

FACTS = {
    'rejected-luna-is-his-fated-mate':
        'On her wedding day, Nova is publicly abandoned when her fiancé, Cole, recognizes Elara as his fated mate. Meanwhile, Alpha King Ronan is also left at the altar by Elara. The next day, Ronan arrives at Nova’s door with 108 chests of betrothal gifts and asks her to marry him. United by betrayal, Nova accepts his proposal and begins a new life as the Luna of the Draven royal family. As Cole desperately tries to win her back and Elara repeatedly schemes against her, Nova gradually discovers that Ronan did not choose her on impulse—he has secretly loved her for twenty years.',
    'the-wife-he-gave-away':
        'Five years married, and he kicked me out for his "amnesiac" sister. After I miscarried, he said, "Let\'s get divorced, just pretend, to keep her calm." So I signed the real papers, blocked him. Her fake amnesia got exposed, she ended up in a psych ward. He faked cancer, then a car crash. Years later, I\'m on Forbes, my sister\'s insane, my mother lives on the $200 a month I give her, and the man who threw me away is just someone I don\'t even bother to name anymore. They tried to destroy me, now I\'m out of their reach.',
    'divorced-she-reclaimed-her-empire':
        'After ten years of sacrificing her career and inheritance for Julian, Sophie discovers he has kept a mistress, fathered a child, and moved millions while planning to divorce her with almost nothing. Instead of confronting him too soon, she gathers evidence, returns to Whitmore Materials Group as its heiress, exposes his betrayal at a family gala, wins the divorce battle, and takes back the company she helped build—leaving Julian with nothing.',
    'trash-boy-s-super-watch':
        'Kyle is the son of a wealthy family. His biological mother died early. At home, he\'s constantly excluded and framed by his stepmother Alicia and his half-brother Ryan. His father Robert banishes him to live in a backyard tool shed. At school, his family background makes him a target as well. He\'s mocked as "Trash Boy" and subjected to relentless bullying. One day, an alien spacecraft crashes into the backyard. Inside the shed, Kyle discovers an injured alien observer named Zorp. The two strike a deal: Kyle will wear Zorp\'s energy wristband and, by overcoming adversity and generating emotional energy, help Zorp repair his ship. In return, the wristband awakens Kyle\'s own latent potential. With heightened perception and physical abilities, Kyle begins fighting back against his bullies, enraging Ryan. In the school cafeteria, Ryan publicly accuses Kyle of stealing a valuable watch and, together with his lackeys, subjects him to brutal humiliation. As his dignity and spirit come under critical fire, Kyle makes a desperate plea for Zorp\'s help.',
    'the-big-wife-s-revenge-from-model-to-queen':
        'Sophia finally marries Damien, the man she’s loved for ten years—only to have her dream marriage shattered by humiliation, betrayal, and his scheming assistant. Heartbroken, she walks away and transforms herself inside and out. Three months later, Sophia returns stunning, confident, and determined to live for herself. But just as she stops chasing Damien, her arrogant husband realizes he’s fallen for her—and now he’ll do anything to win his wife back.',
    'don-t-wake-the-dead-man':
        'On Tidewater Station, dockhand Cole Andrews keeps his head down, takes the abuse, and raises his daughter alone. But when a rigged debt puts fifteen-year-old Kira in the fight ring, the station starts asking who her father really is - and so does the Syndicate that has spent fifteen years hunting a dead man.',
    'dear-brother-your-regret-came-too-late':
        "For sixteen years, Stephanie has lived with a guilt she never deserved — her mother died giving birth to her. Neglected by her father, Morris, and despised by her brother, Alexander — she clings to the only warmth Alexander ever gave her. But when their cousin Abigail moves in, even Alexander turns on her, wishing she were the one who had died. And in a way, he gets his wish when Stephanie is diagnosed with cancer. But after her death, it's Alexander's world that begins to fall apart.",
    'the-school-for-bad-boys':
        "After being sent to Maplewood Reform School—a last stop before prison for the problem sons of wealthy families—openly gay teen Cody Calloway is NOT welcome. After all, the first rule of Maplewood is clear: any homosexual activity earns an immediate expulsion. Enter Beckett Hayes, the school's straight golden boy with a girlfriend, a dark past, and a growing obsession with Cody. Every stolen touch puts their freedom on the line…but some things are worth the risk.",
    'my-twins-picked-a-billionaire-dad':
        'Lena, who possesses extraordinary innate strength, saved Ryan, a framed heir to a financial conglomerate, five years ago. She left after unexpectedly giving birth to a pair of boy-and-girl twins. Five years later, to fend off forced marriage and the inheritance crisis from their families, the two enter into a contract marriage. Ryan has no idea that Lena is the savior he has been searching for for five years, nor that the twins are his biological children. They join forces to fight William, Ryan’s scheming uncle who covets the family fortune. With superior intelligence and unusual strength, the twins repeatedly help them out of dangers. After many twists and turns, the whole family is finally reunited.',
    'the-alpha-who-let-his-luna-die':
        "Pregnant with Alpha Cyrus's child, the only thing that can save Ally Jones's life is the sacred fruit of the Arbor Vitae. But her true mate Cyrus only seems to care about another werewolf, Emma. As Ally's body grows weaker, will Cyrus choose her... just this once?",
    'after-his-number-disappeared':
        'After His Number Disappeared, a 38‑episode modern urban fantasy romance short drama. The heroine Mia has a special ability to see numbers above people’s heads showing how many times they will meet. Since childhood, she saw the huge number above her childhood friend Henry and believed they were soul‑mates, even making boyfriend‑rules for him. The moment Henry showed her a photo of his roommate Liam, the huge number transferred to Liam. Mia let go of her obsession and fell for Liam, who had secretly loved her. Henry tried desperately to win her back after losing her yet could not change fate. Henry moved overseas due to family misfortune, and Mia finally stayed with the sincere Liam.',
    'the-alpha-s-secret-pup':
        'Blind Ayla is "sold" by her fiancé to Ronan, the Wolf King of the North. After one night of passion, she is framed by a witch and exiled from the wolf territory. She struggles to survive alone with the Wolf King\'s child. A year later, her daughter Lumi unexpectedly reunites with Ronan. Facing the witch\'s pursuit, her fiancé\'s betrayal, and Ronan\'s probing, Ayla hides her true identity and secretly plots her revenge. Meanwhile, as Ronan investigates the truth, he gradually realizes he has long been caught in an emotional vortex for Ayla—and willingly becomes the weapon of her vengeance. Curses intertwine with true love, setting off a bittersweet romance that defies race and destiny.',
    'his-defective-robot-boyfriend':
        'In Boston of 2049, after the Global Data Collapse wiped out massive digital archives, androids have woven themselves into human society. Alden Shaw, chief emotionalAI engineer at Wren Robotics, rescues prototype EL0 marked for disposal and labelled defective. He names him Elio. What begins as a technical rescue gradually blooms into a bond crossing the line between human and machine. Elio repeatedly breaks the Three Restrictions programmed into androids, developing jealousy, longing, possessiveness and selfsacrificing love. Drawn into corporate conspiracies, they uncover Gideon’s greed, Silas’ hidden agenda, and Julian’s unfinished hidden core. They are forced to confront one devastating question: is an android’s love merely code and command, or the genuine affection of a freewilled being?',
    'the-school-for-bad-boys-s-x-lessons':
        'Leo is devastated to find out his new roommate at reformatory school is his arch nemesis, Tyler. But when the highly inexperienced Leo falls for the Headmaster\'s daughter, Tyler offers to give him "sex lessons." The more Leo and Tyler lose themselves in these lessons, the harder it becomes the deny their feelings for each other. But getting caught doesn\'t just mean expulsion, it means prison. And Leo and Tyler can\'t decide if being together is worth the risk.',
}

SOURCES = {
    'rejected-luna-is-his-fated-mate': ('platform', 'https://www.reelshort.com/movie/rejected-luna-is-his-fated-mate-6aae902a8b430d94100b20e5'),
    'the-wife-he-gave-away': ('platform', 'https://www.reelshort.com/movie/the-wife-he-gave-away-6a55eb34abf3824e3a08be70'),
    'divorced-she-reclaimed-her-empire': ('platform', 'https://www.reelshort.com/movie/divorced-she-reclaimed-her-empire-6a98fe18f74722e51507e385'),
    'trash-boy-s-super-watch': ('platform', 'https://www.reelshort.com/movie/trash-boy-s-super-watch-6a56ddb45c65371f2b0a3f8a'),
    'the-big-wife-s-revenge-from-model-to-queen': ('platform', 'https://www.reelshort.com/movie/the-big-wife-s-revenge-from-model-to-queen-6ab1dbdd57702faa710e1557'),
    'don-t-wake-the-dead-man': ('platform', 'https://www.reelshort.com/movie/don-t-wake-the-dead-man-6ab21030213827243c039eab'),
    'dear-brother-your-regret-came-too-late': ('platform', 'https://www.reelshort.com/movie/dear-brother-your-regret-came-too-late-6ab8a43a2cdfd334da0580eb'),
    'the-school-for-bad-boys': ('platform', 'https://www.reelshort.com/movie/the-school-for-bad-boys-6ab37198011591995402da38'),
    'my-twins-picked-a-billionaire-dad': ('platform', 'https://www.reelshort.com/movie/my-twins-picked-a-billionaire-dad-6aaf478c87526e1dea08542e'),
    'the-alpha-who-let-his-luna-die': ('platform', 'https://www.reelshort.com/movie/the-alpha-who-let-his-luna-die-6ab3d9467005444d100a9527'),
    'after-his-number-disappeared': ('platform', 'https://www.reelshort.com/movie/after-his-number-disappeared-6ab4ef3d73f5cdd44e0ba279'),
    'the-alpha-s-secret-pup': ('platform', 'https://www.reelshort.com/movie/the-alpha-s-secret-pup-6ab48511b7e3bc54940add55'),
    'his-defective-robot-boyfriend': ('platform', 'https://www.reelshort.com/movie/his-defective-robot-boyfriend-6ab0dd3efcd55b2fca0e84bd'),
    'the-school-for-bad-boys-s-x-lessons': ('platform', 'https://www.reelshort.com/movie/the-school-for-bad-boys-s-x-lessons-6aac8448a2dbec86c80e73d7'),
}
