# -*- coding: utf-8 -*-
"""DRAFT captions, part 1 of 4 of the 28 Sep 2026 new-titles batch (new234).

58 new titles from the 27/28 Sep scrape, written from each title's own platform
page. Where the batch input had no synopsis, it was fetched from the page the
title links to: ReelShort (taming-the-mafia-boss, from the banked book
6800bcd28e63e6be8505c47c), Vigloo (universe.exe), StardustTV (2, rendered),
MoboReels (9), and the fuller on-page description for the two PineDrama titles
(billionaire-alphas-fated-mate, the-return-of-the-amnesiac-heiress). FACTS holds
the exact text each caption was written from.

LEFT OUT, NEEDS A SOURCE:
  justice-in-blood (FlexTV) - the page carries only a teaser blurb: no names,
  no characters, no plot beyond "he lost everything and takes a syndicate
  apart". Nothing to retell without inventing. Needs Cyan or a better source.

THIN BUT WRITTEN, worth her eye: billionaire-alphas-fated-mate (the platform
names nobody, so the caption names nobody), racing-back-to-your-heart (short
source, short caption), my-alien-life (source includes sexual assault; kept
factual and non-graphic, the source's "her body still reacts" left out).
"""

CAPTIONS = {
    'mr-williams-madame-is-dying':
        "Sixteen years of love, and all he wanted was her blood.\nMadison Evans has been in love with Hunter Williams for sixteen years. What Hunter wants from his wife is a walking blood bank for Andrea David, his White Moonlight, and he even wrecks Madison's family to clear a space for Andrea in his life. Then a cancer screening report lands in Madison's hands, and it finally shows her how cold and heartless he really is. The day she stops loving Hunter, she has to face the truth. She gave sixteen years of her life to the wrong man.",

    'escape-with-boss-s-baby':
        "The heiress who went to work as his secretary.\nHermione Garcia is a celebrated computer genius, and she's also the heiress of the Garcia family, the richest name in the South. Three years ago Chris Evans saved her at a banquet and she fell for him. He's President of LM Corporation, and she wants him to love her for herself, so she hides who she is and takes a job as his chief secretary. They've been seeing each other in secret ever since, and he still has no idea who she really is. But a secret that big can't hold forever, especially once there's a baby involved.",

    'ruling-over-all-i-see':
        "No job, no money, and a system that wants his wives to love him.\nJudah Shaw is a graduate who can't find work, and not long after, he ends up in Qirelia as a scholar without a coin to his name. He also has wives. The marriages were only ever a matter of convenience, but a system won't let him rest until he wins every one of them over. Then he finds out who he married. One is a princess, one is a general's daughter and one is a merchant heiress. Together they bring him money and a future far bigger than anything he ever pictured. The man with nothing is about to have it all.",

    'no-escape-as-the-dragon-king-s-mate':
        "She saved a stranger's life. He's the Dragon King, and now she's his.\nLydia is a nurse, and a human one, when she finds a man bleeding one rainy Valentine's night and saves him. He turns out to be Soren, the ruthless Dragon King, and he gives her two choices. She can be his fated mate, or she can die. Pulled into a deadly supernatural world, Lydia fights him every step of the way, until the fight starts turning into something hotter and she catches sight of the softer heart hiding under all those scales. Their deal only runs for thirty days. When time's up, will she take her freedom or stay with the Dragon King for good?",

    'i-m-nothing-but-a-mortal':
        "He reached the Sky Realm in twenty years. His mentor sent him back down.\nIan Colt is a gifted apprentice of the Jade Sect, and it takes him only twenty years of cultivation to rise all the way to the Sky Realm. His mentor Sean Judd decides there's nothing left to teach him, so he tricks Ian into heading down to the mortal realm. Down there Ian meets Jim Cole, a man at death's door. Three skilled doctors have already tried everything and failed, and Jim's daughter Sue Cole is out of hope. Then Ian steps in and saves Jim's life. Where three doctors couldn't, a young man nobody has heard of just did.",

    'taming-the-mafia-boss-he-s-mine-now':
        "She paid to keep a broke rich boy. He runs a mafia family.\nLeah of the Cruz family looks like a spoiled party girl who throws cash around at nightclubs. The truth is she's an heir who lost everything when her stepfather took control. One drunken night, in a big misunderstanding, she spends a fortune to keep Allen, who she thinks is a young master whose rich family went broke. She has no idea he's actually the head of the Smith family's mafia clan. At home he puts on an apron and makes her dinner. When her stepsister Lisa sets her up, he puts a gun to the enemy's head. Leah thought she was the one looking after him. Now her sugar mommy days are over, and she's about to become the mafia boss's wife.",

    'spoiling-my-sweet-wife-to-her-core':
        "She died hated by her fiance. Someone else woke up in her body.\nOn the day she's supposed to get engaged, Anne Miller is framed for cheating. Shawn Smith, her fiance, is furious and swears he'll never marry her. Anne knows her stepsister Elsa Miller planned the whole thing, but Shawn believes every lie Elsa tells him. Anne dies bitter and full of regret. Then the soul of a heroine who happens to share her name slips into her body, and this Anne has made a promise. Everyone who wronged the first one is going to pay.",

    'food-love-robots':
        "Her son wished his dad home for Christmas. He came back a robot.\nSeven years ago Lily lost Elliot, the love of her life, without any warning. This Christmas was meant to be a quiet one, until their son Evan makes a wish and it comes true. Elliot is back. Only now he's a humanoid robot, built with every memory the real Elliot had. Lily starts letting herself love again, while family, romance and technology all collide in one charming mess. But is this second chance real, or is she falling for a program that's just too perfect?",

    'this-time-i-choose-mr-mafia':
        "Second time around, she picks the mafia king.\nThe man Stella loved and his mistress took everything from her. Her family, her good name, her whole life. Then fate turns back the clock and she's standing at the husband selection gala all over again. This time she walks right past her ex and stuns the room by picking Adrian, a ruthless mafia king nobody is brave enough to cross. With Adrian she gets power, protection and plenty of passion. But soon she uncovers his secret. She thought she'd picked herself a weapon. What she really had, the whole time, was a shield.",

    'hero-husband-s-apocalypse-harem':
        'The end of the world, a system, and three women to protect.\nThe apocalypse wrecked the world years ago, and Sam is a nobody just trying to get through each day alive. Then a system shows up and turns his life upside down. It hands him a job, and his own survival depends on it. He has to keep three beautiful women safe, and doing that means Sam has to find out what real bravery looks like. One by one, all three of them decide they want to be his wife.',

    'one-night-with-the-dragon-lord':
        "Her one free night was with a stranger. By morning he was on the throne.\nIsolde takes her sister's place as the Dragon Lord's bride, because it keeps her mother alive. He's a monster, and every bride before her has been torn to pieces. So before the wedding she gives herself one night of freedom, with a man she's never met. The next morning that man is sitting on the throne. It turns out her touch is the only thing that settles his curse, so she stays, planning to use his army for herself. Vael knows exactly what she's up to and lets her. Then she learns it was her own father who cursed him, and that Vael carries her poison. He hands her a blade, and she chooses the crown.",

    'fight-for-me-prison-king':
        "He went to prison for her and thinks she walked away.\nReid Donovan gives up everything and takes the fall for the woman he loves, and it costs him seven years behind bars. The whole time he's inside, he's sure she abandoned him. Prison turns him hard, and by the time he's done they call him the Prison King and everyone is afraid of him. Now Reid is out and wants to start over. What he doesn't know is why she went quiet all those years, and once he learns it, nothing will look the same.",

    'harvest-of-ambition-a-ceo-s-odyssey':
        "He bought every unsold vegetable in Ashville. His wife gave her lover the credit.\nDerek Larsen spends five years grinding away in the city and comes out of it as the CEO of Gilmore Group. He orders the company to buy up every vegetable left unsold in Ashville. Instead of thanks, he gets doubt and ridicule from his family and everyone who knows him. Then his wife Nina Hart pulls up in a car belonging to Simon Hall, the lover she's been hiding, and tells everyone the deal was Simon's doing. The credit for Derek's big move is about to go to the man sleeping with his wife.",

    'married-my-sister-s-groom-and-make-him-regret':
        "Three years married, pretending to be her twin sister.\nHannah's grandmother is dying, and to save her Hannah agrees to spend three years living as her twin sister. That means stepping into her sister's marriage. Her husband has no love for her, he's cruel to her, and he can't let go of his first love. Hannah puts up with all of it until the three years are up. Then she takes the money she earned and leaves. Only once she's gone does he see what he threw away, and by then it's too late.",

    'her-journey-beyond-the-script':
        "She's stuck in a romance novel as the villain who dies.\nCharlotte Chase gets pulled inside a romance novel, and not as the heroine. She's the antagonist, the one whose every choice is a foolish one, written only so the Female Lead looks better next to her. The book has already decided how her story ends, and it ends with her death. If Charlotte wants to live, she has to get away from Fred, the Male Lead, before she's swept into all the power games and plots circling him. But can she change an ending that's already written?",

    'don-s-daughter-doesn-t-need-a-new-mother':
        "The Don's daughter is done staying in the shadows.\nLoretta is the Don's heiress, though hardly anyone knows a thing about her. She's taken all the humiliation she's going to take from her father's mistress, and now she's stepping out into the open. Once everyone learns who she really is, she goes after the traitors and the rot inside the mafia house. Every person who ever crossed her family is about to pay for it.",

    'the-mafia-boss-is-addicted-to-my-touch':
        "His daughter is the baby her husband sold.\nSix years ago Haley spent a night blindfolded with a man she never saw, and that man was the Mafia boss Lester. Now her cheating husband Bill has left her life in ruins, and she and Lester sign a healing marriage contract. Then she makes a discovery. Lester's little girl is the newborn she lost, the baby Bill secretly sold. From there Haley starts a whole new life, putting her toxic exes in their place and falling hard for Lester.",

    'when-she-stopped-chasing-his-love':
        "She was only ever her sister's stand in.\nCamellia was born to play piano, but when she goes deaf in one ear her family writes her off. So she takes Dylan's help to keep going with her music, and the price is becoming a replacement for the woman he really loves, her own sister Malory. Three years go by. Then Malory comes back, and Camellia finally sees her place for what it is and walks out. The moment she does, a mysterious music producer notices her talent. And Dylan starts to understand that the woman he let go was the one he should have kept.",

    'my-gynecologist-is-the-mafia-boss':
        "Her gynecologist is secretly the Mafia King.\nJenna's marriage is humiliating and there's no intimacy in it at all. The one bright spot turns up somewhere she'd never have looked, in her mysterious doctor Wayne. Wayne is actually the ruthless Mafia King. He brings Jenna into his home as his housemaid, and the fragile ex wife turns into a Mafia Queen people are afraid of. Every single person who ever did her wrong gets destroyed along the way.",

    'reborn-with-my-son-married-to-the-snake-king':
        "Her sister and her husband killed her. She came back to choose again.\nSerena was murdered by her own sister and her husband. Then she's reborn, back at the Husband Choosing Rite. This time she turns down the treacherous Wolf Heir and picks Soren, a Serpent Lord everyone says is brutal and broke. The rumors are wrong. Soren is gentle, completely devoted to her, and the richest man in the realm. With her child, her family and every clan to protect, Serena goes after her revenge and holds nothing back.",

    'from-trash-awakener-to-ocean-god':
        "They called his Pandora's Box trash. It held Poseidon.\nAimar is pulled into the Ocean Age, a world overrun with monsters, and the power he awakens is an SSS grade Pandora's Box. Everyone laughs at it and calls it junk. He gets dumped, then kicked out. Then he finally opens the box, and inside are Poseidon and ten ancient gods, all waking up. The outcast nobody wanted now rules the seas, and every enemy he has ends up bowing at his feet.",

    'he-begs-for-the-heart-he-broke-120-times':
        "She confessed to him 120 times. Then she forgot she ever loved him.\nFor ten years Leona loved Everett, and she told him so 120 times. It never worked. Then a terrible fall wipes that love clean out of her. Everett's jealous ex comes after her anyway, setting her up, burning her and locking her away, and through all of it gentle Shane never leaves Leona's side. As Leona starts to flourish, the schemes against her fall apart. Everett is driven mad with regret. But by the time he comes begging, Leona has already moved on.",

    'from-zero-to-hero-the-x-ray-eyed-surgeon':
        'A broke, bullied intern gets X ray vision.\nTristan Rourke is an intern doctor with no money who gets pushed around by everyone, until an accident leaves him with X ray vision. Suddenly he can spot illnesses nobody else can see, catch every plot against him and save patients no other doctor could. The nobody turns into a medical legend. Then Tristan sees a deadly earthquake coming, and he has to decide what matters more. He picks saving the world over getting rich.',

    'her-and-her-a-dangerous-affair':
        "She went undercover to bring down her captain. Then she started falling for her.\nMia is a star young cop, and Internal Affairs Director Vance sends her undercover into the 15th Precinct to dig up proof that Captain Victoria is corrupt. Victoria is cold and hard on her from the start, but Mia can't help being pulled in by how tough and quietly fair she is. When Victoria takes a bullet for her during a raid on the docks, Mia's guard comes down for good. Then the only son of the Oversight Director is murdered at a gallery. Working the case together, they find out the mole is Leo, a colleague they both trusted, and when he lures them to an old chemical plant wired with C4, Victoria shoots him dead. But Vance isn't surprised by any of it, and Leo's file has been wiped clean. Mia realizes she's been used. Vance plans to turn Leo into a fallen hero and pin his death on Victoria with Mia's own gun. Mia tells Victoria why she's really there, and Victoria, heartbroken, throws her out. Vance puts Mia under house arrest and spends 48 hours trying to break her with a fake confession and the threat of life in prison. She holds out. And while she does, Victoria is quietly building the case against him, right up to the press conference where Vance means to call Mia guilty on live TV.",

    'universe-exe-devouring-the-world':
        "Everyone has a system. His eats the others.\nMoyue's story begins in a mine full of corpses. In his world everybody lives and dies by their systems, and he's the only one who has the System King, a system that swallows every other system it meets. Riots, trials and wars come at him one after another, and every enemy he beats feeds his system and makes him stronger. Then the dragon wakes, and Moyue finds out the world is far bigger and far more dangerous than he knew. The nobody from the mine is on his way to devouring the heavens.",

    'the-mafia-lost-his-queen':
        "He made her wait on his pregnant mistress. She lost their baby.\nOn their ninth anniversary, Dominic forces his wife Aria to wait hand and foot on his pregnant mistress. It costs Aria her own baby. Broken, she fakes her death and runs to London, where she falls in love with Caleb, the loyal man who keeps her safe. When Dominic finally sees what he's done, he drops his mistress and follows Aria halfway around the world, begging her to forgive him. He even turns up at her wedding to Caleb, bleeding and pleading. None of it matters. Aria walks away happy and leaves him on his knees, crying.",

    'no-taste-for-blood':
        "The café's famous drink is made with her blood.\nEveryone in Philadelphia loves the creamy house drink at the Crimson Café. The secret isn't milk. It's blood, taken every day from Seraphina, a girl her foster parents have held prisoner for years. When she finally breaks free, she runs straight into a vampire Duke. Ten years ago her blood saved his life, and he's been looking for her ever since. But when she holds out her wrist to him, something in her scent makes him go cold. The Vampire Tribunal hunts them down, with torture, burning pyres and old rituals. Seraphina's blood can heal, bring back the dead and stir the lingering spirit of the Progenitor. Still, she can't shake the feeling that someone is moving her around a chessboard. And she's right. A hidden mastermind lured her in, someone who knows her bloodline, her powers and the fate laid out for her. Is she the most valuable piece on the board, or the one who flips it over?",

    'medical-genius-is-not-someone-to-mess-with':
        "They broke the hand that could have saved him.\nGrace gave up her career for her family, then found out her husband Raymond was having an affair with Vanessa, and that they had a child together. The divorce left her with nothing. So she went back to medicine and came out on top, as the celebrated director of Apollo Medical Centre. Then Julian, Raymond's son, is brought in with an aortic aneurysm that could kill him. Grace agrees to operate, even after the way that family has treated her. They don't trust her, they hound her, and they injure her gifted surgical hand so badly it never recovers. The operation can't go ahead and Julian dies. Even then the family won't let up, until a showdown at a formal dinner brings out a shocking truth. Julian was never Raymond's son at all.",

    'racing-back-to-your-heart':
        "She left to save his racing career. Now he hates her for it.\nSix years ago Hazel found out she was pregnant, and she walked out on Jace without a backward glance so she wouldn't cost him his racing career. Now they've run into each other again. Everything Jace once felt for her has turned into hatred, and yet he'll use any ruthless trick he can to keep her close. Love or hate, he isn't letting her go a second time.",

    'double-marked-luna-s-revenge':
        "She's his Luna. He marked another woman.\nTalia is the Luna, and she has given everything to keep her husband Carter safe. Behind her back, he puts his mark on Ellie. Ellie schemes and Carter falls for every bit of it, until he ties Talia up in a sack and tortures her without any mercy. Barely alive, Talia rejects him. She leaves behind divorce papers and a moonstone necklace with the truth inside it. Then she's gone, and this time it's for good.",

    'from-doomed-baby-to-packs-darling':
        "She's a baby wolf in a book, and the family that took her in is doomed.\nMia wakes up as an abandoned wolf pup, inside the pages of a werewolf story, and the Hawthornes take her in. She knows how their story goes. Serena is going to destroy this whole family, so Mia makes up her mind to save them. What she doesn't know is that Marcus, Ethan and Ryan can hear every single thing she thinks. Her silent warnings keep Ryan's falcon alive and get Cole out of an ambush by three wolves. But they also tip Serena off that the family is listening in on Mia's head. As the Hawthornes rush off to save Cole, Serena locks Mia away, drains her Fortune and lifts a silver blade. Ethan makes it to the door. Is he in time?",

    'the-bastard-who-shook-olympus':
        "No god blessed him. Three of them trained him.\nEveryone laughs at Arion. He's a bastard with no blessing from any god, and they're sure he has no power at all. He enters the brutal trials at the Athenian Military Academy anyway, and he beats every rival in his way. That's when his three mentors show who they really are. They're Athena, Hephaestus and Prometheus, and they're the gods who picked him. Then the warlord chosen by Hades kidnaps Arion's mother. He has twenty days to get her back, and to do it he'll have to wake the blood of Ares inside him. Will that be enough against a warlord the gods have blessed?",

    'claimed-by-my-boyfriend-s-mafia-father':
        "A birthday surprise went wrong. She ended up with her boyfriend's father.\nRosy Walker is a college student without much money. A birthday surprise goes badly wrong, and she ends up in the arms of Leon Vittorio. Leon is a powerful mafia boss, and no man in New York is more dangerous. He also happens to be her boyfriend's father. It's one mistake she'll never be able to forget. Now secrets, betrayal and desire keep dragging them back together, and a forbidden love neither of them saw coming isn't going to let them go.",

    'exiled-bride-of-the-border-king-3':
        "She wins the battle by swinging an unconscious man.\nWhen Fuso attacks, Jenna Wade grabs Leonard Quinn, who is badly hurt and out cold, and swings him at the enemy like a weapon. By morning the battle has turned. Her ruthless tricks and her reforms build the New Army and wipe out the traitors, and before long she's running Southridge in everything but name. Leonard goes from fighting her to backing her up. Now Jenna is sailing for Fuso herself. What's waiting for her there?",

    'tamed-a-tyrant-became-his-love':
        "He raised the boy king. Now the boy king won't let him go.\nThe regent used to be a tutor in the modern world, and he's the one who raised a young tyrant into a king. On his wedding night, the tyrant pins his regent down. The teacher meant to tame him, but instead he's become the one weakness of a mad king, and all that taming ends with the teacher locked in a cage. Then rebels strike, and the regent steps in front of the king and takes a poisoned arrow himself. The king howls the truth. He never wanted the throne. He wanted him.",

    'ten-year-old-cowboy':
        "A legendary gunslinger dies, and comes back ten years old.\nJake is a legend with a gun, and he dies protecting Dylan, the ten year old son of gang leader Robert. Then his spirit ends up inside the boy's small, sickly body. He's stuck in a child's frame, but his quick mind and his deadly aim come with him. Robert has been murdered, and without him the Morrison Gang is in chaos. Dylan's treacherous uncle James is scheming to take control, and ruthless outlaws are closing in. Everyone is hunting a kid they think is harmless. Jake swore to protect this family and this gang, and a ten year old body isn't going to stop him keeping that promise.",

    'the-mafia-dongot-the-wrong-wife-so-i-ran-away-pregnant':
        'He went looking for the woman from that night and found her stepsister.\nAfter one night with Cole, a Mafia godfather, Helena runs off in disgrace. Cole goes looking for her, but his only clue comes from a delivery that went astray, and it points him to her stepsister Ivy instead. Ivy plays along and moves into his estate as Helena. Then Ivy finds out the real Helena is pregnant. She slips Helena a drug to end the pregnancy and fakes a pregnancy test of her own. But Helena drags the whole plot into the open in front of everyone, and now Cole has to dig through his own mistakes to find the woman he really loves.',

    'my-patient-is-a-mermaid':
        "His patient turned out to be a siren.\nDaniel is a psychotherapist in NYC with a strange gift. One touch and he can walk into a person's dreams. When he hypnotizes a soaking wet Elena, he discovers she's a siren from the deep sea. Siren law demands the Kiss of Oblivion, and it erases what each of them remembers. Three years on, at the edge of the ocean, Elena no longer knows who she is. But she still calls out one name, Daniel's, the only thing she hasn't forgotten. And that's all he needs to go after the love that was taken from them.",

    'the-bakery-queen-and-her-five-exes':
        "Five exes, five mafia families, and she has no idea.\nIrene bakes for a living, and she's got five exes who won't give up on her. What she doesn't know is that every one of them runs a mafia dynasty, and they're all rivals. So the five of them quietly team up as the Guardians Alliance and take turns, just for the chance to talk to her. It works fine, until somebody cheats and nearly sets off a war between all five families. Irene, meanwhile, still hasn't noticed a thing.",

    'my-brother-pushed-me-off-a-cliff-so-i-came-back-for-his-crown':
        "Her brother threw her off a cliff. She came back as a maid.\nPrincess Serlany is betrayed by her own brother Kairion, who pushes her off a cliff. The werewolf Greysorn saves her, and Sacred Blood brings her back to life. Serlany goes home disguised as a maid, and from there she uncovers Kairion's plot, a secret her father kept, and a war with the vampires. Kairion takes the crown for himself, but Serlany and Greysorn drag everything he's done into the light. And the throne he stole goes back to her.",

    'billionaire-alphas-fated-mate':
        "Left at the altar, then claimed by the strongest Alpha.\nShe's abandoned on her wedding day, in front of her whole family and every friend she has. Just as her life is caving in, she meets the most powerful Alpha around, a man nobody dares to argue with. What follows is a whirlwind romance nobody saw coming. Her ex fiance soon regrets what he did, but she's found a man who puts her above everything else. After a betrayal like that, trusting anyone again is hard. But the bond between them is no accident. She's his fated mate, and together they're going to shake up the whole supernatural order.",

    'the-return-of-the-amnesiac-heiress':
        "Her billionaire mother is searching for her. She doesn't remember who she is.\nYears ago Eun Seong's cold hearted grandfather made her choose, and to keep her mother alive she had to cut herself off from her. Twenty years on, her mother has become the billionaire head of Cheonhae Group, and she has never stopped looking for the child she lost. Eun Seong has no idea. Amnesia has taken her memories, and she's living a whole other life, stuck with a boyfriend who's cheated on her for five years. Now fate is slowly pulling mother and daughter back together, through a tangle of lies and betrayal. Will the heiress get back her name and the fortune that belongs to her?",

    'fifty-cents-to-find-my-billionaire-dad':
        "Her last two quarters reached her billionaire father.\nGemma was eight when the Carter family illegally bought her, and for seven years they abused her. One snowy night they throw her out of the house for taking a single piece of spare rib. Next to a dumpster she finds a missing child poster, and the face on it is hers. She spends her last two quarters calling the number, and the man she reaches is her real father, billionaire Ethan Whitmore. He races to find her. At the hospital, doctors find years of old injuries, and a DNA test confirms she's the daughter the Whitmores lost. The people who hurt her are made to answer for it, and Gemma finally goes home to the Whitmore penthouse in Manhattan, where her parents' love begins to heal her.",

    'the-stock-queen-returns':
        "She hid who she was and took his company public.\nLouise is Alice Group's stock market queen, famous for never making a wrong call. She married David in secret and helped take his company public. Then the scheming Carol got in the middle of it, and Louise swore she'd make them pay. She divorces David and lets the world see who she really is. And just then Simon walks into her life, the bright spot she never saw coming. So who does the stock queen choose in the end?",

    'undercover-in-the-mafia-queen-s-bed':
        "Her boyfriend sent her undercover. The mafia queen kept her alive.\nScarlett is a rookie cop, and her boyfriend talks her into going undercover to get close to the mafia queen Raven. Things go badly again and again, and every time Scarlett's life is on the line, it's Raven who steps in to protect her. Slowly Scarlett sees it. The woman she was sent to bring down is the only person who has ever really respected her and cared about her. She pulls herself free of her boyfriend's manipulation, and she and Raven team up to blow the whole conspiracy open and make their enemies pay.",

    'fated-at-first-sight':
        "Running from the Ravagers, she ran straight into her mate.\nIsabel is the fiery daughter of the Alpha of the Blood Moon Pack. She's on the run from the Ravagers when she crosses paths with Drake, a man she can't read at all. In the middle of all that chaos, she feels a pull toward him she's never felt before. Her brother Tristan, always protective, keeps getting in the way. Isabel is out to avenge her father's murder, and along the way she learns Drake is her destined mate. But right when she finds out, Tristan starts behaving strangely. But why?",

    'after-i-buy-sperm-from-a-billionaire':
        "She came to buy sperm. He offered it free, with a contract.\nTo grant her mother's last wish, she decides to buy some sperm and get pregnant. The man sitting across from her is far too handsome to be a donor. He looks her over, smiles, and says she can have it for nothing if she signs a contract with him. Then she reads it. They'd be raising the baby together. And the donor she picked is worth more than anyone else in LA. Did she just walk into the wrong room, or the right one?",

    'don-t-mess-with-the-driver-he-s-the-real-boss':
        "The taxi driver is really a top arms dealer.\nRoman is one of the biggest arms dealers there is, but he's back behind the wheel of a taxi. He's chasing a lead he can't confirm, looking for the woman who pulled him out of despair and was meant to be his. He ends up saving a girl named Amy, then marrying her mother, the CEO Charlotte, without realizing she's the very woman he's been searching for. At a banquet thrown by his brother Fitz, Fitz goes out of his way to humiliate Roman. What Fitz doesn't know is that his own boss is Charlotte, and she just married the man he's mocking.",

    'the-true-heiress-returns-the-evil-stepmother-begs-for-mercy':
        "They treated the true heiress like a nobody.\nEmily Reed is a cancer researcher, and when she comes home from Europe nobody gives her a second look. Her father's fiancee, the scheming Victoria Hart, humiliates her every chance she gets. Then it comes out that Emily is the real Reed heiress. She has the family trust, she has evidence nobody can argue with, and she has the medical legacy her mother left behind. She uses all of it to bring Victoria down, publicly and completely. By the end, the stepmother to be is the one begging.",

    'the-don-s-runaway-bride':
        "Called home after ten years just to give her fiance away.\nAlina's stepmother Katherine sent her away for ten years. Now Katherine wants her back, and only so she can hand Alina's engagement to the Mafia don Luke over to her half sister Isabella. On the way home, a dangerous stranger slips into Alina's room and pretends to be intimate with her so the men chasing him will move on. He wants to repay her, so she gives him a fake name to stay out of trouble. He tracks her down anyway, and when she tries to scare him off by dropping Luke's name, he kisses her. Then comes the engagement banquet. The bride they announce isn't Isabella. It's Alina, and the man who steps up to dance with her is someone she's already met.",

    'my-alien-life':
        "Taken by aliens and sold as a slave at eighteen.\nRachel is an eighteen year old human girl when aliens capture her and put her up for sale as a slave. Five powerful aliens buy her together. Christof, Damien, Evan, Bane and Kein call her Ciara and force themselves on her. When native females rescue her, she discovers she's pregnant. Then the tables turn. Now the five of them are the ones being sold, and Rachel buys them herself, to work for her rather than to own them. They take her home on a special pass, and she comes back with a daughter who has alien blood and a head full of memories of her life among them.",

    'they-took-everything-i-took-it-all-back':
        "Her own family came after her. She came back with evidence.\nXia Wan's estranged family won't leave her alone. They spread cruel lies about her, blackmail her, kidnap her and steal her business secrets. Xia Wan never loses her cool. She quietly collects proof of everything they've done and fights back the legal way, until every greedy relative and everyone who helped them is made to answer for it. Free of the nightmare at last, she climbs to the top of her career, finds real happiness and becomes the woman she always wanted to be.",

    'the-silent-wife-is-a-ruthless-avenger':
        "She isn't really mute. She's there for revenge.\nElza Stark enters a contract marriage with the tycoon Barron Drake, and she plays mute the whole time. It's her way into the elite circles where she can avenge the Schmidt family. On top of that she's hiding three secret identities. But Barron isn't fooled. He sees right through the act and falls in love with her anyway, and together they take down their enemies. What started as a marriage of convenience turns into a love that's real and here to stay.",

    'one-betrayal-one-night-with-my-boss':
        "She caught her fiance with her cousin. That night she slept with her boss.\nBlair Warner is a polished executive secretary who always puts everyone else first. Then she catches her fiance cheating with her own cousin, and she leaves. She hides out at the office, and that's where she and her boss Roman Kingston spend one reckless night together. He's a powerful CEO who keeps his own heart locked up tight. It starts as revenge, but it quickly turns into something neither of them can deny. Roman stands between Blair and her manipulative family, and his scheming ex wife too. What scares Blair most is handing her independence over to another man. So when Roman proposes, she has to decide whether trusting him means giving herself up, or finally discovering who she really is.",

    'married-my-ex-s-dad-now-i-m-mafia-queen':
        "Dumped at the altar, she married the groom's father.\nAlex leaves Isabella standing at the altar. To keep her pride and get even, she marries his father instead. Damien is the most powerful mafia boss there is. Once she's his wife, she puts her sharp mind and her growing power to work. She tears Alex down, takes back the fortune that was stolen from her mother and crushes everyone in the family who betrayed her. The abandoned bride becomes a mafia queen. And the cold contract marriage she made with Damien slowly turns into a love that's real, fierce and impossible to stop.",

    'married-the-brother-but-slept-with-the-don':
        "Married to one Caldwell brother. One night with the other.\nFaye is forced to marry Joshua Caldwell, a coward who can't stay faithful. At a gala someone drugs her, and she spends the night with a stranger before running off. The stranger is Anthony Caldwell, the Don the whole city bows to. He knows exactly who she is. He shows her how Joshua has been betraying her, and now she's part of a dangerous game. Faye fights back under her composer name Iris, while Anthony pushes Joshua out bit by bit. Anthony can't stay away from her, because she's the only one who can calm his sensory seizures. Then Faye cracks the files on her father's death and finds Anthony's signature all over the explosion that wiped out her family. Revenge or love, she can't have both.",

    'love-after-divorce-my-ex-husband-wants-me-back':
        "Three years of being ignored, and she's done.\nAdeline gave Brandon everything for three years of a marriage with no love in it, and all she got back was his indifference. So she leaves. She starts over as an independent interior designer, the side of her Brandon never bothered to understand. Without her, Brandon slowly notices everything she used to do for him, all the care and company and quiet sacrifice he'd always taken for granted. When a business project throws them back together, the shy wife who stayed home waiting for him is gone. In her place is a confident professional who's moving on. Brandon is full of regret now, but getting her back is going to take a lot more than being sorry.",

    'the-king-s-physician-bride':
        "The king's problem isn't impotence. It's poison.\nHilwyn is a healer of noble birth who hates everything the aristocracy expects of her. Her newest patient is King Lucien, and the chronic poisoning he's suffering from has been misread as impotence. To keep his secret and get everyone off his back about marrying, Lucien proposes a contract marriage. The terms are eighty thousand gold coins, separate lives, and neither of them meddling. They bicker constantly, but there's a real bond growing under it. Hilwyn puts everything on the line to clear the poison from his body and proves herself in front of the royal court, and Lucien goes from ice cold to fiercely possessive. Then he rips up the contract and tells her how he feels. Will she give up the freedom she fought so hard for?",

}

FACTS = {
    'mr-williams-madame-is-dying': "Thumbs up for this piece! How could he be so heartless and treat his wife rudely? Madison Evans loved Hunter Williams for 16 years, but was asked to be his mobile blood bank for White Moonlight, Andrea David. Hunter Williams destroyed her family, just to make room for Andrea David. A cancer physical examination report made Madison Evans see his cold-blooded and ruthless true face. When she finally didn't love Hunter Williams, she found that she had been infatuated with the wrong person for 16 years.",
    'escape-with-boss-s-baby': "Hermione Garcia is a famous computer genius and the heiress to the Garcia family,the wealthiest family in the South. She falls in love with Chris Evans, the President of LM Corporation, after he saves her at a banquet three years ago. To seek a genuine connection, Hermione conceals her identity and takes on the role of Chris's chief secretary, secretly dating him for three years.",
    'ruling-over-all-i-see': "Soon after unemployed graduate Judah Shaw finds himself a penniless scholar in Qirelia, he is forced by the system to win his wives' affection, despite their marriages being purely convenient. To his surprise, among them are a princess, a general's daughter, and a merchant heiress, who bring him not only fortune but also a future brighter than he ever imagined.",
    'no-escape-as-the-dragon-king-s-mate': "On a rainy Valentine's night, Lydia, a human nurse, saves a bleeding stranger, only to discover he's Soren—the ruthless Dragon King. His ultimatum is brutal: become his fated mate or die. Dragged into a lethal supernatural world, Lydia finds her defiance melting into burning desire as she glimpses the vulnerable heart beneath the tyrant's scales. With the 30-day contract ending, will she claim her freedom, or surrender to the Dragon King forever?",
    'i-m-nothing-but-a-mortal': "Ian Colt, a genius Jade Sect apprentice, ascends to the Sky Realm after just 20 years of cultivation. Believing there's nothing more to teach him, his mentor, Sean Judd, tricks Ian into leaving for the mortal realm.There, Ian encounters Jim Cole, whose life is on the line. Despite the efforts of three skilled doctors, none can save him, leaving his daughter, Sue Cole, desperate. Ian successfully saves Jim.",
    'taming-the-mafia-boss-he-s-mine-now': 'In Taming the Mafia Boss He\'s Mine Now movie: Leah, the daughter of the Cruz family, appears to be a "fierce delicate flower" who throws money around in nightclubs and acts in a cynical way on the surface. In reality, she is a down-and-out heir whose power was seized by her stepfather. During a misunderstanding, Leah, fueled by alcohol, generously spent a large sum of money and "kept" Allen, the "bankrupt noble young master" — little did she know that this man whom she could pin against the wall and whose shirt she tore open was actually the person in power of the Smith family, a mafia clan. A misunderstanding about "keeping someone" kicks off: He can wear an apron and cook dinner, and when she is framed by her stepsister Lisa, he will press the muzzle of a gun against the forehead of the enemy. She once thought that he was a person in distress who needed her protection, but when she herself was in trouble, she discovered that the overwhelming power of the Smith family could be casually wielded by him — she thought she was the hunter, but she didn\'t know that from the moment she pinned him against the locker, he was willing to shed all his disguises just for her... Let\'s see how Leah makes a comeback from the "sugar mommy" to become the wife of the mafia boss, staging an ultimate love story between two powerful individuals where "You hide your power to protect my vulnerable part, and I shed my thorns to give you my sincere heart."',
    'spoiling-my-sweet-wife-to-her-core': "On the day of the engagement, Anne Miller was framed in a cheating scandal. Her fiance, Shawn Smith, was furious and vowed never to marry Anne. She knew that her pretentious step-sister, Elsa Miller, was the mastermind behind it all. Shawn believed entirely in Elsa's lies. Devastated, Anne died with resentment and regret.A soul of a heroine—who shared the same name as Anne—transmigrated into Anne Miller's body and swore to avenge her.",
    'food-love-robots': 'Seven years after her soulmate Elliot’s sudden death, Lily’s quiet Christmas is upended when her and Elliot’s son Evan’s wish comes true: Elliot returns. But this Elliot is a humanoid robot, programmed with her late boyfriend’s memories. As Lily’s heart reopens to love, she must navigate the charming chaos of family, romance, and technology, discovering whether this second chance at happiness is real or just a perfect AI program.',
    'this-time-i-choose-mr-mafia': 'Stella was destroyed by the man she loved and his mistress. Her family, her name, her life were all gone. But fate rewinds the clock. Back at the husband-selection gala, she ditches her ex and shocks everyone by choosing Adrian, the ruthless mafia king no one dares to cross. Adrian gives her power, protection, and passion — until she discovers his secret: he wasn’t her weapon… he was her shield, all along.',
    'hero-husband-s-apocalypse-harem': "Years after the world is ravaged by an apocalypse, Sam is a nobody struggling to survive until a system appears and changes his life. In order to protect his own life, Sam must learn the true meaning of bravery when he's tasked with safeguarding the lives of three beautiful women, all of whom eventually choose to become his wife.",
    'one-night-with-the-dragon-lord': "To keep her mother alive, Isolde marries the Dragon Lord in her sister's place — a monster who shreds every bride. She takes one free night first, with a stranger. Next morning he's on the throne. Her touch alone calms his curse, so she stays to use his army. Vael knows, and allows it. Then she learns her father cast the curse, and Vael carries her poison. He offers a blade. She takes the crown.",
    'fight-for-me-prison-king': 'Reid Donovan sacrifices everything by taking the blame for the woman he loves, only to believe she abandoned him during his seven years in prison. Hardened into the feared Prison King, Reid returns seeking a new life—unaware that the truth behind her silence will change everything.',
    'harvest-of-ambition-a-ceo-s-odyssey': 'After five years of working hard in the city, Derek Larsen becomes the CEO of Gilmore Group and orders the acquisition of all unsold vegetables in Ashville. Unexpectedly, his actions are met with doubt and mockery from his family and acquaintances instead of appreciation. His wife, Nina Hart, arrives to meet him in her secret lover, Simon Hall’s, car and claims that the acquisition is Simon’s deed.',
    'married-my-sister-s-groom-and-make-him-regret': "To save her dying grandmother, Hannah agrees to pose as her twin sister for three years, enduring a loveless marriage, her husband's cruelty to her, and obsession with his first love. When the deal finally ends and she walks away with the money she deserved, the man who once discarded her realizes too late what he's lost.",
    'her-journey-beyond-the-script': 'Charlotte Chase has been whisked into a romance novel! Unfortunately, she takes the role of the antagonist whose every move and decision is rife with… well, stupidity. It is apparent that "Charlotte Chase" was only written to show how much better the Female Lead is. Her inescapable ending, as decided by the book, is death.Charlotte knows she has to get out of the Male Lead, Fred\'s, life before she is dragged into a whirlwind of power plays and conspiracies.',
    'don-s-daughter-doesn-t-need-a-new-mother': "As Don's mysterious heiress, Loretta is stepping out of shadows after she's had enough of humiliation from her father's mistress. The moment her true identity is revealed, she'll expose the traitors and corruption within the mafia house, and make everyone who crossed her family pay.",
    'the-mafia-boss-is-addicted-to-my-touch': "Six years ago, blindfolded Haley was bedded by Mafia boss Lester. Now ruined by her cheating husband Bill, she signs a healing marriage contract with Lester. Finding out Lester's daughter is her lost newborn secretly sold by Bill, Haley starts a thrilling new life -- slapping down the toxic exes while falling deeply in love with Lester.",
    'when-she-stopped-chasing-his-love': 'Camellia was born with a gift for piano, but after losing hearing in one ear, her family gave up on her. To keep chasing music, she accepted Dylan’s help—and became the stand-in for the woman he truly loved: her sister, Malory. Three years later, Malory returns. Camellia finally sees the truth and decides to leave. But when she walks away, a mysterious music producer sees her talent. And Dylan begins to realize… he lost the wrong woman.',
    'my-gynecologist-is-the-mafia-boss': 'Trapped in a humiliating, sexless marriage, Jenna finds hope in an unexpected place: her mysterious doctor, Wayne, who’s actually ruthless Mafia King. Taking her as his housemaid, he turns a fragile ex-wife into his feared Mafia Queen, destroying everyone who ever wronged her.',
    'reborn-with-my-son-married-to-the-snake-king': 'Murdered by her sister and husband, Serena is reborn at the Husband-Choosing Rite. She rejects the treacherous Wolf Heir for Soren, a Serpent Lord rumored brutal and penniless—but actually gentle, devoted, and the realm’s richest man. To protect her child, family, and every clan, Serena unleashes ruthless revenge.',
    'from-trash-awakener-to-ocean-god': "Transmigrated into a monster-infested Ocean Age, Aimar’s SSS-grade Pandora's Box is mocked as worthless trash. Dumped and expelled, he unlocks the artifact—awakening Poseidon and ten ancient gods. Now, the outcast rules the seas, forcing every enemy to bow at his feet.",
    'he-begs-for-the-heart-he-broke-120-times': "After 120 failed confessions, a tragic fall erases Leona's ten-year love for Everett. Driven by envy, Everett’s ex frames, burns, and imprisons her, but gentle Shane stays by Leona’s side. As Leona thrives, the evil schemes unravel. Everett goes mad with regret, only to realize Leona has moved on.",
    'from-zero-to-hero-the-x-ray-eyed-surgeon': 'Bullied and broke, intern doctor Tristan Rourke gains X-ray vision after an accident. Now he can see hidden diseases, expose every scheme, and save lives no one else can. From nobody to medical legend, Tristan even foresees a deadly earthquake—and chooses saving the world over wealth.',
    'her-and-her-a-dangerous-affair': 'Police prodigy Mia goes undercover at the 15th Precinct, tasked by Internal Affairs Director Vance to gather evidence of corruption against Captain Victoria. From day one, Mia endures Victoria\'s cold hostility and harsh treatment, yet amidst the friction, she finds herself drawn to the captain\'s unyielding resolve and hidden sense of justice. During a dock raid, Victoria takes a bullet for Mia—an act that shatters Mia\'s emotional defenses. Shortly after, a gallery murder rocks the city: the victim is none other than the Oversight Director\'s only son. As Mia and Victoria join forces to investigate, they uncover a web of deceit—and discover that their seemingly reliable colleague, Leo, is the real mole. Leo lures them to an abandoned chemical plant, rigged with C4 explosives. In the ensuing firefight, Victoria kills him. The case appears closed, but when Mia reports to Vance, she senses something deeply wrong—he shows no surprise at any of the twists, and Leo\'s personnel file has been systematically erased. Mia realizes she has been a pawn all along. Vance\'s true plan is to rebrand Leo as a ""heroic undercover agent"" who died in the line of duty, and use Mia\'s own firearm as evidence to frame Victoria for murder. Torn between duty and conscience, Mia confesses her undercover identity to Victoria. Devastated and betrayed, Victoria cuts all ties and expels her from the precinct. Vance immediately places Mia under house arrest, threatening her with a forged confession and life imprisonment. Under 48 hours of relentless psychological pressure, Mia refuses to break. Meanwhile, Victoria works in secret, gathering irrefutable proof of Vance\'s collusion with the dark web and his fabrication of evidence. At a live televised press conference where Vance intends to pronounce Mia guilty, Victoria storms in with federal agents and exposes his crimes on air. Vance is arrested, and Mia is publicly exonerated.',
    'universe-exe-devouring-the-world': 'Moyue starts in a corpse-strewn mine. In a world ruled by systems, he alone holds the "System King"—devourer of all systems! Riots, trials, wars... enemies\' systems fuel his rise. When the dragon awakens, Moyue finds a vaster, deadlier world. Watch a king rise from nothing to devour the heavens!',
    'the-mafia-lost-his-queen': "On her ninth anniversary, Aria's mafia husband, Dominic, forces her to serve his pregnant mistress, leading to a tragic miscarriage. Heartbroken, Aria fakes her death and escapes to London, falling for Caleb, her loyal protector. When Dominic realizes his mistake, he abandons his mistress and chases Aria across the world, begging for mercy. But at her wedding to Caleb, Dominic’s bloody pleas mean nothing. Aria happily walks away, leaving her toxic ex kneeling in his own tears.",
    'no-taste-for-blood': 'Philadelphia’s popular Crimson Café is known for its creamy signature drink. Its secret is not milk, but a young girl’s blood collected daily in a crystal cellar bowl. Seraphina, imprisoned for years by her foster parents, escapes and runs into a vampire Duke. She saved his life with her blood ten years ago, and he has searched for her ever since. But a strange scent chills him when she offers her wrist. The Vampire Tribunal comes for them with torture, pyres and ancient rites. Her blood heals and resurrects and resonates with the Progenitor’s lingering spirit. Still, she suspects she is just a pawn on someone’s chessboard. While fighting vampire nobles, she discovers a secret mastermind drew her into a trap. This entity knows her lineage, powers and preordained fate. Will she be the board’s most valuable piece, or the one to overturn everything? Between blood slave and queen lies great power, along with a lie she has never questioned.',
    'medical-genius-is-not-someone-to-mess-with': "After sacrificing her career for her family, Grace discovered her husband Raymond's affair with Vanessa and their love child. Forced into a destitute divorce, she made a triumphant return to medicine, becoming the renowned director of Apollo Medical Centre. When Raymond's son, Julian, was admitted with a critical aortic aneurysm, Grace agreed to operate despite their abuse. Raymond's family, distrustful of her skills, harassed her and permanently injured her gifted surgical hand. This prevented the life-saving surgery, leading to Julian's death. Even afterwards, the family continued their torment. During a confrontation at a formal dinner, a shocking truth emerged: Julian was not Raymond's biological son!",
    'racing-back-to-your-heart': "Six years ago, Hazel was pregnant. She left without looking back. She wanted to protect Jace's racing career. Six years later, they meet again. Jace's love has turned to hatred. He uses every ruthless trick to keep Hazel by his side.....",
    'double-marked-luna-s-revenge': "Luna Talia gave everything to protect her husband, Carter, but he secretly marked Ellie. Manipulated by Ellie's scheme, he stuffed her in a sack, and tortured her without mercy. Clinging to her last breath, Talia rejected him and left behind a moonstone necklace carrying the truth… and a set of divorce papers. Then she walked away. For good.",
    'from-doomed-baby-to-packs-darling': "Mia wakes inside a werewolf novel as an abandoned pup, rescued by the Hawthornes—a family doomed to be destroyed by Serena. She vows to save them, unaware that Marcus, Ethan, and Ryan hear her every thought. Her warnings save Ryan's falcon and spare Cole from a three-wolf ambush—but also reveal to Serena that they can hear Mia's thoughts. While the Hawthornes race to Cole, Serena locks Mia in, drains her Fortune, and raises a silver blade. Ethan reaches the door—but can he save Mia in time?",
    'the-bastard-who-shook-olympus': 'Mocked as a powerless bastard with no divine blessing, Arion enters the brutal trials of the Athenian Military Academy. But when he defeats every rival, his three mentors reveal themselves as Athena, Hephaestus, and Prometheus—the gods who chose him. Then Hades’ chosen warlord kidnaps his mother. With only 20 days to save her, Arion must awaken the blood of Ares. Can he become strong enough to defeat a god-blessed warlord?',
    'claimed-by-my-boyfriend-s-mafia-father': 'A poor college student. A powerful mafia boss. One unforgettable mistake. Rosy Walker’s life changes forever when a birthday surprise goes wrong and leads her into the arms of Leon Vittorio — her boyfriend’s father and the most dangerous man in New York. Now, with secrets, betrayal, and desire pulling them together, there’s no escaping the forbidden love they never saw coming.',
    'exiled-bride-of-the-border-king-3': 'Fuso attacks, and Jenna Wade swings the badly wounded, unconscious Leonard Quinn like a human weapon—turning the tide overnight. Her ruthless tricks and reforms forge the New Army, crush traitors, and make her Southridge’s uncrowned ruler as Leonard Quinn shifts from opponent to backup. Now she sets sail for Fuso—what awaits her there?',
    'tamed-a-tyrant-became-his-love': "A young tyrant pins his regent on his wedding night. The regent, once a modern tutor, raises him into a ruler but becomes the mad king's only weakness. Taming ends with the teacher caged. When rebels attack, he takes a poisoned arrow meant for the king, who howls that he wanted him, not the throne.",
    'ten-year-old-cowboy': "In the lawless Wild West, legendary gunslinger Jake dies shielding gang leader Robert's ten-year-old son Dylan. His spirit is unexpectedly transferred into the boy's frail body. Trapped inside a child's frame, he retains his sharp wits and peerless marksmanship. With Robert murdered, the Morrison Gang falls into chaos; treacherous uncle James plots to seize power while ruthless outlaws close in. Hunted and underestimated, Dylan carries Jake's oath to protect his family and the gang.",
    'the-mafia-dongot-the-wrong-wife-so-i-ran-away-pregnant': 'Helena fled in disgrace after a one-night stand with Mafia godfather Cole. Based on the information from a lost delivery, Cole mistakenly identified her stepsister Ivy as Helena. Ivy impersonated her and checked into the estate, but unexpectedly learned that Helena was pregnant. Ivy fed Helena an abortifacient and forged a pregnancy test report. Helena exposed the conspiracy in public, and Cole had to personally find the woman he truly loved amidst his mistakes.',
    'my-patient-is-a-mermaid': 'Daniel, a NYC psychotherapist who enters dreams by touch, hypnotizes drenched Elena and discovers she\'s a deep-sea siren. Siren law forces the "Kiss of Oblivion," which erases both their memories. Three years later, by the ocean, Elena has lost her identity but still calls out Daniel\'s name—the only memory she keeps—spurring him to reclaim their stolen love.',
    'the-bakery-queen-and-her-five-exes': 'Baker Irene has no idea her five persistent exes lead rival mafia dynasties. They secretly form a "Guardians Alliance," taking shifts just to talk to her—until cheating nearly ignites a five-family mob war, while she remains clueless.',
    'my-brother-pushed-me-off-a-cliff-so-i-came-back-for-his-crown': "Betrayed by brother Kairion, pushed off a cliff—Princess Serlany is saved by werewolf Greysorn. Sacred Blood revives her; she returns as a maid, uncovering Kairion's plot, her father's secret, and the vampire war. As he seizes the crown, Serlany and Greysorn expose his crimes and reclaim her throne.",
    'billionaire-alphas-fated-mate': 'Billionaire Alpha’s Fated Mate follows the heart-wrenching journey of a woman left at the altar, humiliated before her family and friends. Just as her world crumbles, she encounters the most powerful Alpha in the territory, a man whose presence commands absolute authority. This unexpected meeting sparks a whirlwind romance that defies all expectations. While her former fiancé regrets his betrayal, she discovers that her true destiny lies with a protector who values her above all else. In this world of shifting loyalties and deep passion, she must learn to trust again. Their bond is not just a coincidence but a fated connection that will change the supernatural hierarchy forever. Experience a story of healing and profound love as she rises from the ashes of her past to claim her rightful place by his side.',
    'the-return-of-the-amnesiac-heiress': "The Return of the Amnesiac Heiress follows Eun Seong, a young woman forced into a heartbreaking choice years ago. To save her mother's life, she sacrificed their bond at the demand of her cold-hearted grandfather. Now, two decades later, her mother has risen to become the powerful Billionaire leader of Cheonhae Group, desperately searching for the child she lost. However, Eun Seong is living a completely different life, stripped of her memories by amnesia. She remains trapped in a toxic relationship with a boyfriend who has been unfaithful for five years. As fate begins to pull the mother and daughter back together, Eun Seong must navigate a web of lies and betrayal. Will she reclaim her true identity and the fortune that is rightfully hers, or will her past remain a mystery forever? This emotional journey explores the price of sacrifice and the power of blood ties.",
    'fifty-cents-to-find-my-billionaire-dad': "At eight, Gemma was illegally bought by the Carter family and abused for seven years. One snowy night, she was thrown out for taking a piece of spare rib. By a dumpster, she found a missing-child poster with her own face on it. With her last two quarters, she called the number listed and reached her biological father, billionaire Ethan Whitmore. He rushed to find her, and a hospital exam revealed years of old injuries. A DNA test confirmed with 99.9999% certainty that Gemma was the Whitmore family's long-lost daughter. As her abusers face justice, Gemma returns to her family's Manhattan penthouse and begins healing in the love of her parents.",
    'the-stock-queen-returns': 'Louise, the \'never-wrong\' stock market queen of Alice Group, secretly married David and helped his company go public. But when the scheming Carol interfered, Louise vowed revenge—divorcing David and revealing her true identity. Then came Simon, her unexpected light. In the end, her choice was...?"',
    'undercover-in-the-mafia-queen-s-bed': 'Rookie police officer Scarlett is manipulated by her boyfriend into going undercover to approach mafia queen Raven. Yet as Raven repeatedly protects her through one life-threatening crisis after another, Scarlett realizes that her supposed target is the only person who truly respects and cares for her. She gradually breaks free from emotional manipulation, joins forces with Raven to expose the conspiracy and punish their enemies.',
    'fated-at-first-sight': "Isabel, the hot-headed daughter of the Blood Moon Pack's Alpha, encounters the enigmatic Drake while fleeing from Ravagers. Amidst the chaos, she feels an unfamiliar attraction, complicated by her protective brother Tristan's interference. As she seeks vengeance for her father's murder, Isabel uncovers that Drake is her destined mate, just as Tristan begins to act strangely…",
    'after-i-buy-sperm-from-a-billionaire': '"So, how much is your sperm?" "Excuse me?" I looked at the man across from me, wondering why someone so handsome would be donating sperm. But it didn\'t matter—I just wanted to buy some sperm, get pregnant, and fulfill my mother\'s last wish. He gave me a once-over, then smiled. "I can give it to you for free, as long as you agree to sign a contract with me." Wait, what? The contract says we’d co-parent the baby? And this guy turns out to be the richest man in LA? I think I might’ve walked into the wrong place…',
    'don-t-mess-with-the-driver-he-s-the-real-boss': "Driven by an unconfirmed lead, top arms dealer Roman returns as a taxi driver to find his destined love who saved him from despair. He saves Amy and marries her mother, CEO Charlotte, not knowing she's his savior. At brother Fitz's banquet, Fitz humiliates Roman, but Fitz's boss turns out to be Charlotte, the woman who just married Roman.",
    'the-true-heiress-returns-the-evil-stepmother-begs-for-mercy': "Cancer researcher Emily Reed returns from Europe, only to be written off as a nobody and brutally humiliated by her father's scheming fiancée Victoria Hart. When her identity as the true Reed heiress is exposed, she uses the family trust, ironclad evidence, and her mother's medical legacy to take Victoria down in a very public, total reckoning.",
    'the-don-s-runaway-bride': "Alina was exiled for ten years by her stepmother Katherine. When Katherine summons her, it was to make her give her engagement with Mafia don Luke to her halfsister Isabella. On her journey home, a dangerous stranger gets into her room and faked intimacy with her to hide from pursuers. He proposed to repay her, but she gave him a fake name to avoid trouble. But he still found her, and still kissed her when she used Luke's name to scare him. On the engagement banquet, the name announced was not Isabella, but Alina, and that man showed up to dance with her. He was Luke himself.",
    'my-alien-life': 'Rachel, an 18‑year‑old human girl, is captured by aliens and sold as a slave. Five strong alien males—Damien, Evan, Bane, Kein, and Christof—buy her and rename her Ciara. They force themselves on her. She is desperate at first, but her body still reacts. When she is rescued by native females, she finds herself pregnant, and the five males are put up for sale. She buys them—not as slaves, but as workers—and they escort her home through a special pass. She returns home with a daughter who carries alien blood, along with memories of her life among the aliens.',
    'they-took-everything-i-took-it-all-back': 'Faced with relentless attacks from her estranged family—including spreading hurtful lies, blackmail, abduction, and stealing business secrets—Xia Wan remained composed. She meticulously gathered evidence and fought back using the law, ultimately ensuring that her avaricious family members and their accomplices were brought to justice. Freed from the nightmare of her past, Xia Wan reached the peak of her career, found happiness, and became the person she always dreamed of being.',
    'the-silent-wife-is-a-ruthless-avenger': 'Elza Stark marries tycoon Barron Drake under a contract, faking muteness to infiltrate the elite and avenge the Schmidt family. She hides three secret identities. Barron sees through her act, falls for her, and crushes their enemies together. The two move from a marriage of convenience to true, lasting love.',
    'one-betrayal-one-night-with-my-boss': 'Blair Warner, a polished executive secretary, has always put others first, until she walks in on her fiancé cheating with her cousin and walks away. Seeking refuge in her office, she shares a reckless night with her boss, Roman Kingston, a powerful CEO hiding his own guarded heart. What begins as revenge becomes undeniable, as Roman protects her from her manipulative family and his calculating ex-wife. But Blair must confront her deepest fear, that is surrendering her independence to another man. When Roman proposes, she must decide if trusting love means losing herself, or finally finding who she truly is.',
    'married-my-ex-s-dad-now-i-m-mafia-queen': "Isabella is dumped at the altar by her fiancé Alex. To save her dignity and get revenge, she marries his father, Damien, the most powerful mafia boss. After the marriage, with her sharp wit and growing influence, she tears down her ex, reclaims her mother's stolen fortune, crushes family betrayals, and rises from an abandoned bride to a mafia queen. Along the way, a cold contract marriage with Damien turns into something real, a fierce, unstoppable love.",
    'married-the-brother-but-slept-with-the-don': 'Faye was forced into a marriage to the cowardly, unfaithful Joshua Caldwell. Drugged at a gala, she spent a night with a stranger and fled. That stranger was Anthony Caldwell, the Don who made the city kneel. He recognized her, exposed Joshua\'s betrayal, and pulled her into a dangerous game. Faye fought back as the composer "Iris", while Anthony get rid of Joshua step by step. Anthony was drawn to her, she was the only one who calmed his sensory seizures. But when she decoded her father\'s death files, she found the explosion that destroyed her family bore Anthony\'s signature. Now she\'s caught between revenge and a love that burns.',
    'love-after-divorce-my-ex-husband-wants-me-back': 'After three years of a loveless marriage, Adeline decides to leave Brandon. She once devoted herself to him, endured his indifference, but all her patience and love went down the drain. After leaving him, Adeline relauches her career as an independent interior designer, a part of her that Brandon never really understood. Meanwhile, Brandon slowly realizes how much he needs Adeline when all the care, companionship, and quiet sacrifices he once took for granted suddenly disappear. When they unexpectedly meet again through a business project, he no longer sees the timid wife who waited for him at home. She is professional, confident, and determined to move forward. Brandon begins to regret his past choices, but winning her back requires more than that.',
    'the-king-s-physician-bride': 'Hilwyn, a noble healer who despises aristocratic constraints, treats King Lucien for a chronic poisoning that has been mistaken for impotence. To protect his secret and avoid marriage pressure, Lucien proposes a contractual marriage, eighty thousand gold coins, no interference, and separate lives. But their constant bickering masks an unexpected bond. As Hilwyn risks everything to detoxify him and proves her skill before the royal court, Lucien moves from cold indifference to possessive devotion. When he tears up their contract and confesses his heart, Hilwyn must choose between her hard-won independence and a love she never anticipated...',
}
