# -*- coding: utf-8 -*-
"""Batch generated by caption_pipeline.py next.

Fill CAPTIONS. Each value is HOOK newline BODY newline ASIDE.
  HOOK  one sentence, leads as the subheading
  BODY  the synopsis, in our words, ONLY facts from the source below
  ASIDE us talking to the reader, must stand alone with the rest covered

FETCH REQUIRED means there is no fact source on disk. Read the platform page
first, paste what it says into FACTS below, then write. Never write from the
title alone.
"""

CAPTIONS = {

    # 522.7M   The Double Life of My Billionaire Husband
    # FACTS: ReelShort's breakout megahit, 500M+ views on platform.
    'the-double-life-of-my-billionaire-husband':
        "The marriage was supposed to be paperwork.\n"
        "Natalie and Sebastian marry on paper only, strictly business with no "
        "feelings involved. But the arrangement doesn't stay that simple. Her family "
        "is quietly plotting her downfall, and the man she married is living a life "
        "she knows nothing about.\n"
        "We love a marriage of convenience that refuses to stay convenient.",

    # 462.8M   Found A Homeless Billionaire Husband for Christmas
    # FACTS: Humiliated by her fiance, Victoria marries Simon, a homeless man she had been helping, u
    # FACTS: naware he is the billionaire CEO of the country's top Savage Group, then reclaims her di
    # FACTS: gnity back home in Texas.
    'found-a-homeless-billionaire-husband-for-christmas':
        "She married him when he had nothing.\n"
        "Humiliated by her fiance, Victoria marries Simon, a homeless man she had "
        "been quietly helping. She has no idea who he really is. Then she takes him "
        "home to Texas and starts taking back everything she lost.\n"
        "A billionaire is the best kind of gift.",

    # 460.0M   True Heiress vs. Fake Queen Bee
    # FACTS: Wealthy teen Hailey hides her identity at a public school while the maid's daughter Cand
    # FACTS: ice poses as the Kaplan heiress, rising to the top of the social hierarchy as Hailey is 
    # FACTS: bullied at the bottom.
    'true-heiress-vs-fake-queen-bee':
        "One of them is lying about who she is.\n"
        "Hailey is a wealthy teenager who keeps that very quiet at her new public "
        "school. Meanwhile the maid's daughter Candice is passing herself off as the "
        "Kaplan heiress and climbing straight to the top, while Hailey takes the "
        "bullying at the bottom.\n"
        "We would never turn that down.",

    # 416.6M   How to Tame a Silver Fox
    # FACTS: Yale senior Harper Reeves plots Operation Seduction to drive out her dad's overprotectiv
    # FACTS: e best friend and business partner Chris Collins, until his rescues make her fall for th
    # FACTS: e silver fox herself.
    'how-to-tame-a-silver-fox':
        "The plan was to get rid of him.\n"
        "Harper Reeves is a Yale senior with an overprotective problem: her dad's best "
        "friend and business partner Chris Collins. So she launches Operation "
        "Seduction to drive him out. Nothing goes to plan.\n"
        "Nobody is immune to a silver fox.",

    # 413.9M   My Sister Is the Warlord Queen
    # FACTS: At her sister's engagement party, undercover agent Catherine is ridiculed as a janitor u
    # FACTS: ntil her sister is betrayed, and Catherine reveals herself as the Warlord Queen.
    'my-sister-is-the-warlord-queen':
        "They think she cleans floors for a living.\n"
        "Catherine turns up at her sister's engagement party and gets treated like "
        "the hired help. She lets them think it. Then her sister is betrayed, and "
        "Catherine stops pretending.\n"
        "We live for the moment they realise who they just insulted.",

    # 397.9M   Ms. CEO's Baby Daddy Is the Merchant of Death
    # FACTS: Connor Reed, the most powerful arms dealer in the world, saves a Charlotte Hayes and spe
    # FACTS: nds the night with her while he is undercover.
    'ms-ceo-s-baby-daddy-is-the-merchant-of-death':
        "He was undercover. She had no idea.\n"
        "Connor Reed is the most powerful arms dealer in the world, and he is deep "
        "undercover when he saves Charlotte Hayes. They spend one night together, and "
        "she has no idea what he does or who he is.\n"
        "One night, a secret baby, and a genuinely dangerous man.",

    # 358.6M   Breaking the Ice
    # FACTS: Hockey hopeful Easton wins a scholarship and his mother pressures pregnant Caroline to g
    # FACTS: et rid of the baby; love wins and the couple reunites.
    'breaking-the-ice':
        "The scholarship arrives at the worst possible moment.\n"
        "Easton is a hockey hopeful who finally wins his scholarship. His girlfriend "
        "Caroline is pregnant. His mother has very firm ideas about what should "
        "happen next.\n"
        "Sports romance with a lot of heart.",

    # 316.3M   Move Aside! I'm the Final Boss
    # FACTS: Kingsley, secret King of King's Corps and the richest man on Earth, returns from war to 
    # FACTS: be dumped as a nobody. Regret follows.
    'move-aside-i-m-the-final-boss':
        "The nobody they threw away owns everything.\n"
        "Kingsley comes back from war and is dumped for being a nobody. What none of "
        "them know is that he runs King's Corps, and there is no richer man on "
        "Earth.\n"
        "They are all about to eat their words.",

    # 277.2M   Money, Guns, and a Merry Christmas
    # FACTS: A defense-industry CEO mistaken for a broke salesman contract-marries Iris and turns the
    # FACTS:  tables on her sneering relatives at Christmas dinner.
    'money-guns-and-a-merry-christmas':
        "Everyone at that table has him completely wrong.\n"
        "A defence industry CEO gets mistaken for a broke salesman, and contract "
        "marries Iris. Her relatives spend Christmas dinner sneering at him, with no "
        "idea who is sitting across from them.\n"
        "Contract marriage plus a family about to be humbled. Delicious.",

    # 274.3M   In Love with a Single Farmer-Daddy
    # FACTS: Natalie is married off by her conniving family to rural farmer Rhett, single father to a
    # FACTS:  mute daughter, and finds herself shunned yet slowly winning hearts.
    'in-love-with-a-single-farmer-daddy':
        "Her family married her off and washed their hands of her.\n"
        "Natalie is married off to Rhett, a rural farmer raising a daughter who does "
        "not speak. When she first arrives she is shunned. Will she be able to turn "
        "things around?\n"
        "A single dad, a child who needs her, and a fierce slow burn romance.",

    # 234.4M   Married at First Sight
    # FACTS: Summer has been the ideal girlfriend for her ex-boyfriend, Vincent.
    'married-at-first-sight':
        "She sold her own blood to put him through medical school.\n"
        "Summer gave Vincent everything. She sold her blood to help pay his way "
        "through medical school and carried him to the finish line, and he cheated on "
        "her anyway. Done with him, she signs a contract marriage to save a "
        "billionaire she has only just met. Then she finds out who he actually is.\n"
        "A contract marriage to a total stranger, and an ex about to understand what "
        "he lost.",

    # 230.8M   Married The Mafioso I Saved
    # FACTS: Betrayed and abandoned, Hannah flash-marries Alex, the street thug she saved with a sing
    # FACTS: le kiss, not knowing what he really is.
    'married-the-mafioso-i-saved':
        "She saved a street thug with one kiss.\n"
        "Betrayed and abandoned, Hannah marries Alex on the spot, the man she saved "
        "with a single kiss. She has no idea what he really is.\n"
        "Flash marriage to a dangerous man. Need we say more?",

    # 229.1M   Ex-Convict Nanny and Billionaire Single Dad
    # FACTS: Fresh out of prison, Grace landed a job as a nanny. Her boss, the ruthless billionaire A
    # FACTS: lex Hill, cares only about his precious daughter. Grace passed Alex's rigorous test and 
    # FACTS: gradually won over his cold heart, but Grace holds a dark secret, one that could destroy
    # FACTS:  everything good.
    'ex-convict-nanny-and-billionaire-single-dad':
        "She walks out of prison and straight into his house.\n"
        "Fresh out of prison, Grace lands a job as a nanny for Alex Hill, a ruthless "
        "billionaire who cares about exactly one thing: his daughter. Grace passes "
        "every test he sets her. She is also carrying a secret that could take the "
        "whole thing down.\n"
        "This one is served with an extra helping of angst.",

    # 226.8M   Mommy Don't Cry, Daddy is Sorry
    # FACTS: After his wife Sienna dies in a mental hospital, Wayne is fooled into taking home the wr
    # FACTS: ong daughter; Sienna is alive, reborn as ruthless alter-ego Scarlett, hunting vengeance 
    # FACTS: in her daughter's name.
    'mommy-don-t-cry-daddy-is-sorry':
        "The wife he buried is very much alive.\n"
        "Wayne loses his wife Sienna in a mental hospital, then is tricked into "
        "bringing home the wrong daughter. Sienna is alive. She comes back as "
        "Scarlett, and she is not here to forgive anyone.\n"
        "Revenge, a reborn heroine, and a husband with a lot to answer for.",

    # 219.4M   American Sniper: The Last Round
    # FACTS: A legendary sharpshooter hiding as a shooting range handyman steps up when the range fac
    # FACTS: es a hostile takeover.
    'american-sniper-the-last-round':
        "The maintenance guy holds a world record nobody knows about.\n"
        "Carl Oliver was the sharpshooter they called the King of Guns, and he broke "
        "the world record for the longest confirmed kill before disappearing "
        "completely. These days he does maintenance at a shooting range, where the "
        "club captain Albert looks straight through him. Then the range comes under "
        "threat, and protecting its owner Jane and her daughter Rebecca matters more "
        "than staying hidden.\n"
        "A quiet man with a past, pushed one time too many. Hidden identity at its "
        "most satisfying.",

    # 218.8M   Carrying His Triplets, Becoming His Wifey
    # FACTS: Daisy works in a warehouse to pay for her tuition, but her father steals her money.
    'carrying-his-triplets-becoming-his-wifey':
        "One night with a stranger, and then three heartbeats.\n"
        "Daisy is working warehouse shifts to put herself through college, and her "
        "father keeps taking the money she earns. Desperate enough to take a second "
        "job at a strip club, she meets Marcus there, a billionaire she spends a "
        "single night with. Not long after, she finds out she is pregnant with "
        "triplets.\n"
        "A one night stand, a billionaire, and three babies. This is exactly the kind "
        "of chaos we love.",

    # 218.1M   Fated to My Forbidden Alpha
    # FACTS: Kasey Esser's breakout title and one of the best known werewolf verticals.
    'fated-to-my-forbidden-alpha':
        "Her mate turns out to be the one person she cannot stand.\n"
        "On her eighteenth birthday Selene learns that her mate is Alpha Jackson, her "
        "own nemesis, and that he means to reject her. What he does not know is that "
        "she is a Luna, taken as a child and mistaken ever since for an ordinary "
        "wolf. Then she starts planning her escape.\n"
        "A rejected mate and a hidden Luna. Werewolf romance at full volume.",

    # 214.1M   Taming My Bullies
    # FACTS: Emma Parker is a new transfer to Maple Elite Academy - and she's picked a fight with The
    # FACTS:  Big Four, on her very first day!
    'taming-my-bullies':
        "New school, new enemies, all in one afternoon.\n"
        "Emma Parker transfers into Maple Elite Academy and picks a fight with The Big "
        "Four before her first day is out.\n"
        "One girl against the entire pecking order. Sign us up.",

    # 213.1M   My Stepbrother's Dirty Secret
    # FACTS: Alice transfers to St.
    'my-stepbrother-s-dirty-secret':
        "The boy she cannot stand has just moved in.\n"
        "Alice starts at St Mary's High after her mum remarries a millionaire. She "
        "clashes with James, a classmate she wants nothing to do with, right up until "
        "she finds out he is her new stepbrother.\n"
        "Forbidden stepbrother romance, and we are not sorry about it.",

    # 200.6M   How to Break a DILF
    # FACTS: Uncle Jesse's smokin' hot tattoo and great technique on bed awakens Sophie Holland's fan
    # FACTS: tasy in How To Break A DILF Trailer!
    'how-to-break-a-dilf':
        "He is her best friend's dad, and she does not care.\n"
        "Sophie Holland has fallen for Uncle Jesse, who happens to be her best "
        "friend's father. His advice is that she should be dating someone her own "
        "age. She is not taking it.\n"
        "Forbidden age gap, and a man trying very hard to do the right thing.",

    # 198.4M   Snatched a Billionaire to be My Husband
    # FACTS: She falls in love with her ex's uncle.
    'snatched-a-billionaire-to-be-my-husband':
        "Of all the men in the world, it had to be him.\n"
        "She falls in love with her ex's uncle.\n"
        "Age gap with a family complication attached. Awkward does not begin to cover "
        "it.",

    # 197.9M   The Virgin and The Billionaire
    # FACTS: Demoted to maid and substitute bride in her father's house, Cindy finds unexpected love 
    # FACTS: when billionaire Charles Kane falls for her.
    'the-virgin-and-the-billionaire':
        "Her own father turned her into the help.\n"
        "Cindy is pushed down to maid in her father's house and lined up as a "
        "substitute bride. Then the billionaire Charles Kane notices her.\n"
        "Cinderella energy with a substitute bride twist.",

    # 197.6M   Tell Me Not to Love You
    # FACTS: Brie, a servant's daughter raised alongside young master Teddy, fights her feelings as h
    # FACTS: e pursues her across the class divide.
    'tell-me-not-to-love-you':
        "She grew up in his house, never as his equal.\n"
        "Brie is a servant's daughter, raised alongside the young master Teddy. He "
        "wants her. She is doing everything she can not to want him back.\n"
        "Forbidden love across a class divide. Angst, and plenty of it.",

    # 197.0M   Don't Miss Me When I'm Gone
    # FACTS: Orphaned and raised with the Miller brothers, she expects to end up with one of them unt
    # FACTS: il the maid's daughter moves in and her heart is broken; after she leaves, they lose the
    # FACTS: ir minds trying to find her.
    'don-t-miss-me-when-i-m-gone':
        "She left, and every one of them fell apart.\n"
        "Orphaned and raised alongside the Miller brothers, she always assumed she "
        "would end up with one of them. Then the maid's daughter moves in, and the "
        "future she had always assumed was hers quietly disappears. So she goes.\n"
        "Nothing hits like a heroine who walks away and lets them feel it.",

    # 192.3M   The Alpha King and His Virgin Bride
    # FACTS: The Alpha King Killian Storm is cursed to not live past age thirty.
    'the-alpha-king-and-his-virgin-bride':
        "He is not meant to see thirty.\n"
        "Killian Storm is the Alpha King, and a curse says he will not live past the "
        "age of thirty. There's only one way he can survive. He has to find his true "
        "fated mate. But what nobody counted on is that his mate is just a human.\n"
        "A cursed king and a human mate. Some delicious angst for the fated mate fans.",

    # 190.2M   Doctor Boss Is My Baby Daddy
    # FACTS: : When med intern Molly has a one-night stand with a stranger, she thinks it’s a one-and
    # FACTS: -done kind of deal.
    'doctor-boss-is-my-baby-daddy':
        "One night with a stranger. Then she meets her new boss.\n"
        "Molly is a medical intern who spends a night with a stranger and files it "
        "away as a one off. A month later she finds out two things. She is pregnant, "
        "and the stranger is Dr Graham Weston, her new boss.\n"
        "A one night stand and a secret pregnancy. The angst practically writes "
        "itself.",

    # 181.9M   Falling for My Ex's Mafia Dad
    # FACTS: After catching her boyfriend cheating, Fay is pulled into a mob alliance marriage and fa
    # FACTS: lls for his father, the Mafia King.
    'falling-for-my-ex-s-mafia-dad':
        "She caught him cheating. What came next was a wedding.\n"
        "After catching her boyfriend cheating, Fay is pulled into a marriage arranged "
        "to seal an alliance between mob families. The man at the head of it is his "
        "father.\n"
        "Age gap, mafia, and an ex who is about to regret everything.",

    # 176.8M   The Double Life of a Billionaire Heiress
    # FACTS: After three years of marriage, CEO Wes Sterling is convinced that his wife Kira is a che
    # FACTS: ating gold digger.
    'the-double-life-of-a-billionaire-heiress':
        "He is certain he knows exactly who he married.\n"
        "Three years into the marriage, CEO Wes Sterling has convinced himself that "
        "his wife Kira is a cheating gold digger.\n"
        "A husband who has it completely wrong. We cannot wait for him to find out.",

    # 172.5M   I Had a Baby without You
    # FACTS: Five years ago curvy waitress Scarlett saved Brandon's life and spent one night with him
    # FACTS:  before vanishing. Now she's back, unrecognizable, and he's a recluse.
    'i-had-a-baby-without-you':
        "Five years on, he does not recognise her.\n"
        "Scarlett saved Brandon's life five years ago, spent one night with him, then "
        "disappeared. She is back now, and in the years between he has shut himself "
        "away from the world.\n"
        "A secret baby and a second chance. This one aches.",

    # 171.8M   Miss You After Goodbye
    # FACTS: To repay a debt of kindness, Neil signs a secret contract with Keira's father stating th
    # FACTS: at he will marry Keira for five years and help her recover from a painful breakup with h
    # FACTS: er first love, Simon.
    'miss-you-after-goodbye':
        "He signed up for five years. She has no idea.\n"
        "Neil owes Keira's father a debt, so he signs a secret contract: five years of "
        "marriage, and help getting her over Simon, her first love. Keira never learns "
        "the contract exists.\n"
        "A contract marriage with a secret sitting at the centre of it. Pure angst.",

    # 170.3M   The Call Boy I Met in Paris
    # FACTS: Sophie fake-marries a man she mistakes for a callboy. He's a billionaire she met seven y
    # FACTS: ears ago.
    'the-call-boy-i-met-in-paris':
        "",

    # 168.4M   Surrender to My Professor
    # FACTS: Struggling student Sylvia falls into a forbidden romance with her cold, harsh professor 
    # FACTS: Lawrence Calhoun.
    'surrender-to-my-professor':
        "",

    # 168.0M   Step Aside, I'm the King of Capital
    # FACTS: Evan Adams lead vertical.
    'step-aside-i-m-the-king-of-capital':
        "",

    # 167.6M   Baby, Just Say Yes!
    # FACTS: Betrayed by her fiance and stepsister, Victoria needs a husband to claim her inheritance
    # FACTS:  and contract-marries her one-time saviour Teddy; genuine feelings complicate the agreem
    # FACTS: ent.
    'baby-just-say-yes':
        "",

    # 163.3M   The Lost Quarterback Returns
    # FACTS: When Asher Bradshaw, the son of hall-of-famer NFL quarterback Trent Bradshaw and former 
    # FACTS: beauty queen Krista, goes missing in a devastating fire, psychotic fan Donny Lewis takes
    # FACTS:  it as an opportunity to swap Asher with his own son, Wyatt.
    'the-lost-quarterback-returns':
        "",

    # 161.7M   In the Palm of His Hand
    # FACTS: College senior Shelby Yates accidentally saves the life of billionaire ex-mafia CEO Matt
    # FACTS: eo Franconi.
    'in-the-palm-of-his-hand':
        "",

    # 161.3M   Maid for My Nemesis
    # FACTS: Class president Emma hides that she is the poorest girl at her wealthy private school. R
    # FACTS: ival rich bad boy Lucas Bennett gets her fired then hires her as his personal maid, keep
    # FACTS: ing the arrangement secret as long as she caters to his every need.
    'maid-for-my-nemesis':
        "",

    # 155.4M   Accidental Surrogate for Alpha
    # FACTS: Ella, a Luna werewolf hidden from herself, seeks motherhood through insemination and is 
    # FACTS: accidentally given the sperm of an Alpha wolf.
    'accidental-surrogate-for-alpha':
        "",

    # 153.0M   Heiress Crash Lands on Her Husband
    # FACTS: Lily out-trumps her cheating ex, his mistress, a royal suitor and a dominant mother-in-l
    # FACTS: aw in a marathon of revealed identities.
    'heiress-crash-lands-on-her-husband':
        "",

    # 149.0M   Undercover Prison King
    # FACTS: Ex-soldier Troy inherits a corrupt private prison and goes in undercover as an inmate to
    # FACTS:  expose the crime ring running it.
    'undercover-prison-king':
        "",

    # 145.2M   Fated to the Alpha
    # FACTS: Katya, a rare Luna healer without her wolf, flees her pack's threats to Black Creek, whe
    # FACTS: re she meets Alpha Ezra, her fated wolf and protector.
    'fated-to-the-alpha':
        "",

    # 142.4M   If Loving You is a Sin, then I'll Go to Hell
    # FACTS: Good girl Ellie Jones falls for bad boy Asher King and gets pregnant. Her pastor father 
    # FACTS: and his gang family, the Red Snakes, want to keep them apart and take the baby; Asher vo
    # FACTS: ws to protect her at any cost.
    'if-loving-you-is-a-sin-then-i-ll-go-to-hell':
        "",

    # 141.0M   How to Dump a Hockey Star
    # FACTS: : After leaving behind her life as a billionaire heiress, Renee dedicates herself to hel
    # FACTS: ping her husband recover from a vegetative state and pursue his NHL dreams.
    'how-to-dump-a-hockey-star':
        "",

    # 139.4M   Married In A Heartbeat
    # FACTS: Betrayed by her fiance and her own sister, Esther marries Ricky without knowing his real
    # FACTS:  identity – a secret billionaire.
    'married-in-a-heartbeat':
        "",

    # 138.3M   Fated to Find You
    # FACTS: A school janitor who saves a child from kidnapping flash-marries the girl's secret-billi
    # FACTS: onaire father as betrayals and a vengeful ex circle their new family.
    'fated-to-find-you':
        "",
}

FACTS = {  # paste fetched text here for any FETCH REQUIRED row
    # Tier B, but the text on disk was a STAT not a synopsis ("ReelShort's breakout
    # megahit, 500M+ views on platform"), so it is useless as a fact source and the
    # accuracy guard correctly rejected a caption written against it.
    # Fetched 15 Aug 2026 from the platform's own page:
    # https://www.reelshort.com/movie/the-double-life-of-my-billionaire-husband-65a8cec883959aedd8001107
    # 60 episodes. Cast listed: Avery Lynch, Jarred Harper, Molly Anderson.
    'the-double-life-of-my-billionaire-husband':
        "It was supposed to be an emotionless contract marriage and nothing more. But "
        "Sebastian couldn't resist growing a soft spot for Natalie. With her family "
        "planning her downfall and her estranged husband cooking up a deadly plan, "
        "what should Natalie expect?",

    # Stored text was "Kasey Esser's breakout title and one of the best known werewolf
    # verticals" - a note about the ACTOR, not a synopsis. Fetched 15 Aug 2026 from
    # https://www.reelshort.com/movie/fated-to-my-forbidden-alpha-647ffff5be685964fe120217
    # 60 episodes. Cast: Autumn Noel, Kasey Esser, John Williams Dicario, Antheia.
    'fated-to-my-forbidden-alpha':
        "On her 18th birthday, Selene found out that her mate was her nemesis, Alpha "
        "Jackson. He plans on rejecting her. Selene never planned on accepting him as "
        "her mate. He didn't know she wasn't any wolf but a Luna, kidnapped and "
        "mistaken for a regular wolf. As Selene plans on escaping her pack, she meets "
        "Alexander, her fated mate.",

    # Stored text was truncated to "Alice transfers to St." - unusable. Fetched 15 Aug
    # https://www.reelshort.com/movie/my-stepbrother-s-dirty-secret-6807565447c113d594077ca8
    # 62 episodes. Cast: Jenna Gilmer, Cameron Porras, August Williams, Greta Hicks.
    'my-stepbrother-s-dirty-secret':
        "Alice transfers to St. Mary's High School after her mom remarries a "
        "millionaire, only to butt heads with James, a hot classmate who turns out to "
        "be her new stepbrother.",

    # Stored text was trailer marketing copy. Fetched 15 Aug 2026 from
    # https://www.reelshort.com/movie/how-to-break-a-dilf-68ec6024a7344dc50f009aff
    # 68 episodes. Characters named: Sophie Holland, Uncle Jesse.
    'how-to-break-a-dilf':
        "She becomes attracted to her best friend's father, Uncle Jesse, despite his "
        "advice to date age appropriate partners. Sophie Holland.",

    # REFETCHED 15 Aug. The stored line was the FIRST SENTENCE ONLY, so the caption
    # written from it had no male lead, no pregnancy and no romance in it at all.
    # 69 episodes. Cast: Autumn Noel, Mark H. McClafferty.
    'carrying-his-triplets-becoming-his-wifey':
        "Daisy works in a warehouse to pay for her tuition, but her father steals her "
        "money. Financially desperate, gets another job at a strip club to make ends "
        "meet. There, she has a one-night stand with Marcus, a billionaire. Soon "
        "after, Daisy discovers that she is pregnant with triplets.",

    # REFETCHED 15 Aug. Stored line stopped before the two reveals. 63 episodes.
    # Cast: Marc Herrmann, Kirby Ellwood.
    'doctor-boss-is-my-baby-daddy':
        "When med intern Molly has a one-night stand with a stranger, she thinks it's "
        "a one-and-done kind of deal. But a month later, she discovers two shocking "
        "truths: she's pregnant with his baby, and the stranger is her new boss, Dr. "
        "Graham Weston.",

    # REFETCHED 15 Aug. Stored line was one sentence of a much longer synopsis.
    # 89 episodes. Cast: Autumn Noel, Lorenzo Brunetti, Chase Lawless, Ariel Yasmine.
    'married-at-first-sight':
        "Summer has been the ideal girlfriend for her ex-boyfriend, Vincent. From "
        "selling her blood to helping him finish medical school, Summer has been the "
        "best girlfriend. Yet, Vincent cheated on her. Frustrated by their actions, "
        "Summer enters into a contract marriage to save a billionaire she just met. "
        "She was shocked to find out about his identity.",

    # REFETCHED 15 Aug. Stored line omitted the curse's condition and the mate.
    # 80 episodes. Cast includes Mark H. McClafferty.
    'the-alpha-king-and-his-virgin-bride':
        "The Alpha King Killian Storm is cursed to not live past age thirty. Only "
        "finding his true fated mate can break the curse, but what happens when his "
        "fated mate is a human?",

    # REFETCHED 15 Aug. 63 episodes. Cast: Addison Bowman, Marc Sylwestrzak, Piper
    # Jean Jones, Jesse Morales, Mark H. McClafferty, Cameron Somers, Aaron Russell.
    'american-sniper-the-last-round':
        "Carl Oliver, the legendary sharpshooter known as the King of Guns, broke the "
        "world record for longest confirmed kill then vanished from the public eye. He "
        "hid his identity, working as maintenance at a shooting range. He endures "
        "humiliation from the dismissive shooting club captain, Albert, unaware of his "
        "true identity. The shooting range is facing a hostile takeover. In order to "
        "protect Jane, the owner, and her daughter Rebecca, Carl steps up and shows "
        "his legendary shooting skills.",

    # REFETCHED 15 Aug. The platform publishes ONE LINE for this title and no more,
    # so a short caption here is honest rather than lazy. 63 episodes.
    # Cast: Grace Swanson, Jarred Harper, Dante Belardinelli, Courtney Green.
    'snatched-a-billionaire-to-be-my-husband':
        "What happens when you fall in love with your ex's uncle?",
}

