"""The six homepage captions Cyan checks before anything else (28 Sep 2026).

These are live (she said take everything live, but check homepage captions
first). This file is the record behind the standing review page; the text is
exactly what the page shows, so her edits diff against it correctly.
"""
CAPTIONS = {
    'watch-out-i-m-the-lady-boss': "He climbed to the top on her back, then dropped her.\nEleanor spent years helping one man get where he wanted to go, and once he got there he had no more use for her. What nobody knows is that she's the hidden CEO behind Thunder Circle, one of the most powerful names around. Then a billionaire nobody can place asks Eleanor to marry him, and high society can't stop talking about it. Now everyone wants to know who she really is.",
    'revenge-marriage-sweet-love': "Her sister took her boyfriend and her inheritance. So she went after his uncle.\nRebecca didn't stop at stealing Ethan from her sister Cate. She walked off with Cate's inheritance too. One drunken night, with nothing left but anger, Cate decides the best payback is Ethan's handsome uncle Shaun, and she sets out to seduce him. Shaun is cold to everyone, yet Cate lights something in him and he falls for her hard. Then the truth comes out on both sides. Shaun was never Ethan's uncle at all, and now he knows Cate only came to him to get back at Ethan. Can a love that started as revenge survive that?",
    'fake-dating-my-rich-nemesis': "One mistake with her childhood nemesis. Now they're fake dating to get back at their exes.\nWhen she comes back to North Lake High, the last thing she expects is to spend one night with the Beaumont heir, the boy who has been her enemy since they were kids. It was a mistake and they both know it. But they each have an ex they'd love to see squirm, so they strike a deal and start dating for show. It's supposed to be an act. Will they end up falling for each other anyway?",
    'escape-with-boss-s-baby': "The heiress who went to work as his secretary.\nHermione Garcia is a celebrated computer genius, and she's also the heiress of the Garcia family, the richest name in the South. Three years ago Chris Evans saved her at a banquet and she fell for him. He's President of LM Corporation, and she wants him to love her for herself, so she hides who she is and takes a job as his chief secretary. They've been seeing each other in secret ever since, and he still has no idea who she really is. But a secret that big can't hold forever, especially once there's a baby involved.",
    'falling-into-a-dangerous-love': "She broke his heart with a lie. Eight years later he's back for revenge.\nShe was a gifted designer in love with Lee Taebin when everything fell apart at once: her dad's gambling debts, a family in ruins, and a baby on the way. Determined to carry it all by herself, she told him something cruel and untrue and left. Eight years on she's a single mom raising her sick son Yun Suho, and Taebin has become the cold, ruthless CEO who made Jinsung Group what it is. When he turns up in her life again he wants revenge, but he can't tell whether he hates her or still loves her, and he becomes dangerously fixated on her. As eight years of misunderstanding come apart and the truth about the boy's father finally comes out, his revenge turns to regret, and one choice could change everything.",
    'reborn-as-a-genius-baby': "His stepfather killed him. Then he woke up six years old.\nDylan was betrayed, framed and finally murdered by his own stepfather. Then he opens his eyes as a six year old again, still remembering everything that ruined him the first time around. Knowing what's coming, he grows a single insurance payout into a fortune, gets his mother out of poverty, and exposes the billionaire who has secretly been his real father all along. But the family that put him in the ground still wants everything. This time the genius baby gets them first.",
}
