# -*- coding: utf-8 -*-
"""DRAFT captions, part 2 of 4 of the 28 Sep 2026 new-titles batch (new234).

Written from each title's own platform page. FACTS holds the synopsis each
caption was written from, verbatim on one line. Where capwork gave no synopsis
(the MoboReels and StardustTV rows) it was fetched from the title's platform
URL on 28 Sep 2026. Pinedrama's card blurb was thin, so its FACTS also carries
the longer synopsis from the same page's structured data.

LEFT OUT, NEEDS A SOURCE (1):
  after-erasing-his-identity-the-ceo-wife-goes-crazy (StardustTV): the page
    publishes only a two sentence stub with no names ("The male protagonist
    endured humiliation ... So the male lead resolutely chose to leave."). No
    story beyond the premise, so no caption was written. Needs Cyan or a
    better source.

MECHANICAL NOTES for review:
  - Hyphenated names cannot pass the dash ban, so they are left unnamed rather
    than respelled: Young-gi, Gu-in and Kyung-ah in my-baby-daddy-is-my-best-friend
    (Jea is named), and the Kang Sung-hoe organization in
    the-dangerous-bosss-missing-bride.
  - APEX Capital is written Apex Capital (caps ban); God-King is written God King.
"""
CAPTIONS = {
    'watch-out-i-m-the-lady-boss':
        "He climbed to the top on her back, then dropped her.\nEleanor spent years helping one man get where he wanted to go, and once he got there he had no more use for her. What nobody knows is that she's the hidden CEO behind Thunder Circle, one of the most powerful names around. Then a billionaire nobody can place asks Eleanor to marry him, and high society can't stop talking about it. Now everyone wants to know who she really is.",

    'one-fateful-night-with-my-boss':
        "She sold one night to a stranger and left the country.\nAnita needed money badly enough to spend a night with an old geezer for cash, and afterward she left that cold city behind and moved abroad. Six years later she's back with her little boy. Her new job comes with a new boss, Tristan, a CEO people talk about like a legend, and before she can stop it her son has started calling him dad. Is this fate?",

    'rebel-in-devil-s-shackle':
        "Sold on the dark web. Hunted for sport by the rich.\nNina Morgan was born into an aristocratic family, but someone sells her out on the dark web and she ends up as prey in a hunting game played by the wealthy. That's where she runs into Max Luther, a mafia lord, and life with him swings between tenderness and torment. Every time she decides she's leaving, Max locks her back in. They wound each other and rescue each other at the same time, caught up in a love and a desire they were never supposed to feel. Is he keeping her out of love, or out of hate?",

    'almost-lover':
        "She was pregnant. He was rubbing oil on his first love's belly.\nEvelyn gets back from a prenatal appointment and walks in on her husband Edward rubbing oil into the belly of his first love. Later, when Evelyn has a bad allergic reaction, he shuts her in a room and leaves her there in pain, and she loses their baby. Broken, she leaves him and starts over, working at an architecture firm a friend runs. Some months on, Edward turns up on the love lock bridge, the spot where they once promised each other forever, and says he'll jump if she won't forgive him. Does she pull back the man who cost her everything, or let him fall?",

    'the-wedding-day-divorce':
        "The bride thought his sister was his pregnant lover.\nTaylor flies home from abroad for her brother Tyson Jordan's wedding, and his fiancee takes one look at her and decides she's the secret lover carrying his child. Taylor tries to explain the misunderstanding, but the bride won't let it go, and she makes sure Taylor loses the baby. When Tyson finds out what his fiancee did to his sister, his wedding day becomes the day he swears revenge. Her whole family is going to answer for it.",

    'back-to-the-80s':
        "She went to sleep in her own time and woke up in the 80s.\nJulie Stein expects an ordinary morning and opens her eyes decades in the past. The life she's landed in isn't a kind one. She's the cast off daughter of a rich family she isn't even related to by blood, and the man they've lined up for her is an old man with two kids. He was meant for their real daughter. Now it's Julie who has to marry him in her place, in an era that was never hers.",

    'shes-the-apple-of-their-eye':
        "Thrown out as the fake daughter. Welcomed home as the richest heiress in the country.\nEmily grew up as a Porter, until the day she learned she wasn't their daughter at all. The real Porter heiress came home to take back her place, and Emily was shown the door. Then she found her birth family, and it turned out they're the wealthiest dynasty in the nation. Now she has two parents who adore her, five brothers who are each remarkable in their own right and spoil her rotten, and a rich CEO fiance. The Porters let go of the wrong girl.",

    'sweetheart-wife':
        "She married her best friend. The certificate has another man's name on it.\nFour years ago Sandy Young set Queenie up, and Queenie's own father sent her away overseas. While she was abroad she happened to save a man named Shane Lawson. Now she's home, and her fiance Sam Fowler is sleeping with Sandy. So on impulse Queenie marries her best friend Xander Lawson instead. The trouble is Xander was drunk and brought the wrong ID card, and the man Queenie is now legally married to is Shane. The man she once saved just became her husband.",

    'christmas-with-a-country-bad-boy':
        "She came home for Christmas. Her family came for her money.\nCountry music's good girl wraps up a world tour that sold out everywhere and heads home for the holidays, hoping to finally rest. Instead her greedy family corner her and keep pushing her to sign her estate over to them. Meanwhile her record label has sent her its bad boy, a star buried in scandals who needs his image cleaned up. He's the last person she'd expect to be on her side, but he's the one who helps her stand up to them, find her voice again and take her life back.",

    'the-lovers-saga':
        "She spent the night with him. Another woman took the credit.\nCarmelia Sanders takes Maeve Turner's place at the After Hours Club, and by chance she ends up spending the night with Asher Lowery. Asher wakes up to find a pendant Carmelia left behind, and Maeve claims the night as her own. The pendant convinces Asher that Maeve is the daughter of the person who once saved him, so he pours all his love into her and even promises to marry her. But the pendant was never Maeve's.",

    'forbidden-tides-don-t-tell-my-stepson':
        "A weekend away, and her stepson's college friend.\nLisa goes away for the weekend, and something she can't resist catches fire between her and Kai, a college friend of her stepson's. What starts on that trip turns into a string of secret meetings, and Lisa has to hide every one of them from her husband and her stepson while both of them are close enough to catch her. The more she wants Kai, the closer her marriage comes to falling apart, and each choice she makes drags her in deeper.",

    'the-mafia-s-forbidden-swap':
        "She faked amnesia to see if her husband cared. He handed her to his brother.\nEmma is married into the mafia, and her husband Kevin barely looks at her. After she's hurt in a fall she pretends to have lost her memory, hoping for once to feel loved. Instead Kevin tells her his brother Ryan is her real husband, while he parades his mistress around. Ryan is the man everyone fears, the one they call the dark executioner. He's cold and deadly, but what's burning behind those cold eyes is something else entirely.",

    'the-dangerous-bosss-missing-bride':
        "He spent eight months looking for the woman who saved his life.\nLee Kanghyun is a boss people call the most dangerous man in the world, and for eight months he hasn't stopped hunting for the woman who once saved him. When he finally tracks her down, Yoo Seoyeon is bringing up a child on her own, cut off even by her own family. Then he notices the child's birthday lines up exactly with the night they spent together. He tells her he'll take responsibility for her and the baby, and the most dangerous man in the world starts making moves to keep them both safe. He loves her, and the little one might be his.",

    'hidden-hero-his-time-to-shine':
        "His teacher gave everything to the country. A celebrity wants the ward cleared.\nNathan Kent is Logant's best researcher and one of the people working on the Kunst Program, a top secret operation for national security whose members give everything they have for their country's sake. When Nathan's teacher dies of exhaustion, a famous celebrity and his assistant show up demanding that Nathan clear out the ward, and they humiliate him while they're at it. They have no idea who they're pushing around.",

    'the-twins-love-me-too-late':
        "For three years the man in her bed wasn't her husband.\nHannah thought she was married to Aiden. The man she'd actually been sleeping next to for three years was his twin brother Ansel, and the whole marriage was part of a revenge plan Aiden cooked up for Ivy's sake. Then Hannah loses her mother, and loses her baby too. After that she takes her own revenge, shuts both twins out of her life for good and moves abroad to start over. By the time the twins want her back, she's long gone.",

    'my-baby-daddy-is-my-best-friend':
        "Pregnant by a married man, she asks her best friend to be the dad.\nJea finds out she's pregnant, and the father is a married man. She can't bring herself to give the baby up, so she goes to her childhood friend with a proposal nobody saw coming: be the baby's father and her fake husband. His situation leaves him no real way to say no, so he agrees. It starts out as the strangest arrangement either of them has ever made, but raising the child together, they slowly start to care for each other for real. Then the married man's wife discovers the truth, and everything spins out of control.",

    'loving-you-in-my-final-days':
        "She broke his heart on purpose so he'd never know she was dying.\nShe made the man she loved believe she'd betrayed him, because the truth was that she was terminally ill and she didn't want him to see it. A year later he's back, a billionaire CEO now, with another woman on his arm and nothing left for her but bitterness. Each time they run into each other the old hurt tears open again, and he still has no idea why she really let him go. When everything between them rests on one lie, can the truth ever bring them back?",

    'dont-provoke-him-hes-the-king-of-l-a':
        "The taxi driver nobody looks at twice built Apex Capital.\nCain Morgan founded Apex Capital, then walked away from it all to drive a taxi after his eldest son Ethan was killed in a car crash that Damian O'Hara set up on purpose. His younger son Liam keeps butting heads with the rich O'Hara family, and when they take Aurora, Liam's girlfriend, to scare him, Cain stops hiding. He turns his money on them and bankrupts O'Hara Group. Then he meets Lena, who chairs Opal, and puts serious money behind her brand. Her jealous ex Holton snatches her, holds her at Westside Warehouse and makes Cain get down on his knees and give up his Apex shares. It ends with Holton under arrest, Liam moving over to finance so he can marry Aurora, and Cain and Lena together.",

    'the-ceo-who-felt-my-pregnancy':
        "He feels everything she feels. Including the triplets.\nLila Reed grew up poor in the countryside and works at Vaughn Group, and she sleeps with the drugged CEO Hayden Vaughn in the hope of a permanent job. His family carries a rare mating bond, and it means Hayden now feels every sensation in her body as if it were his own. When Lila finds out she's carrying triplets and the pregnancy is high risk, she runs. Hayden tracks her down, marries her, and stands between her and everyone who wants to hurt her, from jealous rivals and spiteful coworkers to greedy family members. They make it through one danger after another, and in the end Hayden proposes, with three babies on the way.",

    'too-late-to-regret-my-lost-goddess':
        "He called their baby a bastard to protect another woman.\nNobody knows Leila is Zeus's granddaughter. To cover for Callista, her husband Damon tells everyone the child Leila is carrying was fathered by a rapist. Leila seals her unborn baby inside crystal, divorces Damon, and then shows them all that the crystal carries the marks of both Ares and Zeus. She lays Callista's scheme bare and calls down the judgment of Olympus on her. Damon doesn't get death. He gets something worse, an eternity of regret spent watching Leila live happily with Orion.",

    'betrayed-at-the-alter-she-married-a-ceo-instead':
        "Eight years of hiding who she was, for a man with a whole other family.\nElla Whitfield is an heiress, and for eight years she kept that quiet and poured everything she had into the man she loved. On the day they're meant to marry, she learns he's been sleeping with the widow of his dead brother, and that the five year old boy they're raising is his. Ella walks out on him and pulls back every resource she ever handed him. He thinks all he's lost is a bride, but everything he has was built by her.",

    'her-mafia-fathers-wrath':
        "Her fiance's childhood sweetheart is wearing her wedding dress.\nEnzo Moretti is godfather to a mafia family that ranks among the most powerful in New York, and his daughter is his princess. He's kept her hidden from that world for her own safety, and so she won't be alone he's arranged for her to marry Leon Scott, the handsome son of the richest man in New York. At her dress fitting she finds Leon's old childhood sweetheart Nicole Hill already in the gown her father had made for her in Milan. Nicole hands her a cheap bridesmaid dress and tells her Leon has agreed that Nicole will be the one walking down the aisle. So the bride picks up the phone and calls Leon for an explanation. And her father hasn't heard about any of it yet.",

    'the-tennis-queen-s-match-point-comeback':
        "Five years married, and she was only ever a stand in.\nIsabel and Enzo play tennis together and have been married for five years when she learns the truth. She was never the one he wanted. She was a replacement for Julie, the woman he never got over. The moment Julie comes back, Enzo drops everything for her. Then Isabel disappears from his life, and suddenly he can't stop wanting her. Now it's Enzo who's in agony, and his regret won't bring her back.",

    'this-time-she-walked-away-first':
        "He gave her a princess dress when she was a little girl. At twenty, she wore it for him.\nLena Clermont has been in love with Andrew Rohan, her father's friend and twelve years older, since the day she first laid eyes on him. He was broad shouldered and sharply dressed, and he smiled at her, patted her on the head and gave her a princess dress. Years later, when Lena is twenty, Andrew is drugged at a banquet. She puts on that same princess dress and goes to him, offering herself as the way out. But this time, she'll be the one who walks away first.",

    'a-nearsighted-girls-journey-through-a-horror-game':
        "Trapped in a horror game, and she can't see a thing.\nShe gets sucked into a horror game, and because she's nearsighted, everything around her is one big blur. So the creepy little girl in the bloodstained dress becomes her daughter, the final boss becomes her husband, and the old ghosts haunting the place become her doting parents. The first time she meets the boss she grabs his abs, tells him he's got a great body and says it's a pity he's on the short side. He's so mad he laughs, picks up the head he'd been holding, puts it where it belongs and asks if she still thinks he's short at six foot one.",

    'loved-twice-by-the-hockey-star':
        "The little girl calling him Daddy is his. He has no idea.\nHazel disappeared seven years ago, pregnant with Alexander's baby. Now she's back under a different name, doing everything she can for her daughter, who is sick. Alexander became a hockey superstar and never gave up looking for the woman he lost. He doesn't know that the little girl who calls him Daddy is his own child. As old secrets come back up and old wounds split open, can what they had survive the truth, or have they already run out of time?",

    'too-late-im-married-to-the-godfather':
        "He proposed with a soda can tab and then picked someone else.\nFive years ago Ethan humiliated Mia by offering her a ring made from a soda can tab, then chose Sophia over her. Now Mia is the wife of Antonio Russo, a powerful Mafia Don in New York, and they're raising a son together. When Ethan runs into her at a luxury hotel he takes her for a beggar. Then Sophia accuses her of stealing. That's when Antonio steps in and tells them exactly who Mia is. She's Donna of the whole Russo family. The old lies start to come apart, including how Sophia wrecked what Mia and Ethan had and almost had Mia assaulted. Sophia falls, Ethan loses everything, and Mia walks away with her family and her freedom.",

    'the-muggle-kingpin':
        "No powers, no family, and a supply mart at the end of the world.\nThe world has ended, monsters are everywhere, and what's left of humanity is barely hanging on. Zane is a muggle, born without a single power, and his own family throws him out. Then he ends up in charge of a supply mart, and there he discovers he can command the very beasts that hunt people down. Could the outcast everybody wrote off turn out to be the one who saves them all?",

    'i-helped-my-husbands-brother-take-the-mafia-throne':
        "Her husband drowned her over his first love's birthday.\nA mafia wife is drowned by her own husband because she spoiled the birthday of his first love. Then she's reborn. This time she stands aside and lets him throw away the whole godfather throne chasing his sweetheart. Meanwhile she makes a bargain with his brother, the one living in exile, and together they take everything he had. This time there's no mercy.",

    'don-t-touch-the-legendary-lawyer-s-grandson':
        "They locked a sick little boy in a plane bathroom. His grandmother is the Queen of Lawyers.\nEleanor is taking her sick grandson on a flight to his surgery when the plane turns out to be overbooked. An influencer named Bella waves her boyfriend's platinum card around and takes the boy's seat, with no idea that the woman she's pushing around is her boyfriend's mother. The crew gag the child and lock him in the lavatory, and the purser holds on to the key while Eleanor begs on her knees. Someone films the whole thing. By the time they land, Eleanor has promised every one of them will pay.",

    'galactic-myth-arena':
        "Earth forgot its gods. Now it needs them back.\nAfter centuries of lost history, nobody on Earth remembers the old gods, and humanity keeps getting crushed in a galactic arena. Now people are facing slavery. Ethan Cole makes deliveries for a living and comes from a different world, and he's the only one who still knows Earth's myths. To save the planet he has to wake its forgotten gods and send them up against alien civilizations that bring powerful gods of their own and play by rules rigged against Earth.",

    'the-king-of-vegas-chose-her-i-chose-freedom':
        "She gave up her family's fortune to build his empire.\nEvelyn walked away from her rich family so she could build an empire alongside Cole, the man she loved. Then he cheated on her, and he wrecked her body for the sake of his mistress. So Evelyn divorced him, took her life back and found real happiness again, while Cole was left with nothing. The King of Vegas made his choice, and it cost him everything.",

    'kiss-of-a-cornered-beast':
        "He sold a kidney to save his boyfriend. It was all a game.\nMilo Thompson works job after job and even sells one of his kidneys to pay for the brain surgery his boyfriend Kane Winslow needs. Then Milo finds out Kane is a rich heir from the Upper East Side and their whole relationship was a cruel game to him. Heartbroken, Milo vanishes. Only then does Kane realize what he felt was real, and he swallows his pride and starts fighting with everything he has to win Milo's forgiveness.",

    'dragons-bow-to-the-trash':
        "The academy's biggest joke has the King of Dragons on his side.\nElias was born without a Dragon Mark, so the whole Royal Dragon Rider Academy treats him as a powerless nobody. What they don't know is that he once sent a Level 72 Demon King running, that dragons obey him with no bond at all, and that he's woken the King of Dragons himself, the ancient Alexstrasza. Now crooked nobles are fixing the trials against him. They picked the wrong person to cheat.",

    'the-janitor-mom-is-the-real-boss':
        "She posed as a cleaner for sixteen years to raise him right.\nFu Jingshu runs the Zhuoyuan Group, but she hid her fortune and lived as a cleaner for sixteen years so Fu Huai'an, the boy she adopted, would grow up tough. When he comes back from abroad he falls under the influence of his birth mother Shen Rong and turns vain. At a banquet he humiliates Fu Jingshu and smashes the family's heirloom jade pendant. That's when she reveals who she really is, just as her three sons walk in. Fu Huai'an learns that everything he ever had came from the mother he looked down on, and he drops to his knees to confess. It's too late. Fu Jingshu cuts him loose and starts a whole new life.",

    'snacks-bought-me-a-wasteland-throne-season-1':
        "His free gift with a snack order was a trip to the wasteland.\nIan Chan orders some cheap snacks, and the free ring that comes with them drops him into a savage wasteland. Back home he's a boss, and in the wasteland his snacks become money. He swaps spicy strips for technology and power and climbs fast while everyone around him is just trying to stay alive. So how high can junk food lift him?",

    'the-world-s-deadliest-body-guard':
        "The world's top assassin retired to drive freight. Then someone put a price on her head.\nKane Mercer used to sit at number one on the Ledger, the underground's registry of its best killers. Three years ago he quit, and he's been driving freight like any ordinary guy out in the American Southwest ever since. Then crime boss Victor Crowe slaughters an entire outfit and puts a price on Tessa Cross, daughter of that outfit's boss. Kane is the one trusted to keep her alive, and it means dusting off everything he'd left behind. Crowe answers by pushing the bounty up to three million, and the best killers in the business start coming.",

    'my-pup-became-my-alpha':
        "He raised the pup. Now the pup is an Alpha, and he wants him.\nTen years ago Raven, the best hunter in his guild, broke its most sacred rules to save Ash, an orphaned pup born to the Moon Wolf clan, the guild's enemy, and brought him up on his own. That clingy little cub is all grown up now, a pureblood Alpha who's used to being in charge, and the devotion he's been holding back has turned hungry and possessive. With their ages, Raven's duty and every taboo standing between them, Raven tries to get away. Then a crisis puts Raven's life on the line, and the only way Ash can save him is to give him a permanent mating mark. After that there's no going back to being just his guardian.",

    'son-from-the-future':
        "Her son from the future says she has one year to start dating.\nEmma is a single attorney, and one day a stranger stops her at her own front door and tells her he's her son, come back from the future. His warning makes no sense. Either she starts dating, or exactly a year from now she dies in a car crash. Emma digs into it to find out what's really going on, and what she finds is far darker. It was never Emma who was going to die.",

    'i-married-a-family-of-liars':
        "A con woman marries into a rich family to expose them. They're conning everyone too.\nShe was a Wall Street con artist until the FIA flipped her into an informant. Her assignment is to pose as an aristocrat, marry into an elite NY family and bring their money laundering to light. On her wedding night she discovers her new in laws are frauds as well. The title was bought on the black market, the Monet is a forgery, and the family fund is a Ponzi scheme. Then she learns the real mastermind is her own FIA handler. Now she has to decide whether to hand over the family and buy her freedom, or join them and bring the real criminal down.",

    'the-warlords-heir-is-my-son':
        "She's hired as a nanny for her own son.\nWilla Gray is betrayed and locked away, and after a night when she was drugged she gives birth to a son, Andy. The boy ends up adopted by Young Marshal Jason Shaw, the father he never knew, who recognizes him as his heir by the Kirin Birthmark. When Andy falls ill, Willa is brought in as his nanny to calm him, and there she finds herself face to face with Jason. She has no idea the man in front of her is Andy's father.",

    'five-years-behind-bars-my-family-begs':
        "The fake daughter framed her. Her own brother locked her up.\nNova Sterling is the real heiress of her family, but an imposter sets her up and her own brother has her sent to prison. She spends five years paying for something she never did. When she gets out she has no tears left, only a cold plan to make them pay. The quiet girl she used to be is gone, and she starts pulling apart every lie that put her behind bars. Then a mysterious CEO, Ethan Walton, claims Nova as his wife. By the time she's exposed everything the fake daughter did, her family are begging her to forgive them, and it's far too late.",

    'testing-love-married-to-a-crippled-billionaire':
        "He showed up to a blind date pretending to be poor and disabled.\nAlexander is a tech mogul who has had enough of gold diggers, so he turns up for a blind date dressed as a man who's broke and disabled. The woman across the table is Morgan, a mechanic with a big heart who's kind to him exactly as he is. They marry fast, and Alexander keeps his real identity to himself while quietly looking out for her. Morgan's snobby cousin Camilla never stops mocking them, but every scheme she tries blows up in her own face. Alexander's mother grows fond of Morgan and nearly lets his secret slip. Once the secret is out, Morgan is hurt that he lied, but she still loves him. They make up, and before long Morgan is pregnant with twins.",

    'his-private-patient':
        "A year married and her husband has never touched her.\nSophia was born out of wedlock, and her scheming mother swapped her at birth. She grew up in the shadow of her sister Laura, who took every bit of love and privilege there was. Then Sophia is pushed into marrying Oscar, the marriage is ice cold, and after a year of him never laying a finger on her, all that bottled up longing turns into hysteria. That's when she meets Brant, a mysterious doctor at the hospital. What sparks between them starts to strip away decades of lies, and underneath them is a secret about her birth that could blow her whole world apart.",

    'one-night-one-deal-one-billionaire':
        "She made a deal with a cold heir to save her father.\nEmily Anderson is a college student who can't cover her father's surgery, so she gets tangled up in a risky money arrangement with Grayson Blackwood, heir to the Blackwood family, who is as cold as he is magnetic. It's supposed to be a trade that suits them both, but they soon can't get enough of each other, and what she knows is right keeps losing out to what she wants. The closer they get, the more goes unsaid. Grayson is drawn in by how gentle and how tough she is, and under his protection Emily becomes someone new and steps into a whole different life.",

    'pregnant-with-the-mafia-boss-s-triplets-love-begins':
        "She saved a mafia boss in a shootout and ended up carrying his triplets.\nAmy Brooks wants to be a dancer, and in the middle of a performance she runs into John Wilson, a mafia boss, right in the middle of a gunfight. She saves his life, and they spend the night together. Not long after, Amy finds out she's pregnant with triplets. Her parents and her younger sister won't stop humiliating her for it, and then they make plans to put her up at an auction and sell her. John has been searching everywhere for Amy the whole time, but again and again they just miss each other. Will he reach her before the auction does?",

    'happy-ever-after-with-my-grooms-brother':
        "Her groom cheated, so she proposed to his brother in the middle of the wedding.\nMia finds out her fiance has been cheating, and right in the middle of the wedding she turns to a man in a wheelchair everyone takes for a nobody and asks him to marry her instead, just to spite the groom. What she's signed up for is a marriage of convenience, but the heat between them keeps blurring what's a lie and what's real. Mia promised to look after him. She has no idea he's a billionaire, and one of the most elusive tycoons in Europe. As his double life comes apart, they still have to get through gold diggers, jealous exes and a lot of late night confessions. Can something that started as a lie turn into the real thing?",

    'the-god-king-returns-too-late-to-beg':
        "Five brides called the God King a fraud. One kept her word.\nA thousand years ago the God King Ares gave up his power to seal away the demons and keep six races safe. Now he's back to claim the marriage pact made with him, and five of his brides turn him away, sure he's an impostor. Their betrayal brings disaster down on everyone. Only the Elven Queen keeps her promise. She stands at his side and goes with him into the Divine Realm. By the time the rest of them realize who he really was, it's much too late to beg.",

    'don-t-mess-with-the-billionaire-s-mother':
        "Her son's fiancee put her in intensive care. She waited for the engagement party.\nGwen Grant was a celebrated medical professor, and after retiring she goes back to St. Paul Hospital, where one of her patients is Emma, the woman her son Ethan is about to marry. A single checkup is enough to uncover Emma's affairs, a serious illness, and the way she's been violently abusing the hospital staff. Then Emma lands Gwen in intensive care. Gwen doesn't fight back, she bides her time. At the engagement banquet, with all of New York's elite there to watch Emma step into high society, Gwen walks in carrying Emma's medical file and evidence of every single thing she's done. Emma is never going to be a Grant.",

    'came-back-hotter-with-lord-s-twins':
        "Her fiance left her over a birthmark. The Lord of the Burning Realm needed her touch.\nJodi has dragonslayer blood and an ugly birthmark, and her fiance Paul walks out on her because of it. Then she meets Nick. He's Lord of the Burning Realm, under a curse that has him burning alive for a hundred years, and her touch turns out to be the only thing that puts out the fire. After one night with him she's carrying twins. Five years on, Jodi returns to the Dragon Lands to find her daughters, and with her mark gone and her face changed, nobody knows her. Melody has filled Nick's head with lies, and Jodi's own family come at her again and again. When Nick finally learns the truth, he realizes his fated mate is the woman he wronged. Together they take down every plot against them, rescue their girls and claim each other at last.",

    'mated-to-my-boyfriend-s-brother':
        "Her boyfriend cheated. His brother the Alpha turned out to be her mate.\nJust before she turns eighteen, Sophia, an Omega, catches her boyfriend Bruce cheating on her with her best friend Louisa. Soon after, she learns her destined mate is Bryan, the Alpha, who happens to be Bruce's brother. And at Bryan's engagement banquet, what she says ruins the whole thing. Bryan is furious. He fires her brother, which leaves her mother sick, and to keep her family afloat Sophia has to go to work as his personal secretary. Bryan treats her coldly, but his wolf wants her. It takes conflict after conflict and more than one crisis before their feelings are real, and so is their mate bond.",

    'evelyn-s-revenge-my-enemy-calls-me-aunt':
        "Her fiance sold her to another man. She died running and woke up that same night.\nEvelyn Sterling is heiress to the Sterling Group, and one rainy night her fiance Marcus Hale sells her to the ruthless Blackwood Group CEO, Damian Blackwood. She runs, and a car hits her. Lying there dying, she hears Marcus on the phone talking about her father's legacy. Then she opens her eyes and it's that same night again, and this time she's not going to be anybody's prey. She goes straight to Damian's suite with an offer: she'll be his if he helps her ruin them. Damian is cold and controlling, but her nerve gets to him. Working undercover as his assistant, she strips the masks off her enemies one by one and digs up the truth about her father's murder. When that truth points back at Damian, he cuts off his own family to stand with her. By the end the Hale Group has collapsed, her enemies are in prison, and Evelyn gets her family's empire back and his heart too.",

    'the-ceo-found-his-savior-and-his-son':
        "She saved the CEO's life and ended up pregnant and beaten.\nHaley saved Josh, the CEO of the Reid Group, and he owes her his life. What she got for it was a pregnancy she never planned and then a vicious beating that broke her legs. A few months later her son arrives early, and she works herself to the bone to pay his hospital bills, holding on to every cent. All that time Josh has been searching for her without a break. When he finds her, Haley is finally going to be loved the way she should have been all along.",

    'reborn-i-choose-the-other-groom':
        "Last time she married the man she wanted, and it got her killed.\nIn her first life Cathy forced her adopted brother Rory to marry her. Her stepsister Marlee loved Rory, and she took her own life. Rory was so angry he ended up killing Cathy by accident. Now Cathy is reborn just before the wedding, and this time she lets Marlee have Rory. She takes on the family's other marriage instead, to the Moss family's crippled son, Nate. Once they're married Cathy discovers Nate's disability was no accident. His uncle Theo and his stepmother Martha did it to him. Together Cathy and Nate take back control of the family, make the villains pay, and build a real family full of love and children. Rory is left with nothing but regret.",

    'one-night-with-three-alphas-changed-everything':
        "Her son died. Her husband betrayed her. Then came a night with three brothers, all Alphas.\nRiley's world falls apart when her son dies and her husband turns on her. Desperate to take back some control, she spends a reckless night with three brothers who are all Alphas, and lands in the middle of a power struggle much bigger than she is. Between feuding werewolf factions, old rituals and a buried family secret, there are people who want her dead. The three Alphas keep her safe, and they wake something in her she never knew she had. Her road runs across Crescent Hollow's wastelands and into the Obsidian Veil, and by the end the broken human she was is gone. In her place is a woman who finally gets to choose her own future.",

    'oops-my-father-s-bff-is-in-my-bed':
        "Five years of loving her dad's best friend in secret.\nFor five years Evelyn has been quietly in love with her dad's best friend, Jacob. The night before her father gets married, Jacob comes back and Evelyn finally goes for it. He holds out, out of loyalty to her dad and because of how much older he is. Then one night, out by the pool, he gives in. Their secret affair is intense, until Evelyn's mother makes Jacob call it off and his ex makes it hurt even more. Jacob goes along with it and breaks Evelyn's heart, to spare her something worse. When it all comes out, Jacob has to face her father's rage. But her father sees how real their love is and gives them his blessing, and Jacob and Evelyn finally stop hiding.",

    'the-top-heir-s-ugly-wife':
        "Her sister's groom is already legally married. To her.\nBecause of what her mother said with her last words, Eliana has spent fifteen years making herself look ugly and foolish. Then her half sister Paige is set to marry Cole, who is a top heir, and it turns out Cole's marriage is already registered, to Eliana. Nobody knows how it happened, but she has to move in with him all the same. As Eliana beats Paige at every scheme she tries, her many hidden identities start coming out one by one, and she and Cole grow closer. But how did her name end up on his marriage record in the first place?",

    'my-mafia-don':
        'One rainy night, one look, and the head of a crime family wanted her.\nBethany crosses paths with Matthew on a rainy night, and he turns out to be the mysterious head of a powerful gangster family. He falls for her the second he sees her and goes after her with no intention of giving up. Slowly Bethany finds herself falling for him too, even with all the danger that comes with his world. Loving a mafia don was never going to be simple.',

}

FACTS = {
    'watch-out-i-m-the-lady-boss': 'After being cast aside by the man she helped rise to power, Eleanor—secret CEO of the powerful Thunder Circle—is thrust back into the spotlight when a mysterious billionaire proposes marriage, shaking high society to its core.',
    'one-fateful-night-with-my-boss': 'After having a one-night stand with an old geezer for money, Anita said goodbye to this cold city and went abroad. Six years later, she comes back with her son and bumps into the legendary CEO, Tristan, who later turns out to be her new boss. Before she knows it, her son starts calling this handsome new boss: “dad”. Could this be fate?',
    'rebel-in-devil-s-shackle': 'Sold out by someone in dark web, Nina Morgan bumps into mafia lord, Max Luther in the riches’ hunting game. Once an aristocracy, Nina is now dragged into inferno by Max, lost in sweetness and tortures. She finally makes up her mind to leave, but Max confines her no matter how many times she tries. It’s out of love, or of hatred? Overwhelmed by love and forbidden desire, the two hurt each other but simultaneously save each other.',
    'almost-lover': "Evelyn returns from her prenatal checkup to find her husband massaging oil onto his first love's belly. When Evelyn suffers a severe allergic reaction, he locks her in a room and ignores her pain—she loses the baby. Shattered, she walks away and rebuilds at her friend's architecture firm. Months later, Edward finds her at the love-lock bridge where they vowed forever, threatening to jump unless she forgives him. Will Evelyn save the man who destroyed her, or let him fall?",
    'the-wedding-day-divorce': "On Tyson Jordan’s wedding day, his sister, Taylor, returns from abroad to celebrate, only to be mistaken by his fiancée for his secret pregnant lover. Despite Taylor's attempts to clarify the misunderstanding, the fiancée harbors resentment and deliberately causes Taylor's miscarriage. When Tyson learns the truth, he vows to seek revenge for his sister, compelling his fiancée’s family to face the consequences of her reckless actions.",
    'back-to-the-80s': 'Julie Stein wakes up from her sleep, expecting just another ordinary day. However, to her surprise, she finds herself in the 80s, a totally different era from where she belongs. Not only is she a disowned daughter of a wealthy family to whom she has no blood connection, but she is also supposed to marry an old man with two children, in place of the family’s biological daughter.',
    'shes-the-apple-of-their-eye': "Emily, the daughter of the illustrious Porter family, had her world upended when she learned she wasn't her parents' biological daughter. When the true Porter family heiress returned to claim her birthright, Emily was kicked out of the family. After rejoining her biological family, she discovered she was the heiress of the nation's wealthiest dynasty. She had five exceptional brothers who showered her with affection, two adoring parents, and a wealthy CEO fiancé.",
    'sweetheart-wife': "Four years ago, Queenie Young was framed by Sandy Young and driven abroad by her father. She coincidentally rescued Shane Lawson abroad.Returning home four years later, Queenie found her fiance, Sam Fowler, cheating on her with Sandy. She impulsively married her best friend, Xander Lawson, but Xander took the wrong ID card because he was drunk. They accidentally registered Queenie's marriage with the male lead, Shane.",
    'christmas-with-a-country-bad-boy': 'After a sold-out world tour, country music’s good girl returns home for Christmas to rest—only to be cornered by her money-hungry family pressuring her to sign away her estate. When her label sends its scandal-ridden bad boy to rehab his image, she least expects him to be the one who helps her fight back, reclaim her voice, and take control of her life again.',
    'the-lovers-saga': "When Carmelia Sanders stepped in for Maeve Turner at the After Hours Club, a twist of fate led her into a night with Asher Lowery. However, Maeve took credit for Carmelia's encounter with Asher. Asher woke up and found the pendant that Carmelia had left behind, becoming convinced that Maeve was the daughter of his savior. He deeply adored Maeve and even promised to make her his bride.",
    'forbidden-tides-don-t-tell-my-stepson': "Lisa's life takes a risky turn during a weekend trip when an irresistible passion sparks between her and Kai, her stepson’s college friend. Caught in an alluring web of secret encounters, she struggles to keep their forbidden affair hidden under her husband and stepson’s noses. As desire threatens to unravel her marriage, every choice pulls her deeper into the abyss.",
    'the-mafia-s-forbidden-swap': 'Emma is a beautiful mafia wife, ignored by her cold husband Kevin. Injured in a fall, she fakes amnesia, aching to feel loved—only for Kevin to name his brother Ryan, the feared "dark executioner," as her real husband while he flaunts his mistress. The dangerous swap throws her into the arms of a lethal man whose cold eyes hide scorching heat.',
    'the-dangerous-bosss-missing-bride': 'For eight months, Kang Sung-hoe boss Lee Kanghyun has searched relentlessly for the woman who saved his life. When he finally finds her, she is Yoo Seoyeon — a woman raising a child alone, abandoned even by her own family. But then he notices something: the child\'s birthday matches the exact night he spent with her. "I\'ll take responsibility for you and the child." The world\'s most dangerous man begins to move — to protect the woman he loves and the child who may be his.',
    'hidden-hero-his-time-to-shine': 'As Logant’s top researcher, Nathan Kent takes part in the Kunst Program, a secret national security operation. All participants unselfishly devote themselves to the operation for the good of the country. However, when Nathan’s teacher dies from exhaustion, a top celebrity and his assistant ask Nathan to empty the ward and even humiliate him.',
    'the-twins-love-me-too-late': "For three years, Hannah slept beside a stranger — her husband's twin, Ansel — in a marriage built on Aiden's revenge scheme for Ivy. After her mother's death and a miscarriage, Hannah gets her revenge, cuts both brothers out of her life, and starts a new life overseas.",
    'my-baby-daddy-is-my-best-friend': "Jea finds herself at a crossroads after becoming pregnant with the child of Young-gi, a married man. Unable to give up her baby, she makes an unexpected proposal to her childhood friend Gu-in. Bound by circumstances he cannot refuse, Gu-in agrees to become her fake husband and the baby's father. What begins as a bizarre arrangement gradually turns into genuine affection as they raise the child together. But when Young-gi's wife, Kyung-ah, discovers the truth, everything spirals out of control. Caught in a tangled web of love, lies, and family, their outrageous romance takes an unpredictable turn.",
    'loving-you-in-my-final-days': 'She pretended to betray the man she loved to hide a terminal illness. A year later, he returns as a billionaire CEO—with another woman by his side and nothing but resentment for her. Every reunion reopens old wounds, while the truth remains buried between them. When love was built on one heartbreaking lie, can the truth still bring them back together?',
    'dont-provoke-him-hes-the-king-of-l-a': 'Cain Morgan, founder of APEX Capital, works as a taxi driver in seclusion after his eldest son Ethan dies in a premeditated car crash caused by Damian O’Hara. His younger son Liam clashes repeatedly with the wealthy O’Hara family, who kidnap Liam’s girlfriend Aurora to threaten him. Cain unleashes his financial power and bankrupts O’Hara Group for revenge. Later he meets Lena, chairwoman of Opal, and invests heavily in her brand. Lena’s ex Holton, consumed by jealousy, abducts her at Westside Warehouse and forces Cain to kneel and hand over APEX shares. Holton is arrested in the end. Liam transfers to the finance department to marry Aurora, while Cain and Lena stay together.',
    'the-ceo-who-felt-my-pregnancy': 'Lila Reed, a poor rural‑born employee at Vaughn Group, sleeps with drugged CEO Hayden Vaughn to land a permanent job. A unique family mating bond lets Hayden share all her physical sensations. When Lila finds herself pregnant with high‑risk triplets, she tries to run away. Hayden finds her, marries her and shields her from jealous rivals, malicious coworkers and greedy family members. After surviving multiple dangers, Hayden proposes to Lila. Connected by their special bond, they look forward to their life with the unborn triplets.',
    'too-late-to-regret-my-lost-goddess': "Leila is secretly Zeus's granddaughter until Damon brands their unborn child a rapist's bastard to shield Callista. She seals the child in crystal, divorces him, then reveals the crystal bears both Ares's and Zeus's marks. She exposes Callista's scheme and calls down Olympus's judgment on her. Damon's sentence: not death, but eternal regret, forced to watch Leila live happily with Orion, forever.",
    'betrayed-at-the-alter-she-married-a-ceo-instead': 'For eight years, heiress Ella Whitfield hid her identity and gave everything to the man she loved. On their wedding day, she discovers he’s been sleeping with his late brother’s widow—and raising their five-year-old son. Humiliated and betrayed, Ella walks away and takes back every resource she ever gave him. He thought he lost a bride. He’s about to find out he lost the woman who built his entire world.',
    'her-mafia-fathers-wrath': 'My father was Enzo Moretti, the godfather of one of New York’s most powerful mafia families. And I was his princess—his most cherished treasure. He hid me from his world to protect me, but he didn’t want me left alone, so he arranged a marriage for me. The groom was Leon Scott—the son of New York’s richest man. Handsome, loaded, and a rising star in the business world. On paper, he was perfect. For our wedding, my father had a custom gown flown in from a designer in Milan. Today was my fitting appointment. When I walked into the bridal boutique, my heart stopped. Nicole Hill, Leon’s childhood sweetheart, was wearing my wedding dress. When she saw me, a smug little smile curled her lips. Then she grabbed a cheap white polyester bridesmaid’s dress from the table and shoved it into my arms. “Put this on,” she said, lifting her chin like she owned the place. “You can wear this for the ceremony.” I looked down at the flimsy fabric in my hands, then back up at her. My voice dropped low. “I’m the soon-to-be bride. And you’re telling me to wear this?” She let out a laugh, sharp and mean. “Just do what you’re told and don’t make this difficult. Leon already gave the word. I’m walking down the aisle in your place. And you? You just stand there like a good little bridesmaid and go through the motions.” For a few seconds, I couldn’t speak. Then I pulled out my phone and dialed Leon’s number. It rang twice before he picked up. “Leon, about Nicole taking my place at the altar. Don’t you think you owe me an explanation?”',
    'the-tennis-queen-s-match-point-comeback': 'After five years of marriage to her tennis partner Enzo, Isabel uncovers a devastating truth: she was merely a shadow of Julie, the woman he never forgot.Enzo abandons everything when Julie returns. But when Isabel vanishes from his life, desire turns to torment—and regret comes far too late.',
    'this-time-she-walked-away-first': "Lena Clermont fell hard for her dad's friend, Andrew Rohan—twelve years older. The first time she saw him, he was all sharp suits and broad shoulders, effortlessly standing out. He smiled, patted her head, and handed her a princess dress. Fast forward to twenty. He got drugged at a banquet. She wore that same dress, offering herself as the cure.",
    'a-nearsighted-girls-journey-through-a-horror-game': 'After I got pulled into the horror game, my nearsightedness made everything blurry. I ended up treating the creepy girl in the blood-stained dress like my own daughter, the final boss like my husband, and the old creepy ghosts like my loving parents. The first time I met the boss, I grabbed his abs and said, “Nice body. Shame you’re kind of short.” He actually laughed in anger, picked up the severed head in his hand, put it back on his neck, and ground out, “I’m six-foot-one. Still think I’m short now?”',
    'loved-twice-by-the-hockey-star': 'Seven years after vanishing with his unborn child, Hazel retuirns under a new identity, struggling to save her sick daughter. Alexander, the hockey supersttar who never stopped searching for the woman he lost, has no idea the little girl calling hhim "Daddy" is his own. As buried secrets resurface and old wounds reopen, can love survivethe truth-or is it already too late?',
    'too-late-im-married-to-the-godfather': 'Five years after Ethan humiliated Mia with a soda-can tab ring and chose Sophia, Mia is now married to Antonio Russo, the powerful New York Mafia Don, and raising their son. At a luxury hotel, Ethan mistakes her for a beggar and Sophia frames her as a thief, until Antonio reveals Mia is the Donna of the Russo family. Old lies unravel: Sophia destroyed their past and nearly had Mia assaulted. As Sophia falls into ruin and Ethan loses everything, Mia chooses her new family and freedom.',
    'the-muggle-kingpin': 'The post-apocalypse is swarming with monsters, and humanity clings to life by a thread. Zane, a muggle with zero powers, is exiled by his own kin. Then he stumbles into running a supply mart and discovers he can control the very beasts hunting humans. Can this rejected underdog become the savior no one saw coming?',
    'i-helped-my-husbands-brother-take-the-mafia-throne': 'A reborn mafia wife was drowned by her husband for ruining his first love’s birthday. This time, she lets him blow the entire godfather throne for his sweetheart, then strikes a deal with his exiled brother to take everything. Savage karma, brutal payback, no mercy.',
    'don-t-touch-the-legendary-lawyer-s-grandson': "Lawyer Eleanor flies with her sick grandson to surgery. Oversold flight: influencer Bella steals his seat, flashing her boyfriend's platinum card, unaware she's bullying his mother, the Queen of Lawyers. Crew gag the child, lock him in a lavatory; the purser keeps the key as she begs on her knees. One films it. Off the plane, she vows they pay.",
    'galactic-myth-arena': "Earth has forgotten its gods. After centuries of lost history and crushing defeats in a galactic arena, humanity faces enslavement. Ethan Cole, a delivery driver from another world who remembers Earth's myths, must awaken its lost deities to face alien civilizations armed with powerful gods and rigged rules.",
    'the-king-of-vegas-chose-her-i-chose-freedom': 'Evelyn left her wealthy family to build an empire with Cole, the man she loved. But when he cheated and destroyed her body for his mistress, she divorced him, reclaimed her life, and found happiness again—while Cole lost everything.',
    'kiss-of-a-cornered-beast': 'Milo Thompson works multiple jobs—and even sells a kidney—to fund his boyfriend Kane Winslow’s brain surgery. Then he learns Kane is a wealthy Upper East Side heir and their love was only a cruel game. Devastated, Milo disappears. Realizing his feelings were real, Kane gives up his pride and begins a desperate fight for forgiveness.',
    'dragons-bow-to-the-trash': 'Born without a Dragon Mark, Elias is mocked as a powerless nobody at the Royal Dragon Rider Academy. No one knows he once routed a Level 72 Demon King, commands dragons without a bond, and has awakened Alexstrasza, the ancient King of Dragons. As corrupt nobles rig the trials against him, the academy is about to learn who the real monster is.',
    'the-janitor-mom-is-the-real-boss': "Fu Jingshu, head of the Zhuoyuan Group, hides her fortune to temper her adopted son Fu Huai'an, posing as a cleaner to raise him sixteen years. Returning from abroad, he becomes vain under his birth mother Shen Rong. At a banquet, he humiliates her, smashing the heirloom jade pendant. Fu Jingshu reveals her true identity as her three sons arrive. Fu Huai'an learns every resource came from his adoptive mother and kneels in confession. Fu Jingshu cuts the past ties, beginning a brand-new life.",
    'snacks-bought-me-a-wasteland-throne-season-1': 'A junk snack order flips Ian Chan’s life: a “free ring” drops him into a brutal wasteland. In the real world he’s a Boss; in the wasteland he barters spicy strips for tech and power, rising fast while others barely survive. How far can a pack of spicy strips take him?',
    'the-world-s-deadliest-body-guard': "Kane Mercer was once the top-ranked killer on the underground assassin registry the Ledger. Three years ago, he retired and became an ordinary freight driver in the American Southwest. When crime boss Victor Crowe massacred his outfit and put a bounty on Tessa Cross, the boss's daughter, Kane was entrusted with protecting her and forced to pick up his old skills. Crowe raises Kane's bounty to three million and draws in top killers.",
    'my-pup-became-my-alpha': "Ten years ago, ace hunter Raven defied his guild's sacred rules to rescue and raise Ash, an orphaned pup from the enemy Moon Wolf clan. Now, the clingy cub has grown into a dominant pureblood Alpha whose suppressed devotion and possessive hunger are spiraling out of control. Torn between age, duty, and taboo boundaries, Raven tries to run—until a fatal crisis forces Ash to execute a permanent mating mark to save Raven's life, shattering the line between guardian and mate forever.",
    'son-from-the-future': 'When single attorney Emma is cornered at her front door by a stranger claiming to be her son from the future, he issues a bizarre ultimatum: start dating, or die in a car accident in exactly one year. But as Emma investigates to the bottom of his warning, she uncovers a chilling truth—the person destined to die was never her.',
    'i-married-a-family-of-liars': 'A Wall Street con woman, flipped into an FIA informant, marries into a NY elite family as an aristocrat to expose money laundering. Wedding night reveals her in-laws are frauds—black-market title, forged "Monet," Ponzi-scheme fund. When her FIA handler emerges as the real mastermind, she must choose: trade them for freedom, or join the family to take down the criminal.',
    'the-warlords-heir-is-my-son': 'Betrayed and imprisoned, Willa Gray gives birth after a drugged night. Her son Andy is adopted by his unknown father, Young Marshal Jason Shaw, identified as heir by the Kirin Birthmark. Hired as a nanny to soothe the ailing boy, she comes face-to-face with Jason, unaware of their connection.',
    'five-years-behind-bars-my-family-begs': "Five Years Behind Bars, My Family Begs follows Nova Sterling’s high-stakes journey of revenge after her own family sent her to prison. With a powerful CEO by her side, she exposes the truth in this trending mini drama. Will their late regrets be enough to earn her mercy? Nova Sterling, the rightful heiress, being framed by a manipulative imposter and heartlessly sent to prison by her own brother. After five years of undeserved suffering, she returns not with tears, but with a cold determination for revenge. This trending short series follows Nova as she sheds her former humility to dismantle the lies of those who betrayed her. When the mysterious CEO Ethan Walton steps in to claim her as his wife, the stakes of this popular mini drama reach a fever pitch. As Nova exposes the fake daughter's schemes, her family’s desperate pleas for forgiveness come far too late. This must-watch short drama delivers a powerful narrative of justice and redemption that keeps viewers hooked until the very last second.",
    'testing-love-married-to-a-crippled-billionaire': "Tired of gold-diggers, tech mogul Alexander shows up to a blind date disguised as a poor disabled man. There he meets Morgan—a warm hearted mechanic who treats him with genuine kindness, flaws and all. They rush into marriage, but Alexander keeps his true identity hidden, quietly watching over her. Morgan's snobbish cousin Camilla constantly mocks them, yet her schemes only end in her own embarrassment. Alexander's mother grows close to Morgan, nearly slipping about who he really is. When the truth finally comes out, Morgan is hurt by the deception, but still loves Alexander. They reconcile, and soon Morgan is expecting twins—completing their happily-ever-after.",
    'his-private-patient': "Sophia, a bastard swapped at birth by her scheming mother, grows up eclipsed by her sister Laura, who steals every scrap of love and privilege. Forced into a cold marriage with Oscar, she endures a year of sexless neglect—her stifled desire curdling into hysteria. Then enters Brant, the hospital's enigmatic doctor. Their charged entanglement peels back decades of lies, exposing a birth secret that could shatter her world.",
    'one-night-one-deal-one-billionaire': 'In order to cover her father’s surgery fees, college student Emily Anderson becomes entangled in a dangerous financial arrangement with Grayson Blackwood—the cold, alluring heir to the Blackwood family. What begins as a transactional relationship of mutual benefit spirals into an addictive obsession with each other’s bodies, intensifying the battle between morality and desire. As their connection deepens, unspoken emotions slowly unravel: Grayson finds himself captivated by her tenderness and resilience, while Emily undergoes a transformative rebirth under his protection, ultimately stepping into a new life.',
    'pregnant-with-the-mafia-boss-s-triplets-love-begins': 'Amy Brooks dreams of becoming a dancer. During a performance, she crosses paths with John Wilson, a mafia boss caught in a shootout. She saves him, and the two end up spending the night together. Amy unexpectedly falls pregnant with triplets. When her parents and younger sister find out about her pregnancy, they subject her to endless humiliation. Worse still, they plan to send her to an auction to be sold. Meanwhile, John Wilson is searching relentlessly for Amy Brooks, yet the pair keep missing each other time and again',
    'happy-ever-after-with-my-grooms-brother': 'A powerful billionaire masquerading as a wheelchair bound "nobody." A bride who proposes to him midwedding to spite her cheating fiancé. Trapped in a marriage of convenience, their explosive chemistry blurs the lines between deception and desire. As his double life unravels, Mia discovers the man she vowed to protect is Europe’s most elusive tycoon. But with forbidden sparks igniting, can their game of lies survive a world of gold-digging schemers, jealous exes, and sizzling midnight confessions?',
    'the-god-king-returns-too-late-to-beg': "God-King Ares sacrificed his power to seal demons and protect six races. A thousand years later, he returns for his marriage pact, but five brides reject him as a fraud. Their betrayal unleashes catastrophe. Only the Elven Queen honors her vow, standing by him and entering the Divine Realm. When others learn the truth, it's too late.",
    'don-t-mess-with-the-billionaire-s-mother': "After retirement, renowned medical professor Gwen Grant returns to St. Paul Hospital and treats Emma, her son Ethan's fiancée. One examination exposes Emma's affairs, serious illness, and violent abuse of hospital staff. After Emma sends her to intensive care, Gwen chooses patience over confrontation. At the engagement banquet, with New York's elite watching Emma enter high society, Gwen arrives carrying her medical records and proof of every crime—ready to destroy Emma's perfect image and end her dream of joining the Grant family.",
    'came-back-hotter-with-lord-s-twins': "Jodi carried the blood of dragonslayers and an ugly birthmark. Her fiancé Paul abandoned her for it. Then she met Nick, the Lord of the Burning Realm, cursed to burn alive for a century. Her touch was the only thing that could stop the fire. One night, she walked away pregnant with twins. Five years later, Jodi returned to the Dragon Lands for her daughters. Her mark faded, her face changed, and she became unrecognizable. But Melody had poisoned Nick's mind with lies, and her own family attacked her at every turn. When Nick finally uncovered the truth, he found his fated mate in the woman he'd wronged. They tore through conspiracies, saved their daughters, and claimed each other.",
    'mated-to-my-boyfriend-s-brother': "Sophia, an Omega, finds out her boy friend Bruce cheated with her bestie Louisa, before her eighteenth birthday. But soon, she finds out Bruce's brother Bryan, the Alpha, is her destined mate. It is on Bryan's engagement banquet, and her words ruin it. Bryan is furious and sacks her brother, which causes her mother to get sick. To save her family, Sophia becomes his personal secretary. He is cold to her, yet his wolf longs for her. After conflicts and crises, they forge real feelings and form a real mate bond.",
    'evelyn-s-revenge-my-enemy-calls-me-aunt': "On a rainy night, Evelyn Sterling, heiress to the Sterling Group, is sold by her fiancé Marcus Hale to Damian Blackwood, the ruthless CEO of the Blackwood Group. She tries to flee but is fatally struck by a car. As she lies dying, she overhears Marcus discussing her father's legacy over the phone. Miraculously, she wakes up back on that same night, no longer willing to be prey. She walks into Damian's suite and proposes a deal: she will be his woman if he helps her destroy them. Damian is cold and domineering, yet her defiance ignites something in him. She goes undercover as his assistant at Blackwood Group, gradually tearing off her enemies' masks and uncovering the truth behind her father's murder. When the past implicates Damian, he chooses to sever ties with his family and stand by her. In the end, the Hale Group collapses, her enemies go to prison, she rebuilds her family's empire and settles every score, and she also wins the heart of that arrogant man.",
    'the-ceo-found-his-savior-and-his-son': 'Josh—CEO of the Reid Group—owed Haley his life. She had saved him. What she got in return was an unexpected pregnancy, then a brutal beating that left her legs broken. Months later she gave birth prematurely to a baby boy, and to pay his hospital bills she worked relentlessly, scraping together every cent she could. All that time, Josh never stopped looking for her. He would find Haley—and give her every bit of the love and care she deserved.',
    'reborn-i-choose-the-other-groom': "In her past life, Cathy made her adopted brother Rory marry her. Her stepsister Marlee, in love with Rory, killed herself. Rory was furious and accidentally killed Cathy. Reborn before the wedding, Cathy chooses to let Marlee have Rory, and takes on the family duty of marrying Nate, the crippled son of the Moss family. After marriage, Cathy finds that Nate's disability is actually caused by his uncle Theo and stepmother Martha. The couple take back family power and punish the villains, forming a true family with love and children, leaving Rory in regret.",
    'one-night-with-three-alphas-changed-everything': "Riley's life shattered when her son died and her husband betrayed her. In a reckless bid to reclaim control, she spent one night with three Alpha brothers, and fell into a power game far larger than herself. Caught between werewolf factions, ancient rituals, and a family secret buried deep, she had to survive a world that wanted her dead. The three Alphas protected her, and awakened something inside her she never knew existed. From the wastelands of Crescent Hollow to the hidden Obsidian Veil, Riley rose from broken human to a woman who could finally claim her own future.",
    'oops-my-father-s-bff-is-in-my-bed': "Evelyn had secretly loved Jacob, her father's best friend, for five years. On the eve of her father's wedding, Jacob returned, and Evelyn made her move. He resisted, bound by loyalty and age, until one night by the pool, he broke. Their forbidden affair burned bright, but Evelyn's mother forced Jacob to end it, and his ex twisted the knife. Jacob played along, breaking Evelyn's heart to protect her from worse. When the truth came out, Jacob faced her father's fury. But in the end, moved by real love, he gave them his blessing. Age, guilt, and fear fell away. Jacob and Evelyn finally stood together, no longer hiding.",
    'the-top-heir-s-ugly-wife': "Following her mother's last words, Eliana made herself look ugly and silly for fifteen years. But when her halfsister Paige was about to marry Cole, a top heir, it was found that he has already registered marriage with Eliana. Though no one knew what happened, she still had to go live with Cole. As Eliana countered Paige's schemes, her multiple identities gradually uncovered, and her bond with Cole grew. Will she find out the truth behind all this?",
    'my-mafia-don': 'On a rainy night, Bethany ran into Matthew, the enigmatic leader of a powerful gangster family. The moment he saw her, Matthew fell for her and pursued her with relentless determination. As time went on, Bethany found herself falling in love with him, despite the dangers that surrounded his world.',
}

SOURCES = {
    'watch-out-i-m-the-lady-boss': ("platform", 'https://www.dramaboxdb.com/movie/41000121776/watch-out-im-the-lady-boss'),
    'one-fateful-night-with-my-boss': ("platform", 'https://www.dramaboxdb.com/movie/41000103356/one-fateful-night-with-my-boss'),
    'rebel-in-devil-s-shackle': ("platform", 'https://www.dramaboxdb.com/movie/41000100701/rebel-in-devils-shackle'),
    'almost-lover': ("platform", 'https://www.dramaboxdb.com/movie/42000001967/almost-lover'),
    'the-wedding-day-divorce': ("platform", 'https://www.dramaboxdb.com/movie/41000110319/the-wedding-day-divorce-dubbed'),
    'back-to-the-80s': ("platform", 'https://www.dramaboxdb.com/movie/41000102609/back-to-the-80s'),
    'shes-the-apple-of-their-eye': ("platform", 'https://www.dramaboxdb.com/movie/41000100832/shes-the-apple-of-their-eye'),
    'sweetheart-wife': ("platform", 'https://www.dramaboxdb.com/movie/41000100836/sweetheart-wife'),
    'christmas-with-a-country-bad-boy': ("platform", 'https://www.dramaboxdb.com/movie/42000000808/christmas-with-a-country-bad-boy'),
    'the-lovers-saga': ("platform", 'https://www.dramaboxdb.com/movie/41000100855/the-lovers-saga'),
    'forbidden-tides-don-t-tell-my-stepson': ("platform", 'https://www.vigloo.com/en/content/15003049'),
    'the-mafia-s-forbidden-swap': ("platform", 'https://www.vigloo.com/en/content/15003225'),
    'the-dangerous-bosss-missing-bride': ("platform", 'https://www.vigloo.com/en/content/15003230'),
    'hidden-hero-his-time-to-shine': ("platform", 'https://www.dramaboxdb.com/movie/41000105143/hidden-hero-his-time-to-shine'),
    'the-twins-love-me-too-late': ("platform", 'https://www.goodshort.com/drama/the-twins-love-me-too-late-31001730620'),
    'my-baby-daddy-is-my-best-friend': ("platform", 'https://www.vigloo.com/en/content/15002979'),
    'loving-you-in-my-final-days': ("platform", 'https://www.flextv.cc/episodes/episode-1-loving-you-in-my-final-days-DAON2V8OPR'),
    'dont-provoke-him-hes-the-king-of-l-a': ("platform", 'https://www.flextv.cc/episodes/episode-1-don%E2%80%99t-provoke-him-he%E2%80%99s-the-king-of-l-a-LMOggQ9OYe'),
    'the-ceo-who-felt-my-pregnancy': ("platform", 'https://www.goodshort.com/drama/the-ceo-who-felt-my-pregnancy-31001769965'),
    'too-late-to-regret-my-lost-goddess': ("platform", 'https://www.vigloo.com/en/content/15003405'),
    'betrayed-at-the-alter-she-married-a-ceo-instead': ("platform", 'https://www.flextv.cc/episodes/episode-1-betrayed-at-the-alter-she-married-a-ceo-instead-qjzb05DZ7W'),
    'her-mafia-fathers-wrath': ("platform", 'https://www.goodshort.com/drama/her-mafia-father-s-wrath-31001663065'),
    'the-tennis-queen-s-match-point-comeback': ("platform", 'https://www.goodshort.com/drama/the-tennis-queen-s-match-point-comeback-31001770565'),
    'this-time-she-walked-away-first': ("platform", 'https://www.goodshort.com/drama/this-time-she-walked-away-first-31001689912'),
    'a-nearsighted-girls-journey-through-a-horror-game': ("platform", 'https://www.goodshort.com/drama/a-nearsighted-girl-s-journey-through-a-horror-game-31001700678'),
    'loved-twice-by-the-hockey-star': ("platform", 'https://www.shorttv.live/drama/loved-twice-by-the-hockey-star-33375'),
    'too-late-im-married-to-the-godfather': ("platform", 'https://www.shorttv.live/drama/too-late-i%E2%80%99m-married-to-the-godfather-25971'),
    'the-muggle-kingpin': ("platform", 'https://www.shorttv.live/drama/the-muggle-kingpin-15738'),
    'i-helped-my-husbands-brother-take-the-mafia-throne': ("platform", 'https://www.shorttv.live/drama/i-helped-my-husband%E2%80%99s-brother-take-the-mafia-throne-25614'),
    'don-t-touch-the-legendary-lawyer-s-grandson': ("platform", 'https://netshort.com/episode/dont-touch-the-legendary-lawyers-grandson-2097995633059737602'),
    'galactic-myth-arena': ("platform", 'https://netshort.com/episode/galactic-myth-arena-2102224479725932546'),
    'the-king-of-vegas-chose-her-i-chose-freedom': ("platform", 'https://netshort.com/episode/the-king-of-vegas-chose-her-i-chose-freedom-2103677570133606402'),
    'kiss-of-a-cornered-beast': ("platform", 'https://netshort.com/episode/kiss-of-a-cornered-beast-2094675398934585346'),
    'dragons-bow-to-the-trash': ("platform", 'https://netshort.com/episode/dragons-bow-to-the-trash-2098349014030798849'),
    'the-janitor-mom-is-the-real-boss': ("platform", 'https://netshort.com/episode/the-janitor-mom-is-the-real-boss-2100422656781529090'),
    'snacks-bought-me-a-wasteland-throne-season-1': ("platform", 'https://netshort.com/episode/snacks-bought-me-a-wasteland-throne-season-1-2103022875379367937'),
    'the-world-s-deadliest-body-guard': ("platform", 'https://netshort.com/episode/the-worlds-deadliest-body-guard-2102941636718571522'),
    'my-pup-became-my-alpha': ("platform", 'https://netshort.com/episode/my-pup-became-my-alpha-2102946450819063810'),
    'son-from-the-future': ("platform", 'https://netshort.com/episode/son-from-the-future-2102948783447683074'),
    'i-married-a-family-of-liars': ("platform", 'https://netshort.com/episode/i-married-a-family-of-liars-2102947941306937345'),
    'the-warlords-heir-is-my-son': ("platform", 'https://netshort.com/episode/the-warlords-heir-is-my-son-2103668893012013057'),
    'five-years-behind-bars-my-family-begs': ("platform", 'https://pinedrama.com/dramas/five-years-behind-bars-my-family-begs'),
    'testing-love-married-to-a-crippled-billionaire': ("platform", 'https://www.flickreels.net/playlist/testing-love-married-to-a-crippled-billionaire/11064/episode-1'),
    'his-private-patient': ("platform", 'https://www.flickreels.net/playlist/his-private-patient/10867/episode-1'),
    'one-night-one-deal-one-billionaire': ("platform", 'https://www.flickreels.net/playlist/one-night-one-deal-one-billionaire/1306/episode-1'),
    'pregnant-with-the-mafia-boss-s-triplets-love-begins': ("platform", 'https://www.flickreels.net/playlist/pregnant-with-the-mafia-bosss-triplets-love-begins/8895/episode-1'),
    'happy-ever-after-with-my-grooms-brother': ("platform", 'https://www.dreameshort.com/en/drama/happy-ever-after-with-my-groom-s-brother-872'),
    'the-god-king-returns-too-late-to-beg': ("platform", 'https://www.stardusttv.net/episodes/01-the-god-king-returns-too-late-to-beg-22708'),
    'don-t-mess-with-the-billionaire-s-mother': ("platform", 'https://www.stardusttv.net/episodes/01-don-t-mess-with-the-billionaire-s-mother-22220'),
    'came-back-hotter-with-lord-s-twins': ("platform", 'https://www.moboreels.com/drama/came-back-hotter-with-lords-twins-60492322'),
    'mated-to-my-boyfriend-s-brother': ("platform", 'https://www.moboreels.com/drama/mated-to-my-boyfriends-brother-59256322'),
    'evelyn-s-revenge-my-enemy-calls-me-aunt': ("platform", 'https://www.moboreels.com/drama/evelyns-revenge-my-enemy-calls-me-aunt-103002322'),
    'the-ceo-found-his-savior-and-his-son': ("platform", 'https://www.moboreels.com/drama/the-ceo-found-his-savior-and-his-son-72843322'),
    'reborn-i-choose-the-other-groom': ("platform", 'https://www.moboreels.com/drama/reborn-i-choose-the-other-groom-64063322'),
    'one-night-with-three-alphas-changed-everything': ("platform", 'https://www.moboreels.com/drama/one-night-with-three-alphas-changed-everything-66075322'),
    'oops-my-father-s-bff-is-in-my-bed': ("platform", 'https://www.moboreels.com/drama/oops-my-fathers-bff-is-in-my-bed-58156322'),
    'the-top-heir-s-ugly-wife': ("platform", 'https://www.moboreels.com/drama/the-top-heirs-ugly-wife-58256322'),
    'my-mafia-don': ("platform", 'https://www.moboreels.com/drama/my-mafia-don-47855322'),
}
