# -*- coding: utf-8 -*-
"""Batch generated by caption_pipeline.py next.

Fill CAPTIONS. Each value is HOOK newline BODY newline ASIDE.
  HOOK  one sentence, leads as the subheading
  BODY  the synopsis, in our words, ONLY facts from the source below
  ASIDE us talking to the reader, must stand alone with the rest covered

FETCH REQUIRED means there is no fact source on disk. Read the platform page
first, paste what it says into FACTS below, then write. Never write from the
title alone.
"""

CAPTIONS = {

    # 432.7M   Bound by Honor
    # FACTS: Trapped in an arranged marriage with Luca, the cold and dangerously seductive heir to th
    # FACTS: e New York mafia, Aria, the innocent little princess of the Chicago mafia, must decide w
    # FACTS: hether giving her body—and perhaps her heart—to a man born of violence is her greatest b
    # FACTS: etrayal or her only chance of survival.
    'bound-by-honor':
        "",

    # 271.3M   The Great and Powerful Genie
    # FACTS: Elijah Baran is a genie in a magic lamp who can grant three wishes. After thousands of y
    # FACTS: ears, a billionaire uses his last wish to grant Elijah freedom, but on one condition: El
    # FACTS: ijah must marry his granddaughter, Christine, for five years! To fulfill the wish, Elija
    # FACTS: h transforms into a human, marries Christine, and secretly helps her become a successful
    # FACTS:  CEO. However, Christine ignores and constantly belittles him during their marriage. Whe
    # FACTS: n the five years are almost up, Elijah starts to realize that Christine might never trul
    # FACTS: y love him. He decides to divorce her.
    'the-great-and-powerful-genie':
        "",

    # 119.7M   The Heiress Blacklisted Her Husband
    # FACTS: Alex Pychtin lead.
    'the-heiress-blacklisted-her-husband':
        "",
}

FACTS = {  # paste fetched text here for any FETCH REQUIRED row
}

